### PR TITLE
Add Time and Attendance Record Management

### PR DESCRIPTION
**Pull request by yamelsenih**
This is a great functionality for Time and Attendance Management.
See: https://en.wikipedia.org/wiki/Time_and_attendance

This is a pull request that result from project https://github.com/adempiere/adempiere/projects/26

Please take a time for read project description and project changes

Time and Attendance Management is a project for handle all attendance for Human Resource, It allows record all attendance from employees.

After entered all attendance is possible determinated what is result for payroll process as Action Notice directly.

A short definition is [https://en.wikipedia.org/wiki/Time_and_attendance](https://en.wikipedia.org/wiki/Time_and_attendance)

The scope is:
 - Enter TNA.
 - Handle Shift Group
 - Handle Shift Wotk
 - Handle Work Group
 - Add Time relation with concept
 - Define Shift Rotatio
 - Define default action notice for shift
 - Convert attendance record to Action Notice

Here a ER Diagram:
time-and-attendance

Fixes: #1834 
Fixes: #1846
Fixes: #1870
Fixes: #1872
Fixes: #2013
Fixes: #2014
Fixes: #2015
Fixes: #2016
Fixes: #2017
Fixes: #2019
Fixes: #2021
Fixes: #2022
Fixes: #2024
Fixes: #2025
Fixes: #2026
Fixes: #2027

From: https://github.com/adempiere/adempiere/pull/2655

### CODE REVIEW

**Comment by marcalwestf** [comment]
Here the log of RUN_MigrateXML.sh : it goes well up to the last step; the it fails.

> 19:04:07.956   MMigrationStep.apply: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD. successfully applied [1]
> 19:04:07.956   MMigrationStep.apply: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD. successfully applied [1]
> :
> :
> 
> 19:04:08.814   MMigration.syncColumn: Synchronizing column: MColumn[54739-Code] in table: MTable[53086-HR_Employee] [1]
> -----------> MMigration.apply: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view
>   Where: PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 67 at RAISE [1]
> -----------> MMigration.apply: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view
>   Where: PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 67 at RAISE [1]
> 19:04:08.979   MMigrationStep.rollback: Rolling back migration step: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD.  [1]
> 19:04:08.979   MMigrationStep.rollback: Rolling back migration step: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD.  [1]
> 19:04:09.000   MMigrationStep.rollback: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD. successfully rolled back [1]
> 19:04:09.000   MMigrationStep.rollback: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 39480; Type: AD. successfully rolled back [1]

..and the rolls back the whole steps

**Comment by marcalwestf** [comment]
it failed both manually applying the xml file or via RUN_MigrateXML.sh, starting on a 392 seed.

**Comment by marcalwestf** [comment]
[20190830_Testing_PR2720.txt](https://github.com/adempiere/adempiere/files/3561962/20190830_Testing_PR2720.txt)

**Comment by marcalwestf** [comment]
I found the culprit.
It is

```
<Step SeqNo="35440" StepType="AD">
   <PO AD_Table_ID="101" Action="U" Record_ID="54739" Table="AD_Column">
       <Data AD_Column_ID="118" Column="FieldLength" oldValue="1">255</Data>
   </PO>
</Step>

```

If you remove this step from 05020_Add_TNA_Functionality.xml, it executes without error.
It seems that changing the length to 255 conflicts with view(s) already defined which in Postgres should be re-defined.

I will continue testing the next XMLs.

**Comment by marcalwestf** [comment]
...continuing with the exceution of XMLs, the following error is thrown when executing _RUN_MigrateXML.sh_ on file _05060_TNA_Add_Missing_Columns.xml_:

```
20:28:33.004   MMigrationStep.apply: Applying migration step: 
Migration 5060 - TNA Add some columns - 3.9.3 (ECA03) ;
 Step: 10; Type: SQL.  
===========> MMigrationStep.applySQL: 
Migration 5060 - TNA Add some columns - 3.9.3 (ECA03) ; 
Step: 10; Type: SQL.  Application failed. 

org.postgresql.util.PSQLException: 
ERROR: column "minattendancerequire" of relation "hr_workshift" already exists
java.sql.BatchUpdateException: Batch entry 2 
ALTER TABLE HR_WorkShift 
ADD COLUMN MinAttendanceRequire NUMERIC(10) DEFAULT '2' NOT NULL 
was aborted: 
ERROR: column "minattendancerequire" of relation "hr_workshift" already exists  
Call getNextException to see other errors in the batch.
```


Remains to find out if this step is not needed anymore, i.e. where column _MinAttendanceRequire_ is already defined.

**Comment by marcalwestf** [comment]
File _05060_TNA_Add_Missing_Columns.xml_ contains the following command:
`ALTER TABLE HR_WorkShift ADD COLUMN MinAttendanceRequire NUMERIC(10) DEFAULT '2' NOT NULL;`

Meanwhile in file _05020_Add_TNA_Functionality.xml_ the same column is already defined:
```
<Step SeqNo="35480" StepType="AD">
      <PO AD_Table_ID="101" Action="I" Record_ID="90553" Table="AD_Column">
:
:
        <Data AD_Column_ID="111" Column="Name">Minimum Attendance Require</Data>
        <Data AD_Column_ID="116" Column="ColumnName">MinAttendanceRequire</Data>
        <Data AD_Column_ID="109" Column="AD_Column_ID">90553</Data>}
        <Data AD_Column_ID="114" Column="AD_Table_ID">53681</Data>}
        <Data AD_Column_ID="2608" Column="AD_Element_ID">56662</Data>
        <Data AD_Column_ID="84306" Column="UUID" isNewNull="true"/>
      </PO>
    </Step>
```

This is the reason why an error is thrown.

**Comment by marcalwestf** [comment]
Same happens with:

`ALTER TABLE HR_ShiftIncidence ADD COLUMN IsAnticipatedRecord CHAR(1) DEFAULT 'N' CHECK (IsAnticipatedRecord IN ('Y','N'));`

and 
   ```
 <Step SeqNo="39020" StepType="AD">
      <PO AD_Table_ID="101" Action="I" Record_ID="90887" Table="AD_Column">
        <Data AD_Column_ID="111" Column="Name">Entrance / Egress Anticipated</Data>

        <Data AD_Column_ID="116" Column="ColumnName">IsAnticipatedRecord</Data>

        <Data AD_Column_ID="226" Column="AD_Reference_ID">20</Data>

        <Data AD_Column_ID="109" Column="AD_Column_ID">90887</Data>

        <Data AD_Column_ID="114" Column="AD_Table_ID">54502</Data>

        <Data AD_Column_ID="2608" Column="AD_Element_ID">60636</Data>

      </PO>
    </Step>
```

**Comment by marcalwestf** [comment]
Repairing the XMLs as stated before, the XMLs are imported without problems.

**Comment by marcalwestf** [comment]
The opening and populating of ATM windows do also work.

**Comment by yamelsenih** [comment]
Hi @marcalwestf I change sequence for all XML for TNA and run migration loader with a database 3.9.2 + current xml and it is ok.

See a fresh image:
Screenshot_20190918_223324


Note that I update branch from develop

**Comment by marcalwestf** [comment]
thanks @yamelsenih  I will start testing anew...

**Comment by marcalwestf** [comment]
I ran on an Adempiere 392 seed the command _RUN_MigrateXML.sh_, and got the very same error as I mentioned before: 
Selection_127


The XML file was loaded and applied correctly. It is when  _MMigration.syncColumn()_ is executed that the error is generated.

I notice that the step 35440 remained in the XML, so it is no surprise that I got the very same error again testing in the same way.

BTW, it seems that a difference between our way of testing is that I use  _RUN_MigrateXML.sh_, whereas you run the process _Import Migration from XML_, but it should not yield different results, should it?

**Comment by marcalwestf** [comment]
... I am about to run it from process _Import Migration from XML_. 
Let's see.

**Comment by marcalwestf** [comment]
@yamelsenih , @e-Evolution, @mckayERP  it seems that migrating with _RUN_MigrateXML_ differs from migration on Swing with _Import Migration from XML_.

Apparently in some cases  _RUN_MigrateXML_ causes errors not encountered when running  _Import Migration from XML_.

**Pull request merged**
