### PR TITLE
#1935 Add IsDefault to AD_User_Roles.  

### LINKED ISSUE #1935: Default role for the System account should be System Administrator
The default role is "Role Template" - or at least that is what appears in the Role combo box on login.  This is confusing for new users.  The Role Template is a special case and the user needs some expertise to use it.

### PR DESCRIPTION
**Pull request by mckayERP**
Fixes #1935
Limit the flag to one record per user. Sort the roles in Login.java so that the default is first in the results.

### CODE REVIEW

**Comment by marcalwestf** [comment]
a sensible modification.

**Comment by marcalwestf** [comment]
starting testing
funny side-effect: cannot execute XML on branch because it needs column **AD_User_Roles.isDefault** for logging in :)

I'll load it with another code...

**Comment by marcalwestf** [comment]
Suggesting minor change: in class **MUserRoles**, method **beforeSave()**, delete unnecessary comments

```
/** Prevents saving
log.saveError("Error", Msg.parseTranslation(getCtx(), "@C_Currency_ID@ = @C_Currency_ID@"));
log.saveError("FillMandatory", Msg.getElement(getCtx(), "PriceEntered"));
/** Issues message
log.saveWarning(AD_Message, message);
log.saveInfo (AD_Message, message);
**/
```

**Comment by marcalwestf** [comment]
.... perhaps can be solved with #2039

**Comment by marcalwestf** [comment]
Pull request https://github.com/adempiere/adempiere/pull/2036 could be accepted by splitting the XML into two files, separating column definition from field definition.

**Comment by mckayERP** [comment]
Fixes #1935.

**Comment by marcalwestf** [comment]
**1** 
Suggesting minor change: in class **MUserRoles**, method **beforeSave()**, delete unnecessary comments. The comments have apparently nothing to do with the code.

```
/** Prevents saving
log.saveError("Error", Msg.parseTranslation(getCtx(), "@C_Currency_ID@ = @C_Currency_ID@"));
log.saveError("FillMandatory", Msg.getElement(getCtx(), "PriceEntered"));
/** Issues message
log.saveWarning(AD_Message, message);
log.saveInfo (AD_Message, message);
**/
```


**2**
Correct translation to:
 ```
<Step SeqNo="220" StepType="AD">
      <PO AD_Table_ID="119" Action="I" Record_ID="0" Table="AD_Message_Trl">
      :
        <Data AD_Column_ID="342" Column="MsgText">Es permitido s&#xF3;lo un registro predeterminado.  Por favor desactivar el registro predeterminado existente antes de seleccionar uno nuevo.</Data>
```

**3**
Just another minor change in the XML file headers which helps trace back to the original issue when testing:
```
<Comments>https://github.com/adempiere/adempiere/issues/1935</Comments>
```

**Comment by marcalwestf** [comment]
Additionally , after loading and applying XMLs, same error pops up -as reported by Pull request: https://github.com/adempiere/adempiere/pull/1947 and Issue: #1944 :

20181005_role_01

This means, first this error has to be solved before tackling this one.

**Comment by marcalwestf** [comment]
Test passes after applying Works only after having applied pull request https://github.com/adempiere/adempiere/pull/1947. 
It works as described.

If the suggested steps 1-3 are changed, this pull request can be accepted.

**Comment by mckayERP** [comment]
Hi Mario, the three items requested have been addressed.

**Comment by yamelsenih** [comment]
Hi All, i have a error with it

**Comment by PraponAon** [comment]
I have to add column with this sql 
"ALTER TABLE AD_User_Roles ADD COLUMN isdefault character(1) NOT NULL DEFAULT 'N'::bpchar;"
But, it makes the Menu window (System Administrator) disappear and had message when start app.
"ADempiere starting: org.compiere.apps.AMenu - java.lang.NullPointerException"

**Pull request merged**
