### PR TITLE
Rename Production Package (Replace #3944)

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request basically change the package name of Production to new structure:

Replace the PR #3944 

Old structure:
```Java
  - org.compiere.model
  - org.compiere.process
  - org.adempiere.process
```

New structure:
```Java
  - org.compiere.production.model
  - org.adempiere.production.process
  - org.compiere.production.process
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN('org.adempiere.process.CalculateReplenishPlan', 'org.adempiere.process.GenerateReplenishPlanProductionReport', 'org.adempiere.process.GenerateReplenishPlanReport', 'org.adempiere.process.GenerateReplenishPlanRequisitionReport', 'org.adempiere.process.ReplenishPlanInitialSetup', 'org.compiere.process.OrderLineCreateProduction', 'org.compiere.process.ReplenishReportProduction');
```
 
 Value|Name
-- | --
 RV_T_Replenish_Production        | Replenish Report incl. Production
 CreateProductionOrder            | Create Production Order
 ReplenishPlan_Generate_Report    | Replenish Plan Generate Report
 ReplenishPlanInitialSetup        | Replenish Plan Initial Setup
 ReplenishPlan                    | Replenish Plan Report
 ReplenishPlan_Production_Report  | Replenish Plan Production Report
 ReplenishPlan_Requisition_Report | Replenish Plan Requisition Report

## Model Validators
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('');
```

Name|Description
--|--

## Forms
```SQL
SELECT f.Name, f.Description
FROM AD_Form f
WHERE f.ClassName IN('');
```

Name|Description
--|--

## Final comments

The support legacy api is from here: https://github.com/adempiere/adempiere-production-support-legacy

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
- checked out branch
- updated project
- Cleaned project on UI

Result:
imagen

Perhaps a name conflict?

**Comment by yamelsenih** [comment]
> * checked out branch
> * updated project
> * Cleaned project on UI
> 
> Result: imagen
> 
> Perhaps a name conflict?

Hi @marcalwestf this was resolved. Thanks

**Review by marcalwestf — COMMENTED** [review]
- Compile: OK
- Build: error
imagen
imagen

The error is produced although on the IDE (Eclipse) the class `MAssetGroup` is found at compile time.
But, when importing the class `org.compiere.model.MAssetGroup`, the IDE seems not to know it:
imagen

It seems that classes `IT_MAsset` and `MAssetGroup` are considered on the IDE to belong to the package `org.compiere.model`,  but at build time, they are not considered to belong to the same package. The package is not accessible on `IT_MAsset`.

**Comment by yamelsenih** [comment]
> * Compile: OK
> * Build: error
>   imagen
>   imagen
> 
> The error is produced although on the IDE (Eclipse) the class `MAssetGroup` is found at compile time. But, when importing the class `org.compiere.model.MAssetGroup`, the IDE seems not to know it: imagen
> 
> It seems that classes `IT_MAsset` and `MAssetGroup` are considered on the IDE to belong to the package `org.compiere.model`, but at build time, they are not considered to belong to the same package. The package is not accessible on `IT_MAsset`.

Hi @marcalwestf this already resolved yet:
Screenshot from 2022-08-01 11-54-44

**Review by marcalwestf — APPROVED** [review]
### Preliminary tests
- Compiler errors: none -> OK
- Build without errors -> OK
- Load and apply XML files -> OK
### Functional Tests (processes)
- CalculateReplenishPlan -> OK
- GenerateReplenishPlanReport -> OK
- ReplenishPlanInitialSetup -> OK
- OrderLineCreateProduction -> OK
### Functional Tests (reports)
- GenerateReplenishPlanProductionReport -> OK
- GenerateReplenishPlanRequisitionReport -> OK
- ReplenishReportProduction -> OK
- Replenish Plan Requisition Report -> OK
- Replenish Report incl. Production -> OK
### Summary
All tests were successful.
Pull Request approved.

**Pull request merged**
