### PR TITLE
#1925  Deleted migration step 890 from 03605_1532...xml

### PR DESCRIPTION
**Pull request by mckayERP**
…cessorWindow.xml

### CODE REVIEW

**Comment by marcalwestf** [comment]
Seems to refer to issue https://github.com/adempiere/adempiere/issues/1564

One question @mckayERP : what is the reason for deleting it?

**Comment by mckayERP** [comment]
Deleting the step will prevent the error from appearing in the logs.  Application of the XML suggests a review of the logs following the application to determine if there were any errors. See step 10 in http://wiki.adempiere.net/Creating_a_New_Seed_Database.

**Comment by marcalwestf** [comment]
Hi,
as I see, the error in step 350 is produced because there is reference to `AD_Column_ID=86204` which doesn't exist and also is not created in file _03605_1532_ProjectProcessorWindow.xml_.
I too agree that when deleting the step, the error doesn't appear.

Perhaps should better @e-Evolution  look at it and create the missing column if it is missing.

**Comment by e-Evolution** [comment]
fixes

**Pull request merged**
