### PR TITLE
Fixed Error on Accounting of Match Invoice

### PR DESCRIPTION
**Pull request by carlosaparadam**
Currently, at reversing invoice, credit note, receipt or vendor return , this generate a new invoice matching  associated to reverse document, but the accounting for this document is incorrect.

Original Document:
image

Reversed Document:
image

Accounting of documents:
image

Accounting of documents after fixed:
image

### CODE REVIEW

**Comment by e-Evolution** [comment]
@carlosaparadam Hi Carlos 

The accounting entries for a reversal must not be of absolute value so as not to inflate or distort the debts and credits.

Thus the reversals must be equal to the original accounting entry but with a negative value, as any other reverse. 

Do you check is reversal with original Accounting?

image

**Comment by carlosaparadam** [comment]
hi @e-Evolution , i try it and it is not working, i don't see when the field IsReversedWithOriginalAcct of document type is supported, in the change i dont use absolute value, i find the original accounting and use the method updateReverseLine from FactLine class.

see this example: 
Document Type Setting
image

Original Document
image

Reversal Document
image

Accounting Comparation
image

**Comment by e-Evolution** [comment]
@carlosaparadam this account working but I new changes was introduced Cost Engine , you need check 
 
@SusanneCalderon test here and  no exist this issue 

https://github.com/adempiere/adempiere/issues/1439
https://github.com/adempiere/adempiere/issues/1348
https://github.com/adempiere/adempiere/issues/1239

**Comment by carlosaparadam** [comment]
ok @e-Evolution, i will test and comment again

**Comment by e-Evolution** [comment]
carlosaparadam the Cost Engine is very complex and sencible to any change 

So any change need complice with requieremets
- The reverse accounting should be equal original, but with opposite sign
- the cost detail transaction should be rigth for costing method , the inventory value should ve right
- the quantity in any accconting fact should be equal that original quantiy,  but with opposite sign

Please consider these important points.

**Comment by carlosaparadam** [comment]
@e-Evolution, i tried again with IsReversedWithOriginalAcct and you have reason, but for it work the table sould be have the column of document type, i will close this pull request and open a new for creating document type for this table and setting a document type by default.

thanks for your help and suggest, i will hope for your comments.

Regards

**Pull request closed without merging**
