### PR TITLE
#1891 Fixed error with role access for process Role Access Update

### PR DESCRIPTION
**Pull request by yamelsenih**
reference to issue: https://github.com/adempiere/adempiere/issues/1891

Please test it for resolve a bug with new feature for role access for dashboard

### CODE REVIEW

**Comment by marcalwestf** [comment]
File _03940_1744_AddDashboardAccesTab.xml_ is missing reference to issue.

**Comment by yamelsenih** [comment]
Hi @marcalwestf  I change it from last commit. Dashboard functionality was added for ZK UI on previous versions but is unsupported for swing

**Comment by marcalwestf** [comment]
... the process _Role Access Update_ runs flawlessly on both _Swing_ and _ZK_ for different roles.

**Comment by e-Evolution** [comment]
@marcalwestf , I think that is necessary change the prefix of table AD_Dashboad_Access to PA_Dashboad_Access because this functionality is Performance Analysis WDYT?

**Pull request merged**
