### PR TITLE
Correct navigation issues with ZK.

### LINKED ISSUE #3365: Problems navigating within paged records in ZK.
Reported by @sksanoopz on gitter.

#### Steps to reproduce

In ZK webui interface, given a table with a large number of records, open a window to display the records.  Switch to table view.  Move to the second page.  Select a record on the page and switch to form view.  The wrong record is displayed.  Verified using SuperUser/System and the Migration table which has > 800 records.

Also, when near the end of a page, hitting Page Down or Down Arrow causes an error.

image
image
image

#### Expected behavior

Switching between tab and form view should remain on the same record.

At the end of the page, the <Down Arrow> or <Page Down> key should move to the next page or the last record without error.

### PR DESCRIPTION
**Pull request by mckayERP**
Fixes #3365.

There are several problems with the navigation in table view in ZK.

1. Given active paging and
    2. the selected row is on the 2nd or higher page, when switching to the form view, then a different record is shown.
    3. a row in range 2 to 6 is selected,  the Page Up key does nothing
    4. a page size of 100 (the default), 
        5. when the last row is selected on any page, the Down Arrow key will cause an exception in ZK
        6. when a row within six rows of the end of any page, the Page Down key will cause an exception in ZK
        7. when the first row is selection on the 2nd page or higher, then the Up Arrow key will cause an exception in ZK
        8. when a row in the range 2 to 6 is selected on the 2nd or higher page, the Page Up key will cause an exception in ZK.

The proposed change fix these issues.  Unit tests are included with the commit that include a range of test cases.

A few changes were made to the behaviour:
- The spacing used to make sure a row is visible in the screen was reduced to 3 rows from 7
- The treatment of the Page Up/Down and Up/Down Arrow keys is handled in the same way. 

To test manually, try the above problems using SuperUser as System Admin and open the Application Dictionary Migration window.  There are over 800 records in that table that can be used for testing.  

If you create a new record in the middle of the table, the navigation keys will be ignored until the record is saved.

Note that there are special cases around the end of the table where Page Down or the Down Arrow will cause a new record to appear.  This is how it the code was written to behave but I have never seen this feature discussed anywhere.

### CODE REVIEW

**Comment by e-Evolution** [comment]
@mckayERP I tested with a window with more the 600 records but got some errors:

the problem appears when you navigate with the forward keys and the grid changes pages, it seems that there is a problem when you go from the last page to the previous one 

image

the log trace.

===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridPanel.onPostSelectedRowChanged(GridPanel.java:674)
>>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>>	at java.lang.reflect.Method.invoke(Method.java:498)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>... [59]
===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridPanel.onPostSelectedRowChanged(GridPanel.java:674)
>>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>>	at java.lang.reflect.Method.invoke(Method.java:498)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>... [59]
===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridPanel.onPostSelectedRowChanged(GridPanel.java:674)
>>	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
>>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>>	at java.lang.reflect.Method.invoke(Method.java:498)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>... [59]
===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridPanel.onPostSelectedRowChanged(GridPanel.java:674)
>>	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
>>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>>	at java.lang.reflect.Method.invoke(Method.java:498)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>... [59]
===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridTabRowRenderer.setCurrentColumn(GridTabRowRenderer.java:775)
>>	at org.adempiere.webui.component.GridPanel.onEvent(GridPanel.java:503)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>... [60]
===========> zkoss.handleError:1130: >>java.lang.IndexOutOfBoundsException: Index: -1, Size: 100
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1855)
>>	at org.zkoss.zk.ui.AbstractComponent$ChildIter.<init>(AbstractComponent.java:1848)
>>	at org.zkoss.zk.ui.AbstractComponent$Children.listIterator(AbstractComponent.java:252)
>>	at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
>>	at org.adempiere.webui.component.GridTabRowRenderer.setCurrentColumn(GridTabRowRenderer.java:775)
>>	at org.adempiere.webui.component.GridPanel.onEvent(GridPanel.java:503)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>... [60]

**Comment by mckayERP** [comment]
Hi Victor,

Dang - I really tested everything on this one.  I'll try to duplicate your
issue and fix it.

Michael McKay
President, mckayERP <http://mckayerp.com>
+1 (613) 297-4483

<http://mckayerp.com>

**Comment by e-Evolution** [comment]
@mckayERP would you solve the last issue to merge this bugfix?

**Comment by niclopup** [comment]
Hi everyone!

Same thing happend to me.

Window Process Audit, when you move to the second page and try to press on a field it shows the same error.


image

**Comment by mckayERP** [comment]
Thanks.  I can now duplicate the error.

**Comment by mckayERP** [comment]
@e-Evolution @niclopup 
Thanks for testing this.  Please try again.  I found the problem - a confusion of the index on the page vs the index in the table.  This is rendering correctly for me and I can select records and edit the data for any row on any page.

**Comment by e-Evolution** [comment]
Hi @mckayERP Mike 

Do you validate that your changes did not introduce the bug again, fixed in #3506? 

On the other hand, I realize that now when reaching the last record it always adds a new record to be saved, even when the preference of the new record is turned off in preference, it seems to me that the validation that made the preference was removed

image

If the Automatic New Record is off why grid create a new record?

image

the rest of the functionality seems fine, I no longer have the exception outside of index

**Comment by e-Evolution** [comment]
@mckayERP Mike, I confirm that the bug reported in #3506 was reintroduced with these changes.

I use the method gridTab.dataRefresh(row); because is the unique way I found to propagate the changes and apply the new context based on the display rule.

According to the case described in #3506 , the Prepare button should be hidden and it is shown even when the credit is not valid.

image

**Comment by mckayERP** [comment]
@e-Evolution Hi Victor,  Using the GardenWorld data, I saw the Display Logic working with the dataRefresh() being called when switching between table and form view.

The test performed was to search for all orders, there were 4.  Then in table view, select one of them and switch to form view.  Verify that the displayLogic was working.

There was one issue noted.  When I first opened the Sales Order window, it had a new record.  When I searched for all records, and switched to table view, I could not navigate off the first record.  The system considered it new.  This has been fixed by resetting the field m_newRow to -1 when the data is refreshed.

For the new row according to user preferences, this is not working in the develop branch either.  Perhaps another issue should be created to deal with it.  Its beyond the scope of this PR.

**Comment by e-Evolution** [comment]
Hi @mckayERP Mike, I assumed it was a possible cause of removing these lines

https://github.com/adempiere/adempiere/pull/3371/files#diff-e9487991a502fcb0fef458bd885d0d35e546fc0cbec4b1804b83a7f1b1fa678cL1076

where is validates if is the total of lines and then on that new records are entered then create a new one? in new code, the total or last row is not is validate as the previous code

On the other hand, the other happens when you select as in the image.

1.- first select all the records in the grid until order 60128 is found
2.- Change to the Single row layout and verify the Credit Status field which is as ok and the prepare button is showing.
3.- Change to grid mode and search for order 60124 using the mouse cursor
4.- Change to the Single row layout and verify the credit status is as No Credit Check and the prepare button is showing when it should be hidden.

The problem happens when using the mouse to navigate 

image

image

image

image

was also difficult for Mario to replicate.

**Comment by marcalwestf** [comment]
at @e-Evolution  Victor's request, I tested if this branch  complies with https://github.com/adempiere/adempiere/pull/3508.
I tested it on Ubuntu 20.04, on an installation with Adopt jdk 11.9+ and Tomcat 9.

I reproduced every step described.
It does comply: the error is not reproducible.

**Comment by marcalwestf** [comment]
**Pagination tests**

I tested this pull request on a client's migrated database with migration up to _08040_Remove_Autocomplete_feature_for_Migration_Data.xml_ (a week ago).

Here the results just on pagination:

- with several hundred entries, the pagination works OK
- either navigating with keyboard arrows  UP/DOWN or clicking on the pagination navigator (at the bottom of the page), the record selected is the correct one.
- navigating with keyboard arrows  UP/DOWN to a page border and surpassing it works well.
- spacing works well, but sometimes it is "forgotten", with no further effect.

Same happens when navigating on a Standard ADempiere Seed 4 days old (up to _09210_Change_name_for_Text_element.xml_), this time on Migration window.


But: there is an error when calling the Quick Entry button on the tool bar:
Selection_002

This error happens with either database.

**Comment by marcalwestf** [comment]
@mckayERP  what doesn't work is the following (tested on Standard ADempiere Seed 4 days old (up to 09210_Change_name_for_Text_element.xml):
- open Business Partner window
- filter one Business Partner (preferably the last one) -> only one record is displayed (OK)
- undo the filter i.e., display all records
- all records are displayed, but the active record is the first! -> (not OK)

If you were at the last record, now you are a the first.
If there is a window with many records, then the user gets lost.

BTW, I don't know if these errors have to do with the pagination....

**Comment by marcalwestf** [comment]
Pagination works now correctly. 

There are still errors on ZK, but I think there are not because of these changes, but there are independent of them.

@e-Evolution, @yamelsenih  please review this and accept it if it's OK.

**Comment by e-Evolution** [comment]
@marcalwestf , this change broke the Quick Entry

**Comment by e-Evolution** [comment]
the intensive testing found multiples issues:

Open the Window Account Fact Balance :

image

Switch to a single row:

image

The first problem is the single mode not how some content although multi-row row 1 is selected 

if switch again to multi-row mode then an empty error is added:

image

Another problem is that when I select a row from a multi-row view, the status bar row does not change.

image

The status bar show 1/105 when I selected other row

**Pull request merged**
