### PR TITLE
First change to build client with gradle

### PR DESCRIPTION
**Pull request by yamelsenih**
This is one of many pull request that wants to build ADempiere with gradle completely.

The build is a hard work and a complete change is not good for test.

Detail: 
- Add `client` and `install` source folders to Gradle and build it.

Now you can see a build folder like this `ADEMPIERE_HOME/install/build/distributions`, inside this folder you can unzip the `install.zip` and run some runners:
- For Linux:
  - `adempiere-swing-ui`
  - `run-migrate`
  - `run-setup`
  - `run-silent-setup`
  - `translation`
- For Windows:
  - `adempiere-swing-ui.bat`
  - `run-migrate.bat`
  - `run-setup.bat`
  - `run-silent-setup.bat`
  - `translation.bat`

All files are automatically generated by `gradle`

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
Run command _gradle clean_ from Eclipse: **successful**

Run command _gradle build_ from Eclipse: **error**
image

Output from Eclipse console:
```
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 8.1.1
Java Home: /data2/programme/eclipse-jee-2023-06/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_20.0.2.v20230801-2057/jre
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: :base:build

> Task :tools:compileJava UP-TO-DATE

> Task :base:compileJava
/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTest.java:401: error: invalid use of a restricted identifier 'yield'
				yield();
				^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTest.java:436: error: invalid use of a restricted identifier 'yield'
					yield();  // Yield To other threads
					^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTestPG.java:291: error: invalid use of a restricted identifier 'yield'
				yield();
				^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTestPG.java:316: error: invalid use of a restricted identifier 'yield'
					yield();  // Yield To other threads
					^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
4 errors

> Task :base:compileJava FAILED
FAILURE: Build failed with an exception.
(follows more error information)


BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

This error happens also if I run other gradle commands like _buildDependents_.

**FIRST QUESTION**
I didn't understand well what you meant IN THE PULL REQUEST EXPALANTION with _Add client source folders to Gradle and build it_. So I run just the _gradle build_ command; perhaps there is another way.

**SECOND QUESTION**
 I wanted to execute the build from the Command Line Interface (CLI), but there I got an error, too:
```
gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'adempiere'.
> The value of a manifest attribute must not be null (Key=Implementation-Version).
```

Line 55 of the _gradle.build_ file contains the following:
`Version = System.getenv("ADEMPIERE_LIBRARY_VERSION")`

I wonder if there is a way to pass the environment variable  at the CLI runtime

**Comment by yamelsenih** [comment]
> Run command _gradle clean_ from Eclipse: **successful**
> 
> Run command _gradle build_ from Eclipse: **error** image
> 
> Output from Eclipse console:
> 
> ```
> Gradle Distribution: Gradle wrapper from target build
> Gradle Version: 8.1.1
> Java Home: /data2/programme/eclipse-jee-2023-06/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_20.0.2.v20230801-2057/jre
> JVM Arguments: None
> Program Arguments: None
> Build Scans Enabled: false
> Offline Mode Enabled: false
> Gradle Tasks: :base:build
> 
> > Task :tools:compileJava UP-TO-DATE
> 
> > Task :base:compileJava
> /data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTest.java:401: error: invalid use of a restricted identifier 'yield'
> 				yield();
> 				^
>   (to invoke a method called yield, qualify the yield with a receiver or type name)
> /data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTest.java:436: error: invalid use of a restricted identifier 'yield'
> 					yield();  // Yield To other threads
> 					^
>   (to invoke a method called yield, qualify the yield with a receiver or type name)
> /data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTestPG.java:291: error: invalid use of a restricted identifier 'yield'
> 				yield();
> 				^
>   (to invoke a method called yield, qualify the yield with a receiver or type name)
> /data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/base/src/org/compiere/dbPort/JdbcTestPG.java:316: error: invalid use of a restricted identifier 'yield'
> 					yield();  // Yield To other threads
> 					^
>   (to invoke a method called yield, qualify the yield with a receiver or type name)
> 4 errors
> 
> > Task :base:compileJava FAILED
> FAILURE: Build failed with an exception.
> (follows more error information)
> 
> 
> BUILD FAILED in 2s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```
> 
> This error happens also if I run other gradle commands like _buildDependents_.
> 
> **FIRST QUESTION** I didn't understand well what you meant in the pull request explanation with _Add client source folders to Gradle and build it_. So I run just the _gradle build_ command; perhaps there is another way.
> 
> **SECOND QUESTION** I wanted to execute the build from the Command Line Interface (CLI), but there I got an error, too:
> 
> ```
> gradle build
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/build.gradle' line: 55
> 
> * What went wrong:
> A problem occurred evaluating root project 'adempiere'.
> > The value of a manifest attribute must not be null (Key=Implementation-Version).
> ```
> 
> Line 55 of the _gradle.build_ file contains the following: `Version = System.getenv("ADEMPIERE_LIBRARY_VERSION")`
> 
> I wonder if there is a way to pass the environment variable at the CLI runtime

Hi @marcalwestf this pull request was created to add gradle support to source folder `client` and `install`. 
Your gradle error maybe can be a wrong enviroment, note that github action is ok: https://github.com/adempiere/adempiere/actions/runs/7105627863/job/19343252952?pr=4259

**Comment by EdwinBetanc0urt** [comment]
This also happened to me when I did the publication in mavenLocal, and it was corrected https://github.com/adempiere/adempiere/pull/4166/files#diff-bf16432804bf564db9af4f7cb0ada7b0c2e18a712f0ef8252bf2d407a475b5e1R401.

**Comment by yamelsenih** [comment]
Hello @marcalwestf this pull request was updated by https://github.com/adempiere/adempiere/pull/4272

**Pull request closed without merging**
