### PR TITLE
fix: Gradle Publish to Maven Local.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
```bash
gradle clean && gradle build && gradle publishToMavenLocal
```

the library directory is expected to be created in the folder `$HOME/.m2/repository/io/github/adempiere`

- `$HOME/.m2/repository/io/github/adempiere/`

imagen

imagen

#### Additional context

fixes https://github.com/adempiere/adempiere/issues/4165

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
- run separately first _gradle clean_ -> OK
- run separately first _gradle build_ -> error

```
gradle build

> Task :base:compileJava
/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_ebetancourt/base/src/org/spin/util/GeneratePassword.java:36: error: unmappable character (0xC3) for encoding US-ASCII
 * @author Raul Mu??oz, rMunoz@erpya.com, ERPCyA http://www.erpya.com
                  ^
:
(several errors)
:
~/adempiere_ebetancourt/base/src/org/spin/util/impexp/GenericQIFBankTransaction.java:50: error: unmappable character (0xC3) for encoding US-ASCII
                return value.replaceAll("[      +^:&??????????????????????????????????????????????????????????????????$]", "");

~/adempiere_ebetancourt/base/src/org/spin/util/impexp/GenericQIFBankTransaction.java:50: error: unmappable character (0xC3) for encoding US-ASCII
                return value.replaceAll("[      +^:&??????????????????????????????????????????????????????????????????$]", "");
                                                    ^

~/adempiere_ebetancourt/base/src/org/spin/util/impexp/GenericQIFBankTransaction.java:50: error: unmappable character (0xA1) for encoding US-ASCII
                return value.replaceAll("[      +^:&??????????????????????????????????????????????????????????????????$]", "");
   and several similar errors 
```

The error in GeneratePassword is because of the character "ñ" in the comments:
image



The code in _GenericQIFBankTransaction.processValue()_ is as follows:
image


I had the same problem with another repository, and I could solve the error by adding in _/base/build.gradle_ and _/build.gradle_ the code beneath, but this time the error persisted:
```
compileJava { 
  options.encoding = "UTF-8" 
}

javadoc {
    options.charSet = 'UTF-8'
}
```

@EdwinBetanc0urt  perhaps you have an idea...
I am still looking for solutions.

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf In several forums this is the solution recommended to apply 
```gradle
compileJava { 
  options.encoding = "UTF-8" 
}
compileTestJava {
  options.encoding = "UTF-8"
}
``` 
However I will also add your
```gradle
javadoc {
    options.charSet = 'UTF-8'
}
```

Another way that might work is to add `systemProp.file.encoding=utf-8` to `gradle.properties` file.

When I have the changes ready I will let you know.
Tanks.

**Comment by yamelsenih** [comment]
Hello @marcalwestf please test adding `systemProp.file.encoding=utf-8` to `gradle.properties` file.

**Comment by marcalwestf** [comment]
hi @EdwinBetanc0urt  , @yamelsenih  , the link https://stackoverflow.com/questions/35435173/prevent-javadoc-from-failing-gradle-build brought me to a solution, where there is no error produced and the process is no aborted.

There, it is suggested to add the following snippet to file _build.gradle:_
```
tasks.withType(Javadoc) {
      failOnError false
      options.addStringOption('Xdoclint:none', '-quiet')
      options.addStringOption('encoding', 'UTF-8')
      options.addStringOption('charSet', 'UTF-8')
}
```

I did not include the line `failOnError false;`, because I wanted that the errors were caught and -if desired- solved.
Instead, I added only
```
tasks.withType(Javadoc) {
      options.addStringOption('Xdoclint:none', '-quiet')
      options.addStringOption('encoding', 'UTF-8')
      options.addStringOption('charSet', 'UTF-8')
}
```
image


This I did on **every** _build.gradle_ file of the project.
I tried to avoid writing all _build.gradle_ files by adding a _gradle.properties_ file on root with these contents, but it didn't work.

The result after executing `gradle build where many warnings and in the end`:

image

**Comment by marcalwestf** [comment]
After the successful build, running the local publish also worked:
```
gradle publishToMavenLocal

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

```
BUILD SUCCESSFUL in 4s
215 actionable tasks: 81 executed, 134 up-to-date

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf @yamelsenih Do I have to make changes?

**Comment by EdwinBetanc0urt** [comment]
Tanks @marcalwestf I will make the changes you propose!

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf  @yamelsenih the fix is ready, I updated with the latest hotfix, for some reason I started to give error compilation so I had to modify a couple of files.

```log
> Task :base:compileJava FAILED
/home/edwin/workspace/prueba/adempiere/base/src/org/compiere/dbPort/JdbcTest.java:401: error: invalid use of a restricted identifier 'yield'
                                yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/home/edwin/workspace/prueba/adempiere/base/src/org/compiere/dbPort/JdbcTest.java:436: error: invalid use of a restricted identifier 'yield'
                                        yield(); // Yield To other threads
                                        ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/home/edwin/workspace/prueba/adempiere/base/src/org/compiere/dbPort/JdbcTestPG.java:291: error: invalid use of a restricted identifier 'yield'
                                yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
/home/edwin/workspace/prueba/adempiere/base/src/org/compiere/dbPort/JdbcTestPG.java:316: error: invalid use of a restricted identifier 'yield'
                                        yield(); // Yield To other threads
                                        ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
5 actionable tasks: 5 executed
```



Besides adding 
```gradle
tasks.withType(Jar){
	// to fix ``Entry org/adempiere/legacy/apache/ecs/ecs.properties is a duplicate but no duplicate handling strategy has been set``.
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
```
in the build.gradle of tools by  
````log
FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
148 actionable tasks: 148 executed
* What went wrong:
Execution failed for task ':tools:sourcesJar'.
> Entry org/adempiere/legacy/apache/ecs/ecs.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.4/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

**Review by marcalwestf — APPROVED** [review]
Steps executed:
- Result of gradle clean: `BUILD SUCCESSFUL` -> OK
- Result of gradle build: `BUILD SUCCESSFUL` -> OK
- Result of gradle publishToMavenLocal: `BUILD SUCCESSFUL` -> OK

All steps executed without errors.
**Tests passed**.

**Pull request merged**
