### PR TITLE
Fixed error with Import Product definition for `Volume` column

### PR DESCRIPTION
**Pull request by yamelsenih**
Just fixed error with Product Import.

## What is the problem?
The problem is the the `Volume` column was defined as `Integer` instead `Amount`. The problem is that a volume unit is not a integer

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih Hello

The problem is that there is no way to define the unit of measurement for the fields Weight, Volume, Shelf Width, Shelf Depth. This would allow establishing complete units for meters, centimeters or pounds. kilos, so the correct thing to do is to add the units of measurement as was done in the vehicle window.

Changing the amount from Integer to Amount does not solve the problem because you will not know if the amount is meters or centimeters. It is better to define the unit of measurement and use the Unit of Measurement conversion tools to obtain more precise data.

The correct approach would be to add the units of measure for each measurement item as in the vehicle window .

* Volume Unit of Measure
* Weight Unit of Measure
* Dimension Unit of Measure

May be

Shelf Unit of Measure

image

kind regards
Victor

**Comment by yamelsenih** [comment]
> @yamelsenih Hello
> 
> The problem is that there is no way to define the unit of measurement for the fields Weight, Volume, Shelf Width, Shelf Depth. This would allow establishing complete units for meters, centimeters or pounds. kilos, so the correct thing to do is to add the units of measurement as was done in the vehicle window.
> 
> Changing the amount from Integer to Amount does not solve the problem because you will not know if the amount is meters or centimeters. It is better to define the unit of measurement and use the Unit of Measurement conversion tools to obtain more precise data.
> 
> The correct approach would be to add the units of measure for each measurement item as in the vehicle window .
> 
> * Volume Unit of Measure
> * Weight Unit of Measure
> * Dimension Unit of Measure
> 
> May be
> 
> Shelf Unit of Measure
> 
> image
> 
> kind regards Victor

Hi @e-Evolution the unit of measurement is not the problem here. Note that the `Volume` column inside `M_Product` was created as `Amout` but the `I_Product` was created as `Integer` then if you want import a product with Volume reference you can't set decimals.

Note: The volume is defined as real number and is a wrong definition assume that these values are integers.

**Comment by e-Evolution** [comment]
@yamelsenih Here I also see another problem, all quantity units are defined with the Quantity reference and not with Amount, Amount is used for monetary units, this can affect why the rounding in Quantity has more precision than that of Amount since this is defined for the currency, so your change should be with the reference Quantity vs Amount

**Comment by yamelsenih** [comment]
> @yamelsenih Here I also see another problem, all quantity units are defined with the Quantity reference and not with Amount, Amount is used for monetary units, this can affect why the rounding in Quantity has more precision than that of Amount since this is defined for the currency, so your change should be with the reference Quantity vs Amount

Hello @e-Evolution I was changed it

**Comment by yamelsenih** [comment]
> > @yamelsenih Here I also see another problem, all quantity units are defined with the Quantity reference and not with Amount, Amount is used for monetary units, this can affect why the rounding in Quantity has more precision than that of Amount since this is defined for the currency, so your change should be with the reference Quantity vs Amount
> 
> Hello @e-Evolution I was changed it

@marcalwestf please test it

**Comment by e-Evolution** [comment]
The change changes from a reference with an integer value to a numerical value that allows decimals, but the solution is incomplete because the unit of measurement of the dimensions cannot be defined.

**Pull request merged**
