### PR TITLE
#4056 [Bug Report] Error when try print any Jasper Report from Swing …

### PR DESCRIPTION
**Pull request by e-Evolution**
…client https://github.com/adempiere/adempiere/issues/4056

Error when try print any Jasper Report from Swing client introduced with #4026

### CODE REVIEW

**Comment by marcalwestf** [comment]
@e-Evolution  hi Victor,
- I didn't find the branch feature/4056 on your repository, but on the ADempiere repository, which I suppose is incorrect, unless you have a compelling reason to do it:
imagen
- According to the descrption of milestones (https://github.com/adempiere/adempiere/milestones), a pure bug fix (like this) should not be done against the **_develop_** branch. Instead, there should be an additional branch (e.g. **_develop-fix_**, **_develop-bugfixes_** or a name according to the developer community) that would collect pure fixes, to be later published for example in version 3.9.4a.
- The branch **_develop_** would be for features and complex bug fixes.

I will test the pull request, but I'd expect you to delete this branch (so the ADempiere repository doesn't get cluttered), to create a branch in your repository and to create a pull request that points to the bug fixes branch on the ADempiere repo.

Thanks!

**Comment by marcalwestf** [comment]
just tested this PR: it runs Jasper Reports on both Swing and ZK.

**Comment by marcalwestf** [comment]
... the changes seem ok to me, so if we agree on repository/branches and @yamelsenih also agrees on the changes, it can be merged.

**Comment by e-Evolution** [comment]
Replace by this PR #4175

**Pull request closed without merging**
