### PR TITLE
Hotfix/3.8.0#002 #495 parameter panel

### PR DESCRIPTION
**Pull request by mckayERP**
Hi Yamel, Victor,  This is the result of the effort to get the parameter panel and browser search defaults to work correctly.  To reduce the duplication of code, I created a single controller for both swing and zk that manages small views were there are a set of fields/ranges.   To make this work, I used the CEditor as the base for all swing and zk editors and moved one of the zk events from the webui to the base.   The general rule was that the controller would understand GridFields and the CEditors but not know about the UI at all.  The View classes would only know about GridFields enough to create the specific editors but not deal with them at all otherwise.  The result is the view is much simpler and the code required to keep the model fields and UI editors in sync with the correct behaviour is all in one place, the controller.   Being able to have a single controller for both UIs is interesting and we should look at this for the main Swing and ZK interfaces.

The change affected a large number of files and most of the changes are small.  There are two new files: SmallViewController and SmallViewEditable.

Please review and let me know what you think.

Mike

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @mckayERP it is nice, before it change the definition for zk was not like MVC, i am making changes in ProcessParameterPanel and other class, i hope that it don't have conflicts :+1: 

Best Regard

**Comment by mckayERP** [comment]
Hi Yamel,

I've synced with the latest in hotfix/3.8.0#002 so the changes should be ok up to that.  If you have other changes not yet committed, I can resync once you have added them.

Mike

**Comment by e-Evolution** [comment]
This process not are work.
 


Not Show rightly of parameters and fail the mandatory parameters

**Comment by e-Evolution** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.apps.ProcessPanel.setComponentVisibility(ProcessPanel.java:381)
	at org.adempiere.controller.SmallViewController.dynamicDisplay(SmallViewController.java:549)
	at org.compiere.apps.ProcessPanel.dynamicDisplay(ProcessPanel.java:360)
	at org.adempiere.controller.SmallViewController.processNewValue(SmallViewController.java:802)
	at org.adempiere.controller.SmallViewController.fieldChange(SmallViewController.java:631)
	at org.adempiere.controller.SmallViewController.propertyChange(SmallViewController.java:835)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.compiere.model.GridField.setValue(GridField.java:1364)
	at org.adempiere.controller.SmallViewController.vetoableChange(SmallViewController.java:527)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
	at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
	at org.compiere.grid.ed.VCheckBox.actionPerformed(VCheckBox.java:235)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.apps.ProcessPanel.setComponentVisibility(ProcessPanel.java:381)
	at org.adempiere.controller.SmallViewController.dynamicDisplay(SmallViewController.java:549)
	at org.compiere.apps.ProcessPanel.dynamicDisplay(ProcessPanel.java:360)
	at org.adempiere.controller.SmallViewController.processNewValue(SmallViewController.java:802)
	at org.adempiere.controller.SmallViewController.fieldChange(SmallViewController.java:631)
	at org.adempiere.controller.SmallViewController.propertyChange(SmallViewController.java:835)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.compiere.model.GridField.setValue(GridField.java:1364)
	at org.adempiere.controller.SmallViewController.vetoableChange(SmallViewController.java:527)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
	at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
	at org.compiere.grid.ed.VCheckBox.actionPerformed(VCheckBox.java:235)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by yamelsenih** [comment]
Hi Víctor It is a similar bug that #590

**Comment by yamelsenih** [comment]
Is better if you create a issue with it report and make a link to issue from it pull request

**Pull request merged**
