### PR TITLE
Add Dockerfile for Adempiere Application And Database

### PR DESCRIPTION
**Pull request by carlosaparadam**
Support to build a docker Adempiere instance

## Step by step to build 

**Before build:**

	- Build Adempiere Source Code
	- cd docker
	- cp ../install/build/Adempiere_393LTS.tar.gz db
	- cp ../install/build/Adempiere_393LTS.tar.gz app
	

**Build a Database Image:**

	- docker build -t adempiere.db --build-arg ADEMPIERE_BINARY=Adempiere_393LTS.tar.gz db

**Build a Application Image using tomcat:** 

	- curl -L https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gz > app/apache-tomcat-9.0.60.tar.gz
	- docker build --build-arg ADEMPIERE_APPS=apache-tomcat-9.0.60.tar.gz \
					 --build-arg ADEMPIERE_BINARY=Adempiere_393LTS.tar.gz \
					 --build-arg ADEMPIERE_APPS_TYPE=tomcat \
					 -t adempiere.app app

**Build a Application Image using Wildfly:**

	- curl -L https://github.com/wildfly/wildfly/releases/download/26.0.1.Final/wildfly-26.0.1.Final.tar.gz > app/wildfly-26.0.1.Final.tar.gz
	- docker build --build-arg ADEMPIERE_APPS=wildfly-26.0.1.Final.tar.gz \
					 --build-arg ADEMPIERE_BINARY=Adempiere_393LTS.tar.gz \
					 --build-arg ADEMPIERE_APPS_TYPE=wildfly \
					 -t adempiere.app app
					 
**Build a Application Image using Jetty:**

	- curl -L https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/10.0.8/jetty-home-10.0.8.tar.gz > app/jetty-home-10.0.8.tar.gz
	- docker build --build-arg ADEMPIERE_APPS=jetty-home-10.0.8.tar.gz \
					 --build-arg ADEMPIERE_BINARY=Adempiere_393LTS.tar.gz \
					 --build-arg ADEMPIERE_APPS_TYPE=jetty \
					 -t adempiere.app app
					 
## Run

    docker-compose up -d

### CODE REVIEW

**Comment by e-Evolution** [comment]
@carlosaparadam What is the difference with the project that we use today?

[ADempiere Docker](https://github.com/adempiere/adempiere-docker)

What is the point of putting this inside the project and not keeping it in a separate repository like it is now?

I ask why this approach is very limited compared to the current approach, which allows you to create multiple deploymnets, with your own customizations, detailed parameterization of ports for the application server and database ports, as well as commands to create or destroy a container via ./application.sh

Did you know that there was already a project for docker?

**Comment by carlosaparadam** [comment]
Hi  @e-Evolution, the idea of placing the definition of the image within the project is that in the future you can take advantage of the actions of github to build and send the image to a docker repository and thus have an updated repository with a specific version of the application, even with each commit made to the repository if you will, this would ensure that you have an environment built at a specific point for testing, for example.

On the other hand, before making this pull request, check the separate project where the docker definition is and I see that it only implements jetty, if you see what I am proposing with the same dockerfile, you could build an image for jetty, tomcat and wilfly. Regarding the configuration of the ports, I think it is something that depends more on the implementation of the container than on the definition of the image and about the customizations, I think it can be solved by documenting the use that can be given to the image for example you could extend the image and append the custom packages.

I remain attentive to your comments, Regards

**Comment by yamelsenih** [comment]
Hi, @e-Evolution I think that this is not a bad idea. Many repositories have this structure and it is not bad for the project. I am try to publish to docker hub the repository named for you but was impossible because not have a way for demostrate that is a official repo of ADempiere. Also was written with very bad practices. See the comment from Docker Hub team:

```
Yamel,

Thanks for the info, that helps clear up the .net/.com questions I had.  As for the Dockerfiles, t[here](https://docs.docker.com/docker-hub/official_repos/) are a lot of problems with them and I would recommend reviewing the documentation carefully to see about improving them per best practices.  A good starting place is here and the many links from that page.  It is also good to review existing Official Repository Dockerfiles to reinforce the documented conventions and style.  

Thanks,

Peter Salvatore
Technical Alliances @Docker, Inc
```

I think that this is a great opportunity to aply power to ADempiere and make presense on Docker Hub.

Best regards

**Comment by marcalwestf** [comment]
@e-Evolution  Víctor, how do we get on here?
It seems that this pull request has a point.

**Comment by yamelsenih** [comment]
This pull request will be closed and rewrited

**Pull request closed without merging**
