### PR TITLE
Fix Error On Production Light

### PR DESCRIPTION
**Pull request by yamelsenih**
- Remove validation by zero when a production is reversed

## Step by Step

- Create a production batch
- Se target quantity to 10
- Set "Automatic Production" flag to false
- Complete batch
- Go to Production window
- Create a new record and select the previous batch created
- Complete production
- Go to production batch

Note that the target quantity is kept instead of being set to "0"

This is because when the production is completed, a cache for class MProductionBatch and the target is updated to the previous quantity instead

- Fixed error with production target quantity

## Step by Step

- Create a production batch
- Se target quantity to 10
- Set "Automatic Production" flag to true
- Complete batch
- Go to Production window
- Complete production generated from batch
- Now reverse production

Note that an exception is thrown with target quantity = 0, this is because the validation is for all instead of validate only when production is completed

### CODE REVIEW

**Comment by marcalwestf** [comment]
I start with the test now.

**Comment by marcalwestf** [comment]
Order Batch completed as on reproduction steps:
imagen



Completing the Production yields an error:
imagen

This is thrown, although Product Info shows availability of 40:
imagen

This was reproduced on a local laptop with Swing and on demo DB provided by Horacio (https://adqa.prolinux.cl/webui/index.zul).
imagen


I tried it with other products that were supposedly in warehouse, but the response after completion was always "Available 0. Not sufficient on stock...":
imagen


It seems that the Production doesn't work on Adempiere 3.9.4.


Context used:
- For Swing: branch from request; database 394
- ZK:  https://adqa.prolinux.cl/webui/index.zul and official 394 database.

**Comment by yamelsenih** [comment]
Hello @marcalwestf the problem is not for complete, the problem is when you reverse document

**Comment by yamelsenih** [comment]
I will review this pull request

**Comment by yamelsenih** [comment]
Hello @marcalwestf the problem is that the Quantity On Hand should be in **Store West**
@
Screenshot from 2023-11-15 16-39-19

**Comment by OFB-Review1** [comment]
@yamelsenih se realizaron las pruebas tratando de reproducir el error y no logre realizarlo. A continuación los pasos que seguí:

1. Crear un production batch
image

2. se comprobó existencia el producto
image

3. Al crear Production muestra el siguiente mensaje.
image

Por esta razón no puede revisarse este error.

**Comment by yamelsenih** [comment]
Hello @OFB-Review1 I saw that you show a image with **Quantity On Hand** of **Fertilizer#50** but the missing quantity is for **Bag 50 Kg**. I think that you don't have a complete behavior.

Remember: A production of **Fertilizer #50** need almost **Bag 50Kg** and **Lawn Fertilizer**

See a image of BOM for **Fertilizer #50**
Screenshot from 2023-11-17 17-53-13

You should check availability for **Bag 50Kg** and **Lawn Fertilizer** instead :(

**Comment by marcalwestf** [comment]
You're right @yamelsenih , it has to be tested correctly

**Comment by marcalwestf** [comment]
@yamelsenih  hi Yamel, **at last, I managed to reproduce the error**: in both cases before, the production batch was done against a product without BOM.

I now made sure the product had a BOM.

**REPRODUCE THE ERROR**

1.- Select a product to be produced, e.g. _Assembly Front Leg_. Make sure that the product has the fields _Bill of Materials_, _Verified_ and _Stocked_ activated.
image

2.- Get the material needed to produced the amount specified in the Pull request. In our case, by completing a Material Receipt in the Location we want to produce:
image

3.- Create and complete a _Production Order Batch_, with the Field _Automatic Production_ deactivated. Make sure you produce on the same locator as the Material Receipt received the items:
image

4.- Open _Production_ window, create a new record, select the previous batch created and complete production
image
image

5.- Check created items
image

6.- Open Production Batch and  assess that the target quantity is kept instead of being set to "0"
image
image

7.- Result: error was reproduced as explained in Pull Request.


**NOW, WE PROCEED TO REPRODUCE THE BUG FIX**


8.- Create and complete a _Production Order Batch_, this time with the Field _Automatic Production_ activated. Make sure you produce on the same locator as the Material Receipt received the items:
image

9.- Open Production window, complete production generated from batch
image

10.- Now reverse production (I selected the action _Void_, but the same occurs with _Reverse Accrual_ and _Reverse Correct_)
image


I don't know if this is correct. It seems rather a  database error, complaining about a foreign key.

**Comment by yamelsenih** [comment]
> @yamelsenih hi Yamel, **at last, I managed to reproduce the error**: in both cases before, the production batch was done against a product without BOM.
> 
> I now made sure the product had a BOM.
> 
> **REPRODUCE THE ERROR**
> 
> 1.- Select a product to be produced, e.g. _Assembly Front Leg_. Make sure that the product has the fields _Bill of Materials_, _Verified_ and _Stocked_ activated. image
> 
> 2.- Get the material needed to produced the amount specified in the Pull request. In our case, by completing a Material Receipt in the Location we want to produce: image
> 
> 3.- Create and complete a _Production Order Batch_, with the Field _Automatic Production_ deactivated. Make sure you produce on the same locator as the Material Receipt received the items: image
> 
> 4.- Open _Production_ window, create a new record, select the previous batch created and complete production image image
> 
> 5.- Check created items image
> 
> 6.- Open Production Batch and assess that the target quantity is kept instead of being set to "0" image image
> 
> 7.- Result: error was reproduced as explained in Pull Request.
> 
> **NOW, WE PROCEED TO REPRODUCE THE BUG FIX**
> 
> 8.- Create and complete a _Production Order Batch_, this time with the Field _Automatic Production_ activated. Make sure you produce on the same locator as the Material Receipt received the items: image
> 
> 9.- Open Production window, complete production generated from batch image
> 
> 10.- Now reverse production (I selected the action _Void_, but the same occurs with _Reverse Accrual_ and _Reverse Correct_) image
> 
> I don't know if this is correct. It seems rather a database error, complaining about a foreign key.

Hello @marcalwestf please remove this constraints and test it again.

I will create a new pull request to resolve the constraints.

**Comment by marcalwestf** [comment]
@yamelsenih  OK

**Review by marcalwestf — COMMENTED** [review]
Drop Constraint on database:
image


Execute reverse:
image

Result (original document): 
image
image


Result (reversal document. See negative quantities)
image
image

Dropping the constraint does the job.

I wonder what's best: accept this pull request knowing that the reversal will produce an exception or perhaps better add/modify the _drop constraint_ in this pull request so it is solved altogether?

**Comment by marcalwestf** [comment]
... as you said, both are different errors, I will accept this PR and wait for the other...

**Review by marcalwestf — APPROVED** [review]
See comments above.
All tests passed.

**Pull request merged**
