### PR TITLE
#4035 [Feature Request] Create the new ADempiere 3.9.4 https://github…

### PR DESCRIPTION
**Pull request by e-Evolution**
….com/adempiere/adempiere/issues/4035

### CODE REVIEW

**Comment by marcalwestf** [comment]
starting test....

**Review by marcalwestf — APPROVED** [review]
- Build ADempiere based on branch
- Install pointing to a new database
- Execute RUN_ImportAdempiere.sh
- Execute RUN_MigrateXML.sh 

Seed 394 was created.
Some basic tests done.

Test passed.

**Review by marcalwestf — COMMENTED** [review]
**Additional comments**

The tests were done in the following context:
- Postgres 10
- Ubuntu 18.04 

Due to the old database used, there were problems with the XML files expanding the fields _Name_ and _Name2_ from table _C_BPartner_, and _Description_ from table _C_Order_ and _C_Invoice_. 

They had to be changed manually. This meant in detail to first delete all dependent views, do the expansion, and then re-create the views. I suppose this will be not an issue on newer databases.

@e-Evolution asked to do an additional test: to run  _Initial Client Setup Process_.

There is an error when creating a new client with the process _Initial Client Setup Process_. This is likely not the fault of this pull request, but perhaps from former pull requests.
Selection_438

Excerpts from the exceptions produced are: 

```
-----------> MBPGroup.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)
        at org.compiere.model.PO.insert_Accounting(PO.java:3531)
.....
===========> MSetup.createBPGroups: BP Group NOT inserted [143]
-----------> MBPartner.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)
------
-----------> MProductCategory.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)
.........
-----------> MTax.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)
.......
09:32:44.249 LiberoValidator.modelChange: M_Product Type: 1 [143]
-----------> MProduct.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)

.....
-----------> MWarehouse.saveFinish: afterSave [143]
java.lang.NullPointerException
        at org.compiere.model.MAcctSchema.getClientAcctSchema(MAcctSchema.java:106)

.........
===========> DB.executeUpdate: INSERT INTO M_ProductPrice (Created,IsActive,Updated,PriceStd,PriceLimit,PriceList,AD_Client_ID,AD_Org_ID,UpdatedBy,CreatedBy,UUID,M_ProductPrice_ID,M_PriceList_Version_ID,M_Product_ID) VALUES (TO_TIMESTAMP('2022-12-30 09:32:44','YYYY-MM-DD HH24:MI:SS'),'Y',TO_TIMESTAMP('2022-12-30 09:32:44','YYYY-MM-DD HH24:MI:SS'),1.00,1.00,1.00,1000001,1000001,100,100,'5552a85a-4b6f-4c48-974a-866ee87d3586',1000000,1000000,1000000) [Setup_a2cb83a3-69c0-408f-acbd-aaddc80f8cc0] [143]
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "m_productprice_key"
  Detail: Key (m_productprice_id)=(1000000) already exists.; State=23505; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
)

===========> DB.saveError: DBExecuteError - ERROR: duplicate key value violates unique constraint "m_productprice_key"
.........
===========> Trx.commit: Setup_a2cb83a3-69c0-408f-acbd-aaddc80f8cc0 [143]
org.postgresql.util.PSQLException: ERROR: insert or update on table "c_bpartner_location" violates foreign key constraint "cbpartner_cbplocation"
  Detail: Key (c_bpartner_id)=(1000000) is not present in table "c_bpartner".; State=23503; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)

.....
===========> InitialClientSetup.process: Error while creating the Accounting Setup. 
Check the error log and the format of the Accounting*.cvs file - No duplicate Accounts and all all defaut accounts must be included (even if you will not use them). [143]
org.adempiere.exceptions.AdempiereException: Error while creating the Accounting Setup. 
Check the error log and the format of the Accounting*.cvs file - No duplicate Accounts and all all defaut accounts must be included (even if you will not use them).
        at org.adempiere.process.InitialClientSetup.doIt(InitialClientSetup.java:187)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:176)

```

The accounting import file was already tested with other clients in different contexts.

I would not make the acceptance of this pull request on solving the error described; nevertheless, it is an error that has to be tackled as soon as possible.

**Review by marcalwestf — COMMENTED** [review]
In case of any need, here's the SQL needed to manually modify the size of fields _Name_ and _Name2_  of table _C_BPartner_:

```
DROP VIEW adempiere.rv_hr_processdetail;
DROP VIEW adempiere.rv_hr_employeebankaccount;
DROP VIEW adempiere.rv_hr_employeedependent;
DROP VIEW adempiere.rv_hr_employeesalarychange;
DROP VIEW adempiere.rv_hr_employee;

DROP VIEW adempiere.rv_reconciliation;
DROP VIEW adempiere.rv_fact_acct;

DROP VIEW adempiere.rv_bpartner;
DROP VIEW adempiere.m_inout_header_vt;
DROP VIEW adempiere.m_inout_header_v;

DROP VIEW adempiere.dd_order_header_v;
DROP VIEW adempiere.dd_order_header_vt;

DROP VIEW adempiere.c_rfqresponse_vt;
DROP VIEW adempiere.c_rfqresponse_v;

DROP VIEW adempiere.c_project_header_vt;
DROP VIEW adempiere.c_project_header_v;

DROP VIEW adempiere.c_payselection_check_vt;
DROP VIEW adempiere.c_payselection_check_v;

DROP VIEW adempiere.c_order_linetax_vt;
DROP VIEW adempiere.c_order_linetax_v;

DROP VIEW adempiere.c_order_header_vt;
DROP VIEW adempiere.c_order_header_v;

DROP VIEW adempiere.c_invoice_header_vt;
DROP VIEW adempiere.c_invoice_header_v;

DROP VIEW adempiere.c_dunning_header_vt;
DROP VIEW adempiere.c_dunning_header_v;

alter table adempiere.c_bpartner alter column name type character varying(255);
alter table adempiere.c_bpartner alter column name2 type character varying(255);
```

Same with field Description of tables _C_Order_ and _C_Invoice_:
```
DROP VIEW adempiere.rv_combinedopenitem;
DROP VIEW adempiere.rv_openitem;
DROP VIEW adempiere.rv_openitemtodate;

DROP VIEW adempiere.rv_c_invoice_customerprodqtr;
DROP VIEW adempiere.rv_c_invoice_customervendqtr;
DROP VIEW adempiere.rv_c_invoice_day;
DROP VIEW adempiere.rv_c_invoice_month;
DROP VIEW adempiere.rv_c_invoice_prodmonth;
DROP VIEW adempiere.rv_c_invoice_productmonth;
DROP VIEW adempiere.rv_c_invoice_productqtr;
DROP VIEW adempiere.rv_c_invoice_prodweek;
DROP VIEW adempiere.rv_c_invoice_vendormonth;
DROP VIEW adempiere.rv_c_invoice_week;
DROP VIEW adempiere.rv_c_invoiceline;
DROP VIEW adempiere.rv_c_invoice;

DROP VIEW adempiere.c_invoice_header_v;
DROP VIEW adempiere.c_invoice_header_vt;
DROP VIEW adempiere.t_invoicegl_v;
DROP VIEW adempiere.t_invoicegl_vt;
DROP VIEW adempiere.c_invoice_v1;


DROP VIEW adempiere.rv_bpartneropen;
DROP VIEW adempiere.c_invoiceline_v;
DROP VIEW adempiere.c_invoice_v;

DROP VIEW adempiere.c_dunning_line_vt;
DROP VIEW adempiere.c_dunning_line_v;

alter table adempiere.C_Invoice alter column description type character varying(16000);
```

Additionally, it has to be synchronized with the _Application Dictionary_.
The deleted Views have to be saved before deletion and re-created after column size modification.

**Comment by piracio** [comment]
To TEST:
git fetch pull/4036/head:4036
git checkout 4036
...

**Review by marcalwestf — COMMENTED** [review]
- build with newest commits: OK
- Install: OK
- Load and apply 09890_4035_Add_Foreign_Keys_3_9_4.xml: OK

**Review by marcalwestf — APPROVED** [review]
- Code review: OK
- Compile: OK
- Build: OK
- Installation: OK
- Basic tests done in former review: passed
- Initial Client Setup Process: passed

**Pull request merged**
