### PR TITLE
Add Time and Attendance Management for ADempiere core

### PR DESCRIPTION
**Pull request by yamelsenih**
This is a great functionality for Time and Attendance Management.
See: https://en.wikipedia.org/wiki/Time_and_attendance

This is a pull request that result from project https://github.com/adempiere/adempiere/projects/26

Please take a time for read project description and project changes

Time and Attendance Management is a project for handle all attendance for Human Resource, It allows record all attendance from employees.

After entered all attendance is possible determinated what is result for payroll process as Action Notice directly.

A short definition is [https://en.wikipedia.org/wiki/Time_and_attendance](https://en.wikipedia.org/wiki/Time_and_attendance)

The scope is:
 - Enter TNA.
 - Handle Shift Group
 - Handle Shift Wotk
 - Handle Work Group
 - Add Time relation with concept
 - Define Shift Rotatio
 - Define default action notice for shift
 - Convert attendance record to Action Notice

Here a ER Diagram:
time-and-attendance

Fixes: #1834 
Fixes: #1846
Fixes: #1870
Fixes: #1872
Fixes: #2013
Fixes: #2014
Fixes: #2015
Fixes: #2016
Fixes: #2017
Fixes: #2019
Fixes: #2021
Fixes: #2022
Fixes: #2024
Fixes: #2025
Fixes: #2026
Fixes: #2027

From: https://github.com/adempiere/adempiere/pull/2646

### CODE REVIEW

**Comment by adaxa-steven** [comment]
Hi Yamel
how are you handling data input?
would this form be able to be used. It is presently configured to capture hours on a project/phase/task that the user is permitted to work on.  It was painful to write but seems ok now.
regards
image

**Comment by yamelsenih** [comment]
Hi @adaxa-steven the form is nice....

We add a Smart Browser for cap Beginning Time and Ending Time for days based on Shift Work, also exists a importer for Attendance from External device:
Screenshot_20190702_095739
Screenshot_20190702_095759
Screenshot_20190702_100010
Screenshot_20190702_100025

**Comment by yamelsenih** [comment]
> Hi Yamel
> how are you handling data input?
> would this form be able to be used. It is presently configured to capture hours on a project/phase/task that the user is permitted to work on. It was painful to write but seems ok now.
> regards
> image

Maybe this can be useful for entry Timesheet tracking instead Attendance Time

Have toy a source code for it?

We want integrate to ADempiere

**Comment by niclopup** [comment]
Hi everyone! 

This is a very usefull functionallity to add to ADempiere!

@yamelsenih or @adaxa-steven It would be great if we can support also the "Time Entry" to the Requests, not only the Proyects, in order to became ADempiere in an Issue Tracker also, with time tracking.

**Comment by e-Evolution** [comment]
@yamelsenih , I tried create an seed from 3.9.2 , and got error :

image


----------> MMigrationStep.bailout: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 100; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "hr_leave" are not allowed [1]
-----------> MMigrationStep.bailout: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D) ; Step: 100; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "hr_leave" are not allowed [1]
17:00:58.803   GridField.loadLookup: (AccessLevel) [1]
17:00:58.803   GridField.loadLookup: (ReplicationType) [1]
17:00:58.809   MMigration.syncColumn: Synchronizing column: MColumn[0-null] in table: MTable[0-null] [1]
17:00:58.809   GridField.loadLookup: (AccessLevel) [1]
17:00:58.809   GridField.loadLookup: (ReplicationType) [1]
-----------> MMigration.apply: @NotFound@ @AD_Table_ID@ 0 [1]
-----------> MMigration.apply: @NotFound@ @AD_Table_ID@ 0 [1]
17:00:58.803   GridField.loadLookup: (AccessLevel) [1]
17:00:58.803   GridField.loadLookup: (ReplicationType) [1]
17:00:58.809   MMigration.syncColumn: Synchronizing column: MColumn[0-null] in table: MTable[0-null] [1]
17:00:58.809   GridField.loadLookup: (AccessLevel) [1]
17:00:58.809   GridField.loadLookup: (ReplicationType) [1]
17:00:58.876   MMigration.updateStatus: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D)  ---> Partially Applied (P) [1]
17:00:58.876   MMigration.updateStatus: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D)  ---> Partially Applied (P) [1]
17:00:58.930   MMigration.updateStatus: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D)  ---> Partially Applied (P) [1]
17:00:58.930 MigrationApply.addLog: 0 - null - null - @NotFound@ @AD_Table_ID@ 0 [1]
17:00:58.930   MMigration.updateStatus: Migration 5020 - HR Attendance: Define E-R Model #1834 - 3.9.3 (D)  ---> Partially Applied (P) [1]
17:00:58.930 MigrationApply.addLog: 0 - null - null - @NotFound@ @AD_Table_ID@ 0 [1]
17:00:58.936 Msg.initMsg: Records=1539 - en_US [1]
17:00:58.936 Msg.initMsg: Records=1539 - en_US [1]
17:00:58.943   MIssue.create: * Not found * Table 0 [1]
17:00:58.944   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: * Not found * Table 0 [1]
org.adempiere.exceptions.AdempiereException: * Not found * Table 0
	at org.compiere.model.MMigration.apply(MMigration.java:174)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:227)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:54)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:300)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:184)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:165)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
caused by: org.adempiere.exceptions.AdempiereException: * Not found * Table 0
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:713)
	at org.compiere.model.MMigration.syncColumn(MMigration.java:461)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:00:58.943   MIssue.create: * Not found * Table 0 [1]
17:00:58.944   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: * Not found * Table 0 [1]
org.adempiere.exceptions.AdempiereException: * Not found * Table 0
	at org.compiere.model.MMigration.apply(MMigration.java:174)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:227)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:54)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:300)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:184)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:165)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
caused by: org.adempiere.exceptions.AdempiereException: * Not found * Table 0
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:713)
	at org.compiere.model.MMigration.syncColumn(MMigration.java:461)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:00:59.142 Trx.rollback: **** TrxRun_1d40d1f9-28eb-4755-b558-e5be52e42665 [1]
17:00:59.142 Trx.rollback: **** TrxRun_1d40d1f9-28eb-4755-b558-e5be52e42665 [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/develop/migration/392lts-393lts/05020_Add_TNA_Functionality.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:170)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  * Not found * Table 0
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:308)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:184)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:165)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

17:00:59.144   MIssue.create: Loading Migration from XML failed. [1]
17:00:59.144   MIssue.create: Loading Migration from XML failed. [1]
17:00:59.145   GridField.loadLookup: (SystemStatus) [1]
17:00:59.145   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/develop/migration/392lts-393lts/05020_Add_TNA_Functionality.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:170)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  * Not found * Table 0
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:308)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:184)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:165)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:143)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Loading Migration from XML failed.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:280)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:80)

*** 2019-07-02 17:00:59.188 Adempiere Log (CLogConsole) ***

**Comment by e-Evolution** [comment]
@yamelsenih can please rename the directory your contribution from org.spin.hr_tna to org.spin.hr_time _and_attendance, we should be explicit with directories name

**Comment by yamelsenih** [comment]
> @yamelsenih can please rename the directory your contribution from org.spin.hr_tna to org.spin.hr_time _and_attendance, we should be explicit with directories name

Ok lets

**Comment by yamelsenih** [comment]
I test it and worked from a seed database, I will to add missing columns

**Comment by yamelsenih** [comment]
I will do a new Pull Request for it

**Pull request closed without merging**
