### PR TITLE
adempiere:#1560 Commission for complete payments: commissions from pa…

### PR DESCRIPTION
**Pull request by SusanneCalderon**
…st months are calculated and displayed

https://github.com/adempiere/adempiere/issues/1560
Correct the xml in line 20 and 44 and change from line seperator CRLF to LF.

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih . I corrected the xml file for the oracle function and the ddl in  /db/ddlutils/oracle/functions

**Comment by RJPC** [comment]
Hi @SusanneCalderon 

**1-** Currently when the invoice is paid in full partially and one of the payments is reversed, still generates commission about the invoice.

**Invoice:** is not yet marked as paid.
invoice

**Open Balances**
open

**Paid Invoice:** it can be seen that the assignment is reversed
facturas pagadas

**Allocations**
asignacion

**Calculation of Commissions:** it can be seen that ADempiere is generating calculation on the amount paid to the invoice
commission

**Total Commission**
line commission

**2-** Does not show the invoice to commission

**Detail Commission**
detail commission

**Comment by SusanneCalderon** [comment]
Hi @RJPC , I will test the cases now and upload the videos.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon can you resolve it conflict?

**Pull request merged**
