### PR TITLE
#1769 Restore password login

### LINKED ISSUE #1769: Add option to restore the password from the login
Currently in adempiere if you forget the password you can not access

### PR DESCRIPTION
**Pull request by yamelsenih**
Hi guys it is a great pull request for users when they forgot password.

It is from https://github.com/adempiere/adempiere/issues/1769

Please review it.

Best regard

fixes #1769

### CODE REVIEW

**Comment by marcalwestf** [comment]
... now the sequence for AD_Token has been created in AD_Sequence.

But when assking for password , the error is now

```
14:58:09,510 ERROR [STDERR] -----------> EMail.isValid: SMTP Host is invalidnull [54]
14:58:09,511 ERROR [STDERR] -----------> EMail.isValid: SMTP Host is invalidnull [54]
```

**Comment by yamelsenih** [comment]
Hi All, i will to describe Step by Step on my site:

 - Import XML
 - Create a new config and test it for client:
screenshot_20181001_233236
 - Note that exist a Email Template for Reset password now:
screenshot_20181001_233126
 - Add EMail for my user (SuperUser) 
screenshot_20181001_234348
 - Run ADempiere Server
 - Go to Login and press **Forgot Password?**
screenshot_20180930_174343
 - Put muy user value **SuperUser** 
screenshot_20181001_233505
 - Go to my EMail: 
screenshot_20181001_233533
 - Press Token buton: 
screenshot_20181001_233546
 - Set my new Password and automatically is loaded **Role Panel** 
screenshot_20181001_233558
screenshot_20181001_233610

Note: you can add **Token Definition** and **Token** window to role for view generated token or change **Token Generator** class

screenshot_20181001_233635

**Comment by ayazbaloch** [comment]
Great effort of @yamelsenih and his team.

**Comment by yamelsenih** [comment]
Thank you @ayazbaloch I hope that it can be useful for all

**Comment by e-Evolution** [comment]
Fixes

**Pull request merged**
