### PR TITLE
#2034 Add Icon Image for any column defined as Button

### PR DESCRIPTION
**Pull request by e-Evolution**
…com/adempiere/adempiere/issues/2034

(cherry picked from commit 1e6cbe54cd243eb12e767303155f6c674da795bb)

### CODE REVIEW

**Comment by marcalwestf** [comment]
There is always an error, when Column and Field definitions are in the same XML.

They have to be in separate files, as the migration process does not commit after each step.

This is the error produced:
20180929_button_01

**Comment by yamelsenih** [comment]
I will test it

**Comment by yamelsenih** [comment]
I find a error:
<pre>
*** 2018-09-29 22:10:11.435 Adempiere Log (CLogConsole) ***
22:10:11.435 Adempiere.startup: ADempiere(r) Release 3.9.0_2017-08-01 -Smart Suite ERP,CRM and SCM- (c) 1999-2017 ADempiere(r); Implementation: ADempiere - Supported by ADempiere community [1]
22:10:11.544 Ini.loadProperties: /opt/Development/ADempiere_Properties/ADempiere_390_Fork_Pull.properties #37 [1]
[INFO] MLog clients using com.mchange.v2.log.FallbackMLog logging.
[INFO] Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? true; trace: 10]
[INFO] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 2, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> AdempiereDS, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kfsx9yb83bjwtuiuzj|32cf48b7, idleConnectionTestPeriod -> 1200, initialPoolSize -> 1, jdbcUrl -> jdbc:postgresql://localhost:5432/ERP?encoding=UNICODE, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 900, maxIdleTimeExcessConnections -> 1200, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> SELECT Version FROM AD_System, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
[INFO] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 2, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> AdempiereDS, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kfsx9yb83bjwtuiuzj|7d7f3de2, idleConnectionTestPeriod -> 1200, initialPoolSize -> 1, jdbcUrl -> jdbc:postgresql://localhost:5432/AD391Seed?encoding=UNICODE, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 900, maxIdleTimeExcessConnections -> 1200, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> SELECT Version FROM AD_System, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
[INFO] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 2, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> AdempiereDS, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kfsx9yb83bjwtuiuzj|52c1a858, idleConnectionTestPeriod -> 1200, initialPoolSize -> 1, jdbcUrl -> jdbc:postgresql://localhost:5432/AD391Seed?encoding=UNICODE, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 900, maxIdleTimeExcessConnections -> 1200, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> SELECT Version FROM AD_System, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT COALESCE(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_MigrationStep WHERE AD_MigrationStep_ID=@AD_MigrationStep_ID@ [59]
-----------> MColumn.load: NO Data found for AD_Column_ID=90939 [59]
-----------> GenericPO.set_ValueNoCheck: AD_Language - Class invalid: class java.lang.Integer, Should be class java.lang.String: 0 [59]
-----------> MColumn.load: NO Data found for AD_Column_ID=90940 [59]
-----------> GenericPO.set_ValueNoCheck: AD_Language - Class invalid: class java.lang.Integer, Should be class java.lang.String: 0 [59]
===========> MField.load: AD_Field_ID=91382, SQL=SELECT Description,IsFieldOnly,AD_ContextInfo_ID,isQuickEntry,IsActive,Created,Updated,IsDisplayedGrid,IsEmbedded,IsAllowCopy,IsDisplayed,IsSameLine,IsHeading,SortNo,IsCentrallyMaintained,Name,IsReadOnly,Help,ObscureType,DisplayLogic,AD_Reference_ID,IsMandatory,DefaultValue,InfoFactoryClass,Included_Tab_ID,PreferredWidth,IsEncrypted,AD_Reference_Value_ID,UpdatedBy,CreatedBy,AD_Field_ID,EntityType,AD_Org_ID,AD_Client_ID,SeqNoGrid,DisplayLength,AD_Tab_ID,SeqNo,AD_FieldGroup_ID,AD_Val_Rule_ID,AD_Column_ID,UUID,AD_Image_ID FROM AD_Field WHERE AD_Field_ID=? [59]
org.postgresql.util.PSQLException: ERROR: column "ad_image_id" does not exist
  Position: 514; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.PO.load(PO.java:1412)
	at org.compiere.model.PO.load(PO.java:1369)
	at org.compiere.model.PO.<init>(PO.java:229)
	at org.compiere.model.PO.<init>(PO.java:178)
	at org.compiere.model.X_AD_Field.<init>(X_AD_Field.java:40)
	at org.compiere.model.MField.<init>(MField.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

-----------> GridField.getDefault: (SeqNoGrid) - Default SQL variable parse failed: @SQL=SELECT NVL(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_Field WHERE AD_Tab_ID=@AD_Tab_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT NVL(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_Field WHERE AD_Tab_ID=@AD_Tab_ID@ [59]
===========> MField.load: [POSave_4bb30444-d572-4fea-82b7-aeae7aa31d7d] - AD_Field_ID=91382, SQL=SELECT Description,IsFieldOnly,AD_ContextInfo_ID,isQuickEntry,IsActive,Created,Updated,IsDisplayedGrid,IsEmbedded,IsAllowCopy,IsDisplayed,IsSameLine,IsHeading,SortNo,IsCentrallyMaintained,Name,IsReadOnly,Help,ObscureType,DisplayLogic,AD_Reference_ID,IsMandatory,DefaultValue,InfoFactoryClass,Included_Tab_ID,PreferredWidth,IsEncrypted,AD_Reference_Value_ID,UpdatedBy,CreatedBy,AD_Field_ID,EntityType,AD_Org_ID,AD_Client_ID,SeqNoGrid,DisplayLength,AD_Tab_ID,SeqNo,AD_FieldGroup_ID,AD_Val_Rule_ID,AD_Column_ID,UUID,AD_Image_ID FROM AD_Field WHERE AD_Field_ID=? [59]
org.postgresql.util.PSQLException: ERROR: column "ad_image_id" does not exist
  Position: 514; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.PO.load(PO.java:1412)
	at org.compiere.model.PO.saveNew(PO.java:2870)
	at org.compiere.model.PO.save(PO.java:2195)
	at org.compiere.model.PO.saveEx(PO.java:2279)
	at org.compiere.model.PO.saveEx(PO.java:2409)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:602)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)

===========> MField.saveNew: [POSave_4bb30444-d572-4fea-82b7-aeae7aa31d7d] - reloading [59]
-----------> MMigrationStep.bailout: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 50; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: SaveError [59]
-----------> MMigration.apply: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 50; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: SaveError [59]
-----------> MField.load: NO Data found for AD_Field_ID=91382 [59]
-----------> GridField.getDefault: (SeqNoGrid) - Default SQL variable parse failed: @SQL=SELECT NVL(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_Field WHERE AD_Tab_ID=@AD_Tab_ID@ [59]
-----------> GridField.getDefault: (SeqNo) - Default SQL variable parse failed: @SQL=SELECT NVL(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_Field WHERE AD_Tab_ID=@AD_Tab_ID@ [59]
===========> Trx.commit: POdel_3eab2b40-b23a-45ba-80eb-c40a8d80c575 [59]
org.postgresql.util.PSQLException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field".; State=23503; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:739)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:760)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:803)
	at org.compiere.util.Trx.commit(Trx.java:336)
	at org.compiere.model.PO.delete(PO.java:3172)
	at org.compiere.model.PO.deleteEx(PO.java:3210)
	at org.compiere.model.PO.deleteEx(PO.java:3243)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:682)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:297)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:204)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)

===========> MColumn.saveError: Error - ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field". [59]
-----------> MMigrationStep.bailout: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD.  Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field". [59]
-----------> MMigration.apply: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD. Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field". [59]
===========> MigrationApply.process: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD. Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field". [59]
org.adempiere.exceptions.AdempiereException: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD. Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field".
	at org.compiere.model.MMigration.apply(MMigration.java:174)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
	at org.eevolution.service.dsl.ProcessBuilder.access$2(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:289)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:286)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:182)
	at org.compiere.process.MigrationFromXML.lambda$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
caused by: org.adempiere.exceptions.AdempiereException: Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD. Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field".
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:272)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:739)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:297)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:204)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field".
	at org.compiere.model.PO.deleteEx(PO.java:3217)
	at org.compiere.model.PO.deleteEx(PO.java:3243)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:682)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:297)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:204)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

===========> MigrationFromXML.process: Loading Migration from XML failed. [59]
org.adempiere.exceptions.AdempiereException: Loading migration from /tmp/04050_2034_AddIconForAnyColumnDefinedAsButton.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 4050 - Add Icon Image for any column defined as Button #2034 - 3.9.1 (D) ; Step: 10; Type: AD. Rollback failed. org.adempiere.exceptions.AdempiereException: ERROR: update or delete on table "ad_column" violates foreign key constraint "ad_column_field" on table "ad_field"
  Detail: Key (ad_column_id)=(90939) is still referenced from table "ad_field".
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:182)
	at org.compiere.process.MigrationFromXML.lambda$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)


</pre>

**Comment by marcalwestf** [comment]
Adding an image to Invoice's _Copy Lines_ button (just for testing's sake).
In production environment it should of course have the correct dimensions:
20181001_icon_01

**Pull request merged**
