### PR TITLE
Synchronize e-Evolution develop brach with ADempiere

### PR DESCRIPTION
**Pull request by e-Evolution**
#1608 Enhancement Update IntelliJ and Scala setting
#1609 Enhancement Move Scala Testing for Test Scala Directory
#1553 HHRR: New SmartBrowser to generate invoices for accumulated
-Fix Script Migration
#1560 Commission for complete payments: commissions from past months
-Fix Script Migration
#1564 Add Project Model Validator to Catch multiples Events
#1580 The enhancement allows defining the payment document type into the document type for pay selection.
#1595 Enable migration script for ADempiere 3.9.0.a
#1415 Barcode Scanner Products Not is Functionality whit Attribute
#1294 Add to support ZK Web debugging using IntelliJ
#1499 Defining two Standard Request Type associated

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution i see a changes for XML that already exist, this changes just remove some steps of XML, i want to know if the removed steps is created in other XML for 3.9.1 or exist other way for resolve it.

Best Regard

**Comment by e-Evolution** [comment]
Hi @yamelsenih, you are in rightly, I removed this columns for column view that no are showed and used , I suppose that was generate when the smart browser was created, but not should exist dependences between improves given the should be agnostic, So 2 columns that was added in other XML 03630_1552_HHRR_FlagPostIndividually.xml was infected into of 03640_1553_SB_HHRR_CreateInvoice_View.xml , as good practice any improves not should infect with changes from other improves , each improve should be agnostic the other.

**Comment by yamelsenih** [comment]
I think that it is ok, but i need know if it will be added in other XML or exist a method for keep the original changes in a upgrade

**Comment by e-Evolution** [comment]
@yamelsenih the two the view columns that were deleted do not affect the operation of the new smart browser since these columns are not displayed in the smart browser, so the change does not represent a risk.

**Comment by marcalwestf** [comment]
Reviewed changes for  issu https://github.com/adempiere/adempiere/issues/1560. No objection this issue concerned.

**Pull request merged**
