### PR TITLE
#3811 [Feature Request] Add support to functionality Adjustment Perio…

### PR DESCRIPTION
**Pull request by e-Evolution**
…d https://github.com/adempiere/adempiere/issues/3811

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
@e-Evolution , hello Victor, can you please explain the purpose of this adjustment and how it can be tested?

**Review by SusanneCalderon — CHANGES_REQUESTED** [review]
The callout calloutGLJournal, method period must be adjusted. Currently the search for c_Period_ID excludes periods type adjustment.

```
String sql = "SELECT C_Period_ID "
				+ "FROM C_Period "
				+ "WHERE C_Year_ID IN "
				+ "	(SELECT C_Year_ID FROM C_Year WHERE C_Calendar_ID ="
				+ "  (SELECT C_Calendar_ID FROM AD_ClientInfo WHERE AD_Client_ID=?))"
				+ " AND ? BETWEEN StartDate AND EndDate"
				// globalqss - cruiz - Bug [ 1577712 ] Financial Period Bug
				+ " AND IsActive='Y'"
				+ " AND PeriodType='S'"
				;
```
Solution:

```

			String sql = "SELECT C_Period_ID "
				+ "FROM C_Period "
				+ "WHERE C_Year_ID IN "
				+ "	(SELECT C_Year_ID FROM C_Year WHERE C_Calendar_ID ="
				+ "  (SELECT C_Calendar_ID FROM AD_ClientInfo WHERE AD_Client_ID=?))"
				+ " AND ? BETWEEN StartDate AND EndDate"
				// globalqss - cruiz - Bug [ 1577712 ] Financial Period Bug
				+ " AND IsActive='Y'"
				//+ " AND PeriodType='S'"
				;
```

**Comment by e-Evolution** [comment]
@SusanneCalderon Hi Susanne, thank you for the revision, I implemented your suggestion for Callout, would you test and send me your feedback?

**Review by SusanneCalderon — CHANGES_REQUESTED** [review]
Tested with Journal without problems.

Starting with a Journalbatch does not return a period. The method FindByCalendar, which is used in MJournalbatch.prepareIt() only returns standard periods.


	```
	//	Get it from DB
	    MPeriod retValue = null;
		String sql = "SELECT * "
			+ "FROM C_Period "
			+ "WHERE C_Year_ID IN "
				+ "(SELECT C_Year_ID FROM C_Year WHERE C_Calendar_ID= ?)"
			+ " AND ? BETWEEN TRUNC(StartDate, 'DD') AND TRUNC(EndDate, 'DD')"
			+ " AND IsActive=? AND PeriodType=?";
        
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		try
		{
			pstmt = DB.prepareStatement(sql, trxName);
            pstmt.setInt (1, C_Calendar_ID);
            pstmt.setTimestamp (2, TimeUtil.getDay(DateAcct));
            pstmt.setString(3, "Y");
            pstmt.setString(4, "S");
			rs = pstmt.executeQuery();
```

**Review by SusanneCalderon — APPROVED** [review]
With the last modifications the funcionality works without problems. Great feature

**Pull request merged**
