### PR TITLE
#3959 [Bug Report] Tomcat does not exist in the Read Connection Pool …

### PR DESCRIPTION
**Pull request by e-Evolution**
…https://github.com/adempiere/adempiere/issues/3959

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @e-Evolution Victor, just had a glance at the changes.

Could you explain to me the motivation for the change (the use of the file `lib/context.xml`) and how to test this PR?

I checked that AdempiereSRDS occurs at the method `org.compiere.db.DB_PostgreSQL.getDataSourceShortRunning` (same for Oracle), but I don't quite grasp what is the use for it.

**Comment by e-Evolution** [comment]
> hi @e-Evolution Victor, just had a glance at the changes.
> 
> Could you explain to me the motivation for the change (the use of the file `lib/context.xml`) and how to test this PR?
> 
> I checked that AdempiereSRDS occurs at the method `org.compiere.db.DB_PostgreSQL.getDataSourceShortRunning` (same for Oracle), but I don't quite grasp what is the use for it.

Hi @marcalwestf ,  Hi Mario , of course in ADempiere 3.9.4 a new connection pool based on Hikari CP is implemented , in this new implementation ADempiere can manage two connection pools at the same time one for long duration transactions and one for short or reading transactions , the idea is that the statement as UPDATE , INSERT , DELETE go through the pool of connections with the JNDI AdempiereDS and the statement  SELECT go through the short transactions through the JNDI AdempiereSRDS, this allows you to define different parameters in the connections according to your requirements.

If no AdempiereSRDS is defined the system uses AdempiereDS by default, this change enables tomcat to display both connection pools.

**Review by marcalwestf — COMMENTED** [review]
- Build ADempiere: OK
- Install ADempiere on Tomcat: OK
- Run Adempiere on Swing (CRUD + SELECT):
An entry for **AdempiereDS** can be found, **but not for** **AdempiereRDDS**:
```
:
-----------> DB_PostgreSQL.getDataSource: Config Hikari Connection Pool Datasource [1]
[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Starting...
:
:
[main] INFO com.zaxxer.hikari.pool.HikariPool - AdempiereDS - Added connection org.postgresql.jdbc.PgConnection@4bff1903
[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Start completed.
-----------> DB_PostgreSQL.getDataSource: Starting Client Hikari Connection Pool [1]
:
```

- Run Adempiere on Tomcat  (CRUD + SELECT) seems also to instantiate AdempiereDS, but there is also an exception with Hikari:
imagen

```
:
11:31:15.295 Ini.loadProperties: /data2/app/Adempiere/Adempiere.properties #34 [1]
11:31:15.295 Ini.loadProperties: /data2/app/Adempiere/Adempiere.properties #34 [1]
[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Starting...
[main] INFO com.zaxxer.hikari.pool.HikariPool - AdempiereDS - Added connection org.postgresql.jdbc.PgConnection@37403f66
[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Start completed.
-----------> DB_PostgreSQL.lambda$getDataSource$0: Connection Lookup JNDI Datasource for java:comp/env/java/AdempiereDS Hikari Connection Pool [1]
-----------> DB_PostgreSQL.lambda$getDataSource$0: Connection Lookup JNDI Datasource for java:comp/env/java/AdempiereDS Hikari Connection Pool [1]
:
```

Result: records can be created, read, updated, and deleted. Also selects do work well due to the fact that some reports were called.
This means, the functionality is OK, but I ignore if the connections are set up as Victor explained. According to the logs both on Swing and Tomcat, I doubt it.

@e-Evolution Victor, perhaps you can tell us if it is OK or if something is missing.

**Comment by marcalwestf** [comment]
@e-Evolution Víctor, additionally to the remarks above: when Tomcat is shut down, the following error appears on log file _catalina.out_ :
```
 java.base@17.0.3/java.util.TimerThread.mainLoop(Timer.java:537)
 java.base@17.0.3/java.util.TimerThread.run(Timer.java:516) [1]
-----------> NamingResourcesImpl.cleanUp: Failed to retrieve JNDI resource [java/AdempiereSRDS] for container [StandardServer[8005]] so no cleanup was performed for that resource [1]
javax.naming.NamingException: Could not load resource factory class [Root exception is java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariJNDIFactory]
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:70)
	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:864)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:158)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:850)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
	at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1035)
	at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1003)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:989)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:811)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariJNDIFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:65)
	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:864)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:158)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:850)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
	at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1035)
	at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1003)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:989)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:811)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)

[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Shutdown initiated...
[main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Shutdown completed.
```

It is almost certain that the connection for AdempiereSRDS doesn't work.

**Comment by e-Evolution** [comment]
> @e-Evolution Víctor, additionally to the remarks above: when Tomcat is shut down, the following error appears on log file _catalina.out_ :
> 
> ```
>  java.base@17.0.3/java.util.TimerThread.mainLoop(Timer.java:537)
>  java.base@17.0.3/java.util.TimerThread.run(Timer.java:516) [1]
> -----------> NamingResourcesImpl.cleanUp: Failed to retrieve JNDI resource [java/AdempiereSRDS] for container [StandardServer[8005]] so no cleanup was performed for that resource [1]
> javax.naming.NamingException: Could not load resource factory class [Root exception is java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariJNDIFactory]
> 	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:70)
> 	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:864)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:158)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:850)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
> 	at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1035)
> 	at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1003)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:989)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:811)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
> 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
> caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariJNDIFactory
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:65)
> 	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:864)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:158)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:850)
> 	at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
> 	at org.apache.catalina.deploy.NamingResourcesImpl.cleanUp(NamingResourcesImpl.java:1035)
> 	at org.apache.catalina.deploy.NamingResourcesImpl.stopInternal(NamingResourcesImpl.java:1003)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:989)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:811)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
> 
> [main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Shutdown initiated...
> [main] INFO com.zaxxer.hikari.HikariDataSource - AdempiereDS - Shutdown completed.
> ```
> 
> It is almost certain that the connection for AdempiereSRDS doesn't work.

Hi @marcalwestf , the error show that > javax.naming.NamingException: Could not load resource factory class [Root exception is java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariJNDIFactory]

It seems that you are running the environment outside of the normal installation because it indicates that the Hikary CP jar is not found, if you are running Tomcat in debug mode from eclipse make sure you have HikariCP-5.0.1.jar in your path

kind regards
Victor

**Review by marcalwestf — COMMENTED** [review]
@e-Evolution  Victor, following your recommendation, and after copying the AdempiereSLib library as follows:
`cp $ADEMPIERE_HOME/lib/AdempiereSLib.jar $TOMCAT_HOME/lib `
the exception disappears.

Doing some random CRUD, there is no exception thrown and everything looks fine either on Swing log or on Tomcat log.

On the Tomcat log, it can be seen that `AdempiereDS` has been established, but I cannot see `AdempiereSRDS`, even after calling reports, doing CRUD, and navigating through several windows:
Selection_282

I wonder if this is OK, or if we should expect some feedback on the `AdempiereSRDS` connection,,,

**Comment by e-Evolution** [comment]
@marcalwestf can please testing again , the problem was solved

**Review by marcalwestf — APPROVED** [review]
### TEST
- Run again Tomcat; this time without manually copying any file to Tomcat
- The installation process itself copies some adempiere*.jar files to Tomcat/shared/lib and there is no exception  -> OK
Selection_345

- Do some CRUD  -> OK
- Shutdown Tomcat  -> OK

Test passed

### OBSERVATION
After shutting down the system, the following message appears on the Tomcat log.
This has apparently nothing to do with the changes of this pull request but it may have some repercussions on the memory.
I document it here in case this is taken up by anybody interested in the case:
```

===========> StandardWrapper.unload: InstanceManager.destroy() for servlet [zkLoader] threw exception [1]
java.lang.NullPointerException
	at org.apache.catalina.core.DefaultInstanceManager.destroyInstance(DefaultInstanceManager.java:197)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1322)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1606)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5465)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1414)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1403)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:988)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1414)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1403)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:988)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:502)

-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [webui] appears to have started a thread named [Thread-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.Thread.sleep(Native Method)
 org.zkoss.io.FileWatchdog.run(FileWatchdog.java:128) [1]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [webui] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.Object.wait(Native Method)
 java.base@11.0.11/java.lang.Object.wait(Object.java:328)
 java.base@11.0.11/java.util.TimerThread.mainLoop(Timer.java:527)
 java.base@11.0.11/java.util.TimerThread.run(Timer.java:506) [1]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [webui] appears to have started a thread named [Thread-6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.Thread.sleep(Native Method)
 org.adempiere.webui.dashboard.DashboardRunnable.run(DashboardRunnable.java:101)
```
imagen

**Pull request merged**
