### PR TITLE
#1632: SQL Error when a commission is running for orders

### PR DESCRIPTION
**Pull request by marcalwestf**
Solving issue  https://github.com/adempiere/adempiere/issues/1632

### CODE REVIEW

**Comment by beruskajimenez** [comment]
Hello @marcalwestf, at the moment of processing the commission for orders it throws the following SQL
image

**Comment by yamelsenih** [comment]
Hi @marcalwestf it have conflicting with some files, please review and change it for merge.

Best Regard

**Comment by marcalwestf** [comment]
hi @beruskajimenez, the original error as stated in issue https://github.com/adempiere/adempiere/issues/1632 states that function _linenetamtrealorderline()_ is not defined in the database.
As can be seen at the code changes, the function is now created and the error does no pop up any longer.

Thus, the error you report is an additional one. I agree to take it up in this pull request.
Could you tell me the class + method of the error? I would now sooner what 's it about.

**Comment by marcalwestf** [comment]
.... I think I found the error: right now , the code in _MCommissionRun.createDetail()_ from line 373 on is as follows:
```
  if (commission.isTotallyPaid()){
            	// Last payment must be within commission period 
                pstmt.setTimestamp(4, getStartDate());
                pstmt.setTimestamp(5, getEndDate());
            }
```
For calculaton on Commissions based on Orders, there are only 3 parameters in the underlying SQL, which leads to an Exception.

In order to avoid the exception, the code has to be changed to
```
  if (commission.getDocBasisType().equals(MCommission.DOCBASISTYPE_Receipt)
					&& commission.isTotallyPaid()){
            	// Last payment must be within commission period 
                pstmt.setTimestamp(4, getStartDate());
                pstmt.setTimestamp(5, getEndDate());
            }
```

**Comment by marcalwestf** [comment]
... now there is no Exception.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it have conflicts, canyou resolve it?

Best regard

**Comment by marcalwestf** [comment]
... now there are no conflicts

**Pull request merged**
