### PR TITLE
Add tax functionality to the requisition 

### LINKED ISSUE #3737: [Feature Request] Add tax functionality to the requisition
## Feature request
Currently adempiere does not allow the handling of taxes in the requisition, in some processes it is necessary to estimate the amount of taxes by line of the requisition

#### Describe the solution you'd like
Implement a similar approach as in the purchase order

#### Describe alternatives you've considered
the only alternative is to use prices with taxes included but it is not possible since it is required to know the detail of the taxes 

image

image

image

### PR DESCRIPTION
**Pull request by e-Evolution**
fixed #3737

### CODE REVIEW

**Comment by marcalwestf** [comment]
@e-Evolution  Víctor, there are build errors.

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf @e-Evolution  the build error is corrected here https://github.com/adempiere/adempiere/pull/3767

**Review by marcalwestf — CHANGES_REQUESTED** [review]
- build, install
- run the XML file 
- Run _Synchronize Terminology_ and _Sequence Check_
- log in as _GardenAdmin_
- Create a Requisiton
- Create a _Requsition Line_

Error produced when saving the Requisition Line, both on Swing and Jetty:
image

image


The error log is as follows:
```
*** 2022-03-22 17:59:37.184 Adempiere Log (CLogFile) ***
17:59:37.183 Adempiere.startup: ADempiere(r) Release 3.9.3_2019-12-01 - Smart Suite ERP,CRM and SCM - (c) 1999-2019 ADempiere(r) Implementation: ${ADEMPIERE_VERSION} 20220322-1734 - ${ADEMPIERE_VENDOR} [1]
17:59:37.201 Ini.loadProperties: /data2/app/Adempiere/Adempiere.properties #34 [1]
-----------> DB_PostgreSQL.lambda$getDataSource$0: Connection Lookup JNDI Datasource for java:comp/env/java/AdempiereDS Hikari Connection Pool [1]
-----------> Msg.translate: NOT found: ServerInfo [1]
-----------> Msg.translate: NOT found: ServerStarted [1]
-----------> DocFactory.lambda$getByResultSet$1: The column name C_DocType_ID was not found in this ResultSet. [32]
-----------> DocFactory.lambda$getByResultSet$1: The column name C_DocType_ID was not found in this ResultSet. [32]
-----------> DocFactory.lambda$getByResultSet$1: The column name C_DocType_ID was not found in this ResultSet. [32]
(SAME MESSAGE HUNDREDS OF TIMES !!!!!!!!!!!!!!!!!!!!!!)


===========> DB.getSQLValue: SELECT nextval('m_requisitiontax_seq') [102]
org.postgresql.util.PSQLException: ERROR: relation "m_requisitiontax_seq" does not exist
  Position: 16; State=42P01; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy5.executeQuery(Unknown Source)
	at org.compiere.util.DB.getSQLValueEx(DB.java:1322)
	at org.compiere.util.DB.getSQLValue(DB.java:1365)
	at org.compiere.util.DB.getSQLValue(DB.java:2250)
	at org.compiere.db.DB_PostgreSQL.getNextID(DB_PostgreSQL.java:900)
	at org.compiere.util.DB.getNextID(DB.java:1907)
	at org.compiere.model.PO.saveNew(PO.java:2722)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.model.MRequisition.calculateTaxTotal(MRequisition.java:644)
	at org.compiere.model.MRequisitionLine.updateHeaderTax(MRequisitionLine.java:416)
	at org.compiere.model.MRequisitionLine.afterSave(MRequisitionLine.java:323)
	at org.compiere.model.PO.saveFinish(PO.java:2342)
	at org.compiere.model.PO.saveNew(PO.java:2943)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.GridTable.dataSavePO(GridTable.java:2199)
	at org.compiere.model.GridTable.dataSave(GridTable.java:1523)
	at org.compiere.model.GridTab.dataSave(GridTab.java:997)

===========> MRequisitionTax.saveNew: No NextID (-1) [102]
-----------> MRequisitionLine.saveFinish: afterSave [102]
org.adempiere.exceptions.AdempiereException: SaveError
	at org.compiere.model.PO.saveEx(PO.java:2317)
	at org.compiere.model.MRequisition.calculateTaxTotal(MRequisition.java:644)
	at org.compiere.model.MRequisitionLine.updateHeaderTax(MRequisitionLine.java:416)
	at org.compiere.model.MRequisitionLine.afterSave(MRequisitionLine.java:323)
	at org.compiere.model.PO.saveFinish(PO.java:2342)
	at org.compiere.model.PO.saveNew(PO.java:2943)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.GridTable.dataSavePO(GridTable.java:2199)
	at org.compiere.model.GridTable.dataSave(GridTable.java:1523)
	at org.compiere.model.GridTab.dataSave(GridTab.java:997)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onSave(AbstractADWindowPanel.java:1681)

-----------> GridTable.saveWarning: Error - SaveError [102]
-----------> Msg.getMsg: NOT found: QuickEntry [48]
-----------> MIssue.set_Value: SourceClassName - Value too long - truncated to length=60 [42]
-----------> Scheduler.doWork: MProcess[241-Delete Notices] [45]
org.adempiere.exceptions.AdempiereException: Notification Recipient Mandatory
	at org.spin.queue.notification.DefaultNotifier.add(DefaultNotifier.java:306)
	at org.spin.queue.util.QueueManager.addToQueue(QueueManager.java:224)
	at org.compiere.server.Scheduler.lambda$runProcess$1(Scheduler.java:249)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.server.Scheduler.lambda$runProcess$2(Scheduler.java:226)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.compiere.server.Scheduler.runProcess(Scheduler.java:211)
	at org.compiere.server.Scheduler.doWork(Scheduler.java:125)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:265)
	at org.compiere.server.Scheduler.run(Scheduler.java:403)
```

**Comment by e-Evolution** [comment]
@marcalwestf execute this functionality from  clean seed generate, you should re sure that configuration native sequence not is activate

**Comment by marcalwestf** [comment]
Hi @e-Evolution  Víctor, you were correct: 
I could have created the native sequence for the newly created table _M_RequisitionTax_,  but instead, as a matter of test,  I did the following: set in _AD_Sysconfig_ the value of entry _SYSTEM_NATIVE_SEQUENCE_ to **N** and then corrected some entries in _AD_Sequence_  (AD_Session and AD_PInstance) and executed a _Sequence Check_. Then I run Adempiere without problem.

**Review by marcalwestf — APPROVED** [review]
After correcting the sequence, it was possible to save a line.

Checks performed:
- _Requisition_ Tab: field _Grand Total_  displayed with correct amount.
- _Requisition Line_ Tab:  fields _Tax_, _Tax Amount_ and _Line Total_ displayed with correct amount.
- _Requisition Tax_ Tab displayed;  Taxes calculated correctly

**Test passed**

**Pull request merged**
