### PR TITLE
#1983 : add iban col to c_bp_bankaccount

### PR DESCRIPTION
**Pull request by homebeaver**
Hi all,
In #1983 IBAN was suggested as alternative to RoutingNo+AccountNo.
IBAN (ISO 13616) is now used by 76 coutries - see https://www.swift.com/sites/default/files/resources/iban_registry.pdf 
In europe the use of IBAN is mandatory. [Countries where the use of IBAN is recommended.](https://www.dnb.no/en/business/transaction-banking/international-payments/example-iban.html)

grafik

### CODE REVIEW

**Comment by homebeaver** [comment]
Hi @yamelsenih please review this PR
I wonder why the ad_column_id is 1000000 - in my opinion for system objects (AD dictionary) the id should be below 1000000!? - for example 92263 would be OK.

grafik

How can I get the right id?
Thanks in advance.

**Comment by homebeaver** [comment]
Hi all, 
I add `commons-validator-1.6.jar` - with class IBANValidator for 74 countries. Bu I do not use it now,
because I miss validator for two countries VA and SV(El Salvador) which are defined in IBAN_Registry.
@marcalwestf - the validator for SV-IBANs is coded in the apache repo and [planned for 1.7.jar, see here](https://github.com/apache/commons-validator/commit/342b4b2ebeae12c774a3f325411fe19eb6df3d07), but I do not know when the jar will be released.

**Comment by yamelsenih** [comment]
Hi @homebeaver have you a test case for validation?

Best regard

**Comment by homebeaver** [comment]
@yamelsenih 
Yes - groovy see: How to use and extend the validator in explaind [here](http://wiki.adempiere.net/DE/Gesch%C3%A4ftspartner_Stammdaten#IBAN_Validator)
But ist not implemented in this PR.

**Comment by yamelsenih** [comment]
Hi @homebeaver is nioce this change but I need a complete test case for include to source, Can you write a before save for **MBPBankAccount** for validate it? 

Other question:
This change is a generic? I think that can be added a flag for Client for validate IBAN

**Comment by homebeaver** [comment]
Hi @yamelsenih - we use only groovy for Processes and Validators. It works fine: here an ui-example:

grafik

And a short instruction how to define it:

- define a Callout for the Column:
grafik
- and a rule with the groovy code:
grafik

```groovy
package com.klst.xxxxxx

import groovy.lang.Binding
import groovy.lang.Script

import org.apache.commons.validator.routines.IBANValidator

import org.compiere.model.GridTab
import org.compiere.util.CLogger

class CalloutIbanValidator extends Script {

	private static CLogger	log	= CLogger.getCLogger(CalloutIbanValidator.getName())
	String CLASSNAME = this.getClass().getName()
	
	public CalloutIbanValidator() {
	}

	public CalloutIbanValidator(Binding binding) {
		super(binding);
	}

	@Override
	public Object run() {
		log.config("${CLASSNAME}:run")
		IBANValidator validator = IBANValidator.getInstance()
		if(A_Value==null) { // new Object 
			log.config("${CLASSNAME}:run '${A_Value}' is null")
			return ""
		}
		if(validator.isValid(A_Value)) {
			log.config("${CLASSNAME}:run '${A_Value}' is valid")
			return ""
		}
		def iban_Value = A_Value
		println "${CLASSNAME}:run '${iban_Value}' is not valid"
		((GridTab)A_Tab).dataIgnore() // Ignore data changes
//		A_Tab.dataRefreshAll() // GridTable: Refresh all Rows - ignore changes
		return "'"+iban_Value + "' is not valid IBAN";
	}
	
	static main(args) {
	//		Script script = new CalloutIbanValidator()
	//		script.run()
		}
	
}
```

> can be added a flag for Client for validate IBAN

In my opinion there is no need for a flag. It is validating every time when changed.

**Comment by yamelsenih** [comment]
Hi @homebeaver thanks for your response.
I think that a callout shoud not be used for a validation, is better if you use a trigger **beforeSave** for  **MBPBankAccount**

Can you add the code as java code?
Here a example:
Screenshot_20190424_091632

For BP Bank Account
<pre>
	/**
	 * 	Before Save
	 *	@param newRecord new
	 *	@return true
	 */
	protected boolean beforeSave(boolean newRecord) 
	{
		//	maintain routing on bank level
		if (isACH() && getBank() != null)
			setRoutingNo(null);
		// validate IBAN
		if(!Util.isEmpty(getIBAN())) {
			IBANValidator validator = IBANValidator.getInstance();
			if(!validator.isValid(getIBAN().trim())) {
				throw new AdempiereException("@ValidationError@ (@Invalid@ @IBAN@)");
			}
		}
		return true;
	}	//	beforeSave
</pre>

For Bank Account C_BankAccount

<pre>
	@Override
	protected boolean beforeSave(boolean newRecord) {
		// validate IBAN
		if(newRecord) {
			if(!Util.isEmpty(getIBAN())) {
				IBANValidator validator = IBANValidator.getInstance();
				if(!validator.isValid(getIBAN().trim())) {
					throw new AdempiereException("@ValidationError@ (@Invalid@ @IBAN@)");
				}
			}
		}
		//	
		return true;
	}
</pre>

Both import it:
<pre>
import org.adempiere.exceptions.AdempiereException;
import org.apache.commons.validator.routines.IBANValidator;
</pre>

Also you must generate **I_** and **X_** class for **C_BP_BankAccount**

**Comment by homebeaver** [comment]
Hi @yamelsenih - this is the commit you requested for both entities.
I don't know why Travis CI - Build fails :-(

Regards EUGen

**Comment by yamelsenih** [comment]
Thanks @homebeaver 

Can you create a new branch with all changes for make a new pull request with only a commit?

Is more atomic
Screenshot_20190425_102731


Screenshot_20190425_102604

Best regard

**Pull request closed without merging**
