### PR TITLE
Feature/allocate inmediate enhance

### PR DESCRIPTION
**Pull request by SusanneCalderon**
This pullrequest moves the flag IsAllocateinmediate from table c_Invoice to table c_Doctype
As attach 3 videos covering the cases:

- amount of purchase order = amount of payment = amount of invoice
- amount of payment < amount of purchase order, amount of invoice = amount of order
- amount of payment < amount of purchase order, amount of invoice < amount of order

[AllocateInmediate.zip](https://github.com/adempiere/adempiere/files/2093313/AllocateInmediate.zip)

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon is nice your change, i think that is good add follow:
 - A document type (Optional) See Image:

You can add a display logic for show **Document Type for Allocation** when **IsAllocateinmediate** flag is setted.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon i test it but i don't know if i have a bad step, my steps are:

1. Login ADempiere As System
2. Go to Migration Window
3. Delete 3690 XML from ADempiere
4. Import new file: migration/390lts-391/03690_1370_InvoiceAllocateInmediate.xml
5. Apply New XML

It throw a error
screenshot_20180720_120057

<pre>
-----------> MColumn.load: NO Data found for AD_Column_ID=86715 [83]
-----------> MMigrationStep.bailout: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD.  Step 270, Record 86715 was not found in table Column (101). [83]
-----------> MMigrationStep.bailout: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Step 270, Record 86715 was not found in table Column (101). [83]
===========> MigrationStepApply.process: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Step 270, Record 86715 was not found in table Column (101). [83]
org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Step 270, Record 86715 was not found in table Column (101).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:274)
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:248)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:519)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
</pre>

**Comment by marcalwestf** [comment]
hi @yamelsenih , thanks for testing.
The last commit from this pull request which is  https://github.com/adempiere/adempiere/pull/1740/commits/127f74cdb474c0e55f1ac648fa68b17a28dc8a7e from June 12th deletes the Record_ID=86715 from sequence 270. The deleted section is -as you can see in the commit- the following:

```
<Step SeqNo="270" StepType="AD">
<PO AD_Table_ID="101" Action="U" Record_ID="86715" Table="AD_Column">
<Data AD_Column_ID="548" Column="IsActive" oldValue="true">false</Data>
</PO>
</Step>

```
The new XML file contains at sequence 270 the following:

    <Step SeqNo="270" StepType="AD">
      <PO AD_Table_ID="107" Action="U" Record_ID="58859" Table="AD_Field">
        <Data AD_Column_ID="181" Column="SeqNo" oldValue="290">310</Data>
      </PO>
    </Step>

Thus I suppose the file used to test was an old one.
Nonetheless, I will try again the import from scratch and report the results here.

**Comment by SusanneCalderon** [comment]
Hello @yamelsenih. The xml for the new column _isallocateinmediate_ was corrected to default value _false_ and ismandatory _true_

**Comment by marcalwestf** [comment]
I tested the new XML and no error was produced.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon i test it and i have three comments:

1. Is nice if **name** and **print name** of element should be more explicit, see image.
screenshot_20180725_204943
2. I think that a new column for a table with existing records never can be **mandatory**, is nice if you can change XML for make **IsAllocateImmediate** no mandatory.
screenshot_20180725_205048
3. I apply it over a DB with 3.9.1 with old bug of **IsAllocateImmediate** column in **C_Invoice** table, but the error is showed when i try open invoice customer. The problem is that **IsAllocateImmediate** is referenced in C_Invoice but column make reference to **C_DocType.IsAllocateImmediate**, see the pic.
screenshot_20180725_210005
screenshot_20180725_210022
The problem is that you changed directly XML from 318 table to 217 then the old field on Invoice (Customer) window was keeped with same column reference but current column now is child of **C_DocType** table
screenshot_20180725_211221
<pre>
===========> GridTable.open: SELECT AD_Client_ID,AD_Org_ID,C_Order_ID,DateOrdered,DocumentNo,POReference,Description,C_DocTypeTarget_ID,IsSelfService,DateInvoiced,DateAcct,C_BPartner_ID,C_BPartner_Location_ID,AD_User_ID,M_PriceList_ID,C_Currency_ID,C_ConversionType_ID,SalesRep_ID,IsDiscountPrinted,C_Charge_ID,ChargeAmt,PaymentRule,C_PaymentTerm_ID,C_Project_ID,C_Activity_ID,C_Campaign_ID,AD_OrgTrx_ID,User1_ID,User2_ID,User3_ID,User4_ID,TotalLines,GrandTotal,DocStatus,C_DocType_ID,IsPayScheduleValid,IsInDispute,CopyFrom,DocAction,IsAllocateImmediate,Posted,IsPaid,InvoiceCollectionType,DunningGrace,C_DunningLevel_ID,IsTaxIncluded,C_CashLine_ID,C_Payment_ID,Processed,IsFixedAssetInvoice,M_RMA_ID,Reversal_ID,DatePrinted,GenerateTo,IsApproved,IsPrinted,IsActive,CreateFrom,Ref_Invoice_ID,Processing,C_Invoice_ID,IsTransferred,IsSOTrx,SendEMail,Created,CreatedBy,Updated,UpdatedBy FROM C_Invoice WHERE (C_Invoice.IsSOTrx='Y') AND (Processed='N' OR Updated>SysDate-1) AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) AND (C_Invoice.C_Invoice_ID IS NULL OR C_Invoice.C_Invoice_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 318 AND AD_User_ID <> 100 AND IsActive = 'Y' )) ORDER BY DocumentNo DESC [54]
org.postgresql.util.PSQLException: ERROR: column "isallocateimmediate" does not exist
  Position: 507; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.GridTable$Loader.open(GridTable.java:3378)
	at org.compiere.model.GridTable.open(GridTable.java:609)
	at org.compiere.model.GridTab.query(GridTab.java:734)
	at org.compiere.grid.GridController.query(GridController.java:727)
	at org.compiere.apps.APanel.stateChanged(APanel.java:1528)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
</pre>



I thin that it can be resolved with a simple SQL on the last step:

<pre>
DELETE FROM AD_Field WHERE AD_Field_ID = 85508;
</pre>

I test with it and is ok.

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih , I included your suggestions.

**Pull request merged**
