### PR TITLE
#3920 GL Distribution doesn't work for any account  https://github.co…

### PR DESCRIPTION
**Pull request by e-Evolution**
…m/adempiere/adempiere/issues/3920

- The changes allow to generate a distribution for any dimension and solve the problem with the dimensions user 3 and user 4

### CODE REVIEW

**Review by niclopup — CHANGES_REQUESTED** [review]
I found an error with the following definition:
Distribución con PR de Victor
Error Actividad en Cabezal

But when the Activity is defined in the lines of a AP the distribution is made correctly

**Comment by niclopup** [comment]
The lineas of the Distribution i am testing.

Distribución Actividad 2

linea 2 diist actividad
linea diist actividad


This distribution, if the Activity is defined in the lines, it make the distribution OK
DxP Posted OK Actiivdad en lineas
Linea de DxP Posted OK Actiivdad en lineas

Asiento de DxP Posted OK Actiivdad en lineas

**Comment by marcalwestf** [comment]
one question: does this pull request replace https://github.com/adempiere/adempiere/pull/3923 ?

**Review by SusanneCalderon — CHANGES_REQUESTED** [review]
@e-Evolution , @niclopup 
I could reproduce the error @niclopup mentioned. The error does not occure when the distribution does not generate a reversal.

**Comment by yamelsenih** [comment]
Hello @e-Evolution  can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by yamelsenih** [comment]
This pull request will be closed this friday 2023-11-10 if not exists changes

**Comment by e-Evolution** [comment]
@yamelsenih Hello, I think that the patch does apply since you should not have two methods to bring the distribution rules, these should apply to all dimensions, so bringing an accounting distribution only for the account can cause inconsistencies, so the change is Valid, I understand that Nicolas @niclopup found a problem, but I think it is not related to this patch, since what he reports is a different problem based on where the activity takes, whether from the header or the line, this problem happening now with or without this patch so unrelated

It would be good if you validated it and gave your peer review, I consider that the patch does apply, and the error that Nicolas found should be reported and fixed but it has nothing to do with this change.

**Comment by yamelsenih** [comment]
I will review this with @carlosaparadam

**Comment by yamelsenih** [comment]
Hello, I test it and is ok. 

The problem reported by @marcalwestf was a wrong setup for distribution. This behavior is when a distribution line have a percent in zero

**Comment by yamelsenih** [comment]
@carlosaparadam please check it

**Review by yamelsenih — APPROVED** [review]
This pull request is ok for me

**Pull request merged**
