### PR TITLE
Hotfix/3.9.4.002 local/#gradle generate asset v1

### PR DESCRIPTION
**Pull request by yamelsenih**
This is one of many pull request that wants to build ADempiere with gradle completely.

The build is a hard work and a complete change is not good for test.

Detail: 
- Add `client` and `install` source folders to Gradle and build it.

Now you can see a build folder like this `ADEMPIERE_HOME/install/build/distributions`, inside this folder you can unzip the `install.zip` and run some runners:
- For Linux:
  - `adempiere-swing-ui`
  - `run-migrate`
  - `run-setup`
  - `run-silent-setup`
  - `translation`
- For Windows:
  - `adempiere-swing-ui.bat`
  - `run-migrate.bat`
  - `run-setup.bat`
  - `run-silent-setup.bat`
  - `translation.bat`

All files are automatically generated by `gradle`

Replace: https://github.com/adempiere/adempiere/pull/4259

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @yamelsenih  I cannot start testing because I got an Eclipse error:
image

**Comment by yamelsenih** [comment]
Hello @marcalwestf this change is to build from Gradle and ant. These changes should be working at build, the classpath is other distinct

**Comment by yamelsenih** [comment]
> hi @yamelsenih I cannot start testing because I got an Eclipse error: image

Hello @marcalwestf please test it

**Review by marcalwestf — APPROVED** [review]
ANT build -> OK
gradle build -> OK

Tests passed

**Comment by marcalwestf** [comment]
This pull request has been tested and accepted; it can be merged, but it is waiting for older pull requests to be merged.

**Pull request merged**
