### PR TITLE
Feature/#3392 aging report enhance the table t aging more columns

### PR DESCRIPTION
**Pull request by SusanneCalderon**
Fixes: #3392

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
@e-Evolution 
I added the XML file and corrected the columnname from PastDue360_plus to PastDue360_Plus

**Comment by e-Evolution** [comment]
@SusanneCalderon  can please update your branch, this way I can testing with the last change the develop

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon I saw that this PR is very old. You can see if is add some here?
Screenshot_20210710_115720

**Comment by yamelsenih** [comment]
The test is ok

**Comment by yamelsenih** [comment]
Comment: just update from develop for merge

**Pull request merged**
