### PR TITLE
#1839, Add old compatibility to Context info for window, reference to

### PR DESCRIPTION
**Pull request by yamelsenih**
issue: https://github.com/adempiere/adempiere/issues/1839

Add old compatibility for context info

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih I see you wrapped the _Query_ access to   _AD_ContextInfo_ID_  in an try-catch .
Is this for databases which do not have the   _AD_ContextInfo_ID_  column defined?

**Comment by yamelsenih** [comment]
Yes Mario, if you install last  ADempiere binary without apply XML then you can't open any Window

**Comment by yamelsenih** [comment]
Is a little change, I tested it and is ok. Please test open a window wit a ADempiere installed without apply XML for context info

**Comment by yamelsenih** [comment]
Bb
  Iin

**Comment by marcalwestf** [comment]
Thanks; I am going to test it right now....

**Comment by marcalwestf** [comment]
when accessing a database without the XMLs _03820_1784_Add_Dynamic_StatusBar.xml_ and _03830_1784_Add_Dynamic_StatusBar_Add_Data.xml_, the following exception is generated, but caught and the program continues flawlessly:

```
09:28:26.917           Trx.close: POSave_46986366-c6da-4dea-aed5-e6ee17c63621 [18]
===========> MADContextInfo.getFromTabIdForField: getFromTabIdForField: org.postgresql.util.PSQLException: ERROR: column "ad_contextinfo_id" does not exist
  Position: 523
  Location: File: parse_expr.c, Routine: transformColumnRef, Line: 766
  Server SQLState: 42703, SQL=SELECT AD_Org_ID,AD_Client_ID,IsActive,Created,AD_Field_ID,Updated,EntityType,IsEmbedded,IsAllowCopy, 
org.postgresql.util.PSQLException: ERROR: column "ad_contextinfo_id" does not exist
etc., etc.
```

**Pull request merged**
