### PR TITLE
#2324 Improve the functionality of the Favorites (User) panel.  

### PR DESCRIPTION
**Pull request by mckayERP**
Allows menu items to be dragged and dropped with no initial folder.  Removes text field and button to create folder and adds the functionality to the right-click pop-up menu.  Adds a trashcan to delete items.  Improve tool tips and add translations where required.

Here is a write up of what it looks like.

**Favorites (User)**

The User Favorites panel is a list of frequently used menu items that you can select and organize as you wish.  Clicking on items in the panel will open the associated menu item.  Having these items easily available saves time when looking for a frequently needed menu item. 
The pane, when empty, appears as shown in the image below.

image

You can add items to the Favorites by simply dragging them from the main menu and dropping them into the panel.  You can create folders to organize the items by right-clicking in the panel or on an existing item and selecting "Add Folder" from the pop-up menu.  The order and structure can be arranged by dragging and dropping items.  An item dropped on another item will be placed after it.  An item or folder dropped on a folder will cause a menu to appear with options to "Insert After"  or "Move Into".

image

A Folder can be renamed by double-clicking on it.  A simple text dialog will open.  Edit the text and hit <Enter> to save the new name or close the dialog.  Hit <Esc> to cancel.  

Folders can also be set to Start Collapsed or Expanded by right-clicking the folder and selecting the corresponding menu entry from the pop-up menu. 

Note: The Folders will be created in the language you are using at the time.  If you switch to a different language, the folder names will not be translated.

The trash can icon at the bottom of the panel can be used to delete items from the list. Simply drag items from the list and drop them on the trash can.  You can also delete items using the right-click pop-up menu.

The Expand Tree check box can be used to expand or collapse the entire tree.

### CODE REVIEW

**Comment by mckayERP** [comment]
Noted the build error.  I'll update to fix it.

**Comment by marcalwestf** [comment]
This will add enormously to user-acceptance.
Start testing now.

**Comment by marcalwestf** [comment]
got the following error when trying to import:

> MigrationFromXML.loadXML: Processing migration file: /home/westfalia/Adempiere/westfaliaRepository/mckayERP/migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml [81]
> MigrationFromXML.loadFile: Loading file: /home/westfalia/Adempiere/westfaliaRepository/mckayERP/migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml [81]
> [Fatal Error] 04430_2324_ImproveFuncDPUserFavorites.xml:48:156: Invalid byte 1 of 1-byte UTF-8 sequence.
> org.xml.sax.SAXParseException; systemId: file:/home/westfalia/Adempiere/westfaliaRepository/mckayERP/migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml; lineNumber: 48; columnNumber: 156; Invalid byte 1 of 1-byte UTF-8 sequence.
> 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
> 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
> 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
> 	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:135)
> 	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
> 	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
> 	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
> 	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
> 	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
> 	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
> 	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
> 	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
> 	at java.lang.Thread.run(Thread.java:748)
> MPInstance.load: ID=1000680 [81]

The culprit is quickly found: the Spanish accents:
20190226_favorites_01

**Comment by marcalwestf** [comment]
The import works well when -according to https://en.wikipedia.org/wiki/List_of_Unicode_characters - replacing in the XML file as follows
á 	&#0225; 	Latin Small Letter A with acute 
é 	&#0233; 	Latin Small Letter E with acute 
í 	&#0237; 	Latin Small Letter I with acute 
ó 	&#0243; 	Latin Small Letter O with acute 
ú 	&#0250; 	Latin Small Letter U with acute

**Comment by marcalwestf** [comment]
When the XML file is changed as described, the imported file is applied and the favorites work as Mike explaines in the issue:
20190227_favorites_02

**Pull request merged**
