### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by yamelsenih**
Just add a new file with code of conduct for any contributor
This implement a standard based on https://www.contributor-covenant.org/faq

### CODE REVIEW

**Review by marcalwestf — APPROVED** [review]

**Comment by OFB-Review1** [comment]
hola, creo que si vamos a usar el código de conducta, debería al menos colocar que se debe participar en los scrum semanales , por un tiempo mínimo de 15 minutos a la semana, o avisar la no asistencia para realizar reprogramación de la reunión.

**Comment by eduardolopezuy** [comment]
This code of conduct is a standard code and should be the beginning of an ordering and incorporation of good practices of open source projects.

**Comment by e-Evolution** [comment]
Unfortunately, codes of conduct have been used as an instrument to expel or reprimand people of one ideology against another of another ideology and whoever wins is generally the majority of one of the ideologies, there are many examples: the drama in Scala, the drama in Rust recent.

The question is we want to introduce political issues in the ADempiere community, I think NO, participation must be strictly respect, professional ethics, universal values, responsibility, professionalism and quality of your contribution.

The problem with the codes of conduct is that they are closely linked to a political position or you are very culture woke or you are very much of the culture of free expression.

My opinion is that Adempiere should not be linked to politics,

Today it is more relevant to define a Contributor License Agreement (CLA)

**Comment by yamelsenih** [comment]
This pr will be rewrited

**Pull request closed without merging**
