### PR TITLE
 #3983 [Bug Report] Is reconciled flag is not correctly set when a payment is in an account statement with draft document status

### PR DESCRIPTION
**Pull request by e-Evolution**
Is reconciled flag is not correctly set when a payment is in an account statement with draft document status https://github.com/adempiere/adempiere/issues/3983

fixed 3983

### CODE REVIEW

**Review by SusanneCalderon — CHANGES_REQUESTED** [review]
@e-Evolution;
When the bank statement is already voided this bank statment lines should not be considered.
```

	private int getC_BankStatementLine_ID() {
		String sql = "SELECT bsl.C_BankStatementLine_ID FROM C_BankStatementLine bsl WHERE bsl.C_Payment_ID=? "
				+ "AND EXISTS(SELECT 1 FROM C_BankStatement bs "
				+ "					WHERE bs.C_BankStatement_ID = bsl.C_BankStatement_ID "
				+ "AND bs.DocStatus NOT IN('VO', 'RE'))";
		return DB.getSQLValue(get_TrxName(), sql, getC_Payment_ID());
	}	//	getC_BankStatementLine_ID
```

**Comment by e-Evolution** [comment]
@SusanneCalderon Hi Susanne, Currently, there is no business logic for "Reverse Correct" in the bank statement, in the case of Void, the lines are emptied and the invoice and payment references are cleared, so there would be no point in validating why they have no effect on the logic.

**Comment by niclopup** [comment]
tested OK

https://user-images.githubusercontent.com/31936815/190438035-f177132d-b424-416d-9f10-060bbbf4f699.mp4

**Review by SusanneCalderon — APPROVED** [review]
@e-Evolution , ok, as there is at this moment only a  business logic for void , it is ok not to filter for voided bank statements.

**Comment by e-Evolution** [comment]
@marcalwestf please Can you merge this bugfix?

**Pull request merged**
