### PR TITLE
#3467 [Bug Report] Generate Receipt from Invoice process is not valid…

### PR DESCRIPTION
**Pull request by e-Evolution**
…ate if was generate a Material Receipt from a previous execution https://github.com/adempiere/adempiere/issues/3467

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi Victor @e-Evolution  please see my comment on  #3467 
Thanks

**Comment by marcalwestf** [comment]
@e-Evolution  now that the error has been reproduced, I will proceed to test the fix.

**Comment by marcalwestf** [comment]
hi @e-Evolution, I did the following in Adempiere standard:

1. Create a Purchase Order and complete it.
2. Create an Invoice (Vendor) and generate the Invoice Line based on the Purchase Order. Complete the Purchase Order.
3. Stay on theInvoice (Vendor) and Create a Material Receipt. 
4. Do not complete the material receipt.
4. Create as many Material Receipts as you please and leave them in the _Draft_ status.

This is an error because users can create a Material Receipt for an Invoice, and choose **not** to complete it.
Then, by mistake, another Material Receipt can be created out of the same Invoice. Now we'd have two Material receipts for the same invoice.
In the end, all drafted Material Receipts can be completed, leaving in a complete disarray the warehouse, and order.

With the changes of this pull request,  you get the following message when there is a Material Receipt even in the _Draft_ status:
imagen

**Review by marcalwestf — APPROVED** [review]
- tested the behavior of standard Adempiere: it is possible to create several Material Receipts out of an Invoice (Vendor) if they are left in the _Drafted_ status.
- with this pull request, this (erroneous) behavior is suppressed.

-> test passed

**Comment by marcalwestf** [comment]
@e-Evolution  Victor, some checks must pass

**Comment by marcalwestf** [comment]
This PR is semantically linked to https://github.com/adempiere/adempiere/issues/3462 and https://github.com/adempiere/adempiere/pull/3464

**Comment by yamelsenih** [comment]
I agree, just update this branch with last changes for approval from CI

**Pull request merged**
