### PR TITLE
Feature/#2747 generate freight order from outbound

### PR DESCRIPTION
**Pull request by yamelsenih**
Add process for generate freight order from outbound order
Screenshot_20190830_234456
Fixes: #2747

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih Hi Yamel.

The idea of creating a line in the freight order is based on the total weight per freight category address of origin to destination, so it should not be created for each line item of order, since it would not make sense to have the same information.

The freight payment is made by freight category, and section of the direction of origin and destination (route)

**Comment by yamelsenih** [comment]
> @yamelsenih Hi Yamel.
> 
> The idea of creating a line in the freight order is based on the total weight per freight category address of origin to destination, so it should not be created for each line item of order, since it would not make sense to have the same information.
> 
> The freight payment is made by freight category, and section of the direction of origin and destination (route)

Hi @e-Evolution I just add a process because already exist product reference inside Freight order as manual freight.

**Comment by e-Evolution** [comment]
@yamelsenih  But the product or charge is use to the service with which the freight will be paid, not the product that generated the freight, that is in the Shipment or movement document lines

**Comment by yamelsenih** [comment]
No problem, I want to add lines for freight order but I can change it very
easy no problem. Let me one minute

Thanks

**Pull request merged**
