### PR TITLE
Add support to import attribute set instance for import inventory

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request allows add support to Attribute set instance for import inventory, note that you can import and make match for attribute set instance now:
Screenshot_20200225_120631

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
Great improvement.
I think it would be helpful to include the guarantee date in line 277
```

if (attributeSet.isGuaranteeDate())
							attributeSetInstance.setGuaranteeDate(importInventory.getGuaranteeDate());
```
If you agree I will generate a change request

**Comment by yamelsenih** [comment]
> Hi @yamelsenih
> Great improvement.
> I think it would be helpful to include the guarantee date in line 277
> 
> ```
> 
> if (attributeSet.isGuaranteeDate())
> 							attributeSetInstance.setGuaranteeDate(importInventory.getGuaranteeDate());
> ```
> 
> If you agree I will generate a change request

Nice

**Comment by SusanneCalderon** [comment]
Perfect!

**Comment by SusanneCalderon** [comment]
@yamelsenih 
2 small remarks:
1. The descripction in an asi is _«564564»_ without guarantee date and _«564564»_26/02/2023_
with guarantee date. So search for an existing asi should use like instead of =.
```

sql = new StringBuffer ("UPDATE I_Inventory i "
		+ "SET M_AttributeSetInstance_ID=(SELECT MAX(M_AttributeSetInstance_ID) "
		+ "FROM M_AttributeSetInstance ai "
		+ "WHERE (TRIM(ai.lot) like TRIM(i.AttributeSetInstanceValue)  OR TRIM(ai.serNo) like TRIM(i.SerNo))"
			+ "AND ai.IsActive = 'Y' "
			+ "AND ai.AD_Client_ID IN(0, i.AD_Client_ID) "
			+ "AND EXISTS(SELECT 1 FROM M_Product p WHERE p.M_Product_ID = i.M_Product_ID AND (p.M_AttributeSet_ID = ai.M_AttributeSet_ID OR (p.M_AttributeSet_ID IS NULL
AND ai.M_AttributeSet_ID = 0)))) "
			+ "WHERE AttributeSetInstanceValue IS NOT NULL"
			+ " AND I_IsImported<>'Y'").append (clientCheck);
```

2. The method setDescription() for a new asi should be called after the setting the guarantee date, so that the description is consistent with the description when you create a new asi with the special form. 

```
if (attributeSet.isLot() && importInventory.getLot() != null)
							attributeSetInstance.setLot(importInventory.getLot(), importInventory.getM_Product_ID());
						if (attributeSet.isSerNo() && importInventory.getSerNo() != null)
							attributeSetInstance.setSerNo(importInventory.getSerNo());
						if (attributeSet.isGuaranteeDate()) {
							attributeSetInstance.setGuaranteeDate(importInventory.getGuaranteeDate());
						}
						attributeSetInstance.setDescription();
```

**Comment by yamelsenih** [comment]
> @yamelsenih
> 2 small remarks:
> 
> 1. The descripction in an asi is _«564564»_ without guarantee date and _«564564»_26/02/2023_
>    with guarantee date. So search for an existing asi should use like instead of =.
> 
> ```
> 
> sql = new StringBuffer ("UPDATE I_Inventory i "
> 		+ "SET M_AttributeSetInstance_ID=(SELECT MAX(M_AttributeSetInstance_ID) "
> 		+ "FROM M_AttributeSetInstance ai "
> 		+ "WHERE (TRIM(ai.lot) like TRIM(i.AttributeSetInstanceValue)  OR TRIM(ai.serNo) like TRIM(i.SerNo))"
> 			+ "AND ai.IsActive = 'Y' "
> 			+ "AND ai.AD_Client_ID IN(0, i.AD_Client_ID) "
> 			+ "AND EXISTS(SELECT 1 FROM M_Product p WHERE p.M_Product_ID = i.M_Product_ID AND (p.M_AttributeSet_ID = ai.M_AttributeSet_ID OR (p.M_AttributeSet_ID IS NULL
> AND ai.M_AttributeSet_ID = 0)))) "
> 			+ "WHERE AttributeSetInstanceValue IS NOT NULL"
> 			+ " AND I_IsImported<>'Y'").append (clientCheck);
> ```
> 
> 1. The method setDescription() for a new asi should be called after the setting the guarantee date, so that the description is consistent with the description when you create a new asi with the special form.
> 
> ```
> if (attributeSet.isLot() && importInventory.getLot() != null)
> 							attributeSetInstance.setLot(importInventory.getLot(), importInventory.getM_Product_ID());
> 						if (attributeSet.isSerNo() && importInventory.getSerNo() != null)
> 							attributeSetInstance.setSerNo(importInventory.getSerNo());
> 						if (attributeSet.isGuaranteeDate()) {
> 							attributeSetInstance.setGuaranteeDate(importInventory.getGuaranteeDate());
> 						}
> 						attributeSetInstance.setDescription();
> ```

Hi @SusanneCalderon can you review it?

I add your changes here: https://github.com/adempiere/adempiere/pull/3028/commits/883e8a3b28c9eb630aef0e7a018335f03f53f5d2

**Comment by SusanneCalderon** [comment]
@yamelsenih 
right now

**Comment by SusanneCalderon** [comment]
@yamelsenih , @marcalwestf 
Tested without problems

**Pull request merged**
