### PR TITLE
Rename Fleet Package

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request basically change the package name of fleet to new structure:

Old structure:
```Java
  - org.eevolution.model
  - org.eevolution.process
```

New structure:
```Java
  - org.eevolution.distribution.acct
  - org.eevolution.distribution.model
  - org.eevolution.distribution.process
  - org.eevolution.distribution.util
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN('org.eevolution.process.ProcessingDriverSelection', 'org.eevolution.process.ProcessingLicenseSelection', 'org.eevolution.process.ProcessingRequirementSelection', 'org.eevolution.process.ProcessingTransportUnitSelection', 'org.eevolution.process.ProcessingTransportUnitSelection', 'org.eevolution.process.ProcessingVehicleSelection', 'org.eevolution.process.GenerateMovement', 'org.eevolution.process.GenerateMovementMaterial', 'org.eevolution.process.MovementGenerate');
```
 
 Value|Name
-- | --
 M_Movement Material Receipt       | Movement Material Receipt from Distribution Order
 M_Movement Generate Movement      | Generate Movement from Distribution Order
 M_Generate Movement               | Generate Movement
 DD_Driver Selection               | Driver Selection
 DD_Vehicle Selection              | Vehicle Selection
 DD_TransportLicense Selection     | Transport License Selection
 DD_TransportRequirement Selection | Transport Requirement Selection
 DD_TransportUnit Selection        | Transport Unit Selection

## Model Validators (does not apply)
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('');
```

Name|Description
--|--

## Final comments
- A new entity type was create for handle the **Distribution Management**
- The model class MDDOrder was moved from base to org.eevolution.fleet source folder because is part of distribution
- The model class MDDOrderLine was moved from base to org.eevolution.fleet source folder because is part of distribution
- The follows source folders depends of fleet source folder:
  - org.eevolution.manufacturing
  - org.eevolution.freight
  - org.eevolution.warehouse
  - org.adempiere.production

The support legacy api is from here: https://github.com/adempiere/adempiere-fleet-support-legacy

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
- No compile errors
- Build OK
- Install OK
- Pointing to a database with applied XMLs up to 09730_Change_Entity_Type_for_Distribution_Management_Tables.xml
- Swing, Jetty login: OK
- Load both 09740_Change_Entity_Type_for_Distribution_Process.xml and 09760_Change_Process_package_class_for_Distribution.xml

**Error when applying** `09740_Change_Entity_Type_for_Distribution_Process.xml` :

imagen

**Comment by yamelsenih** [comment]
> * No compile errors
> * Build OK
> * Install OK
> * Pointing to a database with applied XMLs up to 09730_Change_Entity_Type_for_Distribution_Management_Tables.xml
> * Swing, Jetty login: OK
> * Load both 09740_Change_Entity_Type_for_Distribution_Process.xml and 09760_Change_Process_package_class_for_Distribution.xml
> 
> **Error when applying** `09740_Change_Entity_Type_for_Distribution_Process.xml` :
> 
> imagen

Hi @marcalwestf are you sure of applied all xmls? see the first XML [here](https://github.com/adempiere/adempiere/pull/3921/files#diff-e81cfe9af99f6b3ad98753a2dd3d3aee0dbf557f93cc0cfdd166af454290a992R18)

**Comment by marcalwestf** [comment]
Sorry @yamelsenih  you're right.
The XML sequence by adempiere/develop is as of now at 09730_Configure_Centralized_ID_Management_Process.xml, this sequence **09730**.

I hadn't noticed that your first committed XML is 09720_Add_Entity_Type_for_Distribution_Management.xml, so I started loading at sequence  **09740**, instead of at 09720_Add_Entity_Type_for_Distribution_Management.xml .

I will start the tests with 09720_Add_Entity_Type_for_Distribution_Management.xml.

When the tests are accepted, it would be advisable to synchronize the XML sequence.

**Review by marcalwestf — COMMENTED** [review]
- Loaded and applied successfully both files 09720_Add_Entity_Type_for_Distribution_Management.xml and 09730_Change_Entity_Type_for_Distribution_Management_Tables.xml
- When applying file `09740_Change_Entity_Type_for_Distribution_Process.xml`, the following error is displayed. 

imagen

The error says that the Process with the ID `54470` doesn't exist.
Checking in the database, it is really not there:
imagen

**Comment by marcalwestf** [comment]
... same with step 130 (AD_Process_Para_ID=57990):
imagen

..and step 140:  AD_Process_Para_ID=57988
..and step 150:  AD_Process_Para_ID=58180
..and step 160:  AD_Process_Para_ID=58181
..and step 170:  AD_Process_Para_ID=58182
..and step 180:  AD_Process_Para_ID=58183
..and step 190:  AD_Process_Para_ID=57989

Step 200 was applied successfully though.

**Comment by marcalwestf** [comment]
I also applied file 09760_Change_Process_package_class_for_Distribution.xml.

Here, only one error was generated: `AD. Step 20, Record 54470`

**Review by marcalwestf — COMMENTED** [review]
@yamelsenih perhaps you can do a small change in some files:
Delete the first "or" so the text is **_via info@adempiere.net_**
imagen


Code analysis (and hints to test):
- In ./tools/lib/legacy/fleet-support-legacy-1.0.0.jar, the legacy files are kept.
  The test here would consist for example in installing Adempiere with a legacy package and see if it works as hitherto.
imagen
- Class RefactorUtil for legacy calls:
imagen

- Packages moved to org.eevolution.fleet, e.g.:
imagen
- Some classes have refactored the method implementation, so their functionality must be tested completely:
imagen

- Some files seem to have been generated, but nothing has been added or removed.
  In these cases, it is maybe more efficient to just instantiate the class instead of checking every line of code.
imagen

- Conclusion:
  **Due to the fact that this refactoring affects legacy changes, but also changes many classes around besides the actual Fleet functionality (Invoice, Request, Movement, MRP, ProductPlanning ), it is advisable to do a whole functional test not only on Fleet Management, but also on Material Management and Libero before accepting it.**

**Comment by yamelsenih** [comment]
> 54470

Hi @marcalwestf have you sure of seed? see it:

```SQL
SELECT AD_Process_ID, Value, Name FROM AD_PRocess WHERE AD_Process_ID = 54470;
```

 ad_process_id |                value                 |                  name               
-- | -- | -- | 
 54470 | M_Storage Validate Reserved Quantity | Validate Ordered and Reserved Quantity

**Comment by yamelsenih** [comment]
Here you can download the generated seed: https://github.com/adempiere/adempiere/actions/runs/2518191419
Screenshot from 2022-06-22 15-06-14

**Comment by marcalwestf** [comment]
@yamelsenih thanks Yamel, I will try it out.

**Comment by e-Evolution** [comment]
@yamelsenih , I made some changes to take advantage of the fact that we are doing the restructuring of the distribution functionality so I changed from fleet to distribution.

On the other hand, I realized that the Callouts of the functionality and processes need to be moved, I'll put what I found here.

image

Please use org.eevolution.distribution as packages.

On the other hand, I found another process that should be a move to org.eevolution.distribution.process

image

image

image

kind regards
Victor

**Pull request merged**
