### PR TITLE
Refactory: Request Processor By Email based on new notification queue

### PR DESCRIPTION
**Pull request by yamelsenih**
Remove old implementation of RequestProcessor Class
Add new queue notification

This apply for:
- `org.compiere.server.RequestProcessor`

Related to: #3552

### CODE REVIEW

**Comment by rcapecce** [comment]
Hi @yamelsenih, we found this log issue when testing this functionalty

```
Exception in thread "GardenWorld Request Processor" org.adempiere.exceptions.AdempiereException: User/Contact Mandatory
        at org.spin.queue.notification.DefaultNotifier.add(DefaultNotifier.java:313)
        at org.spin.queue.util.QueueManager.addToQueue(QueueManager.java:224)
        at org.compiere.server.RequestProcessor.lambda$sendEmail$5(RequestProcessor.java:335)
        at org.compiere.util.Trx.run(Trx.java:529)
        at org.compiere.util.Trx.run(Trx.java:497)
        at org.compiere.server.RequestProcessor.sendEmail(RequestProcessor.java:321)
        at org.compiere.server.RequestProcessor.lambda$processRequests$0(RequestProcessor.java:130)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.compiere.server.RequestProcessor.processRequests(RequestProcessor.java:126)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:86)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:261)
```

**Comment by yamelsenih** [comment]
Hi @rcapecce @niclopup this is fixed

**Comment by niclopup** [comment]
now it works correctly

**Review by niclopup — APPROVED** [review]
it works correctly

**Pull request merged**
