### PR TITLE
#1567 Transform reports to pdf version 1.7

### PR DESCRIPTION
**Pull request by homebeaver**
this are implementation steps

1. add newer itext-5 and itext-7 jars
2. find other useful jars to reduce implementation effort (javax.inject, harness, itext-carriage)
3. change the code to transform awt report representation to pdf version 1.7 : this is done in Class `ITextDocument `, a singleton which will be a replacement for `org.adempiere.pdf.Document`. `Document `is marked as deprecated.
4. add methods to append attachments objects into pdf - this method is `ITextDocument:append(...)`

### CODE REVIEW

**Comment by homebeaver** [comment]
fine @marcalwestf - maybe you are also intersted in pull #1601 . This is the other side of the coin, the pdf viewer

**Comment by yamelsenih** [comment]
Hi @homebeaver i test it just now and i have a comments:

- Is nice if you add new library to classpath of project, see image:
screenshot_20180711_185213
- After add all library to project:
  - For Swing UI it is worked correctly
  - ZK UI does not work, i look a error, see:
screenshot_20180711_191129


I think that exist a missing library for ZK, i hope that you can change it, is very very cool it change.

Best regard

**Comment by yamelsenih** [comment]
I find a problem with build project:
<pre>
  [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:98: error: cannot find symbol
    [javac]         final PdfWriter writer = PdfWriter.getInstance(document, output); // throws DocumentException
    [javac]               ^
    [javac]   symbol:   class PdfWriter
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:98: error: cannot find symbol
    [javac]         final PdfWriter writer = PdfWriter.getInstance(document, output); // throws DocumentException
    [javac]                                  ^
    [javac]   symbol:   variable PdfWriter
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:100: error: cannot find symbol
    [javac]         writer.setPdfVersion(PdfWriter.PDF_VERSION_1_7);
    [javac]                              ^
    [javac]   symbol:   variable PdfWriter
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:102: error: cannot find symbol
    [javac]         document.open();
    [javac]                 ^
    [javac]   symbol:   method open()
    [javac]   location: variable document of type Document
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:104: error: cannot find symbol
    [javac]         PdfContentByte contentByte = writer.getDirectContent();
    [javac]         ^
    [javac]   symbol:   class PdfContentByte
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:110: error: cannot find symbol
    [javac]         		document.newPage();
    [javac]         		        ^
    [javac]   symbol:   method newPage()
    [javac]   location: variable document of type Document
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:113: error: cannot find symbol
    [javac]             PdfTemplate temp = contentByte.createTemplate(width ,height);
    [javac]             ^
    [javac]   symbol:   class PdfTemplate
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:115: error: cannot find symbol
    [javac]             Graphics2D g2d = new PdfGraphics2D(contentByte, width, height); // without 4th para FontMapper, DefaultFontMapper is used
    [javac]                                  ^
    [javac]   symbol:   class PdfGraphics2D
    [javac]   location: class ITextDocument
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:122: error: cannot find symbol
    [javac]         document.close();
    [javac]                 ^
    [javac]   symbol:   method close()
    [javac]   location: variable document of type Document
    [javac] /opt/Development/workspace/adempiere_390_Fork_Pull/base/src/org/adempiere/pdf/ITextDocument.java:177: error: method does not override or implement a method from a supertype

BUILD FAILED
/opt/Development/workspace/adempiere_390_Fork_Pull/utils_dev/build.xml:21: The following error occurred while executing this line:
/opt/Development/workspace/adempiere_390_Fork_Pull/base/build.xml:60: Compile failed; see the compiler error output for details.
</pre>

**Comment by homebeaver** [comment]
@yamelsenih 
package `io.konik.harness`  comes from `tools/lib/harness-1.0.0.jar`

**Comment by yamelsenih** [comment]
Hi @homebeaver can you upgrade it branch from develop? #1816 and #1817 was merged yet.

Best regard

**Comment by homebeaver** [comment]
Hallo @yamelsenih , 
I merged 'adempiere/develop' into develop-1567 to upgrade and 
added the jars in the eclipse .classpath
bye

**Comment by yamelsenih** [comment]
Hi @homebeaver i just test it and Swuing UI is OK but ZK UI when i try run a report it throw a error:
<pre>
-----------> Msg.getMsg: NOT found: Load New Report Definition [53]
-----------> Msg.getMsg: NOT found: Load New Report Definition [53]
===========> CWindowToolbar.doOnClick: Could not invoke Toolbar listener method: onReport() [53]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:393)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:357)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
caused by: java.lang.NoClassDefFoundError: org/adempiere/pdf/ITextDocument
	at org.spin.util.ExportFormatPDF.createPDF(ExportFormatPDF.java:94)
	at org.compiere.print.ReportEngine.createPDF(ReportEngine.java:673)
	at org.adempiere.webui.window.ZkReportViewer.renderReport(ZkReportViewer.java:449)
	at org.adempiere.webui.window.ZkReportViewer.init(ZkReportViewer.java:382)
	at org.adempiere.webui.window.ZkReportViewer.<init>(ZkReportViewer.java:198)
	at org.adempiere.webui.window.ZkReportViewerProvider.openViewer(ZkReportViewerProvider.java:67)
	at org.compiere.print.ReportCtl.preview(ReportCtl.java:448)
	at org.adempiere.webui.apps.WReport.launchReport(WReport.java:252)
	at org.adempiere.webui.apps.WReport.launchReport(WReport.java:216)
	at org.adempiere.webui.apps.WReport.getPrintFormats(WReport.java:168)
	at org.adempiere.webui.apps.WReport.<init>(WReport.java:114)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onReport(AbstractADWindowPanel.java:1836)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:393)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:357)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)

===========> CWindowToolbar.doOnClick: Could not invoke Toolbar listener method: onReport() [53]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:393)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:357)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
caused by: java.lang.NoClassDefFoundError: org/adempiere/pdf/ITextDocument
	at org.spin.util.ExportFormatPDF.createPDF(ExportFormatPDF.java:94)
	at org.compiere.print.ReportEngine.createPDF(ReportEngine.java:673)
	at org.adempiere.webui.window.ZkReportViewer.renderReport(ZkReportViewer.java:449)
	at org.adempiere.webui.window.ZkReportViewer.init(ZkReportViewer.java:382)
	at org.adempiere.webui.window.ZkReportViewer.<init>(ZkReportViewer.java:198)
	at org.adempiere.webui.window.ZkReportViewerProvider.openViewer(ZkReportViewerProvider.java:67)
	at org.compiere.print.ReportCtl.preview(ReportCtl.java:448)
	at org.adempiere.webui.apps.WReport.launchReport(WReport.java:252)
	at org.adempiere.webui.apps.WReport.launchReport(WReport.java:216)
	at org.adempiere.webui.apps.WReport.getPrintFormats(WReport.java:168)
	at org.adempiere.webui.apps.WReport.<init>(WReport.java:114)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onReport(AbstractADWindowPanel.java:1836)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:393)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:357)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
</pre>

Is possible that new librarys is not added to ZK library build.

Please review it for merge, is a good change.

Best regard

**Comment by marcalwestf** [comment]
@homebeaver : could you please instruct us **all** tests we'd have to carry out?
As far as I understand, it's foremost about running a report and converting it to PDF.

Are there more functions? Jasper to PDF for example?
Thanks in advance.

**Comment by marcalwestf** [comment]
@homebeaver : could you please instruct us **all** tests we'd have to carry out?
As far as I understand, it's foremost about running a report and converting it to PDF.

Are there more functions? Jasper to PDF for example?
Thanks in advance.

**Comment by yamelsenih** [comment]
Hi, @homebeaver it is a upgrade of library for export to PDF, is faster now.

The problem is that it is unsupported for ZK UI. I think that is a availability of library for ZK

**Comment by homebeaver** [comment]
Hi @yamelsenih - I cannot reproduce the error on ZK UI you reported. Because we use a pached 3.9.0 AD,
not 3.9.1 (develop) and I run in other problems when trying to install it, see #1852  

And I cannot find any reason why `org/adempiere/pdf/ITextDocument` is not found ;-(

What do you mean with _availability of library for ZK_? Do you mean itext-5 or itext-7 or both or something else?

----

Hallo @marcalwestf 

in issue #1567 I documented my motivation. And the pull does not remove the older iText-2.1.7.jar - I only marked `pdf/Document.java` as deprecated. All objects using this have the old functinality with iText-2.

- in `ReportEngine , ArchiveEngine , ExportFormatPDF` (all 3 in base) I changed to new itext
- the `print/Viewer` (swing) and ZK `ZkReportViewer`  and the Attachment/Archive viewer use new itext too
- so the places, where awt-Reports are created and transformed to pdf are changed
- a eclipse search for references to `pdf/Document` results to empty - but sometimes the IDE-result is a rope of sand!
- Jaspers is unchanged - we do not use it and there is no experience. So jaspers ist still iText-2. But can be adopted in the same symetric way.

So the tests should cover `ReportEngine , ArchiveEngine , ExportFormatPDF` and the two viewer

**Comment by homebeaver** [comment]
Hi @yamelsenih - now I could test it on ZK - without any error

- got the actual ZK AD develop + my PR 1576
- run any report - GardenWord sales order
- download the report
- look at the properties : it is PDF-Version 1.7 - created by the new itext ;-)

grafik

bye

**Comment by yamelsenih** [comment]
Hi @homebeaver i will test

**Comment by yamelsenih** [comment]
Hi @homebeaver i tested it but throw a error.

Maybe other contributor (@marcalwestf @e-Evolution or @SusanneCalderon ) can help with test.

Best regard

**Comment by e-Evolution** [comment]
Dear @homebeaver 

I tested patch https://patch-diff.githubusercontent.com/raw/adempiere/adempiere/pull/1576.patchand found problems, unfortunately it is not stable yet :-( , here my comments:

1.- The build project fail , I think that is necessary to add into the tools/build.xml new libraries he my path

[1567_add_libraries_build_xml.txt](https://github.com/adempiere/adempiere/files/2259801/1567_add_libraries_build_xml.txt)

2.- I tested generate the Sales Order 80002 with included images and is ok for swing and ZK, is nice that now to generated PDF is very fast and download PDF is working ok,  but my first problem that I found in ZK when the report  is generate 

image

image

Here first problem when try generate Report Icon:
The
Generate for Swing is ok
image

Generate for ZK  is not ok, the landscape format not work, all is shown as portrait format

image

Second problem when try archive the PDF generated not work , the icon show that was saved, when try recover not found

image

image

image

image

When try open got java.lang.NumberFormatException: For input string: ".5.2"

image


16:16:54.594 Viewer.<init>:  [119]
16:16:54.594 LayoutEngine.<init>: MPrintFormat[ID=120,Name=Invoice Header,Language=Language=[English,Locale=en_US,AD_Language=en_US,DatePattern=MM/DD/YYYY,DecimalPoint=true],Items=57] - PrintData[Invoice Header,Rows=1,TableName=C_Invoice_Header_v] - (C_Invoice_Header_v.C_Invoice_ID=103) [119]
16:16:54.594 LayoutEngine.layoutForm: Row=0 [119]
16:16:54.603 LayoutEngine.includeFormat: MPrintFormat[ID=121,Name=Invoice LineTax,Language=Language=[English,Locale=en_US,AD_Language=en_US,DatePattern=MM/DD/YYYY,DecimalPoint=true],Items=48] - Item=Invoice (7454) [119]
16:16:54.603 DataEngine.getPrintDataInfo: Invoice LineTax - en_US [119]
16:16:54.617 DataEngine.loadPrintData: Rows=6 - ms=14 [119]
16:16:54.617 LayoutEngine.layoutTable: Invoice LineTax - Invoice LineTax [119]
16:16:54.625 ReportExportHandler.load: Using Standard Report Export [119]
16:17:02.257 ITextDocument.writePDF: pageable:org.compiere.print.layout.LayoutEngine@cc872db [17]
16:17:02.356 ITextDocument.writePDF: done document.open() PDFXConformance:0 [17]
16:17:03.592 ADialog.info: Archived - null [17]
16:17:21.968 APanel.actionPerformed: Archive - 16 [17]
16:17:21.968 APanel.cmd_archive: ID=102 [17]
16:17:43.616 APanel.actionPerformed: Archive - 16 [17]
16:17:43.616 APanel.cmd_archive: ID=102 [17]
16:17:44.440 FormFrame.openForm: AD_Form_ID=118 - Class=org.compiere.apps.form.ArchiveViewer [17]
16:17:44.601 Archive.init:  [17]
16:17:44.677 Archive.cmd_query: Length=1 [17]
16:17:44.677 Archive.updateVDisplay: Index=0, Length=1 [17]
java.lang.NumberFormatException: For input string: ".5.2"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jpedal.io.PdfReader.readLegacyReferenceTable(Unknown Source)
	at org.jpedal.io.PdfReader.readReferenceTable(Unknown Source)
	at org.jpedal.PdfDecoder.openPdfFile(Unknown Source)
	at org.jpedal.PdfDecoder.openPdfFile(Unknown Source)
	at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:465)
	at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:605)
	at org.compiere.apps.form.ArchiveViewer.updateVDisplay(ArchiveViewer.java:374)
	at org.compiere.apps.form.ArchiveViewer.cmd_query(ArchiveViewer.java:457)
	at org.compiere.apps.form.ArchiveViewer.query(ArchiveViewer.java:431)
	at org.compiere.apps.AArchive.actionPerformed(AArchive.java:179)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
16:17:49.092 MRole.get: AD_Role_ID=102, AD_User_ID=100, reload=false [29]

**Comment by homebeaver** [comment]
Hi @e-Evolution - thank you for testing

1. the build - I checked `/tools/build.xml` - it seems OK for me
the old `jpedal.jar` is replaced by `icepdf-core-6.2.2.jar + icepdf-viewer-6.2.2.jar`
Do you build with IDEA? Wihout using /tools/build.xml?

To avoid using jpedal I'll remove it. See your trace - there is jpedal in the traceback!

**Comment by e-Evolution** [comment]
@homebeaver , Thank you for your modification.

But if I remove the old library exist dependences that when executing ./adempiere/util_dev/RUN_build.sh fails, and not can build an Adempiere Binary. There is still code with dependencies to the old libraries. to include these improvements it is necessary that an ADempiere Binary can be built and that the behavior of the current functionality does not change, as I warned in my comments archiving documents in Adempiere is not working with the new libraries and the output of the formats for land space and portrait they do not work when you use ZK.

kind regards

**Comment by homebeaver** [comment]
Hi @e-Evolution ,
I have checked `util_dev/RUN_build.sh` and ... can build ! Here my environment and what I done:

`Linux 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64`

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
- I cloned the pull-request branch in a fresh dir
- and start `util_dev/RUN_build.sh`
- here the cmd history:

```
> mkdir branch-1567
> cd branch-1567
> git clone --branch develop-1567 https://github.com/klst-de/adempiere.git
> cd adempiere/utils_dev/
> ./RUN_build.sh

... 
complete:

BUILD SUCCESSFUL
Total time: 4 minutes 17 seconds
```
regards

**Comment by yamelsenih** [comment]
Hi everybody, I will test it.

**Comment by homebeaver** [comment]
Hi @yamelsenih - everytime when I try to replace the old obsolet jpedal jar from eclipse .classpath
( see commit a25fc9a )
I get a conflict. So I revert this step and open an extra pull for it.
bye

**Comment by e-Evolution** [comment]
@homebeaver I testing your last change and fix the problem

**Comment by mckayERP** [comment]
Need to update the Eclipse web deployment assembly.  Its missing the new libraries.  This only affects ZK debugging using Eclipse.

**Pull request merged**
