### PR TITLE
Fix path to class for Import Table

### LINKED ISSUE #4065: [Bug Report] Outdated path of class for import table
## Bug report

When executing a data import process with import tables, due to the change of packages, when the import class is searched, it cannot be found because it belongs to the EntityType Dictionary and does not have a package, so when setting the default , it takes an outdated package `org.compiere.model` instead of `org.adempiere.core.domains.models`.

This causes a cast error because it loads GenericPO instead of the required class.

https://github.com/adempiere/adempiere/blob/5fc84c4f87de754c6b2cc715e4d5c779c387ad5f/base/src/org/compiere/model/MTable.java#L231

https://github.com/adempiere/adempiere/blob/5fc84c4f87de754c6b2cc715e4d5c779c387ad5f/base/src/org/compiere/model/MTable.java#L226-L239

#### Expected behavior

when you need to use the default package, it should be `org.adempiere.core.domains.models` instead of `org.compiere.model`

#### Other relevant information
- Your OS: Xubutnu 22.04
- Java version: 11
- ADempiere version: 394 develop
- Browser [e.g. chrome, safari]: Debug Swing
- DB Provider: PostgreSQL
- DB version: 12.4

### PR DESCRIPTION
**Pull request by rcapecce**
Fix #4065

### CODE REVIEW

**Comment by OFB-Review1** [comment]
se acordó que las correcciones estarán en la rama de hotfix, no la de develop. Por favor modificar.

**Comment by e-Evolution** [comment]
@OFB-Review1 , @yamelsenih , the code is right , @yamelsenih can please resend the PR with hotfix branch please

**Comment by rcapecce** [comment]
> @OFB-Review1 ,the code is right , @rcapecce Raul can please resend the PR with hotfix branch please

Ok, I pushed the PR to the hotfix branch

**Review by OFB-Review1 — APPROVED** [review]
the error is replicated and checks the correct operation of the new code

**Pull request merged**
