### PR TITLE
#1990 Info windows: show newest order, invoice, ... on top

### PR DESCRIPTION
**Pull request by homebeaver**
hi all,
this implements issue #1990

regards EUG

### CODE REVIEW

**Comment by marcalwestf** [comment]
**Invoice Info**
Old sort order: Business Partner Name, DocumentNo.
Suggested sort order: Date Invoiced, DocumentNo

**Comment by marcalwestf** [comment]
**Order Info**
Old sort order: Business Partner Name, Date Ordered, DocumentNo.
Suggested sort order: Date Ordered, DocumentNo

**Comment by marcalwestf** [comment]
**Payment Info**
Old sort order: Account Name, BP Name, Date Trx.
Suggested sort order: Date Trx, DocumentNo

**Comment by marcalwestf** [comment]
As far as I've tested, the suggested info windows display ordered by date/document no rather than by (not systematically) name/date/document no.

IMO, when dealing with large data, sorting by date is preferable.

I'd support this pull request, but I'd like to listen another opinions.

**Comment by marcalwestf** [comment]
.... perhaps we should ask users with experience using this windows....

**Comment by yamelsenih** [comment]
Hi

**Comment by yamelsenih** [comment]
I agree with this improve

**Pull request merged**
