### PR TITLE
Include chart of accounts for Nicaragua

### PR DESCRIPTION
**Pull request by williamjmorenor**
Signed-off-by: William Moreno Reyes <williamjmorenor@fedoraproject.org>

### CODE REVIEW

**Comment by marcalwestf** [comment]
@williamjmorenor  hi William, thank you for your contribution.

Could you explain the reason for the changes? It is to document the whole process.
Usually, when you create a new issue or pull request, there are patterns you can choose from.

Thanks again!!

**Comment by williamjmorenor** [comment]
Any update?

**Comment by berroteran** [comment]
tis a new Document, right?

**Review by marcalwestf — APPROVED** [review]
- Checked csv and ods files
- only tex files added, no code
- no build nor functional test needed
Test **passed**

**Pull request merged**
