### PR TITLE
Add support to import Business Partner Bank Account

### PR DESCRIPTION
**Pull request by carlosaparadam**
Add support to import Business Partner Bank Accounts and support more than one business partner location.

sample:
Screenshot_20200127_115237

Screenshot_20200127_115256

Screenshot_20200127_155224

Screenshot_20200127_155302

Screenshot_20200127_155515

Screenshot_20200127_155551

Screenshot_20200127_155534

Currently has not support to import business partner with more than one location, see this example after change:

Screenshot_20200127_185256

Screenshot_20200127_185311

Screenshot_20200127_185533

Screenshot_20200127_185547

### CODE REVIEW

**Comment by marcalwestf** [comment]
@carlosaparadam  do you have by chance an import file ready to import, so the test can be accomplished more quickly?
Thanks!!

**Comment by carlosaparadam** [comment]
hi @marcalwestf, thanks for your review. i have attached a package with import format and csv with example data for your review.

Regards
[ImportBPartner.zip](https://github.com/adempiere/adempiere/files/4161903/ImportBPartner.zip)
[BusinessPartner.zip](https://github.com/adempiere/adempiere/files/4161904/BusinessPartner.zip)

**Comment by marcalwestf** [comment]
@carlosaparadam  now I am going to review.

**Comment by marcalwestf** [comment]
@carlosaparadam  the migration file _05550_Add_Support_to_Import_Business_Partner_Bank_Account.xml_ is in folder _392lts-393lts_.

IMHO it should be the folder _393lts-394lts_.

**Comment by carlosaparadam** [comment]
hi @marcalwestf, i did the suggested changes. 

Regards

**Comment by marcalwestf** [comment]
Here my results concerning importing bank accounts for business partner:
1.- I cannot manage to import bank accounts, though I have managed to get some data into BP Import, this data was not enough to create a Bank Account for BP.

2.- It seems that bank was not resolved, neither by Name nor by ID

3.- The Import Format I used:
Selection_347

3.- The import file:
Selection_348

4.- The BP Import (bank section): I display only one, but there are three of them:
Selection_349

5.- The BP is imported alright, but no bank account for the customer or even not a bank account at all.

Same happens when instead of the bank ID, the bank name is used in Import Format.

I don't know if there's something I am missing, or doing wrong.

**Comment by marcalwestf** [comment]
@carlosaparadam  with importing locations, I also have problems:
1.- I use the same Import Format and same import file as my last comment.

2.- In the BP import, I see several locations (I depict here only one):
Selection_350

2.- I'd expect that several locations are imported, but only one location is imported (the first one):
Selection_351

3.- But, there were three contacts imported, all directing to the location!!!:
Selection_352

Perhaps you can guide me to test...

**Comment by carlosaparadam** [comment]
hi @marcalwestf , i will review this 

Thanks

**Comment by carlosaparadam** [comment]
Hi @marcalwestf , i did exactly every one the step than you applied and it's work correctly. It seems that in your environment does not find the source changes.

Import Format:
image

Import file:
image

Business Parner Imported:
image

Business Partner Bank Account:
image

Business Partner Locations:
image

Business Partner Contact:
image

**Comment by marcalwestf** [comment]
@carlosaparadam  I will give it another try.....

**Pull request merged**
