### PR TITLE
Add support to ASP by role

### PR DESCRIPTION
**Pull request by yamelsenih**
Currently you can define a Window, Process and Smart Browser by role.

This pull request allows define levels by role, then the role can have
many levels allocated instead only from client. See the gif
Peek 2021-07-14 12-51

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih hi Yamel, I miss the tab _ASP Access_ on window _Role_.
Searching in all XMLs, I cannot find in the database a table named _asp_access_ nor in the XMLs a definition of such a table. I find only the tab _Access Token_.

Perhaps am I missing something?
Thanks.

**Comment by yamelsenih** [comment]
> @yamelsenih hi Yamel, I miss the tab _ASP Access_ on window _Role_.
> Searching in all XMLs, I cannot find in the database a table named _asp_access_ nor in the XMLs a definition of such a table. I find only the tab _Access Token_.
> 
> Perhaps am I missing something?
> Thanks.

Hi @marcalwestf here is create the table https://github.com/adempiere/adempiere/pull/3532/files#diff-418137bfdfab84c6d291500e705a64ef9d878eabe08746777197a5ae20f60957R16

**Comment by marcalwestf** [comment]
thanks @yamelsenih  Yamel, I hadn't seen the commit with the XML file.
Now, I'm going to begin the test.

**Review by marcalwestf — APPROVED** [review]
Load and apply XML file.

Scenario I:
- Log in as _SytemAdministrator_ and create an _ASP Module_ and an _ASP Level_entry.
- As _GardenAdmin_, set in _Client_ window the field _isUseASP_=true.
- In window _Role_, tab _ASP Access_, create an entry and refer to the _ASP Level_.
- In window _Window Customization_, create an entry, making reference to the _ASP Level_ and to any window (e.g. _Business Partner_).
- In the tabs below _Window Customization_, configure tabs and fields as you please.
-  Shut down and re-start ADempiere.

Result: the window (e.g. _Business Partner_) is displayed as configured.

Scenario II

- Log in as _SytemAdministrator_ and create an _ASP Module_ and an _ASP Level_entry.
- As _GardenAdmin_, run process _Role Access Update_ for same role.
- Check entries at window _Role_, tab _ASP Access_.

Result: an entry was generated for defined _ASP Levels_

All tests passed.

**Pull request merged**
