### PR TITLE
Rename store integration package

### PR DESCRIPTION
**Pull request by yamelsenih**
Just change the base package of Store integration.

Previously it was:
```Java
- org.spin.model
- org.spin.util
- org.spin.util.support
```

Now is:

```Java
- org.spin.store.model
- org.spin.store.util
- org.spin.store.util.support
```

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih I tried to try this and I get these errors from a database created from scratch

When open the Basket Window:

image

```
-----------> AbstractADWindowPanel.onNew: Insert Record disabled for Tab [40]
-----------> AbstractADWindowPanel.onNew: Insert Record disabled for Tab [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
===========> GridTable.open: Count SQL=SELECT COUNT(*) FROM W_Basket WHERE (Processed='N' OR Updated>SysDate-1) AND W_Basket.AD_Client_ID IN(0,11) AND W_Basket.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) AND (W_Basket.W_Basket_ID IS NULL OR W_Basket.W_Basket_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 402 AND AD_User_ID <> 100 AND IsActive = 'Y' )) [40]
org.postgresql.util.PSQLException: ERROR: column "processed" does not exist
  Position: 38; State=42703; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at jdk.proxy2/jdk.proxy2.$Proxy5.executeQuery(Unknown Source)
        at org.compiere.model.GridTable$Loader.open(GridTable.java:3430)
        at org.compiere.model.GridTable.open(GridTable.java:628)
        at org.compiere.model.GridTab.query(GridTab.java:744)
        at org.adempiere.webui.panel.ADTabPanel.query(ADTabPanel.java:804)
        at org.adempiere.webui.panel.AbstractADWindowPanel.initTab(AbstractADWindowPanel.java:650)
        at org.adempiere.webui.panel.AbstractADWindowPanel.initPanel(AbstractADWindowPanel.java:363)
        at org.adempiere.webui.panel.ADWindowPanel.initPanel(ADWindowPanel.java:236)

```

**Comment by e-Evolution** [comment]
@yamelsenih The C_PaymentMethod table you are defining as a core class using the C_ prefix, these classes should be defined as MPaymentMethod instead of MCPaymentMethod, so it works system wide.

On the other hand, if it is going to be a system class, the payment methods should be enabled for any payment, not just for store payments.

So I think they should be in the Payment Term menu and be a core class for the whole system.

image

**Comment by e-Evolution** [comment]
@yamelsenih To test this functionality in more depth, do you have documentation available to carry out a complete process and validate that it works as expected?

On the other hand, I see no point in keeping org.spin.store/src/main/java/org/spin/model/validator/VueStoreFront.java by moving the class to another package you have broken backwards compatibility since any customization that uses the model classes will no longer compile since you have to move the import to the new route, this is the reason I say that backward compatibility is broken, in this specific case I could accept it because this functionality is new for this version.

**Comment by yamelsenih** [comment]
Hi Victor, you can see the backward Compatibility here: https://github.com/adempiere/adempiere/pull/3832/files#diff-64c4b3c976b22f5be82eefda29afe4bfaef0d2f33b64cf9357b8205572efa8ce are you sure or review it?

**Comment by yamelsenih** [comment]
>@yamelsenih The C_PaymentMethod table you are defining as a core class using the C_ prefix, these classes should be defined as MPaymentMethod instead of MCPaymentMethod, so it works system wide.

The original functionality is part of store. I can change it but if you review the current functionality is the same. I think that it should no be change the scope.

In other or can be change

**Comment by marcalwestf** [comment]
@yamelsenih , @e-Evolution I get the same error when opening the _Basket_ window, but this happens already on Adempiere without the present changes: if I run it on the branch develop, the same error is generated, so this error is not relevant to the present pull request.

**Comment by yamelsenih** [comment]
> @yamelsenih I tried to try this and I get these errors from a database created from scratch
> 
> When open the Basket Window:
> 
> image
> 
> ```
> -----------> AbstractADWindowPanel.onNew: Insert Record disabled for Tab [40]
> -----------> AbstractADWindowPanel.onNew: Insert Record disabled for Tab [40]
> -----------> Msg.getMsg: NOT found: QuickEntry [40]
> -----------> Msg.getMsg: NOT found: QuickEntry [40]
> ===========> GridTable.open: Count SQL=SELECT COUNT(*) FROM W_Basket WHERE (Processed='N' OR Updated>SysDate-1) AND W_Basket.AD_Client_ID IN(0,11) AND W_Basket.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) AND (W_Basket.W_Basket_ID IS NULL OR W_Basket.W_Basket_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 402 AND AD_User_ID <> 100 AND IsActive = 'Y' )) [40]
> org.postgresql.util.PSQLException: ERROR: column "processed" does not exist
>   Position: 38; State=42703; ErrorCode=0
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
>         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
>         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
>         at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
>         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
>         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
>         at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
>         at jdk.proxy2/jdk.proxy2.$Proxy5.executeQuery(Unknown Source)
>         at org.compiere.model.GridTable$Loader.open(GridTable.java:3430)
>         at org.compiere.model.GridTable.open(GridTable.java:628)
>         at org.compiere.model.GridTab.query(GridTab.java:744)
>         at org.adempiere.webui.panel.ADTabPanel.query(ADTabPanel.java:804)
>         at org.adempiere.webui.panel.AbstractADWindowPanel.initTab(AbstractADWindowPanel.java:650)
>         at org.adempiere.webui.panel.AbstractADWindowPanel.initPanel(AbstractADWindowPanel.java:363)
>         at org.adempiere.webui.panel.ADWindowPanel.initPanel(ADWindowPanel.java:236)
> ```

Hi Victor this was resolved here: https://github.com/adempiere/adempiere/pull/3832/commits/69c02701ba1aaaf26aa12bb1e99729fedd9e292a

**Comment by yamelsenih** [comment]
> @yamelsenih , @e-Evolution I get the same error when opening the _Basket_ window, but this happens already on Adempiere without the present changes: if I run it on the branch develop, the same error is generated, so this error is not relevant to the present pull request.

Hi Mario this was a bad definition of window but was resolved [here](https://github.com/adempiere/adempiere/commit/69c02701ba1aaaf26aa12bb1e99729fedd9e292a)

**Comment by yamelsenih** [comment]
> @yamelsenih The C_PaymentMethod table you are defining as a core class using the C_ prefix, these classes should be defined as MPaymentMethod instead of MCPaymentMethod, so it works system wide.
> 
> On the other hand, if it is going to be a system class, the payment methods should be enabled for any payment, not just for store payments.
> 
> So I think they should be in the Payment Term menu and be a core class for the whole system.
> 
> image

Hi Victor you can approve this pull request and with a final request I can change the definition of `C_PaymentMethod`.

**Review by marcalwestf — APPROVED** [review]
- Check no compiler errors -> OK
- Check build -> OK
- Check code: refactoring and improving imports -> OK
- Check code: class refactoring -> OK
- Loaded and Executed _XMLs 09430_Rename_base_package_of_Store_Integration.xml_ and _09440_Fixed_windows_type_for_basket.xml_
- Check new window type for window _Basket_ -> OK
- Check process, entity type and model vaalidator renaming to org.spin.store -> OK
- Open Basket window (now it is a Maintenance window, not a Transaction) -> OK

Not tested/checked: VueStoreFront, Loan module functionality.
**Test passed**.

**Comment by e-Evolution** [comment]
> > @yamelsenih The C_PaymentMethod table you are defining as a core class using the C_ prefix, these classes should be defined as MPaymentMethod instead of MCPaymentMethod, so it works system wide.
> > On the other hand, if it is going to be a system class, the payment methods should be enabled for any payment, not just for store payments.
> > So I think they should be in the Payment Term menu and be a core class for the whole system.
> > image
> 
> Hi Victor you can approve this pull request and with a final request I can change the definition of `C_PaymentMethod`.

@yamelsenih To facilitate the correct implementation of the class with C_ prefixes, I will merge this pull request, hoping that a new one will also be made to change the focus of C_PaymentMethod and C_PaymentMethodAllocation, and to integrate with MPayment

**Pull request merged**
