### PR TITLE
[Feature Request] Upgrade Tomcat from version 8 to 9 version #3498

### PR DESCRIPTION
**Pull request by e-Evolution**

### CODE REVIEW

**Comment by marcalwestf** [comment]
@e-Evolution  hi Victor, is this PR independent or does it depend on another?
Thanks

**Comment by marcalwestf** [comment]
Testing 

- IDE: Eclipse
- Server Tomcat 9
- Java 8

Start Report _Daily Invoice_
imagen

An errror message pops up;
imagen


imagen

**Comment by e-Evolution** [comment]
Hi @marcalwestf , please validate that you are using JDK 11 and not JDK8

**Comment by marcalwestf** [comment]
with the latest commits by @e-Evolution , this pull request also tests java 11 (https://github.com/adempiere/adempiere/pull/3479), because this pull request's branch build upon jdk11.

So, if this PR works, it will also work JDK11.

**Comment by marcalwestf** [comment]
Tests executed on Server provided by @rcapecce :

- create BP Category, BP, Product Category, Product, PriceList, Location, User, Role
- upload attachments
- create, complete, void documents (Requisition, PO, Payments, Receipts, SO, Sales Invoice, Shipment)

**Review by marcalwestf — APPROVED** [review]
- @niclopup has tested this PR together with https://github.com/adempiere/adempiere/pull/3479
- other tests were done by myself
- all tests were successful

Tests passed.

**Comment by marcalwestf** [comment]
@e-Evolution just resolve the small conflict to merge the PR.
Thanks!

**Pull request merged**
