### PR TITLE
Price entries

### PR DESCRIPTION
**Pull request by SusanneCalderon**
A Smartbrowser to generate or edit prices in the window Pricelist

### CODE REVIEW

**Comment by e-Evolution** [comment]
@SusanneCalderon please no use more null reference in your code, you use for Optional so you can avoid finding found possible future NPE.

On the other hand, when adding a new feature to the dictionary for Adempiere core you should use Entity Type ' D', that means Dictionary the C or A never was used.

[Java 8 Optional](http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html)

i.e.

`Optional<MProductPrice>  productPriceOptional  = Optional.ofNullable(MProductPrice.get(getCtx(), getRecord_ID(), key, get_TrxName()) ); 
        MProductPrice productPrice = productPriceOptional.orElse(MProductPrice(getCtx(), getRecord_ID(), key, get_TrxName()));
`

**Comment by SusanneCalderon** [comment]
OK, Victor, I will change the code, thank you for your observation.

**Comment by wdtz** [comment]
**Test results:**
1.- The base operation is correct

**Improvements:**
1.- Product Group could be part of the filters
2.- Business Partner (Vendor) could be part of the filters

**Comment by SusanneCalderon** [comment]
Thank you Waditza, I will update the smart browser.

**Pull request merged**
