### PR TITLE
fix: Remove deprecated warning with `new Long` constructor.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
`The constructor Long(long) is deprecated since version 9`

`The constructor Long(String) is deprecated since version 9`

imagen

### CODE REVIEW

**Review by marcalwestf — APPROVED** [review]
Review:
- Check code: no compiler errors.
- Check code: use of _valueOf()_ instead of _New()_
- Compiler: warnings reduced.
- Build: ANT build run without errors.
- Usage: random window and reports calling; creating, modifying and deleting records.

Result: no errors -> **PR accepted**.

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  hi Edwin, there is a small conflict that must be tackled before merging.
Thanks!!

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf, I already updated the change with the latest `hotfix/3.9.4.001`.

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf, I already updated the change with the latest `hotfix/3.9.4.001`.

**Pull request merged**
