### PR TITLE
Fixed VButton to hide non active records.

### PR DESCRIPTION
**Pull request by trifonnt**
Fixed VButton to hide non active AD_Ref_List and AD_Ref_List_Trl records.

### CODE REVIEW

**Comment by e-Evolution** [comment]
Hi Trifon!!!
is a pleasure to see you back.

Please, can you make pull request on hotfix/3.8.0#002  branch we are collect here all fix bug to can get a patches release, master only is apply based on release branch.

kind regards
Victor

**Comment by e-Evolution** [comment]
Hi , here a posible alternative solution

http://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Comment by trifonnt** [comment]
Hi Victor,

>Please, can you make pull request on hotfix/3.8.0#002 branch we are collect here all fix bug to can get a patches release, master only is apply based on release branch.

I'm sorry but I'm not sure that I understand what you mean.
Change is quite small, so anyone can pull/push it to whatever branch is needed.

Regards,
Trifon

**Comment by e-Evolution** [comment]
Hi Trifon 
Of idea is that all patches need be push into hotfix/3.8.0#002, this way I can collect all patches and create for old version patches.jar, so this reason because i need that pull request need come from hotfix/3.8.0#002 branch, here the procedure how to : 

1.- make to backup next command cp adempiereSource adempiere.bak
2.- cd adempiereSource 
3.- git pull
4.- git checkout hotfix/3.8.0#002
5.- cp adempiere.bak/client/src/org/compiere/grid/ed/VButton.java adempiereSource/client/src/org/compiere/grid/ed/VButton.java
6.- git commit -m 'Fixed VButton to hide non active records. #51'
7.- git push 
8.- finality you can how create pull request for this commit 

please if you have some doubt can chant via gitter http://adempiere.net/web/guest/chat-on-line

kind regards
Victor

**Pull request closed without merging**
