### PR TITLE
Fixed error with process parameters for process builder

### PR DESCRIPTION
**Pull request by yamelsenih**
Add support to process parameter To on process builder.

If you use ProcessBuilder and add a parameter with **From** and **To**

### CODE REVIEW

**Comment by marcalwestf** [comment]
a question @yamelsenih : is it right that all parameters have to be tested because the whole method was changed?
Thanks

**Comment by yamelsenih** [comment]
Hi @marcalwestf this change apply for all functionalities that are using ProcessBuilder, currently the range parameters is not implemented for this functionality.

**Comment by e-Evolution** [comment]
@yamelsenih please give support to range using a polymorphous method, this way the build pattern DSL is rightly implemented 

`ProcessInfo processInfo = ProcessBuilder.create(getCtx())
.process(GenerateInvoiceInOutBound.getProcessId())
.withParameter(GenerateInvoiceInOutBound.DATEINVOICED, 
TimeUtil.getDay(2019, 1, 1),
TimeUtil.getDay(2019, 1, 31))
.execute(get_TrxName());`

**Comment by yamelsenih** [comment]
hi @e-Evolution this change was done

**Pull request merged**
