### PR TITLE
#1699 Add automatic reconciliation

### LINKED ISSUE #1699: Add support view for Bank Statement Reconciliate
Is nice to have a view for match of payment imported with ADempiere bank movements. It allows compare both movements and reconciliate automatically

### LINKED ISSUE #1700: Add Quicken Interchange Format support
Currently does not exist a Loader Bank Statement for read [QIF format](https://en.wikipedia.org/wiki/Quicken_Interchange_Format), it is a standard format for some banks, is nice to have it for loader import

### LINKED ISSUE #1701: Add support to MT940 format
Currently the format (MT940) [https://en.wikipedia.org/wiki/MT940] is not supported from ADempiere, a reference of it is https://web.archive.org/web/20160725042101/http://www.societegenerale.rs/fileadmin/template/main/pdf/SGS%20MT940.pdf

### LINKED ISSUE #1702: Add generic bank matcher
It is a generic class for matching bank statement, It will be used like example on matching window

### LINKED ISSUE #1706: Add Bank reference for Bank Statement Matcher
Currently exist a Bank Statement Matcher, it is a global matcher but exist many matcher that are distinct for each bank.

My proposal is add a bank reference to matcher and a new tab for Bank definition

### LINKED ISSUE #1713: Add support for import Bank statement from Matching
Is nice to have a automatic process for import bank statement after make match between imported payment and ADempiere payment, it allows create automatically lines of bank statement after a match

### LINKED ISSUE #1773: Bugfix org.zkoss.zk.ui.WrongValueException: Too many characters are entered. At most 10 characters are allowed when a window is open
Currently, the ZK UI to restrict to length for a column, this throws an exception org.zkoss.zk.ui.WrongValueException and interrupt the load for a window.

1.- Change the column size for TaxID of current value to 20 into  C_BPartner table
2.- Save a value into the TaxID with String of 20
3.- Change the column size for TaxID of original value  C_BPartner table
4.- Try open the window business partner.

this throws an exception org.zkoss.zk.ui.WrongValueException.

### LINKED ISSUE #1793: Resolve invalid parse Date
When a bank statement is imported from load bank statement process and it is based on OFX/OFC format, it can generate a error parsing date for opetration, the follow error was throw in a customer:
<pre>
Error parsing date "20180613120000"
</pre>

The error is generated if exist a date with a length greated than expected

See the minor change for code:
<pre>
private Timestamp parseOfxDate(String value) throws ParseException
	{
		try
		{
			if(Util.isEmpty(value)) {
				return null;
			}
			//	Validate length
			if(value.length() > 8) {
				value = value.substring(0, 8);
			}
			SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
			sdf.setLenient(false);
			return new Timestamp (sdf.parse(value).getTime());
		}
		catch(Exception e)
		{
			throw new ParseException("Error parsing date: " + value, 0);
		}
	}   //parseOfxDate
</pre>

### LINKED ISSUE #1807: Add Match class for Reference No
It is a generic class for matching bank statement using only reference number, It will be used like example on matching window

### PR DESCRIPTION
**Pull request by yamelsenih**
Hi everybody, I am happy for share this new contribution for automation of bank statement.

Now is very easy make a bank statement from import:

Technical info: With it pull request is supported follow standard bank statement info:
 - [QIF](https://en.wikipedia.org/wiki/Quicken_Interchange_Format): Quicken Interchange Format
 - [MT940](https://en.wikipedia.org/wiki/MT940)
 - [OFX/OFC](https://en.wikipedia.org/wiki/Open_Financial_Exchange): Open Financial Exchange (older support)

Issues related:
 - fixes #1700
 - fixes #1701
 - fixes #1702
 - fixes #1699
 - fixes #1773
 - fixes #1706
 - fixes #1713
 - fixes #1807
 - fixes #1793

Forms Added:
 - Bank Statement Matcher

Process Added:
 - Create From Bank Statement for Bank Statement Matcher

Changes for Windows:
 - Add tab for relation of Bank Statement Matcher with Bank (Tab is added in Bank Definition)
 - Add Tab for sorting

Here a Step by Step for Functional Testing:

- Basic Setup for load and matching: 
  - Go to **System Rules** -> **Organization Rules** -> **Bank Statement Matcher**
screenshot_20180816_001456
  - Add new Bank Statement Matcher to it, here exist a example list:
screenshot_20180816_001520
  - Now, go to **System Rules** -> **Organization Rules** -> **Bank**
screenshot_20180816_001538
  - Go to **Statement Matcher** tab and add custom matcher that apply for your bank:
screenshot_20180816_001606
  - Go to **Sequence** tab and order priority for matching:
screenshot_20180816_001628
  - Now, you can go to **Statement Loader** tab and define custom loader for bank statement
screenshot_20180816_001756
- Load **Bank Statement**:
  - Go to **System Admin** -> **Data** -> **Data Import** -> **Load Bank Statement**
screenshot_20180816_001705
  - Select **Bank Statement Loader** and and **file to load** parameters and run
screenshot_20180816_001925
- Make matching:
  - Go to **Open Items** -> **Bank Statement**
screenshot_20180816_001949
  - Into **Bank Statement** window go to **Process Run** and select  **Bank Statement Match** option
screenshot_20180816_002003
  - When form is opened, default value is setted for bank account (Now you can press **Refresh** button!!!):
screenshot_20180816_002105
  - When it is loaded you can see all data:
    - Left: **Imported Payments**
    - Right: **System Payments**
    - Below: **Matched Payments**
  - Now you can press **Simulate Match** button
screenshot_20180815_213718
  - All matched payment are showed (Now press ok for add to Bank Statement) See result:
screenshot_20180816_002635

Note: When payments are add to **Bank Statement** they are imported automatically.

Best regard

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih , I tested with the format qif, works perfectly. 
I will continue with the other formats.
Great improvement, it helps a lot to reconcile. Especially when you have a lot of movements in your bank account.

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
As mentioned I tested for qif without problems.
For testing the other formats I need some instructions for the configuration.

**Comment by yamelsenih** [comment]
Here a list of supported format:
Technical info: With it pull request is supported follow standard bank statement info:
 - [QIF](https://en.wikipedia.org/wiki/Quicken_Interchange_Format): <pre>org.spin.util.impexp.GenericQIFBankStatementLoader</pre>
 - [MT940](https://en.wikipedia.org/wiki/MT940) <pre>org.spin.util.impexp.GenericMT940BankStatementLoader</pre>
 - [OFX/OFC](https://en.wikipedia.org/wiki/Open_Financial_Exchange): <pre>org.compiere.impexp.OFXFileBankStatementLoader</pre>

**Comment by yamelsenih** [comment]
Matchers for import:
<pre>org.spin.util.impexp.ReferenceNo_BankMatcher</pre>
<pre>org.spin.util.impexp.ReferenceNoLeftLike_BankMatcher</pre>
<pre>org.spin.util.impexp.ReferenceNoLike_BankMatcher</pre>
<pre>org.spin.util.impexp.ReferenceNoLikeWithImport_BankMatcher</pre>
<pre>org.spin.util.impexp.ReferenceNoLikeWithPayment_BankMatcher</pre>
<pre>org.spin.util.impexp.ReferenceNoRightLike_BankMatcher</pre>

**Pull request merged**
