### PR TITLE
Fixed error with price calculation for RMA

### PR DESCRIPTION
**Pull request by yamelsenih**
Fixes: #4255

### CODE REVIEW

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I could not reproduce the error.
Steps:
1.
PriceList Old, Product Azalee, $30
00_PL_Old

2.
New Order, Product Azalee, Paymentterm Immediate, Tax exempt, Price $30, Linenetamt $30
01_Orderline

3. Change PriceList product azalee to $35
02_PL_New

4. Cache Reset

5. RMA, Product Azalee, Price $30 as in the Orderline
04_rmaline

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon this happen when the return is used from a process or from POS.

**Review by SusanneCalderon — APPROVED** [review]
I tested with different sales orders with different prices.
1. Sales Order with price from the pricelist -- change price in pricelist
Result: RMA and Credit Note with original price OK
2. Sales Order with modified price (Price <> price in priceList) -- change price in pricelist to another value
Result: RMA and Credit Note  with original price OK

**Comment by marcalwestf** [comment]
This pull request has been tested and accepted; it can be merged, but it is waiting for older pull requests to be merged.

**Pull request merged**
