### PR TITLE
Bug fix error to export Jasper Report to Excel

### PR DESCRIPTION
**Pull request by e-Evolution**
#1712 Bug fix error to export Jasper Report to Excel  https://github.com/adempiere/adempiere/issues/1712

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih the project compile ? if compile is ok , I not use eclipse , I have not as include the eclipse setting, but you can include if you want.

I think the code should be agnostic to IDE

**Comment by yamelsenih** [comment]
Hi @e-Evolution can you add changes suggested by @marcalwestf ?

Best regard

**Comment by yamelsenih** [comment]
Hi @all i test it an is ok however classpath is unsupported.

I will merge it and make a direct commit with classpath changes

**Comment by e-Evolution** [comment]
fixes

**Pull request merged**
