### PR TITLE
Fixed error with Printing report from Payroll Process

### PR DESCRIPTION
**Pull request by yamelsenih**
Fixed: #4249

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
Tested on Swing after switching to branch **hotfix/3.9.4.002-local/# 4249-NPE_Printing_Report_from_Payroll_Process**:


1.- Created a Payroll Process 
For a Payroll (in this case it is named _Test_) with some basic _Concepts_:
image

2.- Payroll Report
Before printing,  a _Payroll Report_ must be created; it will be selected as parameter.
image

3.- Print Format of Payroll Report
The Payroll Report has to refer to a Print Format defined as Jasper Process:
image

4.- Jasper Process (role _System Administrator_)
The Jasper Process must display same name for attachment file and field _Jasper Report_:
image

5.- Run Payroll Process Report
Select the _Payroll Report_ created before.
image

6.- Results
The result is  the following:
image

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/data2/entwicklung/westfaliaRepository_2023-08_NEU/adempiere_erpcya/tools/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
-----------> Msg.getMsg: NOT found: ProcessError [58]
===========> ProcessUtil.startJavaProcess: org.compiere.jr.report.ReportStarter [58]
java.lang.NullPointerException
	at org.compiere.jr.report.ReportStarter.startProcess(ReportStarter.java:666)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:357)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:226)
	at org.eevolution.services.dsl.ProcessBuilder.run(ProcessBuilder.java:223)
	at org.eevolution.services.dsl.ProcessBuilder$1.run(ProcessBuilder.java:304)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:301)
	at org.spin.pr.process.PayrollProcessReport.doIt(PayrollProcessReport.java:172)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I expected the report would be displayed.
May I have configured something wrong or missing a configuration?

I don't know if this is an error just for swing. In this case, an additional bugfix would be needed.

Perhaps it must be tested on ZK?

**Comment by yamelsenih** [comment]
Hello @marcalwestf I can add a test data

**Comment by marcalwestf** [comment]
@yamelsenih  thanks Yamel, that would be appreciated!!!

**Review by marcalwestf — APPROVED** [review]
Test performed this time on ZK
image

The NPE does not pop up anymore:
image

In this case the report is empty; it may be because of the print format or the Jasper Report; but the original error (NPE) disappears.

Test passed.

**Pull request merged**
