### PR TITLE
Rename Freight Package

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request basically change the package name of freight to new structure:

Old structure:
```Java
  - org.compiere.model
  - org.eevolution.model
  - org.eevolution.engine.freight
  - org.spin.process
```

New structure:
```Java
  - org.eevolution.freight.model
  - org.eevolution.freight.model.validator
  - org.eevolution.freight.engine
  - org.spin.freight.process
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN('org.spin.process.CreateFreightOrderFromPackage', 'org.spin.process.GenerateAPInvoiceFromFreightOrder', 'org.spin.process.GenerateFreightOrderFromOutbound', 'org.spin.process.GenerateSalesInvoiceFromFreightOrder');
```
 
 Value|Name
-- | --
 GenerateFreightOrderFromOutbound         | Generate Freight Order from Outbound Order
 SBP_GenerateSalesInvoiceFromFreightOrder | Generate Sales Invoice from Freight Order
 SBP_CreateFreightOrderFromPackage        | Create Freight Order From Package
 SBP_GenerateAPInvoiceFromFreightOrder    | Generate AP Invoice from Freight Order

## Model Validators
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('org.eevolution.model.FreightModelValidator');
```

Name|Description                                     
--|--
 Model Validator for Freight Management | This Validator enables freight calculation functionality

## Final comments
- For all model validator I use a query because can be implemented by clients
- The model class MFreight was moved to base source folder because is part of base core

The support legacy api is from here: https://github.com/adempiere/adempiere-freight-support-legacy

### CODE REVIEW

**Review by marcalwestf — APPROVED** [review]
- Loaded and executed xml
- Checked correct name of processes class changed  (4 altogether)
- Checked correct name of validator class changed
- Created Freight Order with Lines
- Created Package
- Call Freight Smart Browsers (3)
- Verify the processes were reached on debug mode

No errors found. **Test passed**.

**Review by niclopup — APPROVED** [review]
Test OK

- Create Package from Material Receipt: OK
- Create Freight Order From Package (SB): OK
- Create Freight Order From Window: OK
- Create Freight Order From Outbound Order (SB): OK
- Generate Sales Invoice from Freight Order: Couldn´t create any invoice from the SB "Generate Sales Invoice From Freight Order". I think that the name of the SB is wrong, it says it creates Sales Invoice while the SB looks for FreighOrder IsoTrx=N. This olso happens in Develop so i guess isn´t a bug of this package rename

**Comment by e-Evolution** [comment]
Testing Result

1.-  Create Sales Order Target Document Type Standard Order, Delivery Via Shipper , UPS , Freight Cost Rule Calculated , Freight Category Ground
2.- Adding line with Azalea previos update Weight and Volume field

image

The system calculate rightly the Freight Amount

 Create Freight Order and validated that use MDDFreight model class 

image

Create Sales Invoice from Freight Order 

image

The invoice is generated 

image


So all the testing was success.

**Comment by niclopup** [comment]
Add this Functional test in Document of "394 Pruebas Funcionales Adempiere V2.0"

**Pull request merged**
