### PR TITLE
 #1113 : The ZK not work jasper report included in print format.

### PR DESCRIPTION
**Pull request by marcalwestf**
See issue https://github.com/adempiere/adempiere/issues/1113
The reports were never executed; with the change, they are.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution can you be more specific for it?

I see issue #1113 but i don't know what is the step by step. Can you please put here a gif or image of problem?

Best regards

**Comment by e-Evolution** [comment]
@yamelsenih , I set in #1653 the step to replicate , this functionality is used when use a print format based on jasper report linking to process defined as report and attachment jasper report.

Here an example.
captura de pantalla 2018-06-13 a la s 15 05 05

**Comment by yamelsenih** [comment]
Thanks @e-Evolution, have you a print shot from user window calling report?

**Comment by e-Evolution** [comment]
@yamelsenih , yes the called is from icon Report , that allow generate a report in short dynamically .

**Comment by SusanneCalderon** [comment]
Please ignore my commits, they are from a branch which is already deleted.

**Pull request merged**
