### PR TITLE
#1620, fixed error with SQL for get product price on view RV_M_Forecast,

### PR DESCRIPTION
**Pull request by yamelsenih**
reference to issue: https://github.com/adempiere/adempiere/issues/1620

Hi @e-Evolution @marcalwestf it pull request is for resolve a error with issue #1620

### CODE REVIEW

**Comment by marcalwestf** [comment]
looking....

**Comment by marcalwestf** [comment]
I found an error trying to apply the commit.
Commented in https://github.com/adempiere/adempiere/issues/1620 .

**Comment by yamelsenih** [comment]
I will look it

**Comment by marcalwestf** [comment]
... as commented on https://github.com/adempiere/adempiere/issues/1620 , the review has passed from my side. So I have no objections to merge the pull request.
Any observations?

**Comment by e-Evolution** [comment]
@yamelsenih  In all history of ADempiere we avoid use keyword that not support with SQL99. So you should change the use of ROWNUM or LIMIT 1, I think that you would use MAX to get an unique records.

**Comment by yamelsenih** [comment]
Hi @e-Evolution both LIMIT AND ROWNUM are valid if each functions are used for distinct PostgreSQL and Oracle, also the view definition is different for DBM.
 
MAX is not a good practice for it case, you can see a example:

I make a select for Product Price, a SQL:
- Seed: ADempiere 3.9.0
- Client: Garden
- Product: Elm Tree
- I change a date from 2017-05-21 to 2017-05-22 for PriceList ID **104**
<pre>
UPDATE M_PriceList_Version SET ValidFrom = '2017-05-22' WHERE M_PriceList_Version_ID = 104;

SELECT plv.ValidFrom, pp.M_Product_ID, pp.PriceStd, pp.PriceList, pp.PriceLimit
FROM M_PriceList_Version plv
INNER JOIN M_ProductPrice pp ON(pp.M_PriceList_Version_ID = plv.M_PriceList_Version_ID)
WHERE plv.AD_Client_ID = 11
AND pp.M_Product_ID = 124
ORDER BY plv.ValidFrom;
</pre>
it retrieve the follow:
m_pricelistv_version_id      | validfrom                    | m_product_id | pricestd | pricelist | pricelimit
**101                                     | 2015-05-01 00:00:00 | 124                 | 57          | 60         | 54**
102                                     | 2015-09-21 00:00:00 | 124                 | 36          | 60         | 24
105                                  | 2017-05-01 00:00:00 | 124                 | 51,82     | 54,55    | 49,1
**103                                     | 2017-05-21 00:00:00 | 124                 | 36          | 60         | 24**
104                                     | 2017-05-22 00:00:00 | 124                 | 57          | 60         | 54
Note that **101** ID has valid from **2015-05-01** and Price Std is **57** 
but **103** ID has valid from **2017-05-21** and Price Std is **36** (Correct Result).

**Date of ID: 103 > that Date of ID 101 but Price of ID 101 > that Price of ID 103**.

If you need get price of product **Elm Tree** with valid from <= 2017-05-21 the correct value should be:
**103                                     | 2017-05-21 00:00:00 | 124                 | 36          | 60         | 24**
Summary: **36**

USING MAX FUNCTION:
<pre>
SELECT pp.M_Product_ID, MAX(plv.ValidFrom) AS ValidFrom, MAX(pp.PriceStd) AS PriceStd, MAX(pp.PriceList) AS PriceList, MAX(pp.PriceLimit) AS PriceLimit
FROM M_PriceList_Version plv
INNER JOIN M_ProductPrice pp ON(pp.M_PriceList_Version_ID = plv.M_PriceList_Version_ID)
WHERE plv.AD_Client_ID = 11
AND pp.M_Product_ID = 124
AND plv.ValidFrom <= '2017-05-21'
GROUP BY pp.M_Product_ID;
</pre>
See result:
m_product_id | validfrom | pricestd | pricelist | pricelimit
**124 | 2017-05-21 00:00:00 | 57 | 60 | 54**
Note that it return the max valid from and max price std and it a bad result.
 - Price returned: **57** instead of **36**

NOW WITH LIMIT USE:

<pre>
SELECT plv.M_PriceList_Version_ID, plv.ValidFrom, pp.M_Product_ID, pp.PriceStd, pp.PriceList, pp.PriceLimit
FROM M_PriceList_Version plv
INNER JOIN M_ProductPrice pp ON(pp.M_PriceList_Version_ID = plv.M_PriceList_Version_ID)
WHERE plv.AD_Client_ID = 11
AND pp.M_Product_ID = 124
AND pp.M_PriceList_Version_ID = (SELECT plvv.M_PriceList_Version_ID 
						FROM M_PriceList_Version plvv
						WHERE plvv.IsActive = 'Y'
                        AND plvv.ValidFrom <= '2017-05-21'
						ORDER BY plvv.ValidFrom DESC
						LIMIT 1);
</pre>

The result is correct, see:
m_pricelist_version_id | validfrom | m_product_id | pricestd | pricelist | pricelimit
**103 | 2017-05-21 00:00:00 | 124 | 36 | 60 | 24**

**Pull request merged**
