### PR TITLE
Rename Asset Package (Replace #3943)

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request basically change the package name of Asset to new structure:

Replace #3943

Old structure:
```Java
  - org.compiere.model
  - org.compiere.process
```

New structure:
```Java
  - org.compiere.FA.model
  - org.compiere.FA.model.validator
  - org.compiere.FA.process
```

Here some checks:
## Processes
```SQL
SELECT p.Value, p.Name
FROM AD_Process p
WHERE p.ClassName IN('org.compiere.process.AssetDelivery');
```
 
 Value|Name
-- | --
 Asset_Delivery_Selection | Deliver Assets

## Model Validators
```SQL
SELECT mv.Name, mv.Description
FROM AD_ModelValidator mv
WHERE MV.ModelValidationClass IN('org.compiere.FA.model.ModelValidator');
```

Name|Description
--|--
 Model Validator to Fixed Assets | Fixed Assets

## Forms
```SQL
SELECT f.Name, f.Description
FROM AD_Form f
WHERE f.ClassName IN('');
```

Name|Description
--|--

## Final comments

The support legacy api is from here: https://github.com/adempiere/adempiere-asset-support-legacy

### CODE REVIEW

**Comment by yamelsenih** [comment]
> I get an exception when saving an Asset: imagen
> 
> In `DB.executeUpdate()` imagen
> 
> In `MAsset.afterSave()`: imagen
> 
> The error can be reproduced in the database: imagen
> 
> The only difference is in `MAssetAcct()`: imagen

Thanks @marcalwestf I was fixed with this pull request

Watch a video

cOMMUNITY-cREATE-aSSET

**Review by marcalwestf — COMMENTED** [review]
- checkout branch
- update project on IDE
- clean project on IDE

Result: 
imagen

According to _.classpath_ file, the path _org.eevolution.fleet/src/main/java/base_ is expected, but it doesn't exist on the project. If a folder _src/main/java/base_ is created manually, or the entry is deleted in _.classpath_, other errors pop up.

**Comment by marcalwestf** [comment]
@yamelsenih  it might be an IDE error, because it is possible to build, even though the IDE -in my case Eclipse- shows a compiler error:
imagen

**Comment by yamelsenih** [comment]
> @yamelsenih it might be an IDE error, because it is possible to build, even though the IDE -in my case Eclipse- shows a compiler error: imagen

Hi @marcalwestf please review it. Already resolved

**Review by marcalwestf — COMMENTED** [review]
@yamelsenih  Yamel, is it correct that two processes named `AssetDelivery` exist with almost identical content?
imagen

**Review by marcalwestf — COMMENTED** [review]
When saving a document _Fixed Asset Split_, the following error is produced:
imagen

The insert statement doesn't include the column `a_asset_acct_id`

**Review by marcalwestf — COMMENTED** [review]
### Basic Tests
- no compiler errors
- build OK
- xml files loaded and applied
- verify code changes
- check correct IDs of tables "A_Asset_Addition", "A_Depreciation_Entry",
"A_Asset_Disposed", "A_Asset"

### Functional Tests 

- Asset tests from Manufacturing Order, Invoice Line, Budget Import, Fixed Assets Browser,  Asset Addition, Asset Disposal, Asset Info, Fixed Asset Split, Depreciation, Registration.
- Tests that involved modified classes (create, read, update, delete): System Issue, Invoice Line, FactAcct, Request, Product, Product Category
- Processes Deliver Assets, FactAcctReset, Project Create Asset, Post Depreciation 
- Reports Asset Delivery Month, Asset Delivery Details, Customer Assets

Result: **tests OK**
When reported error has been eliminated or explained and duplicated process, this PR can be accepted.

**Comment by yamelsenih** [comment]
> When saving a document _Fixed Asset Split_, the following error is produced: imagen
> 
> The insert statement doesn't include the column `a_asset_acct_id`

Hi @marcalwestf this was resolved.

https://user-images.githubusercontent.com/2333092/181840993-efa74895-e914-45e9-adeb-c2ee597f3d46.mp4

**Review by marcalwestf — COMMENTED** [review]
- loaded + applied XML
- open and create a new Fixed Asset Spilt record

Result: OK

**Comment by marcalwestf** [comment]
@yamelsenih Yamel, only expecting your answer on `AssetDelivery`.
If it is repeated, you can delete the obsolete one; if  otherwise, I can accept it immediately,

**Comment by yamelsenih** [comment]
> @yamelsenih Yamel, only expecting your answer on `AssetDelivery`. If it is repeated, you can delete the obsolete one; if otherwise, I can accept it immediately,

Hi @marcalwestf please see it. I remove the file

**Review by marcalwestf — APPROVED** [review]
All modifications done.
No objection to this pull request from my side.

**Pull request merged**
