### PR TITLE
#2247, Fixed error with getUUID function

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request resolve a problem with old compatibility for ADempiere difference of versions

Add old compatibility using java UUID, reference to issue:
https://github.com/adempiere/adempiere/issues/2247

Fixes: #2247

### CODE REVIEW

**Comment by e-Evolution** [comment]
Hi everybody

the implementation of "Surrogate key" from 3.9.1 is mandatory, so the facilities must use the database that has support for this, both Oracle and Postgresql.

The reason for this is that from the version of 3.9.1 conflict resolution and change control for application dictionary and records, replication or export and import of data will be resolved by UUIDs, so it is not recommended to use ADempiere 3.9.1 without Surrogate key since this can bring future synchronization problems or the impossibility of future migrations.

In case you want to use migration based on Script XML, you should apply the migration script from a 390 version.

If you want to migrate the database from a distribution binary of 3.9.1 version, it is advisable to use the migration tool.

unfortunately, the proposed change ignores the approach

**Comment by yamelsenih** [comment]
Here a change:

Fixes: #2249
current mp4

**Comment by marcalwestf** [comment]
Confirming replication of error according to @yamelsenih 's  description in #2247 :
First case:
    * Get last DB seed from ADempiere
    * Run it with last source code

**Comment by marcalwestf** [comment]
Now, turning on to the solution.

When running on an IDE the branch _hotfix/#2247-Add-Old-Compatibility-GetUUID_ of repository https://github.com/erpcya/adempiere/tree/hotfix/%232247-Add-Old-Compatibility-GetUUID with the latest commit 47c5d0933c65f37f6181af70ac224c5d8e033d5e , **I get the very same error**:
20190228_uuid_01


I did expect that with the modification on the above branch, the error would disappear.

So I wonder if I am wrong in my assumption, I tested wrongly or the error hasn't been eliminated.
Perhaps @yamelsenih  Yamel can clarify.
Thanks.

**Comment by marcalwestf** [comment]
@e-Evolution Victor, I didn't understand your explanation of "surrogate keys" nor the later explanations.
I'd be grateful if you could elaborate so we can know if this proposed solution is wrong at all or a valid one.
Thanks!

**Pull request merged**
