### PR TITLE
#508 Buttons on VLookup fields in Find window don't work. 

### PR DESCRIPTION
**Pull request by mckayERP**
https://github.com/adempiere/adempiere/issues/508.

Initialized m_curTab as tab 0 when the window is being initialized.

Also moved the initialization of m_curWinTab up a few lines to be closer to the window section where it fits with the logical flow.
Also cleaned up the header section acknowledgments to use a consistent format.

### CODE REVIEW

**Comment by e-Evolution** [comment]
Hi Mike 

Why modify of credit autor in of class?

**Comment by mckayERP** [comment]
Just to make it consistent in format since there are lots of contributors to this file.  The `@see` moves the link down to the See Also section of the java doc which can make it difficult to relate the link to the change.  If you make the comment like <li><a href="link">text</a>  you get a better output.  This is what it looks like with the change.  No credits where changed, just combined and formatted.

apanerl_doc

**Comment by e-Evolution** [comment]
Nop problem , I see the [change files ](https://github.com/adempiere/adempiere/pull/509/files) and show as if modification was delete lines , but I check and is ok

But you have a good point should we continue with this practice , so that now had github and git history.

I think we not should set here all changes into of class ,  What do you think ?

**Comment by mckayERP** [comment]
OK.  I'll just add my note then and resubmit.

**Pull request closed without merging**
