### PR TITLE
#1904 Link a Bank with Business Partner https://github.com/adempiere/…

### PR DESCRIPTION
**Pull request by e-Evolution**
…adempiere/issues/1904

(cherry picked from commit 48010c99091ef647c7212719b8367eabcd94688f)

### CODE REVIEW

**Comment by e-Evolution** [comment]
@marcalwestf 

The reason is that some reports require the complete information of the bank, this information is regularly found in the window of a business partner.

So this improvement is a way to link bank with your business partner.

I use this information to generate the file of funds dispersion for payments by electronic transfer, the file needs the Tax id of the bank.

The test consists of applying the XML and reviewing the modification in the bank window.

kind regards 
Victor

**Comment by yamelsenih** [comment]
fixes #1904

**Comment by marcalwestf** [comment]
Result:
screenshot_20180824_170233

**Comment by e-Evolution** [comment]
fixes

**Pull request merged**
