### PR TITLE
#3180 Remove fields from Purchase Order.  

### LINKED ISSUE #3180: [Bug Report] The Purchase Order window show the field not should be show
## Bug report
The Purchase Order window show the field not should be show

#### Steps to reproduce
1.- Open a Purchase Order

#### Screenshot or Gif

image

#### Expected behavior
This field not should be show

#### Other relevant information
- Your OS: macOS
- Java version: java 8
- ADempiere version: 3.9.3
- Browser [safari]
- DB Provider: pg
- DB version: 12.2

#### Additional context
the bug was introduced with script 04530_2435_BOMDrop.xml in the issue #2435

@mckayERP  Can please fixed this issue ?

### PR DESCRIPTION
**Pull request by mckayERP**
The fields Order Source, Processed On and Sales Opportunity were added to the top of the form by accident.  The bug was introduced with script 04530_2435_BOMDrop.xml in the issue #2435

Fixes #3180

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @mckayERP let me import it and see

**Comment by yamelsenih** [comment]
@mckayERP please change **05990_#3180_Remove_Fields_From_PO.xml** by **05990_3180_Remove_Fields_From_PO.xml** is not good add special characters to files

Just make it and I can merge

**Comment by mckayERP** [comment]
File name changed.

**Comment by e-Evolution** [comment]
@mckayERP thank you to fixed , kind regards

**Pull request merged**
