### PR TITLE
Enable new functionality to processing document using workflow

### PR DESCRIPTION
**Pull request by e-Evolution**
…document through workflow  https://github.com/adempiere/adempiere/issues/3690

- Enable new functionality to processing document using workflow

### CODE REVIEW

**Review by SusanneCalderon — CHANGES_REQUESTED** [review]
I tested both Processes, _InoutGenerate_ without an additional node, _InvoiceGenerate_ with an additional node, which updates the field _POReference_ with text _invoice generated_.

imagen


Case One, Complete new Invoice manually

- Generate Sales Order, Standard Order
- Generate Shipment with Special Form, docAction Complete
- Generate Invoice with Process Generate Invoice, docAction Prepare


- Complete new Invoice
**Result: Field POReference was set**
imagen

Case Two, Process _InvoiceGenerate_ with DocAction _Complete_
Results

- The Invoice was generated, but in Status Drafted
imagen

- Complete Manually gives the following message
imagen

**Console**
The workflow stops in the node _Complete_ and does not start the last node _SetPOReference_
as it works when you complete manually.

**Comment by e-Evolution** [comment]
@SusanneCalderon thank a lot , I will adding in my test with a new node with your example, in my case, I use a new node to send a email , Would you testing this too, please 

kind regards

**Comment by e-Evolution** [comment]
@SusanneCalderon can please set the image with your node setup to SetPOReference?

**Comment by SusanneCalderon** [comment]
@e-Evolution 
This kind of node we use in several configurations.
imagen

**Comment by SusanneCalderon** [comment]
@e-Evolution 
Debugging, it is interesting that the workflow does not get until this node. It stops at the end of activity of the node DocComplete. 
When you start the workflow from VDocAction the node is executed correctly.

**Comment by SusanneCalderon** [comment]
@e-Evolution 
I tried a sendEmail and it worked. I then again tried a SetVariable Node, this time generated from client GardenWorld and the same error happened.

**Comment by e-Evolution** [comment]
@SusanneCalderon Thank you now I got all the elements to replicate the behavior

**Comment by yamelsenih** [comment]
Hi @e-Evolution is nice it. I have some comments:

- I just saw a implementation for Shipment generation but I think that if you will be add a functionality for core is nice if it can be applied to core documents. Exists many documents like:
  - Complete POS orders generate invoice and delivery
  - Complete Warehouse order generate Shipment
  - Complete Invoice order generate invoices

I think that this solution is not complete solution.

A way for resolve it can be the follow:
- Solution fast
  - Change all core implementations of DocAction
  - Add support on processIt method to new functionality
 
- Real solution is convert the DocAction interface to abstract class and move all functionality to parent

I think that is better make a discussion about it.

Best regards.

**Comment by SusanneCalderon** [comment]
@yamelsenih 
I agree. It is dangerous not to synchronize similar cases. For example methods like _GenerateInvoiceFromLoan_ do not use the workflow. As user I would assume the same behavior.

**Comment by e-Evolution** [comment]
Close this pull request to try other approach

**Comment by e-Evolution** [comment]
Close this pull request to try other approach

**Pull request closed without merging**
