### PR TITLE
remove outdated iText libs

### PR DESCRIPTION
**Pull request by homebeaver**
Hi @e-Evolution , @yamelsenih 

in pull #1576 (on 29 Sep 2018)  I mentioned some TODOs. 

see file base/src/org/adempiere/pdf/ITextDocument.java

Done it now!

- remove outdated iText-2.1.7.jar
- and also remove itext-pdfa-5.5.2.jar because it is replaced by newer
pdfa-7.1.1.jar

I adaped the code to use the actual libs

### CODE REVIEW

**Comment by yamelsenih** [comment]
Very nice @homebeaver thanks, hey can you help us to rewrite dependences to gradle?

**Comment by homebeaver** [comment]
Hi @yamelsenih 
you 're welcome.

gradle? - this build system is a mix of ideas from ant and maven.
To rewrite the AD-dependences it is necessary to analyze and resolve some AD-dependences. I tried to do it with pull #2400 - _get rid of Circular Dependencies_. It was a couple of work but finally effectless, because my pull was commited and then reverted. I've accepted it.

Check:
- open a gradle project
- copy all AD base sources to this project
- try to build
- resolve the dependences with `org.apache.ecs` - the classes are in tools
- resolve jar depemdences and sub-depemdences :

```gradle
dependencies {
	// used in org.adempiere.apps.graph.GraphBuilder:
	compile files('tools/lib/jfreechart-1.0.15.jar')
	// JFreeChart requires the "JCommon" class library:
	compile files('tools/lib/jcommon-1.0.18.jar')
...
```
- finally have to resolve circular dependencies ...

The problems are still similar for those who try to rewrite the build.
Regards

**Comment by homebeaver** [comment]
See
https://stackoverflow.com/questions/38062841/how-to-resolve-circular-dependency-in-gradle
and
https://stackoverflow.com/questions/58178381/resolve-circular-dependency-in-gradle/58186686#58186686

**Comment by e-Evolution** [comment]
@yamelsenih , @homebeaver , now I am using ADempiere with this change, and got an error , please before the remove an library need check and validate that not exist some dependences.

I saw that Jasper Report currently use this iText-2.1.7.jar dependence, may be is necessary update jasper dependences 

Can please fix this problem or is best revert this pull request

Exception in thread "-1002856" java.lang.NoClassDefFoundError: com/lowagie/text/SplitCharacter
	at net.sf.jasperreports.engine.JasperExportManager.exportToPdfFile(JasperExportManager.java:150)
	at net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(JasperExportManager.java:503)
	at org.compiere.report.ReportStarter.startProcess(ReportStarter.java:655)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:392)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.SplitCharacter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 8 more

**Pull request merged**
