### PR TITLE
build Release/3.9.0 in eclipse OXYGEN with java 1.8 from scratch

### PR DESCRIPTION
**Pull request by homebeaver**
to compile base+client I have to change some settings in `.classpath` and `.project`

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @homebeaver i test it and is ok, thank you for it

**Comment by yamelsenih** [comment]
@e-Evolution can you test it also? i think that it can be merged

**Comment by homebeaver** [comment]
Hi @yamelsenih ,
I document my work in https://github.com/klst-de/adempiere/wiki/minBuildWithOxy

**Comment by e-Evolution** [comment]
Hi @yamelsenih, homebeaver 

I not use more eclipse I use IntelliJ , but I ask to Mario @marcalwestf  that make pair revision if not have some issue then merge the pull request

kind regards

**Comment by marcalwestf** [comment]
Hi @homebeaver .
We installed Oxygen 5 weeks ago (from Luna on Suse and Mars on Windows) and could do all tasks without a single error. 

The difference with your approach is that we had already a workspace and you additionally have the goal of creating a "minimalistic" build of Adempiere. It would be interesting to know what it is and what you need it for.

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf ,
_you need it for_?

Our customer works with an old Version of AD ~3.5.4+some proprietary changes. I have to check the effort of moving to 3.9.0. Bacause of the prior changes we cannot migrate the normal migration "Highway". And for the prototype I need the "minimalistic" AD 
* without GardenWorld Validator
* without Manufacturing and HR
* without webUI
* it's good enough to start AD via eclipse to check the data moving progress

**Comment by sramazzina** [comment]
I suggest to keep the project clean from any development environment specificity that must always stay local to the developer's development environment.  

However, remember that when very soon will be migrated to gradle (if this will remain the intention as decided month ago), the gradle module system will automatically configure the development environment of choice without having the developer doing anything. IntelliJ completely levare on Gradle to configure the project and Eclipse too as far as I know. 

Therefore having a build specifically tied to Eclipse in my opinion is a nonsense and a waste of time.

**Comment by homebeaver** [comment]
tkx @sramazzina ,
_very soon will be migrated to gradle_ , means in 3.9.1?

OK, I prepare a new pull for changes done for de_DE (translations and Accounting file) - this is not dependend to the developer's development environment

**Comment by sramazzina** [comment]
We're working on this these days. It will be a gradual path toward gradle. I don't know if everything will be finished for that release but we will try to do our best.

**Comment by homebeaver** [comment]
I close this PR and open a new one https://github.com/adempiere/adempiere/pull/1665 which is a superset and include this

**Pull request closed without merging**
