### PR TITLE
This pull request just add support to gradle builder to manufacturing source folder

### PR DESCRIPTION
**Pull request by yamelsenih**
The gradle structure is the follow:
- adempiereTrunk:
  - org.eevolution.manufacturing:
    - build.gradle

Now you can run the follow command to base source folder:
```Shell
gradle build
```
The dependence from tools is:
```Java
    implementation fileTree(
        dir: '../tools/lib/testing',
        include: [
        'SuperCSV-with_src-1.52.jar'
        ]
    )
    // https://mvnrepository.com/artifact/com.github.lbordowitz.openforecast/openforecast
    api 'com.github.lbordowitz.openforecast:openforecast:0.5.0'
    api 'io.github.adempiere:base:3.9.4-develop-1.0'
    api 'io.github.adempiere:adempiere.test:3.9.4-develop-1.0'
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
```

Note that the library **SuperCSV-with_src-1.52.jar** is very very old
and should be removed soon

See the result:
https://repo1.maven.org/maven2/io/github/adempiere/manufacturing/

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih the refactory for the document type does not work, and on the other hand, the process allows printing multiple selection documents at once, not just a single report.

image

Also, these lines don't work.

PO entity = table.getPO(p_PP_Order_ID, get_TrxName());

The  entity object return is null

So this functionality is not working.

**Comment by yamelsenih** [comment]
Let me test it. Very strange because PP_Order_ID is mandatory, have you a use case  or a step by step?

**Comment by e-Evolution** [comment]
@yamelsenih the Print BOM not work with this change 

image

**Comment by yamelsenih** [comment]
> @yamelsenih the refactory for the document type does not work, and on the other hand, the process allows printing multiple selection documents at once, not just a single report.
> 
> image
> 
> Also, these lines don't work.
> 
> PO entity = table.getPO(p_PP_Order_ID, get_TrxName());
> 
> The entity object return is null
> 
> So this functionality is not working.

Hi Victor, I add some changes:
Multi-Level-and-Formula
SimulatedPickList


Note that you should revert the XML: 09410_Set_default_report_view_to_manufacturing_reports.xml and remove, after it you shoul import and apply

**Comment by e-Evolution** [comment]
@yamelsenih I try your changes again the printing of the material explosion and the simulation of picking list work, but now the printing Pick List , Workflow , Print Pack & Tools List does not work.

Print Release Order

**Comment by yamelsenih** [comment]
Hi Victor let me test it. You can test if the other two process worked?

**Comment by yamelsenih** [comment]
Hi Victor, I found the error, the problem is that the default functionality of printing use the document table as folter to find print format and your process have a vew intead. I change it and is worked in my laptop. Can you test it? here a new Pr more clean: #3844

**Pull request closed without merging**
