### PR TITLE
#1853, Add feature for open result from process, reference to issue:

### PR DESCRIPTION
**Pull request by yamelsenih**
https://github.com/adempiere/adempiere/issues/1853

Hi Everybody, this change allows open a result of process directly after run process, see step by step:

I want know what is business partner that was updated after run **Validate Business Partner** process, for make it just i add some lines to process:

Add information or ID os business partner processed
<pre>
addLog(bp.getC_BPartner_ID(), null, bp.getSO_CreditUsed(), Msg.getElement(getCtx(), "SO_CreditUsed"));
</pre>
screenshot_20180801_213446
Show result after process
<pre>
openResult(I_C_BPartner.Table_Name);
</pre>
screenshot_20180801_213430

**Running process**

 - Open Validate **Business Partner** process
screenshot_20180801_213528
 - After process view result
screenshot_20180801_213544

The window linked to table C_BPartner is opened after runin process.

Nice.

Best regard

### CODE REVIEW

**Comment by marcalwestf** [comment]
..tested as explained by @yamelsenih :
1.- changed class _org.compiere.process.BPartnerValidate,_ method _doIt()_.
Added the line
`openResult(I_C_BPartner.Table_Name);`
2.- changed class _org.compiere.process.BPartnerValidate,_ method _checkBP()_.
Changed from `addLog(0, null,...)` to `addLog(bp.getC_BPartner_ID(), null,....)`
3.- Run process _Validate Business Partner_

Result on Swing: a dialog is displayed and also a **window is opened with the validated Business Partners**.
This means on Swing function test passed.

Still to do: test on ZK.

**Comment by marcalwestf** [comment]
On ZK the test **failed**.
20180809_open_window_from_process_01

Reason: the filter dialog does pop up. It shouldn't appear any filter dialog; just display the window with the processed BPs.

**Comment by yamelsenih** [comment]
Hi @marcalwestf 
It

>On ZK the test failed.
20180809_open_window_from_process_01

>Reason: the filter dialog does pop up. It shouldn't appear any filter dialog; just display the window with the processed BPs.

Was resolved here: https://github.com/adempiere/adempiere/pull/1855

I will merge this branch with develop for fix it

**Comment by yamelsenih** [comment]
It is worked now.

Please test it

**Comment by marcalwestf** [comment]
... now it woks also on ZK.

This works OK for now, but the only complain about it would be that it has to be written code to get the result.
Perhaps in a later phase this could be configured in the Application Dictionary?

**Pull request merged**
