### PR TITLE
#2973 - Add support to attach file result of packout

### PR DESCRIPTION
**Pull request by rcapecce**

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @rcapecce it seems a nice feature to attach the result of packout.

On the other hand, perhaps there are implementations which prefer not to attach; for these cases an additional field "SaveResultToAttachment"  on "Export Package" tab (with default value=false) or similar would be worth considering.

The value==false would be for backward compatibility.

**Comment by rcapecce** [comment]
That is correct, next I need add this flag to indicate if the package needs to attach.

**Comment by yamelsenih** [comment]
Hi @rcapecce thanks for it, iseem that you hace a changes for all lines of Packout class:

- Have you different codification?
- see it: #2135

Screenshot_20200216_001641

**Comment by rcapecce** [comment]
Hello @yamelsenih . I check the settings and tell you.

**Comment by yamelsenih** [comment]
Hi @rcapecce maybe this PR can be rebuilding with a fresh changes from develop, can you make it for review? If is not possible just let me know for close meawhile

**Pull request closed without merging**
