### PR TITLE
#1889, Add support for multiple bank transfer from payment selection,

### PR DESCRIPTION
**Pull request by yamelsenih**
reference to issue: https://github.com/adempiere/adempiere/issues/1889

Please review it new feature for make bank transfer from payment selection.

Best regard

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih have you the screenshot this new functionality?

**Comment by SusanneCalderon** [comment]
Hello, I tested it, it is as described, @adaxa-steven , by chosing a document type Is banktransfer 2 payments are generated, a receipt and a payment. A field payment related in the 2 payments links the 2 documents.
I think it is a great improvement.

**Comment by SusanneCalderon** [comment]
Here the screenshots from our test
1. Window Pay selection
imagen
2. Tab Pay Selection Lines
imagen

3. Window Payments
paymentbanktransfer

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I had problems with the XML 03960, Reference to Issue 1889. To test I deactivated the seq No 160 and the XML run without problems. The Database which I tested was until XML 03910. New XMLs were 03920 and 03921 for quicksheet and 03960 for BankTransfer from Payselection.

imagen

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon have you the last seed? i write XML from last seed, don't forget that Document Type windwos was changed

**Comment by SusanneCalderon** [comment]
Sorry, @yamelsenih, I will test again, I was eager to test the funcionality.

**Comment by e-Evolution** [comment]
@yamelsenih , this functionality should be only when select payment rule for Direct Debit or Direct Deposit, I saw you can select using payment rule check , why?

**Comment by yamelsenih** [comment]
Hi Víctor is very easy, I want to pay to employees a prepayment for expenses and it can be with any payment type. But also I want to handle all prepayment for expenses in a bank account created for each employee.

The process allow generate a payment with any payment rule and make a receipt for bank account selected.

**Pull request merged**
