### PR TITLE
[Feature Request] Slow moving inventory Report #3319

### LINKED ISSUE #3319: [Feature Request] Slow moving inventory Report
## Feature request
Slow moving inventory report shows products in stock but not moving in a period of time

#### Describe the solution you'd like
The report show this columns
- Search Key
- Product Name
- Description
- Product Category 
- Product Group
- Product Class
- Product Classification
- Is Active
- is Stocked 
- Discontinued
- Qty On hand
- Price Last PO
- Price Last Invoice
- Price List Version
- Price List
- Price Std
- Price Limit
- Last Date Receipted
- Last Date Delivered
- Days without movement

Slow moving inventory Total

image

image

Slow moving inventory by Warehouse

image

image

### PR DESCRIPTION
**Pull request by e-Evolution**
Multiples Slow moving inventory Report fixed #3319

### CODE REVIEW

**Comment by marcalwestf** [comment]
- Loaded and applied XML:
imagen

- Steps of migration file: only creates view on database and table (view) in Application Dictionary. No report nor menu created.
imagen

- Also no report visible on the menu, even after running process _Role Access Update_:
imagen

A question @e-Evolution  Victor, is there an additional XML to create report and menu, or does it build on an existing XML, which I haven't considered here?

Thanks

**Comment by e-Evolution** [comment]
Hi @marcalwestf Mario, I recreate again the seed to testing this report, and in my build, all work ok.

after the apply migration script,  you need Update Role Access

image

And the menus are show:

image

image

**Comment by marcalwestf** [comment]
@e-Evolution  hi Victor,
I didn't know of any report/menu entry called _Slow Moving Inventory_ nor _Slow Moving Inventory by Warehouse_ on Adempiere Standard.

I did a "slow moving" (or combinations of it) text search on all XML files starting from directory _migration_, without finding a file that has this text or parts of it.
imagen


So I'd like to know which XML file, pull request or commit was responsible for introducing this report and menu.
Thanks!

**Review by marcalwestf — APPROVED** [review]
- tested with new XML changes that include report, parameters and menu
- loaded and applied XML -> OK
- Role Access Update -> OK
- Find and run both reports _Slow Moving inventory_ and _Slow Moving Inventory by Warehouse_with different parameter combinations -> Results OK

Test passed

**Pull request merged**
