### PR TITLE
Add support to Optional Export Format for Table and Documents of

### PR DESCRIPTION
**Pull request by yamelsenih**
Just a simple change for Replication Strategy that allows select a export format by default on Table and Document, see image:
Screenshot_20200331_111755
Screenshot_20200331_111806

- By default and for old compatibility if a export format is not setted then the search is by Client / Table / Version
- If a export format is setted then the search is by Export Format

### CODE REVIEW

**Comment by trifonnt** [comment]
Hi Yamel,

how do you handle searching of Export Format during import of XML file?

In XML file you do not know which is the Export Format, you know the root of the XML element.

I reference the case when one table for example C_BPartner has more than one export Format.

Kind regards,
Trifon

**Comment by yamelsenih** [comment]
Hi @trifonnt for import format is used Value of Export Format exported:

```Java
String EXP_Format_Value = null;
		EXP_Format_Value = rootElement.getNodeName();
		log.info("EXP_Format_Value = " + EXP_Format_Value);
```

I think that it should not a problem because **Value** is a index for it

**Comment by yamelsenih** [comment]
Best regards

**Comment by trifonnt** [comment]
Hi @yamelsenih,

yes, this will work.

Kind regards,
Trifon

**Pull request merged**
