### PR TITLE
Feature/adempiere1669 statement of accounts

### PR DESCRIPTION
**Pull request by SusanneCalderon**
fixes https://github.com/adempiere/adempiere/issues/1669
In the current version of the process FinStatement the generated reportlines do not include a field account_ID. 

The balance line _beginning balance_ calculates the sum over all included accounts.
So the report works well when you choose a single not-summary account. But when you choose a summary account the result lacks the information of the beginning balance and movements of the indivudual accounts, see the following screenshot.
statementofaccounts_01

**Suggestion to improve the report**: Include account_ID in table T_ReportStatement and in the sqls in class FinStatement.

**Additional Suggestion:** Include the fields account _value_ and _account name_, in order to order the report by account value, or name.
Result see the follwing screenshot

statementofaccounts2

### CODE REVIEW

**Comment by e-Evolution** [comment]
@SusanneCalderon I saw that you are drop the constraint for primary key into the XML Script
ALTER TABLE t_reportstatement DROP CONSTRAINT t_reportstatement_pkey;

It not is good , because can cause inconsistencies , so you need adding constraint for new fields 

ALTER TABLE t_reportstatement
  ADD CONSTRAINT t_reportstatement_pkey PRIMARY KEY(ad_pinstance_id, Account_ID, fact_acct_id);

Can please adding in your XML Script or take my patch file.
[039_1669_StatementOfAccount.txt](https://github.com/adempiere/adempiere/files/2316727/039_1669_StatementOfAccount.txt)

kind regards
Victor

**Comment by e-Evolution** [comment]
@SusanneCalderon , I review that new columns not are in model class for X_T_ReportStatement and I_T_ReportStatement, so you need regenerate the model class.

Will great if the improve also adding account type this way can adding the filter for Asset, Liability , revenue , expense , etc 

kind regards
Victor

**Comment by e-Evolution** [comment]
@SusanneCalderon other change more when create new constraint please purge the table if not you get an error.

I added DELETE FROM T_ReportStatement;

kind regards
Victor

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution 
Thank you for your comments, I will work on it right now

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution 
I changed the column account to accountName, and changed EntityType D

**Comment by e-Evolution** [comment]
@SusanneCalderon 

What happen with the t_reportstatement_pkey, is necessary create a new using news columns , not is good to remove unique constraints?

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution 
As T_reportStatement is a transitory table I did not see a problem in deleting the primary key. But I can include a primary key consisting of 

ALTER TABLE t_reportstatement
  ADD CONSTRAINT t_reportstatement_pkey PRIMARY KEY(ad_pinstance_id, fact_acct_id, account_ID);

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution , I included a new constraint in the XML

**Pull request merged**
