### PR TITLE
Leak transaction caused by incorrect transaction management in Schedule Processors

### PR DESCRIPTION
**Pull request by e-Evolution**
…andling in schedulers https://github.com/adempiere/adempiere/issues/3715

### CODE REVIEW

**Comment by marcalwestf** [comment]
@e-Evolution  there are conflicts to be resolved before we start testing.

**Comment by marcalwestf** [comment]
@e-Evolution  hi Víctor, for Eclipse, it is needed to add  entry for _tools/lib/vavr-1.0.0-alpha-4.jar_ in file _.classpath_:
image

I will continue testing notwithstanding.

**Review by marcalwestf — COMMENTED** [review]
Steps to test:

1. Started the _Application Server_
2. Created a _Scheduler_ for 4 companies (start every 5 minutes). Process: _Client Accounting Processor_, with ID of _Accounting Schema_ as parameter.
3. Deleted all invoice accountings of every company
4. Stopped the _Application Server_
5. Started the _Application Server_

The scheduler started alright.
image


The scheduler starts alright.
It also updates the field _Date Last Run_.
**BUT**, it doesn't update the field _Date Next Run_.
Nevertheless, it starts in the defined frequency.

ONLY: there is a small deviation after every process execution. This is a bug that has Adempiere since the beginnings.

**Comment by marcalwestf** [comment]
@e-Evolution  Víctor: I believe Susanne has a bug fix regarding both issues I mentioned: the shifting of the _Date Next Run_ and the display of it.

It would be nice it it were included.

Just waiting for it and the .class path changes to accept.

**Comment by e-Evolution** [comment]
@marcalwestf , Mario can send me the pull request with the @SusanneCalderon's patch , this way I can integrate and review

**Review by SusanneCalderon — APPROVED** [review]
@e-Evolution , I tested with a database with 4 clientes and several Schedules

**Pull request merged**
