### PR TITLE
Fix NPE when production voided

### PR DESCRIPTION
**Pull request by Raul-mz**
Currently when trying to void a production ADempiere returns a Null Pointer Exception. see the error log:

```
-----------> MTransaction.saveFinish: afterSave [69]
java.lang.NullPointerException
	at org.compiere.model.MTransaction.getByDocumentLine(MTransaction.java:138)
	at org.adempiere.engine.AbstractCostingMethod.createReversalCostDetail(AbstractCostingMethod.java:196)
	at org.adempiere.engine.AverageInvoiceCostingMethod.createCostDetail(AverageInvoiceCostingMethod.java:322)
	at org.adempiere.engine.AverageInvoiceCostingMethod.process(AverageInvoiceCostingMethod.java:392)
	at org.adempiere.engine.CostEngine.createCostDetail(CostEngine.java:500)
	at org.adempiere.engine.CostEngine.createCostDetail(CostEngine.java:273)
	at org.compiere.model.MTransaction.afterSave(MTransaction.java:238)
	at org.compiere.model.PO.saveFinish(PO.java:2342)
	at org.compiere.model.PO.saveNew(PO.java:2943)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.model.MProduction.createTransaction(MProduction.java:298)
	at org.compiere.model.MProduction.lambda$processFromBatch$0(MProduction.java:219)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.compiere.model.MProduction.processFromBatch(MProduction.java:219)
	at org.compiere.model.MProduction.completeIt(MProduction.java:457)
	at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:477)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:294)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:258)
	at org.compiere.model.MProduction.processIt(MProduction.java:419)
	at org.compiere.model.MProduction.reverseIt(MProduction.java:666)
	at org.compiere.model.MProduction.reverseCorrectIt(MProduction.java:750)
	at org.compiere.model.MProduction.voidIt(MProduction.java:608)
	at org.compiere.process.DocumentEngine.voidIt(DocumentEngine.java:510)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:344)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:258)
	at org.compiere.model.MProduction.processIt(MProduction.java:419)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:731)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:787)
```

**Steps:**
Create a Production -> Complete it -> Void it

### CODE REVIEW

**Comment by marcalwestf** [comment]
@mckayERP  it seems the conflict has other causes because #3377 has been merged but the conflict persists.

**Comment by marcalwestf** [comment]
@Raul-mz  hi Raul, could you please correct the conflicts?
Thanks!

**Comment by yamelsenih** [comment]
Hi @marcalwestf @e-Evolution @mckayERP this branch was updated yet. Please review the change, is very simple but functional


Best regars

**Review by marcalwestf — APPROVED** [review]
- Review code -> OK
- Test voiding Production-> OK

Test passed.

**Pull request merged**
