### PR TITLE
Add support to axis column based on Value instead id for where clause

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request allows create a cross tab based on String values as
columns instead ID.

You can define the follow

| Document No   |      Humidity      |  Scrap |
|----------|:-------------:|------:|
|P-001 |  17.9 | 6 |
| P-002 |    15.6   |   5.4 |
| P-003 | 12.6 |    3.6 |

The search for Humidity and Scrap is based on other table that have values like 
- Humidity: **H**
- Scrap: **S**
The old support just make a query based on ID instead values.

Screenshot_20210315_181316

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih When try testing using the smart browser History Payroll it didn't work properly:

image


image


I got a lot of the logs:

image

===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [25]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [25]

I think that should use the ReferenceId based on.  yColumn but how to use xColumn that cause the problem of format.


```
       MColumn column = MColumn.get(field.getCtx(), xColumn.getAD_Column_ID());
	columnName = column.getColumnName();
	referenceId = column.getAD_Reference_ID();
	referenceValueId = column.getAD_Reference_Value_ID();
	tableName = MTable.getTableName(field.getCtx(), column.getAD_Table_ID());
```

On the other hand, show a strange mount, the Smart Browser Should show concept as columns in horizontal head and vertical the employe info as rows.

image

**Comment by yamelsenih** [comment]
Hi @e-Evolution this was resolved yet

**Comment by e-Evolution** [comment]
> Hi @e-Evolution this was resolved yet

Hi @yamelsenih Yamel I tested again and continue with the same problem, can review using swing a trigger multiples errors try show an Amount as TableDir:

Another is that the crosstab is incorrect because should show  Employe  Concept 1 / Amount  , Concept 2 /Amount , etc 

===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]
===========> MLookupFactory.getLookupInfo: No SQL - Amount [80]
===========> MLookupFactory.getLookup_TableDir: Key does not end with '_ID': Amount [80]

**Comment by e-Evolution** [comment]
@yamelsenih I tested was successful.

image
 
image

**Pull request merged**
