### PR TITLE
fix bug in ExportFormatXML

### PR DESCRIPTION
**Pull request by homebeaver**
Hi @yamelsenih @marcalwestf

this PR fixed the bug reported in https://github.com/adempiere/adempiere/issues/2701 / ExportFormatXML should allways use UTF-8 charset

check it, regards EUGen

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @homebeaver I cannot reproduce the error you describe in #2701.

First I tried to reproduce it on the branch _dev+2231+2701_ of your repository without the modification on the _ExportFormatXML_ class (i.e. overwriting the method _convertFile()_ ) without success.

Eventually I ended testing an xml export of a sales order print preview on the latest adempiere commit on the _develop_ branch using the charset _windows-1252_.

As you can see, I can display all Umlaut characters and the "ß".
Selection_120

So perhaps there are other conditions?

**Comment by homebeaver** [comment]
Thkx, I'll ckeck it.

**Comment by yamelsenih** [comment]
Hi @homebeaver any update for it?

**Comment by homebeaver** [comment]
Happy New Year @yamelsenih ,
no update - the commit https://github.com/adempiere/adempiere/pull/2781/commits/8efccfe91beae0b77a327c27d423db873f8f508e fixes it. That's all.

**Pull request merged**
