### PR TITLE
Fix for #1926 ZK Exports migration XML files to different location th…

### PR DESCRIPTION
**Pull request by mckayERP**
…an what is selected in the dialogs.  Removed file name as a parameter from the Export Migration to XML process.  Changed ProcessInfo to include a field for interface type with getters and setters.  Set the interface type in the process dialogs in both SWING and ZK.  Use the interface type in the process to trigger the correct handling of the file download process.  In ZK, use reflexion to dymanically load the correct library.  In Swing, the library is available.

### CODE REVIEW

**Comment by marcalwestf** [comment]
fixes https://github.com/adempiere/adempiere/issues/1926

**Comment by marcalwestf** [comment]
File _04000_1926_RemoveFileNameFromExptMigration.xml_ is missing translations.

**Comment by marcalwestf** [comment]
.. only waiting for translation changes to accept this PR

**Comment by mckayERP** [comment]
Translations added. Thanks to Mario.

**Pull request merged**
