### PR TITLE
#3989 [Bug Report] Error when re-creating a view by altering a table

### PR DESCRIPTION
**Pull request by e-Evolution**
…with the t_alter_column function causing nested casting making recreated views slower by applying nested casting https://github.com/adempiere/adempiere/issues/3989

### CODE REVIEW

**Review by piracio — APPROVED** [review]
I don't see anything strange at code level. looks good.

**Comment by marcalwestf** [comment]
@piracio  could you run the XMLs?
Thanks!

**Comment by marcalwestf** [comment]
@e-Evolution  hi Victor, what should be exactly the steps to reproduce the error?
I did not understand well.

Besides, the correction would be to run the XML files and then do the steps again, right?
Thank you.

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario!

The test is simple to change some column and synchronizes the column.

i.e. change the length of POReference to 255. for the tables C_Order or C_Invoice, this should allow the synchronization and rebuild the dependences views.

i.e. change the length of Descripcion to 4024 into the C_OrderLine or C_InvoiceLine, this should allow the synchronization and rebuild the dependences views.

You can review some views where the field POReference or Description is used and compare between the original view and reapply views.

kind regards
Victor

**Review by piracio — APPROVED** [review]
Feature tested with OL7/ postgreSQL 12
Deployment OK
Migration OK

**Review by piracio — APPROVED** [review]
Test OK

**Review by piracio — APPROVED** [review]
Test OK

**Review by piracio — APPROVED** [review]
Test OK

**Pull request merged**
