### PR TITLE
BF: Pedro's Financial Report is not working #53

### PR DESCRIPTION
**Pull request by armenrz**

### CODE REVIEW

**Comment by armenrz** [comment]
Hi Victor,

In this pull request, I'm not able to isolate the changes I made.
These were the steps I did:

1. I created a new branch hotfix/3.8.0#002 from develop branch in my github repo 
2. I pull the hotfix/3.8.0#002 to my local repo
3. I place the changed files
4. I push back to my github repo
5. I sync my hotfix/3.8.0#002 branch from adempiere/hotfix/3.8.0#002 
6. I create this pull request

**Comment by mckayERP** [comment]
Hi armenrz,
To isolate your commits, create your branch from the head of hotfix/3.8.0#002 and give it a different name, like hotfix/3.8.0#002-BF_Pedro's_report.   Move your changes to this new branch and then create the pull request for this branch into the hotfix/3.8.0#002 branch in ADempiere.  This will ensure that the difference between the target branch and your branch are as small as possible.

Mike

**Comment by armenrz** [comment]
Hi Mike,

I will try your advice. Previously I created my hotfix/3.8.0#002 from
develop branch.

Armen

**Comment by e-Evolution** [comment]
Please send your change as insolation change

**Pull request closed without merging**
