### PR TITLE
feat: Add frequency type Six-monthly and biweekly.

### LINKED ISSUE #3771: [Feature Request]  Support for biweekly and six-monthly frequency types in Commissions.
## Feature request

Currently for the Commissions Definition the following types of frequency are supported: 
 - Annual.
 - Quarterly.
 - Monthly.
 - Weekly.

#### Describe the solution you'd like

However, there are no frequency types:
 - Six-monthly.
 - Biweekly.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
1. Create comission definition with biweekly frequency type.

Commission-Definition-Biweekly

3. Commission Run with date before 15 day.

commission-run-first-biweekly

4. Commission Run with date after 15 day.

commission-run-second-biweekly

fix #3771

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt this change look fine but the dictionary changes must be with centralized ID's: https://github.com/adempiere/adempiere/pull/3772/files#diff-ed5abd0d1ed4b33411b10b6a121fa242c139b4afdb768548fe5bc5d5ce4c622bR6

Give me the pachout and I can generate it for you

Best regards

**Comment by EdwinBetanc0urt** [comment]
Greetings @marcalwestf @yamelsenih , the migration xml has been updated with the new centralized ids.

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt thanks Edwin, proceeding to test right now.

**Review by marcalwestf — APPROVED** [review]
- XML loaded and applied
- Check Reference _C_Commission Frequency_: two entries added (_Biweekly_ and _Six-monthly_), with translations
- Create two new Invoice _Commission Definitions_, one for _Biweekly_ and another for _Six-monthly_ and add Both _GardenAdmin_ and _GardenUser_ as Sales Representatives.
- Create **four** _Commission Runs_, twice referencing one of the new _Commission Definitions_
- Bi-weekly: set dates before and after 15th; Six-monthly: set dates before and after July 1st
- Run action prepare() for each _Commission Run_
- Check results: start and end dates correctly set on every run; correct invoice lines selected; correct commission amount calculated.
- Test was only run on Inovices (not run on Orders etc.) because it was not within the scope of the changes.

**Test passed**

**Pull request merged**
