### PR TITLE
#2658 - first part of the e-invoices enhancement 

### PR DESCRIPTION
**Pull request by homebeaver**
Hi @yamelsenih 

as you wrote in https://github.com/adempiere/adempiere/issues/2658#issuecomment-510513557 you want to test the #2658 feature

there is a drop of bitterness in this PR: as I wrote it depends on https://github.com/adempiere/adempiere/pull/2400 (no circular eclipse projects) and patches #2701 (ExportFormatXML) too

In https://github.com/adempiere/adempiere/issues/2658#issuecomment-520595450 I wrote how to test

regards

### CODE REVIEW

**Comment by homebeaver** [comment]
Hi @yamelsenih 
I updated the PR - for testing see [instructions here](https://github.com/adempiere/adempiere/issues/2658#issuecomment-520595450)
enjoy & regards EUGen

**Comment by marcalwestf** [comment]
hi @homebeaver  Eugen, I read the instructions and I must confess I didn't know anything about OASIS nor UBL, not to mention its implementations. Googling yields also not much, does it?

Perhaps you can tell us more about the scope, actual usage, forecast, etc.? Just as an informationvto the rest of us who are not familiar with the theme.

In principle, the task you suggest to solve is IMO a good idea and thanks for the effort and time spent.
I checked out your code and it seems alright.

Just one remark: I notice a lib called _de.klst.facturx-0.0.X.jar_ is added to this PR. As you posted, it is your contribution (which we all are thankful for because these things take always time).
This seems though not to be a standard library, but a customized one with many classes I don't know where they come from. I wonder if it would be possible to resort to standard libraries instead of a library where we don't have any clue how it came about nor any power to control it.

Other possibility would be to describe how to create/maintain it so anyone of us can update it when needed (a Git repo??).

**I would like to know what others (including you) think about this issue.**

This said, I am going to test this PR the next days and let you know my results.

Last but not least, you've surely noticed there is a conflict with building on Travis...

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf , let me answer in reverse order
- the confict with PO class comes with  pull request #2754 from erpcya. I will solve it.
- the facturx lib is my work. You can see the code in https://github.com/klst-de/e-invoice There is a readme to explain the goal of this project. It is independent to adempiere.
- in #2704 I suggest to create machine readable invoices as an optional feature

**Comment by homebeaver** [comment]
Hi @marcalwestf there are no conflicts with develop trunk now.

**Comment by marcalwestf** [comment]
@homebeaver  there are still conflicts

**Comment by homebeaver** [comment]
Mario @marcalwestf - the new conflicts comes from #2811 which reverts #2400

But you can still test ths PR - you must use a branch/commit before dc168b28c662bfa44b3a95641d65fdf1a8470208 (the commit of #2811)- Commits on Sep 18, 2019 or before are good for testing this PR.

I'll make a completele new PR for this issue when it is acceptet.

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - I guess this PR will be a long lasting. ;-)

I have solved the conflicts and the eclipse build problems. To build with circular project dependencies [eclipse severity](https://stackoverflow.com/questions/17208339/how-to-solve-cyclic-dependency-between-different-modules-in-a-project-in-eclipse) for this is to be ajusted
regards

**Comment by homebeaver** [comment]
New conflicts caused by https://github.com/adempiere/adempiere/commit/a16c495379084dceb894efbde3a5389a32e97f86#diff-2a8f0359b4b2cd274ea4c7e6a21adf95 and others.
I resign resolving ... :-(

**Comment by yamelsenih** [comment]
Hi @homebeaver this pull request has many changes for classpath and other class, can you simplify it?

**Pull request closed without merging**
