### PR TITLE
Bugfix/#2437 next line with shift intro

### PR DESCRIPTION
**Pull request by rcapecce**
Fixed the enter in a multiline field.
Fixes: #2437

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @rcapecce  this is an annoying bug.

Does it solves only the problem of hitting the _ENTER_ key when editing fields like _Description_ or _Help_?  Or does it something additionally?

I wonder how to leave editing fields like _Description_ or _Help_ and get the focus to the next field?

Thanks,.

**Comment by marcalwestf** [comment]
@rcapecce  thanks Raul, I will test accordingly.

**Comment by marcalwestf** [comment]
@rcapecce  Raul , I am about to merge your changes.

I have just one question when editing on the grid ("multirecord").

The following key combinations work:
- CTL + LEFT ARROW (=go to the beginning of the text)
- CTL + RIGHT ARROW (=go to the end of the text)
- SHIFT + LEFT ARROW (=select character-wise to the left)
- SHIFT + RIGHT ARROW (=select character-wise to the right)

I wonder which combination would yield a "**move one character to the left**" or  "**move one character to the right**"  when editing on the grid ("multirecord"). 

The arrows are already reserved for moving to the next field to the right or to the left when editing on the grid ("multirecord"), so they cannot be used. On monorecord, the keys LEFT ARROW and RIGHT ARROW work correctly.

Thanks.

**Comment by rcapecce** [comment]
That is correct, with Ctrl + arrow steps between words and with shift move selecting the characters, in multirecord mode only the single left right arrow is catched for the grid navigation.

**Pull request merged**
