### PR TITLE
Add support to Deliver Asset Browser

### PR DESCRIPTION
**Pull request by yamelsenih**
Fixes: #3085

This pull request allows deliver many assets from browser. See Gif:
Deliver_Asset

Best regards

### CODE REVIEW

**Comment by marcalwestf** [comment]
One question @yamelsenih : in _I_A_Asset_Delivery_, line 106 I see
`public I_C_ValidCombination getAD_User() throws RuntimeException;`

In  the original file, I find this:
`public org.compiere.model.I_AD_User getAD_User() throws RuntimeException;`

I wonder if the change is OK.

**Comment by yamelsenih** [comment]
Hi Mario let me see it.

Thanks.

**Comment by marcalwestf** [comment]
1. XMLs loaded and applied
2. Smart Browser executed, query parameters set
3. Search and select Assets
4. Process executed (in single step)

Result: Delivery created OK.
Selection_001

**Comment by marcalwestf** [comment]
@yamelsenih so the funcionality is actually OK.
Depending on your answer, it can be accepted immediately.

**Comment by yamelsenih** [comment]
Hi @marcalwestf the reference was changed to Account instead search, I fix it yet.

Thanks

**Pull request merged**
