### PR TITLE
Add Documentation Generator from ADempiere

### PR DESCRIPTION
**Pull request by yamelsenih**
Hi guys, this pull request allows generate documentation from ADempiere Application Dictionary, the documentation can be generated for:

- [Markdown](https://en.wikipedia.org/wiki/Markdown)
- [reStructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

The result for it documentation can be some like here: [https://adempiere.github.io/](https://adempiere.github.io/) 
See this video for know what is step by step
current ogv

Fixex: #1934

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih Hi Yamel.

¿The documentation generate es multi-language, or we should add a new parameter for language, this way can generate the documentation for language that we need?

¿Exist a way using UUID to update application dictionary from git or GitHub, if somebody editor fixed some documentation, ie some contributor modify and extend the documentation or help, how we will update the application dictionary? , my suggestion is to use the UUID and language code to have some way the updated the application dictionary a once that a pull request to change the documentation is approved

**Comment by yamelsenih** [comment]
Hi @e-Evolution my reply

>¿The documentation generate es multi-language, or we should add a new parameter for language, this way can generate the documentation for language that we need?

The Multi-language is variable from compile enviroment and format, example:
 - reStructuredText use a multi-language with distincts directory or branchs for habdle it.
 - Markdown is unsupported for mkdocs however exist a way for resolve it with forward and css

For now is unsupported multi-language for it first pull request but is a great start for generate documentation from ADempiere

>¿Exist a way using UUID to update application dictionary from git or GitHub, if somebody editor fixed some documentation, ie some contributor modify and extend the documentation or help, how we will update the application dictionary? , my suggestion is to use the UUID and language code to have some way the updated the application dictionary a once that a pull request to change the documentation is approved

My suggestion is that exist a ADempiere application server with real data and frienly window for update documentation.

This docs is only from application dictionary and can be versioned for each release.

I somebody want to add docs es better from ADempiere or using a different forlder like is loaded from gitbook from @mckayERP

**Comment by mckayERP** [comment]
Hi Yamel,

Great work.  +1 to merge.

Some comments:

How are we going to add version info?  If I generate a version of the documentation for V3.9.2 say, all the links to this document should point at information that has the same version.  Would it be possible to include a version tag in the URL? Something like: `https://adempiere.github.io/v392/functional-guide/window/window-unit-of-measure.html.`  I can change the links in other docs en-mass with a global text change to point all the links to a new version when its ready.

Also would it be nice to have a way to capture screen shots?  Its a bit of a pain and I'm not sure it adds a lot of value  considering all the display logic.

**Comment by yamelsenih** [comment]
Hi @mckayERP off course, github.io is only a compiler the important is the language and release version from docs code as tags or releases.

A example using a own compiler for mkDocs is it:
[http://docs.couchdb.org/en/stable/maintenance/performance.html#delayed-commits](http://docs.couchdb.org/en/stable/maintenance/performance.html#delayed-commits)
[https://docs.couchdb.org/en/1.6.1/maintenance/performance.html](https://docs.couchdb.org/en/1.6.1/maintenance/performance.html)

Both are the same documentation provider but distint version, the version control is a job of source + compiler. We are source and github.io is only a test for it but can be compiled with other owner compiler site

**Comment by e-Evolution** [comment]
@yamelsenih I reviewed this contribution and is ok , you only need modify 3.9.2 the  04420_1934_Process_Generate_Docs  <Migration EntityType="D" Name="Generate docs from Application Dictionary #1934" ReleaseNo="3.9.1" SeqNo="4420">

And I think that the menu should move to General Rules under Generate Surrogate Keys

image

**Comment by yamelsenih** [comment]
>@yamelsenih I reviewed this contribution and is ok , you only need modify 3.9.2 the 04420_1934_Process_Generate_Docs

Hahahaha this change was begining to develop for 3.9.0. fixed

>And I think that the menu should move to General Rules under Generate Surrogate Keys
Fixed
Screenshot_20190315_114931

**Pull request merged**
