### PR TITLE
remove obsolete jpedal.jar - it was replaced with icepdf

### PR DESCRIPTION
**Pull request by homebeaver**
refs https://github.com/adempiere/adempiere/issues/1948

and replace all refs to the jar

eclipse .classpath
IDEA *.iml files
build.xml
.tomcatplugin

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @homebeaver could you please check the conflict? 
Before start testing,
Thanks

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - resolved

**Comment by marcalwestf** [comment]
There is an error on Eclipse, because _icepdf-core-6.2.2.jar_ is declared twice in _.classpath_
20180930_icepdf_01

**Comment by marcalwestf** [comment]
same with icepdf-viewer-6.2.2.jar

**Comment by homebeaver** [comment]
Oops! @marcalwestf sorry

**Comment by marcalwestf** [comment]
Once corrected the duplicates, the project could compile, clean and build under Eclipse.
Under Eclipse it can start Swing and ZK; the preview display and export as PDF works.
Have to still test Swing and ZK installation.

I notice you've changed several files (.classpaths, etc). 
What additional tests should I carry out, what should I look at?

**Comment by homebeaver** [comment]
Hi @marcalwestf 
this PR was triggered by the discussions on #1576 , see https://github.com/adempiere/adempiere/pull/1576#issuecomment-416594424

Now PR #1576 is merged (creating pdfs)
and also PR #1601 is merged into development branch (viewing/reading pdfs with icepdf.jar)

So we can delete the obsolet old jar for viewing pdfs and all references in .classpath and builds - this PR, which is a kind of housekeeping. No new functions is to test.

**Comment by adaxa-steven** [comment]
Hi Homebeaver
this sounds very interesting.
can you do screen shots?
It is not clear to me if 
(a) the customer is sending you a pdf plus csv or equivalent 
(b) the customer is sending you only the pdf and you are reading it and creating the csv.
regards
steven

**Comment by homebeaver** [comment]
Hello Steven @adaxa-steven - for answer see gitter, regards Eugen
> this sounds very interesting.
> can you do screen shots?

**Pull request merged**
