### PR TITLE
Improve performance for running payroll process:

### PR DESCRIPTION
**Pull request by yamelsenih**
- Remove translation for message (this was changed to log with english
language)
- Add cache for agregate functions like SUM, AVG on current running

Currenlty when a payroll is running exist many conditions that make it more slow:
- Translations
- Unnecessary Query's
- Bad calling

I add some homogeneus methods:
```Java
// For amount and Quantity
getLastConcept (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConcept (concept, payroll, date); // Search with Valid To
getLastConcept (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
// For Service Date
getLastConceptDate (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConceptDate (concept, payroll, date); // Search with Valid To
getLastConceptDate (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
// For Text Message and Description
getLastConceptString (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConceptString (concept, payroll, date); // Search with Valid To
getLastConceptString (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
// For Valid From 
getLastConceptValidFrom (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConceptValidFrom (concept, payroll, date); // Search with Valid To
getLastConceptValidFrom (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
// For Valid To
getLastConceptValidTo (concept, payroll); // Get Payroll Document Date and search a Valid To
getLastConceptValidTo (concept, payroll, date); // Search with Valid To
getLastConceptValidTo (concept, payroll, date, useValidFrom); // true for search based on Valid From and false for search based on Valid To
```

### CODE REVIEW

**Comment by e-Evolution** [comment]
@yamelsenih  this changes can be unsure , because the unique key to cache have not warrantees to be  are unique for query parameters, this can cause that the cache return a value where the parameter combination not is rightly  , would fix this this way I can testing

**Comment by marcalwestf** [comment]
@e-Evolution hi Victor,
As we see, it is important to reduce the processing time.

Can you specifiy what would be the unique key for each of the methods where keys are defined?
I suppose  , @yamelsenih would add the required parameters. I cannot figure out which would be additionally needed.
Thanks!!

These are the Key definitions in question, defined in _MHRProcess_:

- Method: _getAttributeInstance_(MHRConcept concept, int partnerId, Timestamp breakDate)
Key: String key = concept.getValue() + "|" + partnerId + "|" + breakDate.getTime();

- Method: _getConcept_(String conceptValue, String payrollValue, int periodFrom, int periodTo, boolean includeInProcess) 
Key: String key = "SUM|" + partnerId + "|" + conceptValue + "|" + payrollId + "|" + periodFrom + "|" + periodTo + "|" + includeInProcess;

- Method: _getConceptAvg_(String conceptValue, String payrollValue, int periodFrom, int periodTo, boolean includeInProcess)
Key: String key = "AVG|" + partnerId + "|" + conceptValue + "|" + payrollId + "|" + periodFrom + "|" + periodTo + "|" + includeInProcess;

- Method: _getLastMovement_(String conceptValue, String payrollValue, Timestamp breakDate, boolean isWithValidFrom)
Key: String key = partnerId + "|" + conceptValue + "|" + payrollValue + "|" + breakDate.getTime() + "|" + isWithValidFrom;
		
- Method: _getConcept_(String conceptValue, String payrollValue, Timestamp from, Timestamp to, boolean includeInProcess)
Key: String key = "SUM|" + partnerId + "|" + conceptValue + "|" + payrollId + "|" + from.getTime() + "|" + to.getTime() + "|" + includeInProcess;
		
- Method: _getConceptAvg_(String conceptValue, String payrollValue, Timestamp from, Timestamp to, boolean includeInProcess)
Key: String key = "AVG|" + partnerId + "|" + conceptValue + "|" + payrollId + "|" + from.getTime() + "|" + to.getTime() + "|" + includeInProcess;

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I tested with two different Payroll definition
Payroll 1:
27 Employees in the same payroll, monthly income, paid twice a month. 

- Fix Income
- Additional income for Christmas  Bonus, exempt from wage tax
- Additional income for Christman Bonus, taxed
- Deductions for Health Service
- Deductions for Social Security 
- Deductions for other Social Security
- Deductions for Wage Taxes
- Provisions for employer Rate for Social Security and Health Service
- The Base for the wage tax is the salary - deductions for health Service and Social Security, rate is stored in a table, the amount is a rate plus a fix amount, which also depends from the income and is stored in the same table

The calculation of the wage taxes are based on previous calculations of the deductions for health service and social security, which in the new code are taken from cache. Values cached: Calculated salary, rate and fix amount for every employee.

This demonstrates that there is no confusion for further calculations.  

The concept wage for half month is called approximately 10 times. 

The performing time is reduced from 10 minutes to 1 minute 30.

Payroll 2:
20 employees in the same payroll

- Variable income read for a time expense report
- Fix wage tax
- No deductions for social security
- Deductions for health service, if the income exceeds a minimal income
The calculations are correct

Valuable changes, we recommend a merge.

**Review by marcalwestf — APPROVED** [review]
based on the tests of @SusanneCalderon , the tests are passed.

**Comment by marcalwestf** [comment]
to be sure, @e-Evolution  should run a different, also complex, payroll and share the results.
Perhaps could also @yamelsenih reports the tests you run before uploading this PR.

**Comment by e-Evolution** [comment]
Executing payroll process before the improves 

image


Executing Payroll process after the improves

image

**Comment by e-Evolution** [comment]
@all calculus is the same result with a best time in processing , so the cache is working, great work

**Pull request merged**
