### PR TITLE
Feature/adempiere 296 create from like sb

### PR DESCRIPTION
**Pull request by yamelsenih**
Request for integrate the new feature for change all create from forms to Smart Browser, reference to issue: #296

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution  this is the pull request for integrate the Create From like SB

**Comment by e-Evolution** [comment]
Hi Yamel . found a different for bank statement in original button create show 



and now show



should be Create from Payments

**Comment by e-Evolution** [comment]
Otee diferente that I found was in filter parameter , have not same ordered , and the authorization code was removed , should be ak original form

**Comment by e-Evolution** [comment]
Other different behavior is that when button Create from Payment , of first time the from us fill with lines of wrist filter , so I think that this SB should auto execute.

The column name have not same names that before , it can cause confusion because of current documentation have other names so this should be same before.

**Comment by e-Evolution** [comment]
When I tried execute the process for new smart browser , I got this exception but this not show in screen under status bar, I think should propagate and know so that is happen , because it should like idle screen.

19:59:22.751   ProcessParameter.validateParameters:  [17]
Exception in thread "AWT-EventQueue-0" 19:59:22.757 MRole.get: AD_Role_ID=102, AD_User_ID=100, reload=false [17]
java.lang.IllegalAccessError: Cannot access Process 53877 with role: GardenWorld Admin
	at org.compiere.model.MPInstance.setAD_Process_ID(MPInstance.java:221)
	at org.compiere.model.MPInstance.<init>(MPInstance.java:113)
	at org.compiere.apps.ProcessParameter.saveParameters(ProcessParameter.java:517)
	at org.compiere.apps.ProcessParameterPanel.saveParameters(ProcessParameterPanel.java:302)
	at org.eevolution.form.VBrowser.cmd_Process(VBrowser.java:499)
	at org.eevolution.form.VBrowser.actionPerformed(VBrowser.java:728)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1673)
	at java.awt.Component.setVisible(Component.java:1625)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.compiere.apps.AEnv.showWindow(AEnv.java:89)
	at org.compiere.apps.AEnv.showCenterScreen(AEnv.java:107)
	at org.compiere.apps.AEnv.showCenterScreen(AEnv.java:117)
	at org.compiere.apps.APanel.actionButton(APanel.java:2691)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1689)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by e-Evolution** [comment]
I found other error for  Total Amount is incorrect because not are validate if payment is a receipt or not

**Comment by e-Evolution** [comment]
finality Yamel I think that is good improve enable next filter:

1.- Add the order and prepayment flag is  is will nice that can conciliate based a order and prepayment
2.- Add the different dimension will be good , example project , activity , campaign , user 1 , user 2
3.- in other case will good can conciliate all payment to a specific change , this payment generality have not have invoice allocated because are for miscellaneous concepts.
4.-Finality will be good can filter for a credit not or invoice link to payment.

kids regards

**Comment by e-Evolution** [comment]
Receipt Material , I review the old screen with new and found the incorrect name for button create from Order/RMA, now show create form lines should be change as before.

**Comment by e-Evolution** [comment]
The new screen from create not have same functionality 
1.- The business partner field not is show as before , it not is nice because the SB or from is emergent dialog , is good know that business partner you are processing as before.
2.-The list to show of purchase order before show 3 field into identifiers now only is show 2 , So should be same way that before 
3.- of Name before say Only from same Warehouse , the new name not is explicit and can be confuse 
4.- The order to entry data was change before the first field was Quantity , UOM , Locator that is more usable that now , is necessary move of mouse 7 column.
5.- No is posible entry a new quantity as before 
6.- The order line no , and RMA and invoice now not are show 

On the other hand some good improves would be added.

1.- New filter should be added as Promised date 
2.- Dimension as project , activity , campaign , user 1 , use2 
3.- in case for Purchase Order blank or Opened is referenced with Order Reference field , will be nice found all purchase order for a Order Reference.

**Comment by e-Evolution** [comment]
Other issue that I can show is that before the location use standard location  , and now is mandatory entry , I think that the system should use of standard location defined in product window , and that user can change , so the locator parameter not is necessary if is posible edit and change for each line.

**Comment by e-Evolution** [comment]
A good nice improve should be the you can make zoom of smart browse line for purchase order line to review any detail when are receipt using of zoom button that how is hide.

**Comment by e-Evolution** [comment]
Other issue now is posible duplicate lines for same sales order for a entry error 

Step to replicate:
1.- Created receipt based on purchase order  select an order from  add 3 lines  accept
2.- next replicate again the first step the result was duplicate lines to 6 for same purchase order this not should work this way because the user can receipt the material for same purchase order 2 or more times.

**Comment by e-Evolution** [comment]
Create receipt from Invoice:

1.- The issue that found the Only from same warehouse not is show when use create from invoice
2.- the column are in different position and Purchase Order , RMA , Invoice columns are missing 
3.- Error Browser Callout when try set the quantity 



===========> BrowserCalloutCreateFrom.start: start: quantity [17]
java.lang.NullPointerException
	at org.eevolution.grid.BrowserRow.getValue(BrowserRow.java:394)
	at org.eevolution.grid.BrowserRow.getValue(BrowserRow.java:404)
	at org.compiere.model.BrowserCalloutCreateFrom.quantity(BrowserCalloutCreateFrom.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eevolution.grid.BrowserCallOutEngine.start(BrowserCallOutEngine.java:113)
	at org.eevolution.grid.BrowserRow.processCallOut(BrowserRow.java:541)
	at org.eevolution.grid.BrowserTable.processCallOut(BrowserTable.java:742)
	at org.eevolution.grid.VBrowserCellEditor.vetoableChange(VBrowserCellEditor.java:217)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
	at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
	at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
	at org.compiere.grid.ed.VNumber.actionPerformed(VNumber.java:580)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)

**Comment by e-Evolution** [comment]
The Return Vendor and Customer show create from and before show Create from Order/RMA

captura de pantalla 2016-07-18 a las 11 28 58 p m

and have same issue the column and information not is same that original window, So if the previos issues are solve then this should solve too, so that is same start browser

captura de pantalla 2016-07-18 a las 11 28 58 p m

**Comment by e-Evolution** [comment]
fixe and refactor InOutCreateFrom 008c8f1

1.- Solve issue browser callout when try entry info in last row summary of a smart browser
2.- Rename variables name to best debug
3.- Remove variables declared as null , this should cause NPE
4.- Refactor to functional programing is a best approach for Java 8

**Comment by yamelsenih** [comment]
Hi @e-Evolution the follow i will create other issues for handle each response separed

**Comment by yamelsenih** [comment]
> Otee diferente that I found was in filter parameter , have not same ordered , and the authorization code was removed , should be ak original form
> 
> 
> 
> finality Yamel I think that is good improve enable next filter:
> 
> 1.- Add the order and prepayment flag is  is will nice that can conciliate based a order and prepayment
> 2.- Add the different dimension will be good , example project , activity , campaign , user 1 , user 2
> 3.- in other case will good can conciliate all payment to a specific change , this payment generality have not have invoice allocated because are for miscellaneous concepts.
> 4.-Finality will be good can filter for a credit not or invoice link to payment.
> 
> kids regards 


The **Authorization Code** alredy addded to SB, also the fields (**IsPrepayment**, **IsReceipt**, **C_Order_ID**, **C_Invoice_ID**, **C_Charge_ID**, **C_Project_ID**, **C_Campaign_ID**, **C_Activity_ID**, **DateAcct**, **C_PaymentBatch_ID**) is added in the next commit

issue217

**Comment by yamelsenih** [comment]
> The Return Vendor and Customer show create from and before show Create from Order/RMA
> 
> captura de pantalla 2016-07-18 a las 11 28 58 p m
> 
> and have same issue the column and information not is same that original window, So if the previos issues are solve then this should solve too, so that is same start browser
> 
> captura de pantalla 2016-07-18 a las 11 30 37 p m

It is because the synchronize terminology was not yet run.

**Comment by yamelsenih** [comment]
> The new screen from create not have same functionality 
> 1.- The business partner field not is show as before , it not is nice because the SB or from is emergent dialog , is good know that business partner you are processing as before.
> 2.-The list to show of purchase order before show 3 field into identifiers now only is show 2 , So should be same way that before 
> 3.- of Name before say Only from same Warehouse , the new name not is explicit and can be confuse 
> 4.- The order to entry data was change before the first field was Quantity , UOM , Locator that is more usable that now , is necessary move of mouse 7 column.
> 6.- The order line no , and RMA and invoice now not are show 
> 
> On the other hand some good improves would be added.
> 
> 1.- New filter should be added as Promised date 
> 2.- Dimension as project , activity , campaign , user 1 , use2 
> 3.- in case for Purchase Order blank or Opened is referenced with Order Reference field , will be nice found all purchase order for a Order Reference.
> 
> 

1. The business partner is a unnecessary field, it just is showed for set context value and make a filter of **Order/RMA/Invoice** from BP, but if the InOut document have the BP then why use the BP like parameter? Currently the **@C_BPartner_ID@** exists in the context and is used for make the filter in **RMA/Order/Invoice** fields.
2. The **C_Order_ID** field is used like **TableDir**, it implement the standard identifier for **C_Order**.
3. The name **Is Same Warehouse** will be change in the next commit.
4. The previous order is not the same for all create from forms, the users is confused by it when go to other create from. The new order is more logic, the **Qty** and **UOM** is previous that **MovementQty** because **MovementQty** is a result of **Qty** and **UOM**. The locator can be moved after of **MovementQty**.
5. The **Order/RMA/Invoice** is unnecessary show in the lines if it is mandatory in search parameter, like reference you can see the **Line No**.

> 1.- New filter should be added as Promised date 
> 2.- Dimension as project , activity , campaign , user 1 , use2 
> 3.- in case for Purchase Order blank or Opened is referenced with Order Reference field , will be nice found all purchase order for a Order Reference.

The new filters will be added in the next commit.

**Comment by yamelsenih** [comment]
> Other issue now is posible duplicate lines for same sales order for a entry error 
> 
> Step to replicate:
> 1.- Created receipt based on purchase order  select an order from  add 3 lines  accept
> 2.- next replicate again the first step the result was duplicate lines to 6 for same purchase order this not should work this way because the user can receipt the material for same purchase order 2 or more times.
> 
> 
> 
> 

It is a behavior that exists in the current **Create From** form, is nice to have it change in the new.

Thank you.

**Pull request merged**
