### PR TITLE
Payment rule in sales order with sub type "Invoice Order"

### LINKED ISSUE #3933: Payment rule in sales order with sub type "Invoice Order"
When a sales order with sub document type "Invoice Order" is created, the payment rule is not automatically set to "Cash", as it happens with the sub type "POS Order".

PaymentRuleOrder

#### Expected behavior
When selecting a type of sales order that has the sub type "Invoice Order" the payment rule must also be set to "Cash".

### PR DESCRIPTION
**Pull request by nsarlabos**
Fixes #3933

### CODE REVIEW

**Comment by e-Evolution** [comment]
@niclopup Hi Nico!  what is the document type for Invoice Order, When was introducing in core and how work , Do you know how are work?

**Comment by e-Evolution** [comment]
@nsarlabos You can send the pull request without modifying the end-of-line characters, since now it shows that you have changed several lines but there really is no change https://github.com/adempiere/adempiere/pull/3934/files, If the PR is sent in this way it is difficult to review the change in the code because at first glance it shows the real changes but also others that are not really changing.

**Comment by yamelsenih** [comment]
Hello @nsarlabos  can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by yamelsenih** [comment]
This pull request will be closed this friday 2023-11-10 if not exists changes

**Comment by nsarlabos** [comment]
Hi @yamelsenih I wanted to move forward but I still have problems with the line separators (CRLF/LF).
I hope I can solve this soon.

**Comment by yamelsenih** [comment]
Hello @nsarlabos can you try it with other IDE?

**Comment by nsarlabos** [comment]
> Hello @nsarlabos can you try it with other IDE?

Hi @yamelsenih

Using the VIM editor I was able to correctly make pull request #4190. I understand that this could be closed.

**Pull request closed without merging**
