### PR TITLE
bugfix for #1782 Movement Date in MProduction

### PR DESCRIPTION
**Pull request by homebeaver**
see https://github.com/adempiere/adempiere/issues/1782

prepareIt: check only if MovementDate is in the past 
by the way I added toString-Method

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @homebeaver i think that all documents with workflow must be validate with period, it is for:

1. Period control.
2. Fact Account changes.

**Comment by marcalwestf** [comment]
@yamelsenih does your comment mean that -if the commit for this pull request is OK- the actual pull request can be accepted?

Or doest it mean that similar changes must also be done for period control and fact account changes before accepting this pull request?

**Comment by homebeaver** [comment]
Hi @yamelsenih @marcalwestf 
yes you are right. But this is a plan, see screenshot here #1782 - and the planned movement date must be in the future.
When the production is completed, days ore weeks later, the movement date then has to be within the accounting period. 
Do I understand the Manufacturing planned order process wrong?
Regards E.

**Comment by marcalwestf** [comment]
@homebeaver you're right. I will test the pull request as of your explanation.

**Comment by yamelsenih** [comment]
Hi @homebeaver itest it but i find follow:
 - Validation for period for production Order (**M_ProductionBatch**) is removed when it is to future (Ok)
 - Validation for period for production (**M_Production**) is removed when it is to future (It should be keep like previous version, the production change quantity and make account acct).

For code revision i find some improvements:
Please change identation, see images:
screenshot_20180813_142445
screenshot_20180813_142515
screenshot_20180813_142533

**Comment by yamelsenih** [comment]
Please fiux it for merge

**Comment by yamelsenih** [comment]
Testing...

**Pull request merged**
