### PR TITLE
feat: Configure Centralized ID Management process.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
1. Import XML migration scripts.
2. Run `Role Access Update` process.
3. Relogin with `System` role.
4. Expand `Application Dictionary` menu.
5. Open `Configure Centralized ID Management` process.
6. Fill parameters with your credentials and run.
7. Open `System Configurator` window and verify the values of your credentials.

https://user-images.githubusercontent.com/20288327/172983748-01fc7a3d-a811-478c-b859-bb1ca2c6122d.mp4

fixes https://github.com/adempiere/adempiere/issues/3910

### CODE REVIEW

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  nice feature!
I will test it ASAP.

**Comment by e-Evolution** [comment]
@EdwinBetanc0urt can please change name of class from ConfigureCentralizedIDManagement to ConfigureCentralizedIdManagement , we use the camel case syntax

**Review by marcalwestf — APPROVED** [review]
Steps:
- Loaded and executed both XML files 09720_Update_System_Configurator_Dictionary_Centralized_ID.xml and 09730_Configure_Centralized_ID_Management_Process.xml.
- Run the process _Configure  Centralized ID Management_ and type in different values. 
- Verify the records in window _System Configurator_.

Result: the _System Configurator Dictionary ID_ entries can be changed as described.
Functional test passed.

Two small changes have to be done to merge it: 

1- In file 09720_Update_System_Configurator_Dictionary_Centralized_ID.xml change the _Entity Type_ to _Dictionary_. Right now it is _User Maintained_.
imagen

2- The process is not inserted properly in the menu, which differs from the video describing the process:
imagen

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf you were right, the menu was not correct, the entity type was changed as you suggested.

Screenshot_20220611_121449


@e-Evolution changed the process class name (`ConfigureCentralizedIdManagement`) using the camel case syntax as you suggested.

**Pull request merged**
