### PR TITLE
#2389 Adds a specific icon for smart browsers and updates Recent Items look and feel

### PR DESCRIPTION
**Pull request by mckayERP**
This is what it looks like.

image

The change only affects the Java Client.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @mckayERP can you add support to ZK UI also?

Best regard

**Comment by yamelsenih** [comment]
Hi @mckayERP I can see this change but I find a difference between main menu and user favorites. see 
screenshot_20190306_101916
image:

**Comment by mckayERP** [comment]
I'll check.

Mike

**Comment by mckayERP** [comment]
To fix the recent items, I'm changing the structure from toolbar buttons to a tree.  It will look and behave the same as the menu tree items but without summary folders.

image

Note the system favorites, document tasks, views and activities are still to do.

**Comment by mckayERP** [comment]
Fixes #2389 
Fixes #2443

Made the choice of image icon consistent - use AEnv.getMenuIconFile().
Changed the implementation to a tree to match the main menu and User favorites.
Added tooltip text to help the user.

**Comment by yamelsenih** [comment]
I test it and is ok
Screenshot_20190402_222851

**Pull request merged**
