### PR TITLE
Revert "#2231 - get rid of Circular Dependencies"

### PR DESCRIPTION
**Pull request by e-Evolution**
Reverts adempiere/adempiere#2400

Hello @homebeaver , @marcalwestf Mario!

I have to reverse this merge for the following reasons.

1.- A pull request where 155 files are modified is unreasonable or indicates that many changes were applied. this took me to the next point

2.- In the detail of the changes, classes of the org.adempiere.request, org.adempiere.project directories were moved to base. this that goes against what we planning for the future:

ADempiere / develop / org.adempiere.request
ADempiere / 390a / org.adempiere.project
In previous versions, we started separating the code from the base directory to directories based on functionality, so returning the files to the base directory is a step back from the goal we want to achieve.

The goal is as far as possible the functionality should be separated by bounded context by business functionality, this case org.adempiere.project and org.adempiere.request was already in separate directories. In the future, the idea is to have smaller jar files with specific functionality for when a change is required, the update can be done for business functionality and not for a fat jar .

3.- It is necessary to correctly review the configuration for developers who use eclipse for circular references, I totally agree this must be resolved.

An important observation to take in consideration, @trifonnt Trifon added the possibility of being able to import the complete adempiere project from the Adempiere root to have a complete construction from a single configuration which requires a machine with sufficient hardware.
On the other hand, @trifonnt Trifon added the possibility of open the project for each directory, in order to optimize and use fewer resources, the development only import the directory where need to modify

Perhaps this is causing confusion for new developers since it can work with a complete configuration and one per directory. This pull request removes this possibility which I consider is not suitable for developers who do not have a machine with sufficient hardware

While this pull request was made with good intentions is not adequate, I will ask our friend @yamelsenih Yamel who develops using eclipse to update what is necessary for developers to work.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi eveyone I think that 155 class is very hard change. Can you make it for bit?

I approve this revert.

**Comment by osdevguy** [comment]
@e-Evolution @yamelsenih @homebeaver 

Moving forward on this project is of utmost importance - making it impossible and huge hurdle for new developers to figure out what is going on should be most important issue.

1- Clearly there is misunderstanding of what the "future" is --- if you talk about future - the future is TODAY -- not "one" day.  Base should be the base functionalities like core ERP core reporting core transactional processing etc.   Having errors on "freight module" when building base is just not conducive to community mechanisms. 

2- Clean code and clean architecture should be no 1 priority ! This project needs it after 10 years it seems how did it get here ?  If the future is Today then make the call - but future and current should be clearly thought through.  Not because it is difficult changes but then rather fork client specific requirements out of this project asap. 

3 - the project should build out the box for developers in Eclipse then IJ -- IJ has some great features but Eclipse should be the main point of reference to start off with -- one never know with paid for IDE what directions they take - especially for a community project. 

4- Clearly an issue of project governance: what is LTS release  vs dev release vs minor/major release - still not clarified it seems. 

5- Also many issues in the project pointed here - why is @yamelsenih more say than @homebeaver  as to the future - this causes politics and if proper governance to the vision of a project is not followed it fails and stalls like it seems to be experiencing in general !?

This is really a sad day if one cannot resolve this imporant issue.

**Comment by yamelsenih** [comment]
Hi @osdevguy thanks for your comments...

> @e-Evolution @yamelsenih @homebeaver
> 
> Moving forward on this project is of utmost importance - making it impossible and huge hurdle for new developers to figure out what is going on should be most important issue.
> 
What is your propose for moving fordward?
Exists a personal reason or is oriented to improve ADempiere ERP?

> 1- Clearly there is misunderstanding of what the "future" is --- if you talk about future - the future is TODAY -- not "one" day. Base should be the base functionalities like core ERP core reporting core transactional processing etc. Having errors on "freight module" when building base is just not conducive to community mechanisms.
> 
What is your base or pattern desing?
I think that this comment is very subjetive

> 2- Clean code and clean architecture should be no 1 priority ! This project needs it after 10 years it seems how did it get here ? If the future is Today then make the call - but future and current should be clearly thought through. Not because it is difficult changes but then rather fork client specific requirements out of this project asap.
> 
If we are not working for improve architecture then who will work for it? A project is not just a simple "Hello World"

> 3 - the project should build out the box for developers in Eclipse then IJ -- IJ has some great features but Eclipse should be the main point of reference to start off with -- one never know with paid for IDE what directions they take - especially for a community project.
> 
If you have a better propose for it I want to listen it. And you are welcome to share with all.

> 4- Clearly an issue of project governance: what is LTS release vs dev release vs minor/major release - still not clarified it seems.
> 

?????

> 5- Also many issues in the project pointed here - why is @yamelsenih more say than @homebeaver as to the future - this causes politics and if proper governance to the vision of a project is not followed it fails and stalls like it seems to be experiencing in general !?
> 

Nobody say that @yamelsenih is more that @homebeaver anybody is welcome to contribute with this big project. I was merged many pull request from @homebeaver without problem. 
Please see this little list of pull request approved:
https://github.com/adempiere/adempiere/pull/2503
https://github.com/adempiere/adempiere/pull/2461
https://github.com/adempiere/adempiere/pull/2459
https://github.com/adempiere/adempiere/pull/1964
https://github.com/adempiere/adempiere/pull/1826
https://github.com/adempiere/adempiere/pull/1825
https://github.com/adempiere/adempiere/pull/1822
https://github.com/adempiere/adempiere/pull/1779
https://github.com/adempiere/adempiere/pull/1601

> This is really a sad day if one cannot resolve this imporant issue.

Have you a contribution for this project? You are welcome "To contribute"

No personal.

In other hand please add a step by step for #2769

Best regard

**Comment by osdevguy** [comment]
@yamelsenih 

As a clever man once said --- rules are made by those that show up. 

Clean code, clean architecture project and many more people will show up, but the down side of this is that the 'few' may loose their perceived power for the good of the all -- but, otherwise, just run as you are with swing modules written in 1999.

I can see many people like the few have come and gone in this project - its unfortunate. 

Have a great day.

**Comment by yamelsenih** [comment]
Thanks, You are wecome to contribute "not only with word".

**Comment by osdevguy** [comment]
Its unfortunate to take that stance @yamelsenih - why must a new dev spend 3 days to build the system in dev environment - you do understand the difference between build for deployment and build for testing ... The platform should be able to engage any level of dev - even one who wants to try to do a "hello world"  -- -this is what is missing here indeed

**Comment by homebeaver** [comment]
Hi Victor @e-Evolution , thkx for explaining the reasons. I wonder that this comes after 7 month - the time the PR #2400 was open. So you can understand, I'm disappointed.
Regards

**Comment by marcalwestf** [comment]
Hi @homebeaver  Eugen, I understand you're disappointed. On the one hand you've spent so much time, on the other hand it took so long for you to implement these changes, catch up with the _develop_ branch and so on.

In the first place, I do not have an error of "circular dependencies" in Eclipse, but I thought I would look at your changes because you develop and contribute a lot. Perhaps you wanted to do further development and you encountered errors I didn't had hitherto? In any case, I decided to have a look.

At accepting you pull request, I misinterpreted the moving of files with the effort to catch up with the _develop_ branch changes. So if somebody is in part to blame it is me for not looking thoroughly at every change, although the result was OK. Here my apologies.

This said, I hope very much you don't take it personally, but try to solve the original problem in a way that it is accepted.

Now going into the details, the reason @e-Evolution Victor gave me and I agree with is that we are trying since years to get a less monolithic code. This can be confirmed by looking at the code: some classes are now at _org.adempiere.pos_, _org.adempiere.production_, _org.eevolution.cashflow_, etc. instead of to _base/src/org ..._. 

And exactly this is what is happening with your changes. 

The solution would be to get rid of these circular dependencies, but still sticking to the policy of decreasing the monolithic structure. I am very aware that this is by far not enough and that a proper effort is needed, but -we are in a community project- as long as nobody does it, we have to cope with what is at hand.

I am available any time to talk about this issue and get it over the counter.
Have a nice day.

**Comment by marcalwestf** [comment]
@osdevguy hi.

If you look at the channels we communicate -mainly Gitter and Github- you see that the participants of the project Adempiere do address each other and the issues in a polite manner. We're all nice guys.

On the other hand, if you'd talk personally to any member of Adempiere's Gitter or Github, you'd notice that everyone, me included,  would do many things in a different way than it is currently done or is disappointed of somebody or something. 

So in short, we communicate politely with each other, but we not agree 100% with each other. This is the basis of working together.

But -and here your behavior differ from how conversations are held in this project- you are personal in your posts and are subjective when arguing. This way, you divert the attention from the matter to the person, and this is to be avoided.

I'd recommend you to read the etiquette of this project and avoid at all costs to compare one person to another, to demand something from anybody, to ask in general "why has this or that not been done?", to patronize with quotations of whatever clever minds have said, because by doing this you may break the harmony we try to maintain in our conversations. 

This post has not the intention of being the begin of a tit-for-tat conversation. So I'd be happy if we leave it as it is.

Thank you and have a nice day.

**Comment by e-Evolution** [comment]
Unfortunately, I not work with eclipse to develop in Adempiere, so I did not understand that I was trying to fix, given the comments that importing a project in eclipse was not working and have the circular references, I gave myself the task of checking it, for myself same, after a few minutes I could verify that there is no problem, you can see my comments in the gitter forum https://gitter.im/adempiere/adempiere.

This come to me when I checked their changes and when I saw a pull request where 155 files are changed immediately I realized that something was wrong.

If you need to solve a problem, your changes must be atomic, that is, they must not include other things you are trying to solve.

That means that you must send complete non-partial solutions, when there are multiple commits in a pull request we immediately realize that something is wrong.

As we have already said pull request with few commits allow you to easily review the changes

On the other hand, I am struck that @marekmosiewicz mentioned that all problems appear when they select the "Search for nested projects" option.

For some reason I don't know, they selected this option when importing the project in eclipse and it causes the mentioned problems.

Please do not use this flag when importing the project in eclipse.

As I said @trifonnt  I configure eclipse so that each directory can be opened as an individual project if it has limited resources.

**Pull request merged**
