### PR TITLE
#3209 credit card and iban validator update to version 1.7

### PR DESCRIPTION
**Pull request by homebeaver**
see desc in issue #3209 and #3231 (validation for CreditCards):

_when a Credit Card Number is enterd VISA, MASTER etc. the number should be validated before save_

### CODE REVIEW

**Comment by homebeaver** [comment]
Hi @marcalwestf - how are you?

I've added a validation for credit card numbers. To test use the following:

```
VALID_VISA       = "4417123456789113"; 
ERROR_VISA       = "4417123456789112"; 
VALID_SHORT_VISA = "4222222222222"; 
ERROR_SHORT_VISA = "4222222222229";
VALID_AMEX       = "378282246310005"; 
ERROR_AMEX       = "378282246310001";
VALID_MASTERCARD = "5105105105105100";
ERROR_MASTERCARD = "5105105105105105";
```
grafik

regards EUGen

**Comment by marcalwestf** [comment]
The ant library in your repository differs from the Adempiere lib:
Selection_968
Maybe you should stick to Adempiere, since this PR doesn't have any ant.jar added.

**Comment by marcalwestf** [comment]
Testing invalid card number:
Selection_970

Testing different valid credit cards:
Selection_969
Selection_971

All valid and invalid card numbers, and some private were successfully tested.

As the constructor of _CreditCardValidator()_ goes to _commons-validator-1.7.jar_, the PR is OK.

It remains to be accepted changing _tools/build.xml_ to be in sync with Adempiere.

**Comment by homebeaver** [comment]
> 
> 
> The ant library in your repository differs from the Adempiere lib:
> Selection_968
> Maybe you should stick to Adempiere, since this PR doesn't have any ant.jar added.

Hi Mario @marcalwestf 
my PR does not depend on `ant.jar`!  
mckayERP commits the ant change on Jan 5, 2021  / commit https://github.com/adempiere/adempiere/commit/791d87a49849d4e65d224313d5c824182f029bb8 - month after my PR

So, take ant from Mike's commit (left side) and validator-1.7 from my PR (right side)

regards EUGen

**Comment by homebeaver** [comment]
Hi @marcalwestf - I merged the actual adempiere/deveop branch to this PR.
So the `tools/build.xml` looks good now:

grafik

**Review by marcalwestf — APPROVED** [review]
tests run and passed.

**Pull request merged**
