### PR TITLE
Adempiere #3407 Taxdeclaration Consider DateAcct

### PR DESCRIPTION
**Pull request by SusanneCalderon**
Fixes https://github.com/adempiere/adempiere/issues/3407

### CODE REVIEW

**Comment by e-Evolution** [comment]
@SusanneCalderon I tested and is ok, but I need you to help me by being consistent using only the first letter as uppercase for fields and only fully uppercase for SQL statements. please change PROCESSED to Processed

On the other hand, if your approach is only to include taxes based on the accounting date, do you should not also validate that the invoice is posted , so should you adding the validating the "Processed"  you should also validate the Posted = 'Y'?

**Comment by carlosaparadam** [comment]
Hi @SusanneCalderon , i think that resolving the comments that write @e-Evolution  it will be fine.

Regards

**Comment by SusanneCalderon** [comment]
@carlosaparadam 
Hi, Carlos, I included a parameter isOnlyPosted and corrected the sql Statement.

**Comment by e-Evolution** [comment]
@SusanneCalderon please fix the description of new elements, now show all without spaces, I think we can be more explicit as Use Account Date to Created of declaration and Validate the use of document posted, also check the translation.

image

I think that the processed field should be always read-only 

image

and finality can merge develop with your branch to avoid any conflict.

**Comment by SusanneCalderon** [comment]
@e-Evolution 
Hi, Victor, I updated the XML.
imagen
imagen

**Pull request merged**
