### PR TITLE
Remove JDK8 compatibility gradle

### PR DESCRIPTION
**Pull request by yamelsenih**
Just a minor change for all gradle subproject and remove JDK8 compatibility flag

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
Execute command _gradle build_ on console:
- I wonder if the _Implementation-Version_ should have a default value because there is a compile error when interpreting the manifest:
```
jar {
    manifest {
        attributes("Implementation-Title": "Adempiere Project Management",
                   "Implementation-Version": version, 
                   "EntityType": entityType)
    }
}
```
The error disappears when setting a value for all _build.gradle_ files where the snippets appear.
I don't know if it is expected that the value should be set when calling _gradle build_, but it is nowhere evident or obvious.
- If the error was circumvented, another error appears at _DB_Oracle.java_, _DB_Postgres.java_, _DB_MariaDB.java_:
imagen

I reported this error already on the last commit of Gradle. 

Due to the fact that Gradle isn't the official build tool yet, this pull request could be accepted as it is, hoping that the issues will be solved in due time.

**Comment by yamelsenih** [comment]
Hi @marcalwestf just export the `ADEMPIERE_LIBRARY_VERSION` variable

run it before build in the same terminal
```Shell
export ADEMPIERE_LIBRARY_VERSION="1.0.0"
```

**Comment by yamelsenih** [comment]
A step by step for test it:

## Requirements
- [Gradle](https://gradle.org/install/)
- JDK 11

## Before build

```Shell
export ADEMPIERE_LIBRARY_VERSION="test-version"
```

## Build project

- Go to ADempiere project
- run gradle build

```Shell
gradle build
```

**Comment by marcalwestf** [comment]
Adding to the steps described by @yamelsenih, the JAVA_HOME context variable must be exported in the console where _gradle build_ is about to be launched:
`export JAVA_HOME="<path to JDK>"`

Remember to select a JDK version >= 11; otherwise, an error will be thrown.
This was the case with my tests.

**Review by marcalwestf — APPROVED** [review]
Test executed on:
- Linux (Ubuntu 18.04)
- JDK 11.0.11
- Gradle version 7.5.1

Context variables:
- export JAVA_HOME="path to jdk"
- export ADEMPIERE_LIBRARY_VERSION="version desired"

On console run `gradle build`

Result: **build successful**
imagen

Test passed.

**Comment by marcalwestf** [comment]
Waiting for @e-Evolution 's test on another operating system before merging it.

**Review by e-Evolution — APPROVED** [review]
The build was success

image

**Comment by e-Evolution** [comment]
@yamelsenih  Hi Yamel, @marcalwestf Mario, please could you put evidence that the change in the viewer in Jasper Report still works correctly, if all is ok then merge this PR

**Review by marcalwestf — APPROVED** [review]
- Created a test jasper report according to pr #3929
- run it on ZK
- report displayed successfully:
  
imagen

**Test passed**

**Pull request merged**
