### PR TITLE
[Bug Fixed] Display rule does not work correctly between records when browsing in grid mode for #3506

### PR DESCRIPTION
**Pull request by e-Evolution**
bugfix to #3506

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution can you add here a gif with behavior?

Best regards

**Comment by marcalwestf** [comment]
**Test Scenario I**

- According to @e-Evolution this occurs only on **ZK**, so the test will be made on ZK. 
- Define in _Application Dictionary_ for window _Sales Order_, tab _Order_, Field _Process Order_ a _Display Logic_ @GrandTotal@<100. This would display the Field _Process Order_ (i.e. the Process button) only if the _GrandTotal_ is less than 100.
image
- Log in as _GardenWorld Admin_ in _GardenWorld_, open _Sales Order_ window.
- Create an Order that complies with the _Display Logic_ and another that doesn't comply with the _Display Logic_.
- Open the Sales Order that complies with the Display Logic.
- Change to the Grid view and go to the Order that doesn't comply with the Display Logic.
- Open this Order (which doesn't comply) with the rule.
- Result: **the button is not displayed**, as expected.

image
image


Summary: with a simple _Display Logic_ rule (@GrandTotal@<100), this case cannot be reproduced.

Another scenario has to be constructed to reproduce this error.

**Comment by marcalwestf** [comment]
Test Scenario II

- Test on Standard Adempiere.
-  Create in table _C_Order_ a SQL Column with the Element _SOCreditStatus_.
  The SQL Column value is _(SELECT SOCreditStatus FROM C_BPartner WHERE C_BPartner.C_BPartner_ID=C_Order.C_BPartner_ID)_
image

- For window _Sales Order_, tab _Order_, bring Field _Credit Status_.
- For window _Sales Order_, tab _Order_, Field _Process Order_, create a _Display Logic_ = @SOCreditStatus@='O'.
- Log in as _GardenWorld Admin_ in _GardenWorld_, open _Sales Order_ window.
- Configure _Business Partners_ so that one complies and the other doesn't complywith the _Display Logic_ .
- Create an _Order_ that complies with the _Display Logic_ and another that doesn't comply with the Display Logic.
- Open the _Sales Order_ that complies with the Display Logic.
- Change to the _Grid_ view and go to the _Order_ that doesn't comply with the Display Logic.
- Open this Order (which doesn't comply) with the rule.
- Result: the button is not displayed, as expected.
  
image


Doing the same steps on branch e-Evolution:feature/3506 the same result is achieved -> **at least under the scenarios and circumstances described, this error cannot be reproduced neither on Standard Adempiere nor on branch e-Evolution:feature/3506**.

BUT
when looking at the _Context_, the TabInfo shows a **wrong** _C_Order_ID_ for getting it:
image
image

This means

- I cannot reproduce the error under the test scenarios described
- It is something wrong with the context.

At @e-Evolution Victor, is there any other way this case can be reproduced?

**Comment by marcalwestf** [comment]
at last, and thanks to @e-Evolution Victor's help, I was able to reproduce the error and verify the fix.

For this, you must

- Display in  _Single-row_ mode a record with Display Rule = true
- Then, change to _Grid_ mode and **select with the mouse!!!** a record which Display Rule=false
- The "old" Display Rule applies to the new record, which is wrong.

**Review by marcalwestf — APPROVED** [review]
- Test on ZK
- Reproduce the use case with standard Adempiere -> Display Rule doesn't apply
- Reproduce the use case with this PR -> Display Rule applies

Result: test passed.

**Pull request merged**
