### PR TITLE
#1937 Corrected the tool tip and translation for the Log Migration Script Message

### PR DESCRIPTION
**Pull request by mckayERP**
Corrected the tool tip and translation for the Log Migration Script message.

From
`Log Migration Script - Save migration scripts file in %TEMP%/migration_script_*.sql`
To
`Log Migration Script - The script will be found in the Migration window.`

Translated in Spanish as

`Registre el script de migración - El script se encontrará en la ventana de Migración`

### CODE REVIEW

**Comment by marcalwestf** [comment]
I execute the process _Import Migration from XML_  for file _04040_1937_ChangeLogMigrationToolTip_, but it is not loaded in Migration table.
I ignore why. I've tried to delete some lines, without success.
Will continue testing later.

**Comment by marcalwestf** [comment]
test stuck same as with pull request https://github.com/adempiere/adempiere/pull/1950

**Comment by marcalwestf** [comment]
I'll do the same and report....

**Comment by marcalwestf** [comment]
@mckayERP Mike I think I found what's wrong: the file **lacks the xml suffix**.

Its name is _04040_1937_ChangeLogMigrationToolTip_; is should be _04040_1937_ChangeLogMigrationToolTip.xml_.

**Comment by mckayERP** [comment]
Added the missing extension to the file name.

**Comment by marcalwestf** [comment]
starting test....

**Comment by marcalwestf** [comment]
hi Mike, due to the accents in Spanish (ó, á,), the XML is not parsed:
_SAXParseException Invalid byte 2 of 4-byte UTF-8 sequence_

When I modify translation part as follows, changing the direct accents by Unicode, the XML can be parsed, applied and the results are as expected.


```
<Step SeqNo="20" StepType="AD">
      <PO AD_Table_ID="119" Action="U" Record_ID="0" Table="AD_Message_Trl">
        <Data AD_Column_ID="342" Column="MsgText" oldValue="Log de Script de Migraci&#xf3;n">Registre el script de migraci&#xf3;n</Data>
        <Data AD_Column_ID="341" Column="AD_Language" oldValue="es_MX">es_MX</Data>
        <Data AD_Column_ID="6767" Column="AD_Message_ID" oldValue="53007">53007</Data>
        <Data AD_Column_ID="343" Column="MsgTip" oldValue="Log de Script de Migraci&#xf3;n -Guarda el script de migraci&#xf3;n en %TEMP%/migration_script_*.sql">Registre el script de migraci&#xf3;n - El script se encontrar&#xe1; en la ventana de Migraci&#xf3;n</Data>
      </PO>
    </Step>
```

**Comment by mckayERP** [comment]
Fixes #1937.

**Comment by e-Evolution** [comment]
@mckayERP , please follow the recommendation for comments on any commits:

#Id Issue Description about the issue and URL of issue

When you have to review community contributions, time is valuable, so providing reviewers with a quick way to locate and get to information on each issue is crucial

**Pull request merged**
