### PR TITLE
Bugfix/#4114

### LINKED ISSUE #4114: Conversion Rate in Dunning Run Line with error
## Bug report

IF you create a Dunning run with the check of " Include All Currencies", the Conversion Rate is obtenied with Time and minutes  so if you have a Rate for one DAY it doesnt works

image

image

Instead if the rate has a range: It will work

image

It shouldn't has to be with minutes to obtain the currency rate.

#### Screenshot or Gif

Demostration of the error

TC en Conversión de Línea de Cálculo de Morosidad

Demostration of the solution changing the Date of the Conversion Rate

TC en Conversión de Línea de Cálculo de Morosidad con Solución de FECHAS

### PR DESCRIPTION
**Pull request by nsarlabos**
Fixes #4114

### CODE REVIEW

**Comment by e-Evolution** [comment]
Hi @nsarlabos , I found this problems 

This pul request has the following problems

1.- It does not have the proper format because it modifies all the content of the class, making it very difficult to review the code

2.- the pull request has classes and changes that have nothing to do with the reported issue and is not based on the branch adempiere:hotfix/3.9.4.001 which does not contain new features, here it seems that a merge was done with develop

3.- No unit or integration tests are included

kind regards
Victor

**Comment by yamelsenih** [comment]
Hello @nsarlabos  can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by yamelsenih** [comment]
This pull request will be closed this friday 2023-11-10 if not exists changes

**Comment by nsarlabos** [comment]
Hi @yamelsenih I wanted to move forward but I have problems with the line separators (CRLF/LF) when committing the MDunningRunLine class, it looks bad both when doing it from IntelliJ and from Visual Studio Code.

I had to delete the branch from the pull request, and that's why it was closed.

I'm still looking for the solution to make a new pull request.

**Pull request closed without merging**
