### PR TITLE
#2231 - get rid of Circular Dependencies

### PR DESCRIPTION
**Pull request by homebeaver**
Hi @yamelsenih 

this is my second attempt with a PR on this issue / #2231 . The first pull #2232 was closed unmerged by yourself.
Regards EUGen

> 
> Hi @homebeaver is a big change for source, exists over 2k files that will be changed.
> Can you upgrade your source code and make a new pull request?
> I can revew your new pull request.
> 
_Originally posted by @yamelsenih in https://github.com/adempiere/adempiere/pull/2232#issuecomment-466007032_

Hi all,

as I suggested in #2231 the sources from `project + request` are moved to base. Thus there ara no circular dependencies anymore.
Also the minor problems with `oracle.jar` and the missing eclipse project definitions are solved.

I hope there are no side-effects for the IDEA-dev env!

### CODE REVIEW

**Comment by marcalwestf** [comment]
@homebeaver  Hi Eugen,
I wonder how would the test of this PR look like?
I imagine checking out your branch and opening it with Eclipse.
I'd say a check would be to make sure it compiles and builds.
And then?

Could you give us a hint on what do we look at and watch for?
Additionally, I don't use Scala; so I wonder how I would do the test for the Scala file.

Thanks!
Mario

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf,
there ara no functionality changes. So the test is building in both IDE, IDEA and eclipse. And a ant build when deploying.
regards EUGen

**Comment by marcalwestf** [comment]
thanks EUGen @homebeaver ; I will test accordingly.

**Comment by marcalwestf** [comment]
Hi EUGen @homebeaver  I fetched and checked out your branch _dev+2231_.

I get exactly the same error as described in issue #2395 . I suggest you update the PR by merging as in #2395 and I'll try again.
Thanks!

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - thanks. It was a good test!
I merged the #2395 commit
bye EUGen

**Comment by marcalwestf** [comment]
Eclipse works OK, now I will test Idea

**Comment by homebeaver** [comment]
tkx Mario, @marcalwestf . 
I checked whether there is really a conflict with moved `ProjectClose.java`-file. 
No. There is not. It is resolved by Auto-merging:

```
C:\Users\eugen\Documents\eclipseWS\OXY-klst-de\ad391>git merge remotes/adempiere/develop
Removing org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/test/SideServer.java
Auto-merging base/src/org/compiere/process/ProjectClose.java
...
```

**Comment by marcalwestf** [comment]
@homebeaver  hi Eugen, sorry to disturb you (again) regarding this already long-standing Pull Request.
It was not accepted into 392, because I ("we") didn't had the time to test it with IntelliJ (which I do seldom use), but with Eclipse it worked.

To accept it at last, I tested the branch https://github.com/klst-de/adempiere/tree/dev%2B2231 and there are no conflicts with Eclipse: I can clean , do a build and start Adempiere with the 392 seed without problems.

Unluckily, I cannot merge because of the conflicts displayed above.
Cuold you (again) merge the branch https://github.com/klst-de/adempiere/tree/dev%2B2231 so I can accept this pull request?

Thanks

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf ,
yes - it is long-standing PR. Meanwhile some file are changed in the "old" dirs. The files has been moved to base dir by the PR to avoid circular dependences. This results to the conflicts. For example:
`org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java` is changed on May 9, 2019 

Currently I do not know what is the best way to solve the dilemma. Mybe I have to create a completly new PR. I'll do my best.
regards EUGen

**Comment by homebeaver** [comment]
@yamelsenih do you have an idea how to solve the conflict? tkx in advance

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - I solved the conflicts :-)

I have to to it with git command interface. I hope there are no side effects.
regards EUGen

**Comment by homebeaver** [comment]
@marcalwestf - I tested the resolved conflicts in eclipse. Build is OK, 
Trevis CI is OK, too! PR can be merged.

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - to avoid the PR becomes stale, I have to resolve the next upcoming conflicts.
The job is done. I hope you can merge this PR soon.
Regards EUGen

**Comment by homebeaver** [comment]
A new conflict file. To be solved...

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf - once again I have been resolving conflicts to keep this PR actual with `origin/develop` branch. Is there a chance to merge the PR to avoid this repeatedly work?
regards EUGen

**Comment by osdevguy** [comment]
Hello Sir
How is it that this issue is not resolved or a fix is presented for this. This seem an inherently structural problem in the build and this is not prioritized over new functionality to be released in a new dev. As someone looking to get involved in the Adempiere project it seems that "own" efficiency is more important than "community" efficiency for all to benefit from having a release that works.

Is there a workaround for this or best to also fork and just run your own parallel system like many seem to be doing while the "core" is running for the benefit of a few.

**Comment by homebeaver** [comment]
@osdevguy tkx for feedback. You can vote for the pull request and the correspondig isssue #2231 to be merged. regards

**Comment by osdevguy** [comment]
Hello @homebeaver where does one vote --- on the "smiley" face ? 

Surely one should be warning all users of the release that the release 3.92 does not actually build and has some serious issues. 

I cannot seem to be warning all potential users of the release around this. I wish to note it somewhere -- how does it work to give feedback as such. 

What a waste of time it is to be struggling with such issues. 

thanks

**Comment by marcalwestf** [comment]
@osdevguy you assertion is not correct. If you cannot build Adempiere 392, it does not necessary mean that it is not possible. We all in our company can, and I know of several people of different countries who also can. I'd be careful which such assertions.

Also we should shun issuing personal comments or feelings in this section (the comment "_what a waste of time..._" in the post). If you notice the tone in the postings of our project, we try to be as matter-of-fact as possible to avoid hurting or offending.

This said, it is great you show intention to get involved with the ADempiere project.  

If you want to contribute on this issue, you could checkout the branch @homebeaver  Eugen is suggesting to be integrated, test it thoroughly and give a feedback, the more detailed the better. No smiles required: just a simple thorough test and a detailed feedback.

If your findings are positive, perhaps other(s) will follow suit and the pull request will be accepted.

I will comment on my following post the situation concerning this very issue.

**Comment by marcalwestf** [comment]
Hi Eugen @homebeaver  , back (again) to this long-standing issue, which perhaps wins a price for perseverance ;) .

Newest test:
1.- Checkout branch _dev+2231_: **OK**
2.- Compile on Eclipse: **OK**
3.- Build on Eclipse: **OK**
3.- Running on Adempiere 3.9.2 seed/Postgres DB: **OK**

So it seems to do what you set out to achieve: get rid of circular dependencies.
The last commits were obviously to keep the branch synced with the _develop_ branch (sorry for that and thanks for your patience).
Reading my comments, I checked already that the main problem is not having it tested on IntelliJ.

I do not use IntelliJ (anymore) so perhaps to be 100% sure, I suggest that somebody who uses InteliJ (@e-Evolution  Victor, perhaps you @homebeaver  Eugen?) can do the same and reports his/her findings.

Then the pull request would be accepted.

**Comment by marcalwestf** [comment]
@osdevguy  it would be a nice, delimited issue to test: do the steps I did on Eclipse and IntelliJ, then document here your findings.

This way you would see how we move work.

**Comment by osdevguy** [comment]
@marcalwestf -- just to be clear for assertion -- the system can build for "production" environment scenario - albeit very slowly -- so it builds the modules thus to deploy. but for actual building for testing and development day-to-day or evaluation it does not work and you have to spend a good few *days* putting the puzzle together ( for what point ? ). 

So thus I mentioned for developers this is not productive/efficient/not any good to be working like this.  So hence it will not work out the box for a newbie developer in the project and it should be clearly stated what the objective of the "development" documentation is -- its really "building" for production ... not for dev. Or is my assertion not correct thus ?

**Comment by homebeaver** [comment]
thks Mario @marcalwestf for testing. IntelliJ? No sorry, I do not have it installed and have no experiance on it.
regards EUGen

**Comment by rcapecce** [comment]
Hello @marcalwestf
I test with IntelliJ this pull request, these were the steps.

1. Checkout this pull request
2. I restarted my adempiere.iml, this one had changes from my other branch.
3. I build the project from IntelliJ (Ctrl+F9) -> Ok, no errors detected.
4. I run the $ADEMPIERE_SOURCE/utils_dev/RUN_Build.sh -> Ok, Build Successful, this ran in 3 min and 22 secs.
5. I generate a database with postgres seed from source -> Ok
6. I run the $ADEMPIERE_HOME/RUN_setup.sh and $ADEMPIERE_HOME/utils/RUN_Server2.sh -> ok and I can login with GardenAdmin (I test this with tomcat)
7. I run ADempiere from IntelliJ Run/Debug Configuration -> ok, I can login with GardenAdmin

Regards

**Comment by marcalwestf** [comment]
@rcapecce  thanks a lot Raúl, now we know the changes by @homebeaver  Eugen do not have side-effects on any IDE.

**Comment by e-Evolution** [comment]
Hello @homebeaver  , @marcalwestf Mario!

I have to reverse this merge for the following reasons.

1.- A pull request where 155 files are modified is unreasonable or indicates that many changes were applied. this took me to the next point

2.- In the detail of the changes, classes of the org.adempiere.request, org.adempiere.project directories were moved to base. this that goes against what we planning for the future:

- ADempiere / develop / org.adempiere.request
- ADempiere / 390a / org.adempiere.project

In previous versions, we started separating the code from the base directory to directories based on functionality, so returning the files to the base directory is a step back from the goal we want to achieve.

The goal is as far as possible the functionality should be separated by bounded context by business functionality, this case org.adempiere.project and org.adempiere.request was already in separate directories. In the future, the idea is to have smaller jar files with specific functionality for when a change is required, the update can be done for business functionality and not for a fat jar .

3.- It is necessary to correctly review the configuration for developers who use eclipse for circular references, I totally agree this must be resolved.

An important observation to take in consideration, @trifonnt Trifon added the possibility of being able to import the complete adempiere project from the Adempiere root to have a complete construction from a single configuration which requires a machine with sufficient hardware.
On the other hand, @trifonnt Trifon added the possibility of open the project for each directory, in order to optimize and use fewer resources, the development only import the directory where need to modify 

Perhaps this is causing confusion for new developers since it can work with a complete configuration and one per directory. This pull request removes this possibility which I consider is not suitable for developers who do not have a machine with sufficient hardware

While this pull request was made with good intentions is not adequate, I will ask our friend @yamelsenih  Yamel who develops using eclipse to update what is necessary for developers to work.

**Pull request merged**
