### PR TITLE
#1685 Bug when try Send Mail Text the process throw NPE, if email not…

### PR DESCRIPTION
**Pull request by e-Evolution**
… can be created https://github.com/adempiere/adempiere/issues/1685

(cherry picked from commit 5c29bead0742818791453ad8d62c47d4761049d6)

### CODE REVIEW

**Comment by wdtz** [comment]
In Functional Review

**Comment by e-Evolution** [comment]
@wdtz can please try again , I fixed the validation.

**Comment by yamelsenih** [comment]
It is ok

**Comment by e-Evolution** [comment]
fixes

**Pull request merged**
