### PR TITLE
1690 Bug with database record lock when enabling accounting immediate is enabled.

### PR DESCRIPTION
**Pull request by e-Evolution**
Bug with database record lock when enabling accounting immediate is enabled. #1690 https://github.com/adempiere/adempiere/issues/1690

### CODE REVIEW

**Comment by yamelsenih** [comment]
It have syntax error:
screenshot_20180711_214946

**Comment by marcalwestf** [comment]
I would strongly reccomend not to mix naming refactoring changes with functional changes in the same issue.

Example of naming refactoring:  https://github.com/adempiere/adempiere/pull/1756/commits/2eeb8f5a225a056c61ac4b23523a197a3903a056

It would be better if there is one issue for refactorting names and another for functional changes, even if they apply to the same class.

When a large class is involved, this improves checking and testing.

**Comment by marcalwestf** [comment]
Moreover, I would be grateful if you could explain step by step how to reproduce the error, this means under which circumstances an immediate accounting locks a table.

I didn't understand it well by the explanation given in https://github.com/adempiere/adempiere/issues/1690 .
Thanks

**Comment by yamelsenih** [comment]
Hi Víctor, exist a path for solve it?

**Pull request closed without merging**
