### PR TITLE
#3900 [Feature Request] Add SSL/HTTPS support for ADempiere deploymen…

### PR DESCRIPTION
**Pull request by e-Evolution**
…t with Wildfly and Jetty https://github.com/adempiere/adempiere/issues/3900

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
- Generate a build file
- Install build file with Oracle's jdk-17
- Install with _Tomcat_, _Jetty_, _Firefly_
- After each installation, delete _keystore_ directory.

Results: 
- all three servers work with **http**
- all three servers throw error when being accessed with **https**:
Selection_195

I wonder if I must do some additional work before calling https.

**Comment by marcalwestf** [comment]
@e-Evolution is there an additional step needed to test?

**Review by marcalwestf — COMMENTED** [review]
New test:
- install on Jetty, this time with port 4444
- run on Firefox

Result: still have only connection with HTTP; no connection with HTTPS.
Log displays no error.
Selection_200

**Review by marcalwestf — COMMENTED** [review]
New test, this time as follows:
-  SSL Port 4444
- Firefox
- Jetty
- URL: https://localhost:4444/webui/
- Question of an insecure connection accepted

Result:  the following error is shown:
Selection_201

Also. according to _nohup.err_, the following error persists:
```
java.lang.IllegalArgumentException: Table Name Not Found - AD_QueueType
        at org.compiere.model.Query.<init>(Query.java:133)
        at org.spin.queue.model.MADQueueType.getAll(MADQueueType.java:121)
        at org.spin.queue.model.MADQueueType.getByQueueType(MADQueueType.java:90)
        at org.spin.queue.util.QueueLoader.getQueueManager(QueueLoader.java:67)
        at org.compiere.util.WebEnv.lambda$initWeb$0(WebEnv.java:183)
        at org.compiere.util.Trx.run(Trx.java:529)
        at org.compiere.util.Trx.run(Trx.java:497)
        at org.compiere.util.WebEnv.initWeb(WebEnv.java:181)
        at org.compiere.util.WebEnv.initWeb(WebEnv.java:131)
        at org.compiere.web.AdempiereMonitor.init(AdempiereMonitor.java:896)

Using URL http://localhost:8888/webui works.

```

**Review by marcalwestf — COMMENTED** [review]
Yet another test, this time with IP instead of localhost:
- SSL Port 4444
- Firefox
- Jetty
- URL: https://192.168.0.9:4444/webui/ (also: https://192.168.0.9:4444)
- started from both local host and host in LAN
- Question of an insecure connection accepted

Result: same as before: `<h2>HTTP ERROR 400 Invalid SNI</h2>`

If the installation is done with Tomcat, the result is OK (see URL and Port)
imagen

Results with Firefly: is displays shortly the login dialog and immediately goes over to timeout:
imagen

**Comment by e-Evolution** [comment]
@marcalwestf this is that I found with the solution 

https://stackoverflow.com/questions/69945173/http-error-400-invalid-sni-jetty-https-servlet

**Comment by marcalwestf** [comment]
thanks, @e-Evolution Víctor, I have tested with IPs and with names without ".".
I will change the hostname so it resembles a domain name and report.

**Review by marcalwestf — APPROVED** [review]
New test:
- Ubuntu 18.04, Postgres 12
- Generate seed from 393 up to newest XML
- Generate a build file
- Delete keystore directory.
- Install build file with **Oracle's jdk-11**
- Install with Jetty
- use a fully qualified canonical host/domain name (**westfalia.local**)
- use port 4444
- run on **Firefox** and **Chrome**: https://westfalia.local:4444/webui/
- Accept all security warnings

Result:  under these circumstances, it is possible to run https
imagen

Using JDK 17, this is not possible.

There is still an error on **nohup.err**:
```
org.apache.jasper.JasperException: /login.jsp (line: [66], column: [60]) [${initParam.#AD_Client_ID}] contains invalid expression(s): [javax.el.ELException: Failed to parse the expression [
${initParam.#AD_Client_ID}]]
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:292)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:98)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.getJspAttribute(Validator.java:1443)
        at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1252)
```
.. but it seems to stem from Jasper, not from https.

**Firelfly**: same configuration as with Jetty, with the difference that it runs on Chrome, but not on Firefox. It also must be JDK 11, not 17

**Comment by marcalwestf** [comment]
@e-Evolution  I'd say, before accepting this PR, we ought to know and document under which exact conditions HTTPS is possible.
As of now, and according to my tests:

Runs only on JDK 11.
It doesn't run on JDK17.

Tomcat and Jetty: run on Firefox and Chrome.
Firefly: runs only on Chrome. It doesn't run on Firefox.

It runs only on a fully qualified canonical host/domain name.

The port to be used is the SSL port.

Perhaps you or another reviewer can put here their findings so we all know exactly under what circumstances HTTPS runs.

**Comment by e-Evolution** [comment]
@marcalwestf For this to work, make sure you don't have the myKeyStore file generated and when you do RUN_setup.sh you use an IP or domain on the application server, this way it works even using JDK 17

image

image

**Review by marcalwestf — APPROVED** [review]
At last, I found the way to use HTTPS with this PR: it works only using **Azul JDK**. Thanks @e-Evolution for the hint.

When HTTPS is needed, here is the configuration that worked for me:
- Ubuntu 18.04, Postgres 12
- Generate seed from 393 up to newest XML
- Generate a build file
- Install build file with **Azul jdk-17**
- Install with Jetty and Firefly
- Delete keystore directory after each installation
- Use a fully qualified canonical host/domain name (westfalia.local)
- Use port 4444
- Run on Firefox and Chrome: https://westfalia.local:4444/webui/
- Accept all security warnings

Additional comments
- Using Oracle's JDK11, HTTPS doesn't work 
- Using Oracle's JDK17, under some circumstances (see comments before)
- After the merge to the newest develop commit, the class not found errors disappear.

Tests passed.

**Pull request merged**
