### PR TITLE
[Feature Request] Change Connection pool library c3p0 to HikariCP

### LINKED ISSUE #3582: [Feature Request] Change Connection pool library c3p0  to HikariCP
## Feature request
Currently Adempiere uses a library c3p0  no longer supported for cool connections. so we propose to switch to HikariCP https://github.com/brettwooldridge/HikariCP 

#### Describe the solution you'd like
Replace the current code with the new implementation

### PR DESCRIPTION
**Pull request by e-Evolution**
fixed #3582

### CODE REVIEW

**Review by marcalwestf — APPROVED** [review]
- tests on Swing and ZK
- different tasks on: windows, smart browsers, reports, attachments, etc.

Result: functional operation works properly.
Tests passed.

**Comment by marcalwestf** [comment]
@e-Evolution just correct the discrepancies to accept this PR.
Thanks!

**Comment by dram** [comment]
I saw lots of following messages in the console when running Swing client after this PR merged, seems to be abnormal:

```
-----------> DB_PostgreSQL.getCachedConnection: # Connections: HikariDataSource (HikariPool-1) [1]
-----------> DB_PostgreSQL.getCachedConnection: # Connections: HikariDataSource (HikariPool-1) [1]
-----------> DB_PostgreSQL.getCachedConnection: # Connections: HikariDataSource (HikariPool-1) [1]
-----------> DB_PostgreSQL.getCachedConnection: # Connections: HikariDataSource (HikariPool-1) [1]
-----------> DB_PostgreSQL.getCachedConnection: # Connections: HikariDataSource (HikariPool-1) [1]
...
```

**Comment by dram** [comment]
Those messages are printed by following code, I kind of think that those lines of code are not needed anymore, and can be deleted all together, as it's a workaround for c3p0 connection leak (see commit eaa1730), which is not valid for HikariCP.

BTW, the same can be done for `DB_MariaDB`, `DB_MySQL` and `DB_Oracle`.

https://github.com/adempiere/adempiere/blob/efb437db1b67f2ddda1ecd50e5cb253746379862/base/src/org/compiere/db/DB_PostgreSQL.java#L534-L545

**Comment by dram** [comment]
Another problem, now there are two version of `slf4j-api` in `tools/lib`, `slf4j-api-1.6.0` and `slf4j-api-1.7.32`.

**Comment by marcalwestf** [comment]
@dram thanks for testing and commenting.
We'll look into it.

**Pull request merged**
