### PR TITLE
Add support openJDK11

### PR DESCRIPTION
**Pull request by zalevan**
1. simple change build.xml files and set target to jdk11.
2. some deprecated lib in jdk (awt, swing...) is hided and need to be import. it is done by `<compilearg>` tag.
3. javax.activation in openjdk 11 is go to independent jar.
4. in jdk11 var is keyword and need to rename var.java to varEl.java
5. some generic class need update to <? extends clazz> syntax.
6. Add jdk 11 in version checks functions.

Build OK. Tested runs of client and tomcat server on postgresql 11.

### CODE REVIEW

**Comment by zalevan** [comment]
I see in travis CI checks used java 8, but this commit need java 11!!!

**Comment by yamelsenih** [comment]
Hi @zalevan I will to review it

**Comment by marekmosiewicz** [comment]
AFAIR there is more missing classes. There is also need to remove startup param ENDORSED_DIR for tomcat and jboss. Maybe it would be good to upgrade tomcat and jboss to wildfly, but I had problem with tags for zkoss

**Comment by marekmosiewicz** [comment]
I also remember that there was necessity to add option for jdk 11 for certificate creation in setup

**Comment by zalevan** [comment]
Yes, i forgot.
7. Keystore change to apache Base64 class.
I am build clear system. Key generetaion and db import is was succsessefull.

**Comment by yamelsenih** [comment]
Hi, is a little change but some testing, I will test it

**Comment by marekmosiewicz** [comment]
I have problem in utils_dev RUN_build2.sh and RUN_build.sh checking for tools.jar in jdk. If I remove this check everything builds ok.

**Comment by marekmosiewicz** [comment]
Same problem when running RUN_setup.sh from built Adempiere

**Comment by marekmosiewicz** [comment]
There is no jdk11 check sun jdk

**Comment by zalevan** [comment]
> There is no jdk11 check sun jdk

Sun JDK is not free after 11.

**Comment by osdevguy** [comment]
Just to confirm --- "someone" needs to run jdk 11 in production environment first before it will be supported :

image

**Comment by osdevguy** [comment]
Have to review this issue together with : https://github.com/adempiere/adempiere/issues/2231

**Comment by e-Evolution** [comment]
implementing with #3479 Thank you a lot @zalevan for your contribution.

**Pull request closed without merging**
