### PR TITLE
Fixed error with Transaction for Import Attendance

### PR DESCRIPTION
**Pull request by yamelsenih**
This resolve a transaction problem with import attendance.

The follow log:

```Shell
===========> ImportAttendance.process:
org.postgresql.util.PSQLException: ERROR: insert or update on table
"i_hr_attendancerecord" violates foreign key constraint
"hrattendancebatch_ihrattendanc"
  Detail: Key (hr_attendancebatch_id)=(1000002) is not present in table
"hr_attendancebatch". [341]
org.postgresql.util.PSQLException: ERROR: insert or update on table
"i_hr_attendancerecord" violates foreign key constraint
"hrattendancebatch_ihrattendanc"
  Detail: Key (hr_attendancebatch_id)=(1000002) is not present in table
"hr_attendancebatch".; State=23503; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at org.compiere.util.Trx.commit(Trx.java:338)
	at org.compiere.util.Trx.run(Trx.java:532)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.spin.tar.process.ImportAttendance.lambda$1(ImportAttendance.java:63)
	at java.base/java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:593)
	at org.spin.tar.process.ImportAttendance.doIt(ImportAttendance.java:62)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)

```

## Testing
All need files are here:
- `data/import/Example_Attendance_Format.xlsx`: Complete excel format
- `data/import/Example_Attendance_Format.tsv` Tab separed Values format for import attendances
- [Online File](https://docs.google.com/spreadsheets/d/1TdFblRwDDUh-nXqJuMqNZCSyGGRMkI7W/edit?usp=sharing&ouid=112500014010442521967&rtpof=true&sd=true)

## Some Data
Note that this pull request have two XML's:
- `10000_4086_Add_Attendance_Import_Format.xml`
- `10010_4086_Add_Garden_World_Test_Data.xml`

After import, you should see one import format:
- `Attendance Record`: This should match with `data/import/Example_Attendance_Format.tsv` format

## Some Info
Note that this pull request depending from https://github.com/adempiere/adempiere/pull/4186

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hello @e-Evolution @marcalwestf can you see it?

**Comment by e-Evolution** [comment]
Hi @yamelsenih When applying the XML migration script they fail, apparently an attempt is made to add employees with departments that are not created, can you please validate to be able to test the import of incidents

-----------> MHREmployee.load: NO Data found for HR_Employee_ID=50001 [1]
===========> Trx.commit: POSave_867bd33d-a2f7-4340-8f83-0bbfef76fbca [1]
org.postgresql.util.PSQLException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".; State=23503; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at org.compiere.util.Trx.commit(Trx.java:338)
	at org.compiere.model.PO.save(PO.java:2238)
	at org.compiere.model.PO.saveEx(PO.java:2313)
	at org.compiere.model.PO.saveEx(PO.java:2443)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:608)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:235)
	at org.compiere.model.MMigration.apply(MMigration.java:157)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)

===========> MHREmployee.saveError: Error - ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
21:16:25.046 Trx.rollback: **** POSave_867bd33d-a2f7-4340-8f83-0bbfef76fbca [1]
-----------> MMigrationStep.bailout: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
-----------> MMigration.apply: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
-----------> MHREmployee.load: NO Data found for HR_Employee_ID=50001 [1]
===========> Trx.commit: POSave_f647aff8-bd4a-4e65-8b04-92f3f404f8c7 [1]
org.postgresql.util.PSQLException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".; State=23503; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at org.compiere.util.Trx.commit(Trx.java:338)
	at org.compiere.model.PO.save(PO.java:2238)
	at org.compiere.model.PO.saveEx(PO.java:2313)
	at org.compiere.model.PO.saveEx(PO.java:2443)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:608)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:235)
	at org.compiere.model.MMigration.apply(MMigration.java:157)
	at org.compiere.model.MMigration.apply(MMigration.java:179)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)

===========> MHREmployee.saveError: Error - ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
21:16:25.131 Trx.rollback: **** POSave_f647aff8-bd4a-4e65-8b04-92f3f404f8c7 [1]
-----------> MMigrationStep.bailout: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
-----------> MMigration.apply: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
-----------> MMigration.apply: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
21:16:25.139 MigrationApply.addLog: 0 - null - null - Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
===========> MigrationApply.process: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department". [1]
org.adempiere.exceptions.AdempiereException: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".
	at org.compiere.model.MMigration.apply(MMigration.java:184)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:357)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:198)
	at org.eevolution.services.dsl.ProcessBuilder.run(ProcessBuilder.java:223)
	at org.eevolution.services.dsl.ProcessBuilder$1.run(ProcessBuilder.java:304)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:301)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
caused by: org.adempiere.exceptions.AdempiereException: Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:278)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:630)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:235)
	at org.compiere.model.MMigration.apply(MMigration.java:157)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:357)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:198)
caused by: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".
	at org.compiere.model.PO.saveEx(PO.java:2320)
	at org.compiere.model.PO.saveEx(PO.java:2443)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:608)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:235)
	at org.compiere.model.MMigration.apply(MMigration.java:157)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:357)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:198)

21:16:25.155 Trx.rollback: **** TrxRun_99086c7e-af88-4d08-972d-23a513bc7378 [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/EE3.9.4.001/install/build/Adempiere/migration/394lts-395lts/10010_4086_Add_Garden_World_Test_Data.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:167)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:357)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:198)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 10010 - #4086 Add Garden World Test Data - 3.9.5 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: ERROR: insert or update on table "hr_employee" violates foreign key constraint "hrdepartment_hremployee"
  Detail: Key (hr_department_id)=(50000) is not present in table "hr_department".
	at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:312)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)

org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Loading Migration from XML failed.
	at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:276)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:96)

*** 2023-11-23 21:16:25.171 Adempiere Log (CLogConsole) ***

**Comment by yamelsenih** [comment]
Hello @e-Evolution thanks, let me test it and fix.

**Comment by yamelsenih** [comment]
Replaced by https://github.com/adempiere/adempiere/pull/4223

**Pull request closed without merging**
