### PR TITLE
#1772 New feature for dynamic tree

### LINKED ISSUE #1772: New feature for Dynamic Tree
Currently exist a branch for handle dynamic tree https://github.com/adempiere/adempiere/tree/feature/ADEMPIERE-442-Dynamic-Tree-Functionality
i propose integrate it with develop branch, is nice to have any table as tree table and many hard code will be removed

### PR DESCRIPTION
**Pull request by yamelsenih**
https://github.com/adempiere/adempiere/issues/1772
Hi guy, this is a new functionality for handle tree on ADempiere, please see it.

Best Regard

fixes #1772

### CODE REVIEW

**Comment by e-Evolution** [comment]
Hi @yamelsenih , I testing the new enhancement , first strange that I found is that currently tree structure for organization and dimension for Garden World are lost.

image

I ran check tree for organization tree and not solve the issue.

**Comment by e-Evolution** [comment]
@yamelsenih here my testing.

1.- Create new element for any accounting dimension , successful
2.- Create new company and check if the tree was created , successful
3.- Create a new menu tree and adding new element and attachment to new role and test the access menu, successful
4.- Execute Verify tree for Garden World Organization and not fix 
4.- Create a new tree with tree customization for sales order , this work but I got after two try , so that throw a error that the column Name not found , so I think that when you adding tree customization should system validate the table selected have isSummary and Name field to allows the configuration.

**Comment by RJPC** [comment]
Hi @e-Evolution 

- could place a step-to-step of the testing 5.
- the tree of the organization It will be reviewed.
- the process of verify tree comply the same functionality that in an environment without the changes.

**Comment by yamelsenih** [comment]
>4.- Create a new tree with tree customization for sales order , this work but I got after two try , so that throw a error that the column Name not found , so I think that when you adding tree customization should system validate the table selected have isSummary and Name field to allows the configuration.

It can be resolved with a validation of tables with (IsSummary, Name) columns

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I tested financial report with a new hierarchy/tree for Business partner without problems.
Also I updated the table c_OrderSource by field _issummary_ and it is presented as a tree.
imagen

**Pull request merged**
