### PR TITLE
Add support to Sales representative based on sales region

### PR DESCRIPTION
**Pull request by yamelsenih**
Fixes: #1456

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih  started testing.

One little observation: _sr.SalesRep_ID_ seems to be repeated on _CalloutOrder.bPartner()_:  
Selection_367

**Comment by yamelsenih** [comment]
> One little observation: _sr.SalesRep_ID_ seems to be repeated on _CalloutOrder.bPartner()_:

hi @marcalwestf thids is fixed yet

**Comment by marcalwestf** [comment]
Second test: it works for Sales Orders:

- Define the Business Partner without Sales Representative
- Set a  Sales Representative for a Region
- Define a Region for a Location of the Business Partner
- Create a Sales Order with the Business Partner

Result: selecting the Business Partner finds the Sales Representative of the Region.
Test passed.

**Comment by marcalwestf** [comment]
@yamelsenih when creating an Invoice, it doesn't work:
perhaps the same treatment for _CalloutInvoice.bPartner()_ is needed?

**Comment by yamelsenih** [comment]
> @yamelsenih when creating an Invoice, it doesn't work:
> perhaps the same treatment for _CalloutInvoice.bPartner()_ is needed?

Mario Sales Rep is not setted from Invoice originally

**Comment by yamelsenih** [comment]
> @yamelsenih when creating an Invoice, it doesn't work:
> perhaps the same treatment for _CalloutInvoice.bPartner()_ is needed?

Maybe can be added as new feature in other pull request

**Pull request merged**
