### PR TITLE
#3469 [Bug Report] In the process Generate an Invoice from the Receip…

### PR DESCRIPTION
**Pull request by e-Evolution**
…t is not validate if an Invoice was generated https://github.com/adempiere/adempiere/issues/3469

### CODE REVIEW

**Comment by yamelsenih** [comment]
I will review it

**Comment by marcalwestf** [comment]
this pull request is similar to https://github.com/adempiere/adempiere/pull/3468.
The difference is that here, we concentrate on the Material Receipt instead of the Invoice (Vendor).

I did the following in Adempiere standard:

1. Create a Purchase Order and complete it.
2. Create a Material Receipt and generate a Material Receipt Line based on the Purchase Order. Complete the Material Receipt.
3. Stay on the Material Receipt and Create an Invoice (Vendor).
4. Do not complete the  Invoice (Vendor).
5. Create as many  Invoices (Vendor) as you please and leave them in the Draft status.

This is an error because users can create an Invoice (Vendor) for a Material Receipt, and choose not to complete it.
Then, by mistake, another  Invoice (Vendor) can be created out of the same Material Receipt. Now we'd have two  Invoices (Vendor) for the same  Material Receipt.
In the end, all drafted Invoices (Vendor) can be completed, most undesirable.

**Comment by marcalwestf** [comment]
With the changes of this pull request, you get the following message when there is a matched Invoice Vendor even in the Draft status:
imagen

**Review by marcalwestf — APPROVED** [review]
-  tested the behavior of standard Adempiere: it is possible to create several Invoices (Vendor) out of a Material Receipt if they are left in the Drafted status.
- with this pull request, this (erroneous) behavior is suppressed.

-> test passed

**Comment by yamelsenih** [comment]
Hi @e-Evolution @marcalwestf I think that the merge for all PRs should be taking the created date as priority, existing many olds PR that is less without approve

**Comment by marcalwestf** [comment]
this pull request is linked to https://github.com/adempiere/adempiere/pull/3464 and https://github.com/adempiere/adempiere/pull/3468 .

**Comment by yamelsenih** [comment]
I agree, just update this branch with last changes for approval from CI

**Pull request merged**
