### PR TITLE
[Feature Request] Adding support for Java JDK 11 (LTS)

### PR DESCRIPTION
**Pull request by e-Evolution**
Adding support for Java JDK 11 (LTS)  #3477 
Other related issues  #1941 #2326

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution I have some questions
- Why this pull request was add if already exists a pull request for this? => #2326 I think that is more honorable make suggestions to original pull request and try to resolve instead create a new, also the original credits are from @zalevan


Some Comments: I agree with reopen original PR and try resolve instead create a new

Best regards

**Comment by e-Evolution** [comment]
> Hi @e-Evolution I have some questions
> 
> * Why this pull request was add if already exists a pull request for this? => #2326 I think that is more honorable make suggestions to original pull request and try to resolve instead create a new, also the original credits are from @zalevan
> 
> Some Comments: I agree with reopen original PR and try resolve instead create a new
> 
> Best regards

@yamelsenih he my comment.

first because the pull requests are very very old, trying to update any of the branches was more work than doing it again, on the other hand it was important to carefully review and test the suggested changes

Second, because there are two different migration approaches, one where some obsolete classes were rewritten making a port when it was not necessary and the other was not complete.

third because neither of the two approaches solved the problem of sending emails that stopped working in zk webui since javax.mail stopped being part of Java 11

on the other hand, the credits were added in the header of the files that had it, so the credits are being respected.

In the past you have reviewed yourself and made comments on some of these pull requests and absolutely nothing happened.

rather it seems that their goal is to set foot and delay the project rather than test the implementation and provide more than one comment.

Anyway, I prefer someone like Mario to review it with more criterial

**Comment by yamelsenih** [comment]
thanks, I only ask because exist more ways for resolve:
>first because the pull requests are very very old, trying to update any of the branches was more work than doing it again, on the other hand it was important to carefully review and test the suggested changes

I think that a good option can be make a PR to https://github.com/zalevan/adempiere/tree/openjdk11 instead and wait for He for update branch before

>Second, because there are two different migration approaches, one where some obsolete classes were rewritten making a port when it was not necessary and the other was not complete.

Any contributor can have many approaches and always is good suggest a change instead take the change

>third because neither of the two approaches solved the problem of sending emails that stopped working in zk webui since javax.mail stopped being part of Java 11

This apply the same comment of first 

>on the other hand, the credits were added in the header of the files that had it, so the credits are being respected.

I don't have a doubt about it, I think that @zalevan was implement many time making the PR #2326 and always is better suggest a change instead take the change

>In the past you have reviewed yourself and made comments on some of these pull requests and absolutely nothing happened.
I don't see the reason here

Note: I don't want create a conflict, just I think that always is good help to any contributor to propose changes and materialize it instead take changes and only add credits on file header

Best regard

**Comment by e-Evolution** [comment]
@yamelsenih  Well, that appreciation is correct when there is an answer and they attend to the observations, but if there is no answer you have to move forward and take it into your hands.

Here are the comments I made that had no response:

image


image


image



As documented, the contribution is not only from @zalevan with #2326 but long before @ghost an anonymous user removed from GitHub, with commits from @marekmosiewicz with #1941,  so that  I think that is more valuable and useful for this project to join the work of @marekmosiewicz, @zalevan, and my own work, investing the necessary time out of respect to reviewing and testing the proposed changes and solving any problems that arise along the way.

It is not much use to say I will review and testing and in the end, absolutely nothing happens.


image

image

Where are your review and testing?

The important for the project is to move forward.

**Comment by marcalwestf** [comment]
@all this is a very important Pull Request, which has to be tested thoroughly.
It would be of great help if others would also participate in the test.

**Comment by vdevsoft** [comment]
Great, I'm going to test it on my server.

**Comment by marcalwestf** [comment]
I am going to test with AdoptOpenJDK ( https://adoptopenjdk.net/index.html).
See motivation here: https://adoptopenjdk.net/about.html.
It is an alternative to Oracle and is supported by big companies which want to keep Java open (https://adoptopenjdk.net/sponsors.html).

**Comment by marcalwestf** [comment]
Test on **Swing**

I Create and modify Master data: 
- Product
- Business Partner
- Price List, Price List Version, Product Price
- BP Groups

II Create and complete documents

- Purchase Order
- Material Receipt
- Sales Order
- Invoice (Customer)
- Shipment

Test passed without errors.

**Comment by mckayERP** [comment]
If you enable the integration tests in util_dev/test.properties and then
run the build, it should run all the unit and integration tests.  This
would help save some time in testing as the tests cover many of the common
operations.

Mike

**Comment by marcalwestf** [comment]
thanks, @mckayERP  Mike, I had forgotten the tests!!!!
I just set the _util_dev/test.properties_ file accordingly and am about to start the build.

image

**Comment by marcalwestf** [comment]
@mckayERP  hi Mike, I got the following error. It says "**invalid target release: 11**".
In tools/build.xml (and actually also in all build.xml files), the java 11 compiler is selected.

Any hint where the valid compiler is set?
image
image
image

**Comment by mckayERP** [comment]
Hi Mario,

You need Java 11 jdk installed and added to Eclipse.

image

Look at the Adempiere project properties and check the java library.  It should be Java 11 jre.

Here is before:
image

Remove it and add a new library
image

Here is after:
image

**Comment by mckayERP** [comment]
This pull request is targeting the develop branch from a private repository.  In my opinion, its a long way from being ready.  There are several old Sun libraries that will need to be replaced along with their implementations.   I'd suggest that this work should be done in a feature branch in the main repository that everyone can contribute to directly without the PR process.  Then, when it is fully fixed, we can perform a single PR from the feature to the develop branch with a good review.

An alternative to upgrading the code is to use the Java11 JRE but keep the code compliance at java8.  This isn't really an upgrade though.

**Comment by e-Evolution** [comment]
> This pull request is targeting the develop branch from a private repository. In my opinion, its a long way from being ready. There are several old Sun libraries that will need to be replaced along with their implementations. I'd suggest that this work should be done in a feature branch in the main repository that everyone can contribute to directly without the PR process. Then, when it is fully fixed, we can perform a single PR from the feature to the develop branch with a good review.
> 
> An alternative to upgrading the code is to use the Java11 JRE but keep the code compliance at java8. This isn't really an upgrade though.

Hi @mckayERP Mike, if you check in detail, it was updated and replaced the obsolete code and libraries.
Also added the libraries that are no longer part of the JDK 11
This pull request is the work of multiple people to achieve the migration,so the intention of publishing the pull request is for others to test and report any problems 

Did you find a problem? 

What other Sun old libraries need to be updated?

kind regards 
Victor

**Comment by mckayERP** [comment]
Sorry Victor. Please ignore my previous comment.  I forgot about the need
to  include the exported libraries in Java 11.  Haven't figured out how to
make that work in Eclipse. I'll deleted the comment.

Mike

**Comment by e-Evolution** [comment]
Support ADempiere for JDK 11 and Eclipse 

1.- Install Eclipse Version 2021-06 (4.20.0)

Download the last stable version https://www.eclipse.org/downloads/

2.- Execute the Eclipse 

image

3.- Import the ADempiere project 
image

image

4.- Project imported without errors

image

5.- Validate that IDE is using Java Compiler for JDK 11

image

5.- The Eclipse IDE setting is ready without errors

image

**Comment by e-Evolution** [comment]
> Sorry Victor. Please ignore my previous comment. I forgot about the need to include the exported libraries in Java 11. Haven't figured out how to make that work in Eclipse. I'll deleted the comment. Mike
> […](#)

Hi @mckayERP Mike, do not worry. please check, I fixed the Eclipse project, and now is working, please testing and report any problem

**Comment by marekmosiewicz** [comment]
I do not know about status of this pull request. I have now some contract clauses, so I can not help writing code, but I can explain my old pull request for JDK 10.
1. There are some obvious replacement for old sun API in Swing client
2. For setup project it is better to use JDK11 pull request.
3. There was sun LDAP code used in Adempiere. I have copied JDK (GPL) implementation but maybe it is possible somehow to use hidden API which maybe still exist there.
4. There was Tomcat (or Jboss I do not remeber) issue not starting because of removed java option. For JDK10 removing this option seemed to work, but maybe it is time to upgrade Tomcat.
5. There was need to add missing methods for JDBC interfaces for CResultSet if I remember correctly. Probably they can be unimplemented. At least they are not used directly.
6. For JBoss I do not know about depreciated RowSet for transfering resultset to client.

**Comment by e-Evolution** [comment]
> I do not know about the status of this pull request. I have now some contract clauses, so I can not help writing code, but I can explain my old pull request for JDK 10.
> 
> 1. There are some obvious replacement for old sun API in Swing client
> 2. For setup project it is better to use JDK11 pull request.
> 3. There was sun LDAP code used in Adempiere. I have copied JDK (GPL) implementation but maybe it is possible somehow to use hidden API which maybe still exist there.
> 4. There was Tomcat (or Jboss I do not remeber) issue not starting because of removed java option. For JDK10 removing this option seemed to work, but maybe it is time to upgrade Tomcat.
> 5. There was need to add missing methods for JDBC interfaces for CResultSet if I remember correctly. Probably they can be unimplemented. At least they are not used directly.
> 6. For JBoss I do not know about depreciated RowSet for transfering resultset to client.

Hello @marekmosiewicz, thank you very much for sending your comments.

This pull request is based on the combination of your contribution and another, create another pull request to facilitate the implementation of your changes and the other contribution that implemented Java 11

So use the best approach of both contributions #1941 and #2326, on the other hand in the process libraries were updated and removed the ones that are no longer needed as they are included in JDK11.

Since Java 11 handles the Classpath as a module it is necessary to remove the jar files with duplicate dependencies and make a setting in the Eclipse compiler parameters.

Now everything is working IntelliJ, Eclipse, Tomcat 8.5

Thank you all for your contributions. 

kind regards
Victor

**Comment by marcalwestf** [comment]
I followed the steps suggested by @e-Evolution  and @mckayERP :

- downloaded latest Eclipse version (2021-06)
- downloaded latest Java 11 (AdoptOpenJDK 11+9)
- used new workspace

I still get some errors:
image

According to the comments of @marekmosiewicz  , it seems to be a problem cuased by the usage of _com.sun_ classes, which are not supported by newest Java versions.

I remember that by changing from Java 6 to Java 8 there were also some issues with _com.sun_ classes.
I will cntinue digging into it.

**Comment by marcalwestf** [comment]
I think the comment by Marek is important here
> 3. There was sun LDAP code used in Adempiere. I have copied JDK (GPL) implementation but maybe it is possible somehow to  use hidden API which maybe still exist there.

**Comment by marekmosiewicz** [comment]
@marcalwestf You need to check modularization introduced in JDK9. Maybe it is possible to access this classes in some way.

**Comment by marcalwestf** [comment]
thanks @marekmosiewicz  Marek, this is what I am doing right now...

**Comment by marcalwestf** [comment]
I think this is the commit I will concentrate on: https://github.com/adempiere/adempiere/pull/1941/commits/298885d214d17d4457077ceae60c1b2486ec6f44

@marekmosiewicz  Marek, do you have by chance the hole commit? So I don't have to get all changes manually. 
Thanks!!

**Comment by e-Evolution** [comment]
Hi Mario, this was solve with commit 

https://github.com/adempiere/adempiere/pull/3479/commits/7d1c1a818fe7c094655515d09fcba1fc0e378d30

		<attributes>
 			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
 			<attribute name="module" value="true"/>
 			<attribute name="add-exports" value="java.desktop/sun.swing=ALL-UNNAMED:java.desktop/sun.awt=ALL-UNNAMED:java.base/sun.security.provider=ALL-UNNAMED:java.naming/com.sun.jndi.ldap=ALL-UNNAMED:java.xml/org.w3c.dom=ALL-UNNAMED"/>
 		</attributes>
 		
Now with the modularity you need this setting to access this sun Java clasess 

so you need check that have last chance and tha use jdk 11 and compile 

Kind reagrds
Victor

**Comment by mckayERP** [comment]
It is this bit from the Intelij .iml that needs to be applied to Eclipse somehow.

<attribute name="add-exports" value="java.desktop/sun.swing=ALL-UNNAMED:java.desktop/sun.awt=ALL-UNNAMED:java.base/sun.security.provider=ALL-UNNAMED:java.naming/com.sun.jndi.ldap=ALL-UNNAMED:java.xml/org.w3c.dom=ALL-UNNAMED"/>

I haven't figure that out yet.

**Comment by marekmosiewicz** [comment]
> 
> 
> I think this is the commit I will concentrate on: [298885d](https://github.com/adempiere/adempiere/commit/298885d214d17d4457077ceae60c1b2486ec6f44)
> 
> @marekmosiewicz Marek, do you have by chance the hole commit? So I don't have to get all changes manually.
> Thanks!!

If you will use sun classes this commit will be not necessary.

**Comment by e-Evolution** [comment]
Hi @mckayERP , @marcalwestf ,@marekmosiewicz

No further changes are required, the configuration is already enabled in .classpath for Eclipse in this pull request, can find this lines into your  .classpath file 

<attribute name = "add-exports" value = "java.desktop / sun.swing = ALL-UNNAMED: java.desktop / sun.awt = ALL-UNNAMED: java.base / sun.security.provider = ALL-UNNAMED: java.naming / com.sun.jndi.ldap = ALL-UNNAMED: java.xml / org.w3c.dom = ALL-UNNAMED "/>

sun package classes exist into the JDK 11 only is require exporting with the previous conficuration as part of the ALL-UNNAMED module

so nothing else is required, the project compiles and is builing without problems and works (utils_dev/build.sh), check that you are using jdk 11

The configuration with eclipse since in my case both Intellij and Eclipse work correctly

someone else followed the steps indicated, you must download the latest version of eclipse, jdk11 and import the project into a new workspace for eclipse


Kínd regards 
Victor

**Comment by e-Evolution** [comment]
Any way If for some reason it does not work in your version you can add the configuration manually as indicated here:

https://stackoverflow.com/questions/54068992/how-to-tell-eclipse-to-add-exports-when-compiling/54071487

kind regards 
Victor

**Comment by marcalwestf** [comment]
At last I got!!!

Eclipse 2021-06 and jdk11 now compile correctly eevolution's jdk11 branch (_e-Evolution:feature/3477_).
The reason was very simple: I didn't notice that Eclipse without reason (at least so it seems to me) removed the _com.sun.jndi.ldap_ reference from _.classpath_ when opening the project, as you can see in the following image..
image


@e-Evolution @mckayERP  @marekmosiewicz  thank you all for your kind support!

Now, I wonder what I wanted to do hahahaha.
Ahh I remember, to do the Unit and Integration tests as recommended by Mike!! Let's see...

**Comment by marcalwestf** [comment]
build with Unit Tests successful!
image

**Comment by marcalwestf** [comment]
Activating the Integration Tests there is an error when executing the build:
image

Now, I going to investigate what happened...

**Comment by marcalwestf** [comment]
Is there a way to start the Tests and debug them? This way I could find out where and why the integration test fails.
Looking for a _main()_ method.

**Comment by yamelsenih** [comment]
Hi everyone I saw that exists many comments here,very hard work.
Please just consider let it waiting for merge until all pull request before it can be merged or closed (if is unapplied for merged)
I can help to test it the next week. I am happy of contribute here
Best regards

**Comment by marcalwestf** [comment]
@yamelsenih  hi Yamel, you're right: this should be the last merge to be done.

Looking forward for you to test!

**Comment by mckayERP** [comment]
Hi Mario

Individual tests can be run by opening the test file and the typing
Alt-Shift-X,T. To debug, use Alt-Shift D,T.

A launch configuration should be created when you do this.  Set the junit
launcher to Junit5 and then you can set tags or the expand the launcher to
cover all tests in a module.

There is some old junit4 code hidden somewhere in a jar that is preventing
a single launcher to run all the tests.  This would best be done with an
ANT script.

Mike

**Comment by marcalwestf** [comment]
.. the build was successful, I could install ADempiere and start the swing clientN from the installation....

**Comment by marcalwestf** [comment]
... now started Tomcat and ADempiere is running on JAVA_HOME=/usr/lib/jvm/jdk-11.0.11+9.
Access via Web browser successful.

Now we can start testing.

I think besides windows, reports, processes, etc. I will also try out Workflows and Jasper processes .

**Comment by marcalwestf** [comment]
Tested successfully on Tomcat:

- Create Product, BP, BP Group, Product Price, User, Location, BP Vendor.
- Attachments
- Requisition create + complete (Window)
- Create PO from Requisition (Process)
- PO complete
-  Material Receipt create + complete (Window)
- Create Material Receipt Lines from PO (Process)
- Generate Invoice from Material Receipt (Process)
- Create Quotation
- Convert Quotation to Sales Order (Process)
- Sales Order complete
- Generate Invoice from Order Lines (Form)
- Complete Invoice
- Generate Shipment from Order Line (Smart Browser)
- Shipment complete (Window)
- Payment create + complete (Window)
- Several reports, including copying and modifying Print Formats
- Partial Payments

**Comment by marcalwestf** [comment]
Additional tests:

- Changes in Application Dictionary
- Workflow (Element) navigation
- Misc: Zoom (De-referencing), Zoom Across
- BOM Editor
- MRP Process
- Views filter + access: Product, BP, Invoice, Order, Shpment, Payment, Account
- Workflow editor
- Calculate Low Level (MRP)

**Comment by niclopup** [comment]
Tested successfully on Tomcat and Java 11:
Sales

- Complete Sales Order "Orden Estandar"
- Complete Sale Order "Orden a Crédito"
- Complete Sale Order "Orden de Almacén"
- Proces Orders in Batch "Process Order" Smart Browser
- Generate Invoice from Order Lines (SmartBrowser)
- Generate Shipment from Order Lines (SmartBrowser)
- Complete Invoice
- Void Invoice with correct adjustment in Invoice Quantities of the Order Line
- Void Shipment with correct adjustment in Invoice Quantities of the Order Line

POS

- Generate Pos Order from POS
- Look for order (History Records)
- Look for Business Partner OK
- Pos Bank Statemnt Close
- POS Withdrawal
- Reverse the sales transactions


Purchase
- Complete Purchase Order
- Complete Invoice from Purchase Order
- Generate recipt from Order
- Generate Invoice From Reciept by "Create Invoice from Recipt"


Payment 

- Compelte Payment ok
- Generate Payment from Invoice AP OK
- Payment Alocation (Form) ok

- Bank Statement ok
- Create Line in Bank Statement
- Create Payment from Bankstatemnt Line
- Create Payment with Charge from Bankstametent Line
- Control line with no Payment when you try to complete the Bankstatement

Payment Selection

- Create Payment Selections from Invoice
- Create Payment Selections from Payment Selection
- Create Payment from Payment Selection with the Payment Print/Export

Accounting

- Trial Balance ok
- Financial report OK
- Trial Balance Drillable Report Ok


Reports

- Order Detail OK
- Open Items ok
- Aging with payments (revalued) OK
- Dunning Run OK
-

**Review by marcalwestf — APPROVED** [review]
- several workflows have been tested
- different users have carried out tests without errors

Test passed.

**Pull request merged**
