### PR TITLE
Add Microsoft Azure Authentication

### PR DESCRIPTION
**Pull request by carlosaparadam**
# Microsoft Azure Authentication

- [Create an Application Registration with Application Support  **Microsoft Azure Authentication**](#application-registration)
- [Setting the Parameters](#setting)
- [Logout for view Login with Azure](#login)
- [Documentation References](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols)

## Application Registration
image

## Setting  

| Parameter | Value | 
| - | - |
| Redirect URI | `http://adempierehost/webui` |
| Client ID | `<Client Identifier>` |
| Secret | `<Client Secret>` |
| Issuer | [Issuer Setting](#issuer-setting)|

## Issuer Setting

| Value | Help | 
| - | - |
| `common` | for both Microsoft accounts and work or school accounts | 
| `organizations` | for work or school accounts only | 
| `consumers` | for Microsoft accounts only| 
| `<<Tenant ID>> or example.com` | the tenant ID or domain name |

## Login
image

### CODE REVIEW

**Comment by rcapecce** [comment]
Testing of this functionality is performed.

Microsoft Azure application is configured in portal.azure.com
From there ClientID, Secret, Issuer is obtained and RedirectURL is configured to ADempiere instance (must be with https and ssl configured) to configure in AppRegistration.

The instance is restarted and it is observed that in the Login the link to access with Microsoft Authenticator is now displayed

Peek 2023-06-21 10-43

If you are not logged into your account through Microsoft, you will be redirected to the Microsoft login to later login to ADempiere

**Review by rcapecce — APPROVED** [review]
This functionality was tested in this comment https://github.com/adempiere/adempiere/pull/4020#issuecomment-1600901130
https://github.com/adempiere/adempiere/pull/4020#issuecomment-1600901130

**Review by niclopup — APPROVED** [review]
OK

**Comment by e-Evolution** [comment]
Hello @carlosaparadam Carlos, you can modify the release of the XML from 3.9.4 to 3.9.5, and create a new directory migration/394lts-395lts, in this way I can merge this code

**Comment by carlosaparadam** [comment]
Hi @e-Evolution Victor, the changes requested has been made

**Comment by e-Evolution** [comment]
The functionality has been tested and is working.

**Pull request merged**
