### PR TITLE
Add Financial Management integration for ADempiere Core

### PR DESCRIPTION
**Pull request by yamelsenih**
This is a grat pull request with a functionality tested for a customer. The project is ADempiere Loan Management but the definition is for support a financial management like bank, loan and other.

Screenshot_20190628_113048

This have support to interest calculation based on [Rule 78s](https://en.wikipedia.org/wiki/Rule_of_78s)

Fixes: #1857
Fixes: #1848
Fixes: #1847
Fixes: #1726
Fixes: #1703
Fixes: #1698
Fixes: #1696
Fixes: #1693
Fixes: #1692
Fixes: #1691
Fixes: #1686
Fixes: #1681
Fixes: #1680
Fixes: #1678
Fixes: #1666
Fixes: #1663
Fixes: #1647
Fixes: #1644
Fixes: #1616
Fixes: #1599
Fixes: #1589
Fixes: #1588
Fixes: #1587
Fixes: #1586
Fixes: #1585
Fixes: #1583

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih  can you please give us a rough description of how to test this seemingly big functionality ?
How to start, and then step by step how to proceed.
Thanks.

**Comment by yamelsenih** [comment]
Off course right now I add this

**Comment by yamelsenih** [comment]
> @yamelsenih can you please give us a rough description of how to test this seemingly big functionality ?
> How to start, and then step by step how to proceed.
> Thanks.

Hi @marcalwestf please see this complete manual created by @wdtz : 
[Requerimientos](https://docs.erpya.com/adempiere/vertical/loan-management/loan-requirements/)
[Ejecución](https://docs.erpya.com/adempiere/vertical/loan-management/loan-running/)
[Préstamo](https://docs.erpya.com/adempiere/vertical/loan-management/loan/)
[Generar Selección de Pagos
](https://docs.erpya.com/adempiere/vertical/loan-management/generate-payment-selection/)
[Generar Pago](https://docs.erpya.com/adempiere/vertical/loan-management/generate-payment/)
[Generar Factura](https://docs.erpya.com/adempiere/vertical/loan-management/generate-invoice/)

All users manual are in Spanish, is nice to have it for ADempiere as Spanish and English language, anybody is welcome to contribute

**Comment by yamelsenih** [comment]
[Here](https://docs.erpya.com/l) is all [ERPCyA](http://erpya.com/) docs

**Comment by marcalwestf** [comment]
@yamelsenih thanks a lot Yamel, luckily it is enough for me to have the documentation in Spanish and I will use it to test.

Nevertheless it would be great if somebody could translate it.

**Comment by eduardolopezuy** [comment]
@yamelsenih can you check the conflict with  the .classpath file?

**Comment by marcalwestf** [comment]
The branch cannot be tested under Windows: the git checkout fails.
Under Linux it works well.

I suppose, the error can be found in file _org.eclipse.wst.common.component_
Here there is an entry
`<wb-resource deploy-path="/WEB-INF/classes" source-path="/org.spin.loan_and_invesment_management /src/main/java/base"/>`

If you look well, in the value of the element _source-path_ a space is included: _org.spin.loan_and_invesment_management /src..._ .

When checking out the branch _feature/Financial-Management_ under Windows, an error message stating that the path _/org.spin.loan_and_invesment_management /src/main/java/base_ cannot be created is issued.

**Comment by yamelsenih** [comment]
Hi @marcalwestf this is updated and ready for review.

**Comment by marcalwestf** [comment]
@yamelsenih  Yamel, it seems there is still conflict with _.classpath_.

We will test anyway, but for accepting this pull request, the conflict has to be solved.

**Comment by yamelsenih** [comment]
This was resolved

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I have some observations regarding windows and processes.

- Special form Loan Simulator does not open (swing)

- In window Financial agreement the field __issotrx__ is not visible. In the field definition the display logic is Y, the default value is empty. I think it should be default value Y.

- To insert a capital amount you have to switch between the windows _agreement_ and _financial loan_.
In Financial Loan you can change the capital amount, but you have to generate the financial account first in the window financial agreement. In this window the capital amount is not visible.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon I will to add changes for merge
Best regard

**Comment by yamelsenih** [comment]
> Hi @yamelsenih
> I have some observations regarding windows and processes.
> 
> * Special form Loan Simulator does not open (swing)
Only for ZK (Swing is deprecated for it)
> * In window Financial agreement the field **issotrx** is not visible. In the field definition the display logic is Y, the default value is empty. I think it should be default value Y.
> * To insert a capital amount you have to switch between the windows _agreement_ and _financial loan_.
The capital amount can be used from form for it.
>   In Financial Loan you can change the capital amount, but you have to generate the financial account first in the window financial agreement. In this window the capital amount is not visible.
Capital amount is a functionality for loan and Financial Agreement is a generic window for any financial transaction

I will to hange IsSOTrx for it and resolve classpath conflicts

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon this is changed.

Best regard

**Pull request merged**
