### PR TITLE
GL Distribution doesn't work for any account

### LINKED ISSUE #3920: GL Distribution doesn't work for any account
## Feature request

GL Distributions Example 
image

If you define a different GL Distribution but only with other Dimension  in N and with the check of "Any Account" in Y, it doesn't work.

image

The reason of this is that right now it only look for the Account, and not for the other Dimensions in the Account Combination.

#### Describe the solution you'd like

The code must consider a GL Distribution defined to "ANY ACCOUNT" and with other dimensions defined.

### PR DESCRIPTION
**Pull request by nsarlabos**
Fixes #3920

### CODE REVIEW

**Comment by nsarlabos** [comment]
Hi @e-Evolution, can you tell me about the change you talked about with Nicolás López?

**Comment by e-Evolution** [comment]
@niclopup Nico , @SusanneCalderon Susanne 

please check this code line 

image

Can please check here the code , because should fix here not in the other class.

https://github.com/adempiere/adempiere/blob/758ed8bd791ed4c0d22c976beb1b2f2e49a76826/base/src/org/compiere/acct/Fact.java

**Comment by e-Evolution** [comment]
@niclopup the two important testing :

1.- Create a distribution with account.
2.- Create a distribution with same account and activity to testing multiples dimensions
3.- Both distributions  should work.

**Comment by nsarlabos** [comment]
Hi @e-Evolution 

I have tried to make the change in the "Fact.java", but I have the problem that it makes the distribution also for the accounts of the head (business partner of the head of the invoice), and the asset/liability accounts should not be distributed.

Please, I would be grateful if you could tell me exactly how the change to be made in the "Fact.java" would be, or if we see that perhaps an extra control should be added to avoid taking the accounts from the head of the document.

**Review by SusanneCalderon — APPROVED** [review]
@nsarlabos 
I tested to distribute Purchase Invoices to distribute to different cost centers (user1_ID) without problems.

**Comment by nsarlabos** [comment]
> @nsarlabos I tested to distribute Purchase Invoices to distribute to different cost centers (user1_ID) without problems.

@SusanneCalderon With this change we had some errors when posting invoices without accounting distribution

**Comment by marcalwestf** [comment]
@nsarlabos  can you tell us the status of this PR?

It is not completely clear if it works now, or if you found an error.
Thanks.

**Comment by yamelsenih** [comment]
Hello @nsarlabos  can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by yamelsenih** [comment]
Hello @nsarlabos here a complete refactory for this: https://github.com/adempiere/adempiere/pull/3963

**Comment by nsarlabos** [comment]
> Hello @nsarlabos here a complete refactory for this: #3963

Hi @yamelsenih, so #3963 would be the correct fix? If so we can test it.

In that case I understand that this pull request should be closed.

**Comment by yamelsenih** [comment]
> > Hello @nsarlabos here a complete refactory for this: #3963
> 
> Hi @yamelsenih, so #3963 would be the correct fix? If so we can test it.
> 
> In that case I understand that this pull request should be closed.

Hi @nsarlabos off course, please test the PR and let us if is ok.

I will to close it

**Pull request closed without merging**
