### PR TITLE
#1697 Add row style change

### LINKED ISSUE #1697: Add definition for change style
It is for add a new definition or E-R diagram with ADempiere changes

### LINKED ISSUE #1709: Add Need to change the style of the field editors
It allows define a custom style for a element on ZK interface.

### LINKED ISSUE #1710: Add gridfield support for new column AD_FieldDefinition_ID
This allows to obtain the field condition definition to change the style of the field

### PR DESCRIPTION
**Pull request by yamelsenih**
Hi Guys We have a new feature for add style for rows in ADempiere, please review it.

Issues: 
- fixes #1697
- fixes #1710
- fixes #1709 

This project is created for define distinct field style.

The ADempiere field is very static and it does not show distinct behavior when exist important values for end user.

With field style definition a user will can see a field with a distinct Style if a little condition is apporved, example:

We want change color of Document No when delivered quantity is less of ordered quantity

Document No | Quantity Order | Quantity Delivered
-------------------|---------------------|-----------------------------
:red_circle:#001 | 10 | 5|
:large_blue_circle:#356 | 15 | 15|

Here is the E-R Diagram:
changestyledefinition

### CODE REVIEW

**Comment by marcalwestf** [comment]
Hi @yamelsenih how would the different configuration scenarios look like?
Thanks

**Comment by marcalwestf** [comment]
Names and sequences don't match: 
File _04000_1697_AddColumnFieldDefinition.xml_ has SeqNo="3790". It should be **4000**.
File  _04010_1697_AddWindowFieldDefinition.xml_ has SeqNo="3800". It should be **4010**.

**Comment by marcalwestf** [comment]
...also in _04000_1697_AddColumnFieldDefinition.xml_ the reference to the issue is missing.

**Comment by marcalwestf** [comment]
Testing on a seed database up to _03910_1704_FixedAssetBalanceSmartBrowser.xml_.

XML _04000_1697_AddColumnFieldDefinition.xml_ loaded and applied.

XML _04010_1697_AddWindowFieldDefinition.xml_ loaded, but when applied, the following error message appears:
20180827_windowcolumnfielddefinition_01

Haven't found the cause yet, but I suppose -it has happened already in older XMLs- that when defining columns which later are used for window definitions, in the window definition the column is not known because the commit is issued at the end of the XML.

The error here pops up when as a consequence of the unknown reference, the step is rolled back, but fails because is is already referenced.

Will see into it later and report.

**Comment by marcalwestf** [comment]
... it requires the Quick Entry XMLs....so the earliest XML has to be _03921_1088_Add_Column_IsQuickEntry.xml_

**Comment by marcalwestf** [comment]
The migration of file _04010_1697_AddWindowFieldDefinition.xml_ works by splitting it in two parts:
- the first part from step **10** to **360**, which includes definition of Element and Column
- the second part from step **370** to **1360**.

Confirming the previously stated supposition: **when defining a column which is later used in the window definition, the XML of defining column and field has to be splitted in a column definition section and a field definition section**.

**Comment by marcalwestf** [comment]
After executing the XMLs, a  field is displayed in the Application Dictionary, at the "Field" tab of any Window definition:
20180827_windowcolumnfielddefinition_04a


But it is not possible to zoom it (the zoom icon is dim), because in the table **AD_FieldDefinition**, there is no window defined for this table. The table has to be configured to be related to the window as the following image depicts:
20180827_windowcolumnfielddefinition_05a

After correcting the table, the zoom icon is eligible. However, when selecting the _zoom_ icon, an error message is displayed:
20180827_windowcolumnfielddefinition_06


.... looking at the role definition for **SystemAdministrator**, the window _Field Definition_ is not allowed:
20180827_windowcolumnfielddefinition_07a

Once that done, the window _Field Definition_ is displayed and edited:
20180827_windowcolumnfielddefinition_08

**Comment by marcalwestf** [comment]
... now at last, I can proceed to test...

**Comment by marcalwestf** [comment]
This is how the window _Field Definition_ looks like:
20180827_windowcolumnfielddefinition_09

Observations:
- How does the condition have to look like?
Is it an SQL? Can the environment syntax be used? etc. etc.
- Same with stylesheets: which can be used?
A good starter good be to enumerate the possible choices in the help section of the window definition.

**Comment by marcalwestf** [comment]
..when trying to save a condition, this is the result:
20180827_windowcolumnfielddefinition_10

And the error at the console:

> ===========> MSequence.getNextID: No record found - AD_FieldCondition [18]
> ===========> MFieldCondition.saveNew: No NextID (-1) [18]
> -----------> GridTable.saveWarning: SaveError -  [18]

I suppose the sequence was not created.

**Comment by marcalwestf** [comment]
and a last observation: it would be of great help it there was an example for GardenWorl of how to use it.

**Comment by marcalwestf** [comment]
here an example of how the configuration goes, kindly provided by Nicolas Lopez ( @niclopup ) : https://www.youtube.com/watch?v=8xS04fCx5Rg&feature=youtu.be

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
I have 2 observations:

- The XML _04010_1697_AddWindowFieldDefinition.xml_ creates en error at seqNO 350. When you move the steps =>350 into a new migrationfile it runs without problems.

- The tables _AD_FieldDefinition_ and _AD_FieldCondition_ have entitytype _spinConstribution_, which has modelpackage _org.spin.model_. The classes _MFieldCondition_ and _MFieldDefinition_ are generated in package _org.compiere.model_, which leads to the error _classnotfound_.

Correcting these points everything runs without problems.

**Comment by SusanneCalderon** [comment]
Example: Name of Business Partner is red when open amount > 500
imagen

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon i will change it, thank you for it revision

**Comment by yamelsenih** [comment]
I will to create a new Pull request for habdle a clear commit

**Comment by yamelsenih** [comment]
Please see it https://github.com/adempiere/adempiere/pull/2055

**Pull request closed without merging**
