### PR TITLE
Add Support to Accounting by Document Base Type

### PR DESCRIPTION
**Pull request by carlosaparadam**
## Purposed Changes

- Document Base Type Window
- Document Base Type field on Document Type

## Document Base Type Added

| Document Base Type | Table | Accounting Class Name | Entity Type | 
| ----------- | ----------- | ----------- | ----------- |
| AP Credit Memo | C_Invoice | org.compiere.acct.Doc_Invoice | Dictionary |
| AP Invoice | C_Invoice | org.compiere.acct.Doc_Invoice | Dictionary |
| AP Payment | C_Payment | org.compiere.acct.Doc_Payment | Dictionary |
| AP Payment Selection | C_PaySelection |  | Dictionary |
| AR Credit Memo | C_Invoice | org.compiere.acct.Doc_Invoice | Dictionary |
| AR Invoice | C_Invoice | org.compiere.acct.Doc_Invoice | Dictionary |
| AR Pro Forma Invoice | C_Invoice |  | Dictionary |
| AR Receipt | C_Payment | org.compiere.acct.Doc_Payment | Dictionary |
| Attendance Record | HR_AttendanceBatch |  | Spin Contribution (Time and Attendance Record) |
| Bank Statement | C_BankStatement | org.compiere.acct.Doc_BankStatement | Dictionary |
| Cash Journal | C_Cash | org.compiere.acct.Doc_Cash | Dictionary |
| Distribution Order | DD_Order | org.compiere.acct.Doc_DDOrder | e-Evolution Libero Manufacturing Management |
| Financial Agreement | FM_Agreement |  | Investment and Loan Management System |
| Financial Transaction Batch | FM_Batch |  | Investment and Loan Management System |
| Fixed Assets Addition | A_Asset_Addition |  | Dictionary |
| Fixed Assets Depreciation | A_Depreciation_Entry |  | Dictionary |
| Fixed Assets Disposal | A_Asset_Disposed |  | Dictionary |
| Fixed Assets Split | A_Asset_Split |  | Dictionary |
| Freight Order | DD_Freight |  | Spin Contribution |
| GL Document | T_InvoiceGL |  | Dictionary |
| GL Journal | GL_Journal | org.compiere.acct.Doc_GLJournal | Dictionary |
| HR Incidence | HR_Incidence |  | Spin Contribution (Time and Attendance Record) |
| Leave Request | HR_Leave |  | Spin Contribution (Time and Attendance Record) |
| Maintenance Order | PP_Order |  | e-Evolution Libero Manufacturing Management |
| Manufacturing Cost Collector | PP_Cost_Collector | org.compiere.acct.Doc_PPCostCollector | e-Evolution Libero Manufacturing Management |
| Manufacturing Order | PP_Order | org.compiere.acct.Doc_PPOrder | e-Evolution Libero Manufacturing Management |
| Manufacturing Planned Order | M_ProductionBatch |  | Dictionary |
| Match Invoice | M_MatchInv | org.compiere.acct.Doc_MatchInv | Dictionary |
| Match PO | M_MatchPO | org.compiere.acct.Doc_MatchPO | Dictionary |
| Material Delivery | M_InOut | org.compiere.acct.Doc_InOut | Dictionary |
| Material Movement | M_Movement | org.compiere.acct.Doc_Movement | Dictionary |
| Material Physical Inventory | M_Inventory | org.compiere.acct.Doc_Inventory | Dictionary |
| Material Production | M_Production | org.compiere.acct.Doc_Production | Dictionary |
| Material Receipt | M_InOut | org.compiere.acct.Doc_InOut | Dictionary |
| Package | M_Package |  | Spin Contribution |
| Payment Allocation | C_AllocationHdr | org.compiere.acct.Doc_AllocationHdr | Dictionary |
| Payroll | HR_Process | org.compiere.acct.Doc_HRProcess | e-Evolution Libero Human Resource & Payroll |
| Project Issue | C_ProjectIssue | org.compiere.acct.Doc_ProjectIssue | Dictionary |
| Purchase Order | C_Order | org.compiere.acct.Doc_Order | Dictionary |
| Purchase Requisition | M_Requisition | org.compiere.acct.Doc_Requisition | Dictionary |
| Quality Order | PP_Order |  | e-Evolution Libero Manufacturing Management |
| Sales Commission | C_CommissionRun |  | Dictionary |
| Sales Order | C_Order | org.compiere.acct.Doc_Order | Dictionary |
| Warehouse Management Order | WM_InOutBound |  | e-Evolution Libero Warehouse Management |

## Behavior

With this feature there is the possibility that custom posted by one especifically document type, without change or patches the accounting process of ADempiere core, see this example:

- [Create a copy of Doc_Invoice and change the accounting behavior](#copyClass)
- [Build the project](#buildProject)
- [Create a Document Base Type, setting accounting class name with the class customized](#settingDocBaseType)
- [Create a Document type with the Document Base type created](#settingDocType)
- [Create a Document with the Document type created and see accounting](#createDocument)

## <a name="copyClass">Create a copy of Doc_Invoice and change the accounting behavior</a>
copyClass

## <a name="buildProject">Build the project</a>
buidProject

## <a name="settingDocBaseType">Create a Document Base Type, setting accounting class name with the class customized</a>
settingDocBaseType

## <a name="settingDocType">Create a Document type with the Document Base type created</a>
settingDocType

## <a name="createDocument">Create a Document with the Document type created and see accounting</a>
createDocument

### CODE REVIEW

**Comment by e-Evolution** [comment]
@carlosaparadam Hi Carlos, now I understand the proposal better and it seems like a good improvement.

I have some concerns that I cannot see their implementation in your changes.

How are the default base documents created for each type of document?

Are they created as System Administrator?

Are they created by each Company/Client?

When a Company/Client is created does it consider the configuration of the base document types?

kind regards
Victor

**Comment by carlosaparadam** [comment]
@e-Evolution hi Victor, 

The Document Base Types were created as System Administrator and the Document Base Type field were update in the Document Types entity in migration script 07690_Add_Document_Base_Type_Data.xml. 

When a Company/Client is created does'n it consider the configuration of the base document types because the default document base type has been defined as as System Administrator.

**Comment by e-Evolution** [comment]
@carlosaparadam Hi Carlos 

Please adding factory patterns to create the instance for each document.

Here can see some implementation

WMS Engine
 https://github.com/adempiere/adempiere/tree/b039ad16f3fb20ef277347dd37cb2e05bdc2c680/org.eevolution.warehouse/src/main/java/base/org/eevolution/engine/warehouse

Freight Engine
https://github.com/adempiere/adempiere/tree/b039ad16f3fb20ef277347dd37cb2e05bdc2c680/org.eevolution.freight/src/main/java/base/org/eevolution/engine/freight

On other hand, change the direct use of Optional.ofNullable(importPayrollMovement.getProcessName()) by declare values using the prefix maybe, and use lamda function or map , flapmap , here examples

https://github.com/adempiere/adempiere/blob/3f56f6d48d2e1343e9529a61dcc91c2f4845c7b1/org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/ImportPayrollMovements.java#L85

https://github.com/adempiere/adempiere/blob/826f1179e13f4123af615876b966c5d82cafd994/org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java#L237

https://github.com/adempiere/adempiere/blob/b039ad16f3fb20ef277347dd37cb2e05bdc2c680/org.eevolution.warehouse/src/main/java/base/org/eevolution/engine/warehouse/WMRuleEngine.java#L411

kind regards
Victor

**Comment by carlosaparadam** [comment]
@e-Evolution Hi Victor,

The requested changes is doit

Regards

**Comment by e-Evolution** [comment]
@carlosaparadam can please resolve the conflicts to merge this great feature.

On the other hand I merge the contribution the @mckayERP and refactor the Accounting Engine , please check and review and you should are sure that your change are compatible with this new refactory.

kind regards
Victor

**Comment by carlosaparadam** [comment]
@e-Evolution Hi Victor,

The requested changes is doit

Regards

**Comment by marcalwestf** [comment]
@e-Evolution hi Victor, is this pull request eligible for acceptance?
Thanks

**Comment by e-Evolution** [comment]
@carlosaparadam Hi Carlos

Hi Carlos, I have reviewed your contribution and found the following.

1.- When I create a new company, the base document type seems empty, although it is mandatory, although I understand that now DocBaseType stepped into making an identifier, this should be set by default when creating a new company

image

image


2.- On the other hand, if DocBaseType was moved to its own C_DocBaseType table to define there by default which class will be used to handle the accounting behavior for each document, I have some doubts.

What about all the dependencies that exist in the code for DocBaseType, I have checked in the code and there is no re factory to use the new table now.?

image

A clear example is C_PeriodControl where DocBaseType vs C_DocBaseType is still used and a lot of lines of code that refer statically to DocBaseType.

image


If at any time the C_DocBaseType_ID of the document does not match the DocBaseType defined in the table vs the document type, the system will behave in a strange and erratic way.

What happens with new documents, which value is saved in DocBaseType, since this is a mandatory field that is linked to multiple behaviors and business logic, but the field was hidden?

What will happen to all the legacy code that references DocBaseType?

The only idea would be to use C_DocBaseType and C_DocBaseType_ID to set DocBaseType but not remove it from C_DocType we can set  DocBaseType as read-only and have it set when C_DocBaseType_ID is set so as not to make a very large re factory, this can be implemented in the callout or beforeSave of the table C_DocType.

When I try to re-post any document I get the following error:

[INFO] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 2, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> AdempiereDS, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1hgeas1aiop4t0e128qek|273e7444, idleConnectionTestPeriod -> 1200, initialPoolSize -> 1, jdbcUrl -> jdbc:postgresql://0.0.0.0:55432/adempiere?encoding=UNICODE, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 900, maxIdleTimeExcessConnections -> 1200, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 1, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> SELECT Version FROM AD_System, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1458)
	at org.compiere.process.DocumentEngine.postImmediate(DocumentEngine.java:1385)
	at org.compiere.apps.AEnv.postImmediate(AEnv.java:954)
	at org.compiere.acct.AcctViewer.actionRePost(AcctViewer.java:932)

kind regards 
Victor

**Comment by e-Evolution** [comment]
Reviewing I found another problem where the base document types exist some that do not have their class for accounting even though there is a class for the document ie Doc_AssetAddition.

image

image

kind regards
Victor

**Pull request merged**
