### PR TITLE
#1672, Add new currency for Venezuela VES, reference to issue:

### PR DESCRIPTION
**Pull request by yamelsenih**
https://github.com/adempiere/adempiere/issues/1672

It is a new ISO for Venezuela currency

### CODE REVIEW

**Comment by marcalwestf** [comment]
XML imported and applied:
20180815_currency_bs_01

**Comment by yamelsenih** [comment]
Hi @marcalwestf your request is done yet.

Best regard

**Comment by marcalwestf** [comment]
the sequence number in the XML file has to be in accordance to the file name:
20180815_currencu_bs_02

**Comment by yamelsenih** [comment]
It is ready @marcalwestf best regard

**Pull request merged**
