### PR TITLE
this implements issue #1577 - a pdf viewer using icepdf

### PR DESCRIPTION
**Pull request by homebeaver**
-  the first step to replace old jpedal.jar version "3.00b21STD" from 30.01.2007. I replace it with icepdf 6.2.2 - there is a brand [new 6.3 release](https://www.icesoft.com/major-release-icepdf-6-3-0-arrived/), but not as a jar in mvnrepository, where this jars are from
- in a quick and dirty form I've replaced the code in PDFViewerBean - mostly delete unnecessary stuff, because icepdf has its own toolbar with features we need 
- here the old toolbar and the new to compare:

grafik

grafik

- while testing I detect that FitWidthButton-action runs out of memory. To avoid this I do not show the fit-Buttons.
- another test : attachments are not shown directly when window is build : the reason is the `pack();` -stmt in `Attachment.displayData()` which is unnecessary. Solved and committed [here](https://github.com/adempiere/adempiere/pull/1576#commits-pushed-df1020a)

### CODE REVIEW

**Comment by homebeaver** [comment]
@e-Evolution - ready for testing

**Comment by yamelsenih** [comment]
Hi @homebeaver it pull request depend of https://github.com/adempiere/adempiere/pull/1576

I will waiting for changes for merge

**Comment by homebeaver** [comment]
Hi @yamelsenih , with #1817 you have merged
this should compile now. Bye

**Comment by yamelsenih** [comment]
please update it from develop branch for test

**Comment by homebeaver** [comment]
@yamelsenih 
merged and added the two icepdf jars :-)

**Comment by homebeaver** [comment]
@yamelsenih done :-)

**Comment by yamelsenih** [comment]
Nice

**Pull request merged**
