### PR TITLE
Feature/#3732 add gradle support

### LINKED ISSUE #3732: [Feature Request] Handle adempiere project with gradle
## Feature request

At this time, adempiere requires configuring sources and dependencies for IntelliJ on the one hand and Eclipse on the other hand (and also for the rest of the IDEs that are used).
It is intended to incorporate Gradle to make the management of sources and dependencies transparent to the IDE

### PR DESCRIPTION
**Pull request by rcapecce**
Resolve #3732

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @rcapecce can you please add a library fromm maven central instead?
https://github.com/adempiere/adempiere/pull/3867/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R46

**Comment by rcapecce** [comment]
Hi @yamelsenih, I uploaded the change to resolve the library from the maven repositories

**Comment by e-Evolution** [comment]
@rcapecce please can solve the conflict this branch and @yamelsenih can review the change to gradle

**Comment by yamelsenih** [comment]
Hello, the conflict will be resolved?

**Comment by yamelsenih** [comment]
Hello @rcapecce can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by niclopup** [comment]
we close this issue to analyse it better

**Pull request closed without merging**
