### PR TITLE
adempiere Payselection for Bank Transfers. Charge is not copied. PayAmt>Open Amount for invoices

### PR DESCRIPTION
**Pull request by SusanneCalderon**
Fixes https://github.com/adempiere/adempiere/issues/2995

### CODE REVIEW

**Comment by e-Evolution** [comment]
@SusanneCalderon , My comments below :

about the #2995 I need to check with detail the code, but @yamelsenih created this functionality to transfer money between banks from the pay selection line, so I think that was testing before, Why should change, @yamelsenih do you think the need of charge?

about the #2995 I need to check with detail the code, but @yamelsenih created this functionality to transfer money between banks from the pay selection line, so I think that was testing before, Why should change, @yamelsenih do you think the need of a charge?

about #2997, I think that no is a good idea or practice allow pay an invoice for mayor amount that open amount, this can cause fraud or embezzlement for any company.

I have not any  business case where allow a payment mayor of open amount for an Invoice is ok, anyone would say it's a bug

**Comment by yamelsenih** [comment]
Hi everyone

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon I suggest the follow change:

Keep the follow code or implement a flag for Payment selection document for allows pay document with over amounts:
```Java
if (getC_Invoice_ID() > 0 && getOpenAmt().subtract(getPayAmt()).subtract(getDiscountAmt()).signum() < 0 )
			throw new AdempiereException("@PayAmt@ > @C_Invoice_ID@ @Amount@ @OpenAmt@ ");
```
Also I agree with solucion for issue:#2995 but I think that is better if you create two pull request: one for bugfix of charge for bank transfer and other for feature of pay selectionj for AP document with over amount

**Comment by SusanneCalderon** [comment]
@yamelsenih 
OK, I will generate two pull requests.

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih , @e-Evolution 
I reverted the modification in MPayselectionLine, now the commit only includes issue 2995.
@e-Evolution , the over amount is precisely what our newest customer wants.

**Pull request merged**
