### PR TITLE
#3987 [Feature Request] Synchronize Entity Type https://github.com/ad…

### PR DESCRIPTION
**Pull request by e-Evolution**
…empiere/adempiere/issues/3987

#3987 fixed

### CODE REVIEW

**Review by marcalwestf — CHANGES_REQUESTED** [review]
- git pull
- open Adempiere swing as to load and apply the XML files
- an error is thrown:
imagen

- looking at the DB, I notice that for the class **FixedAsset** the code defines the package **org.compiere.asset.model.validator** whereas the database expects a model validator **org.compiere.FA.model.ModelValidator** .
imagen

Perhaps the refactoring was done after testing the functionality, but it was not tested after the last commit.

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario 

The Fixed Asset Package was moved from org.compiere.FA to org.compiere.asset was one of the things I had requested in PR from @yamelsenih  which I did as it was not included.

So if you want to test this functionality you must generate the database seed again , since the fixed assets functionality refactory XML was changed , if you generate your seed again you should not have any problems , use RUN_MigrateXML.sh to perform this task

**Comment by marcalwestf** [comment]
I find the error here:
imagen

**Comment by marcalwestf** [comment]
ahhh ok Victor, thanks.
I will create the new seed and test on it.

**Review by marcalwestf — CHANGES_REQUESTED** [review]
Swing does not work either from the installation or from the IDE:
imagen

imagen

ZK works.

**This error is not caused by the changes in this pull request**.
Rather, it is caused by changes done before: I tested this and other pull requests and they also do not work on Swing.

@e-Evolution , @yamelsenih , @niclopup  et al, please confirm if you can reproduce the error, and if you can reproduce it, perhaps you help find out the pull request which causes the error.

I will continue to try out and document it on this thread.

**Comment by e-Evolution** [comment]
> Swing does not work either from the installation or from the IDE: imagen
> 
> imagen
> 
> ZK works.
> 
> **This error is not caused by the changes in this pull request**. Rather, it is caused by changes done before: I tested this and other pull requests and they also do not work on Swing.
> 
> @e-Evolution , @yamelsenih , @niclopup et al, please confirm if you can reproduce the error, and if you can reproduce it, perhaps you help find out the pull request which causes the error.
> 
> I will continue to try out and document it on this thread.

@marcalwestf the image show that not exists the AD_System table , this only happen when the database have not ADempiere a valid connection or RUN_ImportAdempiere.sh not was executed , so check first that the connection si valida and the the AD_System table exist.

**Comment by marcalwestf** [comment]
@e-Evolution  Víctor, thanks for your hinh. I found the error.
For some weird reason I haven't investigated yet, after executing RUN_ImportAdempiere.sh and RUN_Migrate_XML.sh, the database had the schema "postgres", instead of "adempiere.

After running the command
`ALTER SCHEMA postgres RENAME TO adempiere`
I can run Swing...

Does it happen to you or can you imagine why It happened.
It run it twice and both times, the schema was "postgres".
Perhaps I must drop the database first... I'll check out and document it here....

**Comment by marcalwestf** [comment]
The process  "Synchronize Entity Type" seems not to have defined the Data Access  Level:
imagen

**Comment by e-Evolution** [comment]
> The process "Synchronize Entity Type" seems not to have defined the Data Access Level:
> imagen

@marcalwestf Than you , Mario , I fixed to Only System

kind regards
Victor

**Review by marcalwestf — APPROVED** [review]
- Build -> OK
- XML load and apply -> OK
- Check process and parameters -> OK
- Check code -> OK
- Check window, process etc:

imagen

Check results -> OK
The entity type of the window, process etc. was changed accordingly to the parameter selected.

Notes:
- id changes recursively menu objects
- it doesn't change recursively inside an object. It only changes the selected object.
  This means for the window, the process changes the window, tab, and fields, but not the table and column.

Tests passed

**Pull request merged**
