### PR TITLE
Calculate for Not Realized Gain / Loss for Account Element Multi-Currency #2354

### PR DESCRIPTION
**Pull request by e-Evolution**

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @e-Evolution can you add a gif or step by step for test this functionality or reproduce the bug?

Also the change make conflicts with current branch.

You can do the follow:
- Create a new Branch from develop
- Compare and merge changes manual
- Create a new pull request from new branch
- Close it with reference to new PR

Best regard

**Comment by yamelsenih** [comment]
Hi @e-Evolution this pull request make conflicts with trunk, can you change It?

**Comment by yamelsenih** [comment]
Also can you please create a Step by Step or a gif with each step for replicate it?

Best regard

**Comment by yamelsenih** [comment]
Hi @e-Evolution please make a new pull request with 1 commit instead of 3, it make the pull reques tmore atomic 
Best regard

**Comment by e-Evolution** [comment]
replace with  #2505

**Pull request closed without merging**
