### PR TITLE
feature/#1088_Quick_Sheet

### PR DESCRIPTION
**Pull request by yamelsenih**
See: https://github.com/adempiere/adempiere/issues/1088
Hi everybody, this is a new fuctionality for handle quick sheet.

Please take a time for review it.

Best regard.

### CODE REVIEW

**Comment by marcalwestf** [comment]
Hi, I've been ivolved in the testing of the requesting branch.
Now, I'm goin to test the pull request.....

**Comment by marcalwestf** [comment]
The file migration/**380lts-390lts/03000**_1088_Add_Column_IsQuickEntry.xml has to be renamed to migration/**390lts-391/03920**_1088_Add_Column_IsQuickEntry.xml.

03920 is the actual sequence; depending on whether there has been another pull request, it should be eventually changed.

**Comment by marcalwestf** [comment]
... comparing ADTabPanel.java from the requesting repository with Adempiere's repository, the merging conflicts can IMO solved by just adopting the differences.

**Comment by marcalwestf** [comment]
.... accotdingly, the header of _....Add_Column_IsQuickEntry.xml_ file should be changed to
```
<Migration EntityType="D" Name="QuickEntry" ReleaseNo="3.9.1" SeqNo="3920">
 <Comments>See: https://github.com/adempiere/adempiere/issues/1088</Comments>
```

**Comment by marcalwestf** [comment]
... still in the XML file, there must be entries for translations

**Comment by marcalwestf** [comment]
... moreover in the XML file, the View _ad_field_v_ is changed.
It has to be changed also for Oracle and the changes also documented in _ddlutils/../views_.

**Comment by marcalwestf** [comment]
.. again in the XML, the definition of column _isQuickEntry_ in table _AD_Field_ must such that the default value equals **N**.
Right now it is not defined, so it defaults to NULL. 

Additionally, the already existing fields must -via SQL- be set to N (for example in Postgres):
`update adempiere.ad_field set isquickentry='N'`
Otherwise, there is an error when saving.

**Comment by marcalwestf** [comment]
thanks @Raul-mz I will do the whole testing again....

**Comment by marcalwestf** [comment]
Checked out branch _feature/develop_QuickSheet_ and executed all XMLs.

After having finished the XML execution, I proceeded to configure the Quick Sheet for Sales Order Lines.
When trying to save the first field, an error was prompted:
20180726_quicksheet_02



The error on the console when trying to save is
_-----------> GridTable.saveWarning: SaveErrorDataChanged - isQuickEntry= false(java.lang.Boolean) != DB: null -> New: true(java.lang.Boolean)_ 

When executing the SQL
`update adempiere.ad_field set isquickentry='N'`
the error when saving disappears.

**Comment by marcalwestf** [comment]
... actually this seems to be an error from Adempiere.
I don't understand why if there is a null value and you want to set it to true (in the database =N) it is considered an error.

Perhaps there is a deeper meaning behind it?

**Comment by yamelsenih** [comment]
Hi @marcalwestf for now we can change default value for it

**Comment by marcalwestf** [comment]
ok. I'd say then do please change the default value and I'd proceed to accept the pull request.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is solved yet

**Comment by marcalwestf** [comment]
...testing ....

**Comment by marcalwestf** [comment]
... checked out and XMLs executed.
Now it is possible to configure the Quick Sheet for fields.
I will start testing the functionality.

**Comment by marcalwestf** [comment]
... perhaps as a small improvement: the icon for launching the Quick Sheet in the icon bar (the one at the outmost right) is depicted in the "not available" modus. 

Users do expect a full drawn icon when Quick Sheet is available and the present one when not available.

See screenshot:
20180730_quicksheet_01

**Comment by marcalwestf** [comment]
A helper for testing without much clicking:

How to open Quick Sheet Dialog

- Open dialog with only one new record
- Open dialog with all existing records



Buttons
- F10: Open Quick Entry Dialog
- F2: New record
- ENTER at row end: New record
- ENTER inside a row: edit column
- F3: Delete record
- F4: Save record
- F5: Refresh
- UP, DOWN, LEFT, RIGHT arrows: Function depends on context

- Shitf + ENTER: Navigate to prior column
- ESC: leave edit mode
- Ctrl + Q:	Close Quick Entry Dialog
- Ctrl + ENTER: Close Quick Entry Dialog

(Positive) Side effects: 
- Standard Grid can be navigated with arrows
- Fields of Standard Grid  can be edited with ENTER
- "Normal" Grid and Quick Entry dialog in sync 

**Preferrable to use newest browsers**

**Comment by marcalwestf** [comment]
**Functional test passed!!!**

Merge can be done right now, but if (just for completness sake) the icon issue I commented a couple of minutes before is to be changed, I can wait untill it is solved prior doing the merge of this pull request.

**Comment by Raul-mz** [comment]
@marcalwestf this is ready to try.

**Comment by marcalwestf** [comment]
thanks @Raul-mz ; test follow suit.....

**Comment by marcalwestf** [comment]
I suppose the commit has been done, but the push is missing.
The reason: if I checkout **remotes/origin/feature/develop_QuickSheet** and **feature/develop_QuickSheet**, I see differences, though it should be none.

Here the result after `git checkout feature/develop_QuickSheet`:
20180806_quicksheet_02
This is the result on the console:
```
git checkout feature/develop_QuickSheet
Switched to branch 'feature/develop_QuickSheet'
Your branch is behind 'origin/feature/develop_QuickSheet' by 3 commits, and can be fast-forwarded.
```



Wheras after `git checkout remotes/origin/feature/develop_QuickSheet`:
20180806_quicksheet_01

This is the result on the console:
```
Note: checking out 'remotes/origin/feature/develop_QuickSheet'.
You are in 'detached HEAD' state. You can look around, make experimental
```

**Comment by marcalwestf** [comment]
As I see that the repository was synchronized, I proceeded to testing.
The test was done on a seed database, parting from the latest XML (03910).

**Comment by marcalwestf** [comment]
When executing the file _03920_1088_Add_Column_IsQuickEntry.xml_ as it is on a seed up to XML 0390, there is an error at step 40:
20180807_quicksheet_01

The error is generated because in step 40 the field _isQuickEntry_ should be created for the tab _Field_ in the Application Dictionary, but in the database the column _isQuickEntry_ of table _AD_Field_ -needed for this step- doesn't exist.
And it doesn't exist because in step 30 the column isQuickEntry was created for the AD table _AD_Field_, **but not synchronized with the database**.

Evidently, the migration process synchronizes columns with the database at the end of the migration process.
Unluckily in this case, the synchronization is needed directly after step 30, but it dosen't occur then.
So the column is not synchronized and step 40 tries to create en entry for AD_Field which generates the error.

**The error can be avoided by splitting the XML file into two: the first containing steps 10 to 30; the second containing the other steps.**
Executing the so separated XML file in two chunks, it works.

**Comment by marcalwestf** [comment]
.... thanks @Raul-mz , now the XMLs are applied flawlessly and the translations are executed as well.
Now a short funtional test....

**Comment by marcalwestf** [comment]
all tests passed!

**Pull request merged**
