### PR TITLE
#2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields

### PR DESCRIPTION
**Pull request by marcalwestf**
Issue: https://github.com/adempiere/adempiere/issues/2467

### CODE REVIEW

**Comment by marcalwestf** [comment]
...additionally, I corrected the number of records found, which always yielded 0

**Comment by yamelsenih** [comment]
Hi @marcalwestf is nice if can be used String.split(',') instead
<pre>
value = value.replace(" ", "");
								String inStr = new String(value);
								StringBuffer outStr = new StringBuffer("(");
								int i = inStr.indexOf(',');
								while (i != -1)
								{
									outStr.append("'" + inStr.substring(0, i) + "',");	
									inStr = inStr.substring(i+1, inStr.length());
									i = inStr.indexOf(',');

								}
								outStr.append("'" + inStr + "')");
								//	BR [ 342 ]
								sql.append(field.ColumnSQL).append(" IN ")
								.append(outStr);
</pre>

**Comment by e-Evolution** [comment]
This pull request introducing an error

image

Execute Browser Sales Order:

image

===========> VBrowser.run: SELECT DISTINCT o.C_Order_ID AS O_C_Order_ID, bp.Name AS BP_Name, o.AD_Org_ID AS O_AD_Org_ID, o.M_Warehouse_ID AS O_M_Warehouse_ID, o.C_DocType_ID AS O_C_DocType_ID, o.DocumentNo AS O_DocumentNo, o.POReference AS O_POReference, o.C_BPartner_ID AS O_C_BPartner_ID, bp.SOCreditStatus AS BP_SOCreditStatus, o.SalesRep_ID AS O_SalesRep_ID, o.DateOrdered AS O_DateOrdered, o.DatePromised AS O_DatePromised, o.OrderType AS O_OrderType, o.IsSOTrx AS O_IsSOTrx, o.C_Currency_ID AS O_C_Currency_ID, o.TotalLines AS O_TotalLines, o.GrandTotal AS O_GrandTotal, o.AD_User_ID AS O_AD_User_ID, bp.C_BP_Group_ID AS BP_C_BP_Group_ID, o.C_BPartner_Location_ID AS O_C_BPartner_Location_ID, o.Bill_BPartner_ID AS O_Bill_BPartner_ID, o.Bill_User_ID AS O_Bill_User_ID, o.DocStatus AS O_DocStatus, o.InvoiceRule AS O_InvoiceRule, o.C_PaymentTerm_ID AS O_C_PaymentTerm_ID, o.PaymentRule AS O_PaymentRule, o.PriorityRule AS O_PriorityRule, o.DeliveryRule AS O_DeliveryRule, o.DeliveryViaRule AS O_DeliveryViaRule, o.M_Shipper_ID AS O_M_Shipper_ID, o.IsCreditApproved AS O_IsCreditApproved, o.IsApproved AS O_IsApproved, o.IsDelivered AS O_IsDelivered, o.IsInvoiced AS O_IsInvoiced, o.C_Campaign_ID AS O_C_Campaign_ID, o.C_Activity_ID AS O_C_Activity_ID, o.C_Project_ID AS O_C_Project_ID, o.C_POS_ID AS O_C_POS_ID FROM  C_Order o INNER JOIN C_BPartner bp ON (o.C_BPartner_ID=bp.C_BPartner_ID)  WHERE  1=1  AND o.AD_Org_ID=?  AND o.M_Warehouse_ID=?  AND o.IsSOTrx=?  AND o.DocStatus=?  AND o.C_Currency_ID=?  AND  lower( o.GrandTotal) >= ?  AND  lower( o.GrandTotal) <= ?  AND o.M_PriceList_ID=?  AND o.AD_Client_ID IN(0,1000000) AND o.AD_Org_ID IN(0,1000000) AND (o.C_Order_ID IS NULL OR o.C_Order_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 259 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (bp.C_BPartner_ID IS NULL OR bp.C_BPartner_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 291 AND AD_User_ID <> 100 AND IsActive = 'Y' )) [321]
org.postgresql.util.PSQLException: ERROR: function lower(numeric) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 1484; State=42883; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:654)

**Comment by marcalwestf** [comment]
...right
I forgot the last commit.
Now I'm putting it again

**Pull request merged**
