### PR TITLE
Improve Standard Request Type

### PR DESCRIPTION
**Pull request by yamelsenih**
- Add Subject field for predetermine on request
- Add support to **Year** as time unit
- Allows generate a Request with a document event without document type
and document status filter
- Add support to DateDoc column for set current date of request
- Add support to sales representative based on document

## How configure it?

Screenshot_20210505_115502

## How to see it?
Screenshot_20210505_115917

## A Example
Peek 2021-05-05 11-58

Please use **Squash and Merge**

### CODE REVIEW

**Review by mckayERP — APPROVED** [review]
OK as is.
Consider adding tests.  There are already tests for TimeUtil.java but not for the addDuration methods.  The RequestModelValidator and MStandardRequestType class would also benefit from tests.

**Comment by yamelsenih** [comment]
Thanks @mckayERP

**Review by marcalwestf — APPROVED** [review]
- Apply the XML file
- Do create a _Standard Request Type_ for table _M_In_Out_ as described
- Create a _Standard Request_ for the desired status
- Complete a _Sales Standard Order_
- Create a _Shipment_ out of an _Order line_
- Create a _Request_ out of the created _Shipment_
-  Result: a _Request_ is automatically created with all fields filled as defined in the _Standard Request Type_ -> **Test passed**

**Comment by marcalwestf** [comment]
as both @mckayERP  and myself have approved this PR, I will proceed to accept it.

**Pull request merged**
