### PR TITLE
#3902 [Bug Report] ADempiere WebStore login.jsp [${initParam.#AD_Clie…

### PR DESCRIPTION
**Pull request by e-Evolution**
…nt_ID}] contains invalid expression(s): https://github.com/adempiere/adempiere/issues/3902

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
- build an executable
- install with Oracle's JDK 17 and Jetty 10.07
- Run Application Server
- Log in as _SuperUser_
- Watch file _$ADEMPIERE_HOME/utils/nohup.err_

Result: the _jsp_ error reported disappeared

BUT:
1- a different error appeared in _$ADEMPIERE_HOME/utils/nohup.err_ :
 ` java.lang.IllegalArgumentException: Table Name Not Found - AD_QueueType`

Selection_196

By the way, this very error is also displayed when **installing with Tomcat**:
`===========> RequestProcessor.lambda$sendEmail$5: Table Name Not Found - AD_QueueType [22]`

2-  Moreover, when executing the process _Role Access Update_, the following error pops  up:
`org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block, SQL=SELECT IsActive,Updated,Created,IsDependentEntities,IsExclude,IsReadOnly,AD_Client_ID,AD_Org_ID,UpdatedBy,AD_Table_ID,Record_ID,AD_Role_ID,CreatedBy,UUID FROM AD_Record_Access WHERE (AD_Role_ID=?) AND IsActive=? ORDER BY AD_Table_ID
`imagen

I ignore if the first error causes this error, or if it is independent of it.

**Comment by marcalwestf** [comment]
@e-Evolution Víctor on the one hand, the error you reported disappeared, so this pull request could be accepted.

On the other hand, a new error is generated at the same place, so if the error can be solved relatively easy, it could be done on top of this pull request.

Also, the second error could be managed the same way.

The other possibility would be to accept this PR and create two more issues.

You tell me what would be more suitable.
Thanls!!

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario

Hello Mario!

Try this pull request from a new seed , from what I can see the errors it shows are because the database you are working on already has the refactoring migration XMLs applied, but the code does not match that seed.

If you generate the seed of the database with the XML Script of the pull request it should work

**Comment by marcalwestf** [comment]
Ok, thanks @e-Evolution Víctor

**Review by marcalwestf — COMMENTED** [review]
Took the 393 seed and tested again.
The same error is generated.

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario , In my case I have no error, I put here the output of nohup.err and nohup.out

image

image

Apparently it has to do with how you do your deployment

@rcapecce Could you help me with this test please?

**Review by marcalwestf — APPROVED** [review]
Tested again, this time with a database with latest XML loaded and applied.
Login OK, no error in file _nohup.err_

Thanks, @e-Evolution  Victor for your support.

**Pull request merged**
