### PR TITLE
Fixed error with Role Access Update for System Administrator Role

### PR DESCRIPTION
**Pull request by yamelsenih**
## Bug
After merge #3428 the **System Administrator** role is wrong after run
process **Update Role Access** as System Administrator.

## What is the problem?
The system **Administrator Role** is was create with **AD_Role_ID = 0**,
when the role is create with **MRole** constructor, by default is
created a new instance instead find the role.

## Step by Step
- Login as **System Administrator**
- Run process **Update Role Access**
- Logout
- Login after
- Try Open **Table and Column** window

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @mckayERP I will to change for resolve the test for role. If you have any help is nice

**Comment by mckayERP** [comment]
@yamelsenih Good catch.  Yes, I'll have a look.

**Comment by yamelsenih** [comment]
Thanks @mckayERP please, if you can see the test class for resolve this can be so many helping for me

**Comment by e-Evolution** [comment]
@yamelsenih Hi Yamel you can update the branch, since it presents errors in the building

**Review by marcalwestf — APPROVED** [review]
Do as described without changes:
image

With changes: the window _Table and Column_ is displayed correctly.
Test passed.

**Pull request merged**
