### PR TITLE
Use AD_Client_ID constant for 10.000x speedup.

### PR DESCRIPTION
**Pull request by sdgathman**
Out of the box, import time on SSD for 2.3 million products is 4.5 years.  Working that down to a reasonable number of hours.  This is low hanging fruit.

I followed the style of using .append(), but IMO using '+' operator is much more readable and not significant for performance when not in an inner loop.

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @sdgathman  Stuart, thanks for your contribution.

At first glance, your changes seem OK.

Usually, the workflow is as follows:
- you create an **issue** where you describe the case so others can understand your motivation.
- If it is an error, describe the steps to reproduce it.
  I think you did these steps on Discord. It should be in this case a matter of Copy+Paste.
- Supposing it is an error you are describing, write the solution in the PR explanation: how to solve the error with your modifications.
- If you have files or artifacts that help testing, the better.
- In the Pull Request, you write in the first line
 _Solves # < ISSUE NUMBER >_ 
 (without spaces). This way both the Pull Request and the Issue are automatically closed when accepted.
- The following has not been published, but it was decided by the Technical Team: 
  - if there is a Feature, the Pull Request goes against the **develop** branch. 
  - If it is a bug fix, the Pull Request goes against the present bug fix branch, which right now would be hotfix/3.9.4.001 (https://github.com/adempiere/adempiere/tree/hotfix/3.9.4.001)

Thanks again, we look forward to more contributions from you!

**Comment by marcalwestf** [comment]
I found the complete discussion here: https://github.com/adempiere/adempiere/discussions/4120

**Comment by sdgathman** [comment]
I'm sure the same problem appears in other ImportXXXX classes.  Products just happen to be where I slammed into a brick wall.  What about .append() vs '+' operator coding style?

**Comment by sdgathman** [comment]
Do you still need an issue ("Unusably slow Product Import") ?

**Comment by marcalwestf** [comment]
hi @sdgathman  for now, the discussion gives sufficient information, so no need of an issue; perhaps next time.

Do you have a file you used to test in _Garden World_? 
I mean, how are we supposed to test your bug fix?

On the other hand, it could be argued that if the import of a small number of items work, the same would apply to a large number... (just thinking aloud).

Botom line: do you think you can deliver a file to import such a great number of products, or is it enough to import a couple of hundred products? In either case, a file would be handy.

BTW, as this is a bug, the pull request must point to hotfix/3.9.4.001.

I think this coming Friday, September 1st there's a Bug Day planned; perhaps you can participate or give us hints how to tackle this bug.

**Comment by e-Evolution** [comment]
Hi @sdgathman Stuart!

Reviewing the improvement, it seems to me that the problem is that there are multiple "UPDATE" statements without having indexes, and it is for this reason that the inserts are taking too long.

I think that if the proper indexes are added, no change is required in the code.

On the other hand, if it is required to implement an approach like this, the best practices in SQL
we must avoid the code .append(m_AD_Client_ID).append
in favor of using parameters
i.AD_Client_ID=?) this to avoid a potential SQL injection security hole


here are examples of indexes you can create and surely additional DBA work is required

CREATE INDEX C_BPartner_Client_Value_idx ON C_BPartner(AD_Client_ID, Value);
CREATE INDEX M_Product_Client_Upc_idx ON M_Product(AD_Client_ID, Upc);

kind regards
Victor

**Comment by sdgathman** [comment]
m_AD_Client_ID is an integer, not a string, so there is no sql injection possible.

**Comment by yamelsenih** [comment]
Hello @sdgathman  can you update this pull request? we want update all pull request and is possible that this pull request will be closed if not exists a update

**Comment by yamelsenih** [comment]
Hi @sdgathman can you make this pull request to `/hotfix/3.9.4.001` branch instead? I will to test it meanwhile

**Comment by yamelsenih** [comment]
> Hi @sdgathman Stuart!
> 
> Reviewing the improvement, it seems to me that the problem is that there are multiple "UPDATE" statements without having indexes, and it is for this reason that the inserts are taking too long.
> 
> I think that if the proper indexes are added, no change is required in the code.
> 
> On the other hand, if it is required to implement an approach like this, the best practices in SQL we must avoid the code .append(m_AD_Client_ID).append in favor of using parameters i.AD_Client_ID=?) this to avoid a potential SQL injection security hole
> 
> here are examples of indexes you can create and surely additional DBA work is required
> 
> CREATE INDEX C_BPartner_Client_Value_idx ON C_BPartner(AD_Client_ID, Value); CREATE INDEX M_Product_Client_Upc_idx ON M_Product(AD_Client_ID, Upc);
> 
> kind regards Victor

Hello @e-Evolution I think that this pull request can be approved for me. I nice to have a new pr with improvements also but just need that @sdgathman change the target branch from develop to hotfix/3.9.4.001

Best regards

**Comment by yamelsenih** [comment]
Hello @sdgathman  Here a step by step to change the target branch from develop to hotfix/3.9.4.001
https://docs.github.com/en/enterprise-server@3.6/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by yamelsenih** [comment]
I am testing now this

**Pull request merged**
