### PR TITLE
#2658 invoice externalization for e-invoicing UBL and CII

### PR DESCRIPTION
**Pull request by homebeaver**
this implements issue #2658 both schemas

- OASIS UBL
and
- UN/CEFACT

Hi Mario @marcalwestf ,
do you remember? A year ago you started to test a PR for this issue.
See you remarks and questions : https://github.com/adempiere/adempiere/pull/2704#issuecomment-530473764
and my answers : https://github.com/adempiere/adempiere/pull/2704#issuecomment-530694867

I updated the description how to test: see https://github.com/adempiere/adempiere/issues/2658#issuecomment-520595450

I stopped then the work on this topic. And now I resume.
Can you please review the new PR?

regards EUGen

### CODE REVIEW

**Comment by homebeaver** [comment]
Travis build is OK now.

**Comment by homebeaver** [comment]
tkx to @e-Evolution for solving  #3290 - travis is OK now. All checks have passed + no conflicts.

**Comment by marcalwestf** [comment]
@homebeaver  scheduled to test.
Perhaps could others like @trifonnt also test?

**Comment by marcalwestf** [comment]
hi @homebeaver  starting the test.
A few remarks: 

- is it possible for you to also publish the sources & packages of the libraries you use, for example, _de.klst.facturx-1.0.0.jar_?
As we are moving towards substituting ANT for Gradle and we'll use the Github functionality of  _Package Registry_, it would be nice if we also had control of the sources for this package. Otherwise, we would have to resort to / depend on you for any problem.
- Same applies to the packages under _tools/lib/testing_:
Selection_964
(by the way, how do you use them, how can we test them or what are they useful for concerning this functionality?)
- You did some changes in _MInvoice_ and _PO_, both **core** classes in Adempiere. I will check with other operations if there are no side effects for obvious reasons.
- besides both classes mentioned before, all your changes are isolated in _/base/src/org/adempiere/einvoice_. I wonder if it would be possible to create a pseudo-package like _org.adempiere.pos_ or _org.adempiere.crm_, with all classes but  _MInvoice_ and _PO_. It wouldn't add any new functionality but go accordingly to the philosophy of isolating functionality. 
- last but not least, it seems that due to the time delay between (all?) your postings and the test begin, it has become almost customary to have a conflict ;). It will be needed to be solved before any acceptance.

I will test anyway and report my findings here.
Thanks.

**Comment by marcalwestf** [comment]
Analysis of class _PO_:
Selection_966
Add public method _externalize()_. Not intrusive.

Analysis of class _MInvoice_:
Selection_967
Method _externalize()_ was added.
If there is no entry in table _AD_Sysconfig_ for  _XML_EINVOICE_SCHEMA_NAME_,  same behavior as hitherto.
Otherwise, call _AbstractEinvoice.createEinvoice(xmlSchema)_.
Seems not intrusive and safe.

**Comment by marcalwestf** [comment]
Functional test:

- an invoice was opened. The invoice preview was called.
- an XML export was conducted, as described in https://github.com/adempiere/adempiere/issues/2658#issuecomment-520595450 

Results:

1. Test **without** an entry in table _AD_Sysconfig_ for _XML_EINVOICE_SCHEMA_NAME_: same result with standard Adempiere and with this PR.
2. Test **with** an entry in table _AD_Sysconfig_ for _XML_EINVOICE_SCHEMA_NAME_:  different, correct XMLs were issued, depending on the value: _os-UBL-2.1_ for _OASIS UBL_ and  _CrossIndustryInvoice:100_ for _UN/CEFACT (CII)_.

Conclusion:
The changes are not intrusive and are backward-compatible.
The XMLs generated are correct. 
I haven't tested if the XMLs generated are semantically correct or if they do conform to the specifications.
This PR can be accepted if the remarks on my previous comment are considered.

**Comment by homebeaver** [comment]
Hi Mario @marcalwestf ,
- the conflict is resolved - it was not easy 
- pseudo-package : my goal was to avoid dependences between base and einvoice-mapping and vice versa
- the sources for `facturx.jar` can be download in https://github.com/klst-de/e-invoice/releases : 
grafik

- in this repo you can also find an explanation and the goals, see README example and more de-examples. The jar has nothing to do with adempiere. It can be integrated in any other system that generates e-invoices. The "glue" or mapping between AD-invoices and facturx is in `org.adempiere.einvoice`

Hope this helps to accept the PR. 
Regards EUGen

**Comment by yamelsenih** [comment]
Hi @homebeaver how are you? Please can you use a fresh branch for all changes? exist 329 files to review and I see that is the same code for with changes.

**Comment by homebeaver** [comment]
Hi  @yamelsenih 
The reason for many files is conflict resolving eg. ea975fe

@marcalwestf - I'll make a new PR. It takes a while

regards

**Comment by marcalwestf** [comment]
@homebeaver integrating to an European standard e-invoicing is very important.
Your Pull Request actually works and we will test it as soon as you upload changes.

For others: this PR deploys the classes as follows:
Selection_997

It is requested, to pack them similar to:
Selection_999

**Comment by yamelsenih** [comment]
Hi @homebeaver I think that this functionality can be a Location Deutsch **LDE**

Can you be a part of Location?

**Comment by homebeaver** [comment]
> 
> 
> Hi @homebeaver I think that this functionality can be a Location Deutsch **LDE**
> 
The functionaliy is not limited to DE! The standard EN16931 is valid for whole europe and is obligatory in DE and FR now. 
But like IBAN the standard can be used in all countries. In SEPA-countries the use of IBAN is obligatory .

**Comment by trifonnt** [comment]
I also agree that this functionality is not limited to DE only.
Better to be part of the core.

Regards,
Trifon

**Comment by homebeaver** [comment]
@marcalwestf - I've tried to move the "glue" / mapping AD to facturx to a separate subproject. Just now I have trouble with AD building. So I suggest to do the moving in a next step in new issue+PR.

**Comment by e-Evolution** [comment]
@all , I will review the code, but we need 2 premises

1.- Any big fuctionality need a specifc directory, we need no increase the sIze base. So fact we are try disacopling

2.- Any new funcionality of a specific domain should not touch of core , you can use any model validator to add any behavior, the result the new funcionaly should be an separate jar file as ie euroinvooce.jar that is deployment in package other can see the pos funcionality https://github.com/adempiere/adempiere/tree/develop/org.adempiere.pos


you can see the implementatio of https://github.com/adempiere/adempiere/tree/develop/org.eevolution.freight

kind regards

**Comment by homebeaver** [comment]
> 
> 
> ... Please can you use a fresh branch for all changes? ...
Hi @yamelsenih - PR #2658 is this "fresh branch"
regards E.

**Comment by homebeaver** [comment]
I close this issue as there are successors #3348 and #3349

**Pull request closed without merging**
