### PR TITLE
 #1603 Bugfix when an active is generate as expense the active not is…

### PR DESCRIPTION
**Pull request by e-Evolution**
… created  https://github.com/adempiere/adempiere/issues/1603

- Now when an invoice have a fixed asset line as expense is posible adding the asset only as control and tracking

(cherry picked from commit b6de1ce39748f8b26940a06b685c8a36485d1345)

### CODE REVIEW

**Comment by RJPC** [comment]
Hi, the pull request is already under review

**Comment by wdtz** [comment]
Hello @e-Evolution, I think it convenient to make a change, the definition of the following points of interest for functional tests:

- Benefit of Change
- Previous operation procedure
- New operation procedure (Change)

In this way, it will be easier to understand the proposed change, thus giving an opportunity to give an opinion and evaluate its optimal functioning.

**Comment by e-Evolution** [comment]
Hi @wdtz Waditza, 

- The benefit of Change:  allows generated an addition of an asset fixed that not is depreciated to have a control of any fixed asset.

- Previous operation procedure: not allow create any Fixed Asset not depreciated and Fixed Asset Addition.

-  New operation procedure (Change): see the steps list for issue #1603

**Comment by e-Evolution** [comment]
fixes

**Pull request merged**
