### PR TITLE
#1938 Changed the Default Logic in AD_MigrationStep

### PR DESCRIPTION
**Pull request by mckayERP**
#1938 Changed the Default Logic in AD_MigrationStep to reference AD_Migration_ID = @AD_Migration_ID@ instead of AD_MigrationStep_ID = @AD_MigrationStep_ID@

### CODE REVIEW

**Comment by marcalwestf** [comment]
seems that the next sequence does -as implemented now- depend on the selected Migration Step.
Here how it is defined:
screenshot_20180830_083341_migration_step


and if a Migration Step is created manually, it confirms the supposition that the sequence is taken based on the selected Migration Step instead of the highest sequence number:
screenshot_20180830_083341_migration_step_02

**Comment by marcalwestf** [comment]
start testing the bug fix

**Comment by marcalwestf** [comment]
same as with pull request _https://github.com/adempiere/adempiere/pull/1951_ : importing _04030_1928_ErrorSettingSeqNoInAD_MigrationStep.xml_, doesn't load into the Migration table.

But if I do import _4030_1928_ErrorSettingSeqNoInAD_MigrationStep.xml_, the contents are loaded into the Migration table.

This mean. the importing and loading do work, only with these files it doesn't.

Something is wrong with the XML files.

**Comment by marcalwestf** [comment]
... I changed manually the Default Value as specified in the XML file: it works as expected: the next **Sequence No** depends on the highest existing sequence of the Migration:
screenshot_20180830_083341_migration_step_03

**Comment by marcalwestf** [comment]
here, same as pull request https://github.com/adempiere/adempiere/pull/1951 : file name should be **04030_1928_ErrorSettingSeqNoInAD_MigrationStep.xml**, instead of as of now 04030_1928_ErrorSettingSeqNoInAD_MigrationStep.

**Comment by yamelsenih** [comment]
Hi @mckayERP @marcalwestf it change is very good, i can test it... Or @marcalwestf have all test completed?

**Comment by yamelsenih** [comment]
Please @mckayERP change file Name.

From **04030_1928_ErrorSettingSeqNoInAD_MigrationStep** to **04030_1928_ErrorSettingSeqNoInAD_MigrationStep.xml**

**Comment by mckayERP** [comment]
Added the missing extension to the file name.

**Pull request merged**
