### PR TITLE
Add Queue Manager support

### PR DESCRIPTION
**Pull request by yamelsenih**
## What is the new functionality?
- Add queue manager for handle generic queue
- Add Default implementation for Queue manager
- Add Notifiers:
  - EMail queue notifier
  - Note queue notifier

[ADempiereQueue.pdf](https://github.com/adempiere/adempiere/files/6819389/ADempiereQueue.pdf)

## Step by Step
Here a Step by Step using last seed from **GardenWorld**

- Import All XML's
- Re-Login as **Garden World** client and run Functionality Setup for senders
Peek 2021-07-15 10-46
Note that is created two app registrations:
Screenshot_20210715_104725
Screenshot_20210715_104736
Also is created a Scheduler for flush the queue
Screenshot_20210715_110557
- Configure your server mail
Screenshot_20210715_105208
Screenshot_20210715_105232
- Run the class `org.spin.queue.notification.DefaultNotifier` this have a main for simple test and you should add the mail from args
- See your notes:
Screenshot_20210715_105835
- See you incoming mails
Screenshot_20210715_105714

Here a list of item for queue
Screenshot_20210715_123543
Notification queue implementation
Screenshot_20210715_123606

## Some questions
- How I can send a notification from the new functionality?
Is very easy and you can see a example here `org.spin.queue.notification.DefaultNotifier:`
```Java
DefaultNotifier notifier = (DefaultNotifier) QueueLoader.getInstance().getQueueManager(QUEUETYPE_DefaultNotifier)
					.withContext(Env.getCtx())
					.withTransactionName(transactionName);
			//	EMail
			notifier
				.clearMessage()
				.withApplicationType(DefaultNotificationType_EMail)
				.withUserId(100)
				.withText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla faucibus enim quis aliquam. Integer tincidunt et dui vitae egestas. Suspendisse felis est, commodo at ex eu, pellentesque varius leo. Pellentesque tempor quis felis et rutrum. Curabitur imperdiet euismod leo, in pretium ante convallis eu. Nam non odio vulputate, luctus est sed, semper dolor. Vivamus auctor, odio vitae sodales vestibulum, lacus metus auctor ex, nec accumsan est nibh a erat. Ut suscipit velit a imperdiet vestibulum.\n" + 
						"\n" + 
						"Maecenas vel felis ac nulla eleifend volutpat in ac magna. Duis dui est, facilisis at posuere eu, faucibus at nisl. Duis efficitur porttitor lorem. Curabitur tincidunt lorem massa, in sollicitudin ante fringilla sit amet. Nunc nec neque pharetra, tempor mi ac, pharetra risus. Donec tristique laoreet dolor tincidunt venenatis. Sed et leo eget diam molestie venenatis in a eros. Cras nibh arcu, laoreet et suscipit sed, ornare eu mauris. Nulla egestas lacus efficitur, faucibus odio sed, elementum velit. Proin fringilla bibendum lacinia. Vivamus maximus vulputate hendrerit. Fusce mauris ex, finibus eget augue at, volutpat viverra ipsum. Nullam justo nibh, maximus vel nisl tempus, sollicitudin tempor magna.\n" + 
						"\n" + 
						"Sed odio dui, tristique sit amet pretium vitae, vehicula vitae enim. In et interdum quam. Etiam id metus a quam interdum tempor. Sed luctus, tellus et mollis porttitor, dolor lectus dignissim eros, in commodo mauris ligula quis eros. Suspendisse scelerisque ipsum at turpis suscipit interdum at ac velit. Aenean suscipit ipsum ut velit cursus sodales. Nulla viverra mi quis commodo aliquam. Ut auctor condimentum urna sed mollis. Fusce neque neque, interdum eget purus ut, efficitur vestibulum lectus. Praesent sagittis nunc ut tincidunt posuere. In faucibus, elit vel vehicula porta, felis ligula finibus arcu, in suscipit odio risus pellentesque lorem. Etiam viverra lacus a eros placerat, eget tempus mi eleifend. Donec ac arcu vel lacus tristique imperdiet. Quisque venenatis arcu egestas ex viverra accumsan. Aenean vitae massa sed elit hendrerit faucibus.\n" + 
						"\n" + 
						"In hac habitasse platea dictumst. Sed tellus ante, pretium ut viverra feugiat, consectetur et velit. Nulla quis nibh est. Quisque pharetra sem eget ultrices efficitur. Phasellus maximus posuere metus, facilisis dictum justo bibendum ut. Sed aliquet scelerisque risus vel luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse eget diam vestibulum risus venenatis pellentesque. Suspendisse tincidunt orci et nisl malesuada, ut porta neque dictum. Quisque at mollis arcu. Nulla sodales diam id lacus efficitur aliquet. In dui leo, pharetra vulputate purus quis, tincidunt ultricies enim. Nulla facilisi. Donec sagittis pharetra ante. Aenean et condimentum ligula, sed volutpat lorem.\n" + 
						"\n" + 
						"Nulla laoreet faucibus odio, in rutrum diam semper ut. Praesent at purus id massa hendrerit ultricies. Nam sodales sapien id diam finibus viverra. Duis efficitur hendrerit vulputate. Cras urna enim, vestibulum sit amet ex nec, lobortis viverra massa. Morbi accumsan vel magna in dictum. Cras sed mollis libero. Etiam egestas, orci sed dapibus tempus, ligula ex vulputate lacus, sit amet volutpat urna nulla ac massa. Phasellus ac sollicitudin purus. Ut sit amet ligula eget justo imperdiet rhoncus non nec lectus. Mauris euismod ornare felis et dictum. Maecenas vestibulum dictum dui, ut elementum tellus convallis ac. In congue nunc vel felis elementum, at ultrices velit pharetra.\n")
				.addRecipient("email@email.com")
				.addAttachment(file1, "Just a Test")
				.addAttachment(file2)
				.withDescription("Hello by EMAil")
				.addToQueue();
```
- What is the manager for queue?
This `org.spin.queue.util.QueueManager`
- Exists some implementation using queue?
This is a implementation `org.spin.queue.notification.DefaultNotifier`
- What is the contract used for implement a queue?
You can see this contract here `org.spin.queue.util.QueueManager`
- Who is the queue processor?
The queue processor was created using a process named Flush Queue `org.spin.queue.process.FlushSystemQueue`, also the process is added to ADempiere scheduler automatically when is runned the functionality setup for queue manager. I allows run each queu type with the adempiere alert processor
- Exists some base implementation without functionality?
Yes you can see it here `org.spin.queue.test.DefaultTest`
- What is the main methods that should be implemented when is defined a new queue?
  - **Add**: This method is called when a new item is added to queue, note that ypu can implement your own business logic here for register data in a new table or anythings when is add a new item
 
  ```Java
  public void add(int queueId) {
	logger.warning("Queue Added: " + queueId);
  }
  ```  
  - **Process**: Is called from **Flush Queue Process** when a item is processed. Here is where you will should implement the action like send a mail, whatsapp, telegram, process a record to be replicated and other task that will be running with a async processing
 
  ```Java
  public void process(int queueId) {
	logger.warning("Queue Processed: " + queueId);
  }
  ```

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih I notice that this PR uses the apache-ant library 1.10.9, whereas in adempiere/develop it is 1.10.10 used.
Would you please merge with branch adempiere/develop so there are no conflicts when accepting this PR?
Thanks

**Comment by marcalwestf** [comment]
@yamelsenih  it is only the file .classpath that has to be changed. It is enough to merge.

**Comment by marcalwestf** [comment]
@yamelsenih another small change: set release to 3.9.4
imagen

**Comment by marcalwestf** [comment]
..all XMLs applied:
imagen

**Review by marcalwestf — APPROVED** [review]
- uploaded and applied XMLs
- set up email server and client configuration, tested it
- checked XML results
- ran org.spin.queue.notification.DefaultNotifier.main() with email recipient
- checked outgoing and incoming emails.

Result: emails are sent, even if there is an error with the connexion.

Test passed.

PS/
There are still issues like timeout and number of repetitions that can be improved, but this functionality is better than the current one.

**Comment by e-Evolution** [comment]
@yamelsenih when I execute the Functionality Setup Process , the scheduler is created but this had an error 

The Supervisor field is mandatory and Flush System Queue have null value


image

The record  should be create with a supervisor because is mandatory field

**Comment by e-Evolution** [comment]
@yamelsenih Hi Yamel  Why we have here two description field , it can be confuse?

image

**Comment by e-Evolution** [comment]
@yamelsenih I have same observation that @marcalwestf about the Release No should be 3.9.4

image

**Comment by yamelsenih** [comment]
> @yamelsenih Hi Yamel Why we have here two description field , it can be confuse?
> 
> image

Hi @e-Evolution the description is a field but the second is named text instead. Is nice to have a new name for it. I will to make other pull request for it

**Comment by yamelsenih** [comment]
> @yamelsenih I have same observation that @marcalwestf about the Release No should be 3.9.4
> 
> image

No problem. I will to change it

**Comment by yamelsenih** [comment]
> @yamelsenih when I execute the Functionality Setup Process , the scheduler is created but this had an error
> 
> The Supervisor field is mandatory and Flush System Queue have null value
> 
> image
> 
> The record should be create with a supervisor because is mandatory field

I will to add the current user for it instead

**Comment by yamelsenih** [comment]
Hi @marcalwestf @e-Evolution all changes are done

**Comment by yamelsenih** [comment]
> @yamelsenih Hi Yamel Why we have here two description field , it can be confuse?
> 
> image

Hi @e-Evolution I was created a pull request for it: https://github.com/adempiere/adempiere/pull/3550 the main reason is that the element alreasy exist for ADempiere core

Best regards

**Pull request merged**
