### PR TITLE
fix: Clean warning HashMap should be parameterized

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
Currently there are multiple (66) warning messages concerning the hashmap is a raw type:

`HashMap is a raw type. References to generic type HashMap<K,V> should be parameterized`

hashmap-warning

### CODE REVIEW

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt Edwin, one question about the changes on file _CompiereDataSourceFactory_: I notice that you call the _ReportViewDataSource_ class constructor without the parameter _params_. Is this correct?
imagen

**Comment by marcalwestf** [comment]
.... I see you deprecated it:
imagen

What is the reason?
Thanks

**Review by marcalwestf — APPROVED** [review]
Tested on a build Adempiere:
- Cache
- JasperReports
- Other Reports
- Grid Button
- Issues

No errors, functionality maintained.

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  just waiting for the explanation of DataSourceFactory, and perhaps a hint how to test it.
Thanks!

**Comment by EdwinBetanc0urt** [comment]
Greetings @marcalwestf, the `params` argument is never used inside the `ReportViewDataSource` method of the [org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/ReportViewDataSource.java](https://github.com/adempiere/adempiere/blob/develop/org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/ReportViewDataSource.java#L54-L58) class. 

image

That method is only used once in the whole project, specifically in the `createDataSource` method of the [org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/CompiereDataSourceFactory.java](https://github.com/adempiere/adempiere/blob/develop/org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/CompiereDataSourceFactory.java#L47) class.

image

I duplicated the `ReportViewDataSource` method, the new one just removed the `params` variable, and made use of it in `createDataSource`, and the previous `ReportViewDataSource` method I wanted to remove but I put it in disuse to avoid breaking any customization.

**Pull request merged**
