### PR TITLE
Fix/#3309 fix garden world clean up

### LINKED ISSUE #3309: GardenWorldCleanUp not working as expected
The GardenWorldCleanUp process, which is run at the end of the migration loader and is available in the System menu, if failing.

It is supposed to move the dates in GardenWorld so that they appear to be more recent.  The intent was to ensure the GardenWorld demo data was somewhat up-to-date.

The process is failing as not all the dates were being updated.  New documents were not being updated as the GardenWorldCleanUp code did not account for them.  As a result, the Garden World calendar kept shifting until dates for some documents no longer fall within existing periods.

The code needs to be refactored so it does not depend on particular table models and can discover the documents that need to change.

### PR DESCRIPTION
**Pull request by mckayERP**
Fixes #3309

The GardenWorldCleanup class was failing and not adjusting the dates of the demo client properly.  Some tables had been added to the system and the GardenWorldCleanup class had not been adjusted.  As a result, the class kept shifting the calendar but not moving these dates.  After a few years, the calendar no longer covered some of the dates and errors were being thrown.

This PR fixes the issue and reduces the fragility of the code by moving the responsibilities to the correct classes.  Specifically, the Doc class is responsible to know which column in a document is used for the DateAcct.  In most cases, this is standard, but there are a few which use other date columns.

Tests are added to make sure the Cleanup process works correctly and the integration tests run it on the current database.

In refactoring the code, some improvements were added to the Msg class - a wrapper for message keys to use in stead of "@" + message + "@", and some utility functions in MPeriod and TimeUtils.

### CODE REVIEW

**Comment by e-Evolution** [comment]
@mckayERP can please update and solve the conflict with the last develop branch.

**Comment by mckayERP** [comment]
@e-Evolution Conflict resolved.  Thanks.

**Comment by e-Evolution** [comment]
@mckayERP 

2.- I try to apply the 07260_RefactorAndFixGardenWorldCleanup.xml but got an error, I think that codepage for Spanish is incorrect, I fixed it, I will send the fix

19:05:19.842   MigrationFromXML.loadXML: Processing migration file: /Users/e-Evolution/Develop/ADempiere/develop/migration/393lts-394lts/07260_RefactorAndFixGardenWorldCleanup.xml [49]
19:05:19.843   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/develop/migration/393lts-394lts/07260_RefactorAndFixGardenWorldCleanup.xml [49]
[Fatal Error] 07260_RefactorAndFixGardenWorldCleanup.xml:102:79: Invalid byte 2 of 3-byte UTF-8 sequence.
org.xml.sax.SAXParseException; systemId: file:/Users/e-Evolution/Develop/ADempiere/develop/migration/393lts-394lts/07260_RefactorAndFixGardenWorldCleanup.xml; lineNumber: 102; columnNumber: 79; Invalid byte 2 of 3-byte UTF-8 sequence.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:134)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:168)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:113)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at java.lang.Thread.run(Thread.java:748)
19:05:19.880         MPInstance.load: ID=1002040 [49]

2.- After the fix the XML Script, I got another error NPE

===========> GardenWorldCleanup.process: java.lang.NullPointerException [41]
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at org.compiere.util.TimeUtil.getYearsBetween(TimeUtil.java:1313)
	at org.compiere.process.GardenWorldCleanup.determinePeriodOffset(GardenWorldCleanup.java:416)
	at org.compiere.process.GardenWorldCleanup.doIt(GardenWorldCleanup.java:516)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:168)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:113)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:360)
	at java.lang.Thread.run(Thread.java:748)

**Comment by e-Evolution** [comment]
@mckayERP here are bugfix to XML Script using the right code page 

https://github.com/e-Evolution/adempiere/commit/5a16a1ba2c9936c34abd3d48a3fdbb81eca76d44#diff-a9b6fcc602cae0417196c26e7ef8ca4478fe1a14b278d4cb6174c5f8705141bf

**Comment by mckayERP** [comment]
Thanks Victor.  I appreciate you testing all this for me.

I'll have a look over the next few days and get back to you.

Michael McKay
President, mckayERP <http://mckayerp.com>
+1 (613) 297-4483

<http://mckayerp.com>

**Comment by yamelsenih** [comment]
Hi @mckayERP maybe this is related or I resolve the same error here #3433 tell me if is necessary my solution or not for close. I apologize for it

**Comment by mckayERP** [comment]
HI Yamel,  No worries.  I did something similar to #3433.  But I also fixed the reason it was happening.   The GardenWorldCleanUp process shifts the dates on the GardenWorld client.  It was necessary as the demo was based on 2003 data.  The problem was it wasn't shifting all dates so some were getting left behind.  Each seed, the dates would shift further until 393.  There they shifted right off the calendar - resulting in the errors.  On your PR, check the resulting dates of the calendar in GardenWorld and try to run the client accounting processor.  The dates may in the calendar may be well in the future.

**Comment by mckayERP** [comment]
@e-Evolution @yamelsenih This PR seems to be working well.  To test, I merged it with the CI work and you can see the result here:  https://github.com/mckayERP/adempiere/actions/runs/758562315

At the end of the seed creation process, you can see the following output

     [exec] 14:49:38.357 MigrationLoader.main: Process=Garden World Cleanup Error=false Summary=GardenWorldCleanup:Success [1]
     [exec] 14:49:38.323 GardenWorldCleanup.reportResults: Document Dates min/max = 2019-01-22 00:00:00.0/2020-02-26 00:00:00.0 [1]
     [exec] 14:49:38.325 GardenWorldCleanup.reportResults: Period dates min/max =2019-01-01 00:00:00.0/2032-12-31 00:00:00.0 [1]
     [exec] 14:49:38.327 GardenWorldCleanup.reportResults: GardenWorldCleanup:Success [1]

There is a note in the log that the messages can't be found but they are there.  The next run of the process doesn't show the error.  Perhaps the XML additions are not added to the cache?  I haven't checked.

**Comment by yamelsenih** [comment]
Hi @mckayERP can you just change GardenWorldCleanup and divide this PR in two:
- GardenWorldCleanup
- Account Test

This change can help to fix the build checks of #3434 

Best regard

**Comment by mckayERP** [comment]
OK.  Let me have a look.

Mike

**Comment by e-Evolution** [comment]
@mckayERP please can resolve conflicts to merge this bugfix

**Pull request merged**
