### PR TITLE
Add support to CRM as class name of core

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request allows that all model classes of CRM entity can be
called like **M** + **Table Name without prefix**

The class of CRM before change to CRM entity type was called like it:

```Java
- C_Opportunity: MOpportunity
- C_SalesStage: MSalesStage
```

After change it to CRM entity should be called:
```Java
- C_Opportunity: MCOpportunity
- C_SalesStage: MCSalesStage
```

With this change can keep like is previously

### CODE REVIEW

**Comment by marcalwestf** [comment]
@yamelsenih can you provide a short description for testing this PR so it can be tested correctly?

I tried to find places where _MTable.getClass()_ is called by CRM classes but didn't find any, Perhaps you can tell me where.

Secondly, I think this PR can only be tested _after_ the XMLs from https://github.com/adempiere/adempiere/pull/3881 (_09650_Add_CRM_Entity_Type.xml_ and _09660_Change_Entity_Type_for_CRM.xml_)  have been applied, right?

Thanks

**Comment by marcalwestf** [comment]
Answers to the questions:

1. It is enough to write to CRM windows like Opportunity and Sales Stage. 
2. It is as stated: this PR depends on https://github.com/adempiere/adempiere/pull/3881.

**Comment by marcalwestf** [comment]
@yamelsenih Yamel, could you please merge this PR with develop?
This way I can test it, now that https://github.com/adempiere/adempiere/pull/3881 has been approved.
Thanks.

@e-Evolution Victor, you can test here also PR 3881 as it is related to this one.

**Comment by yamelsenih** [comment]
Hi Mario this branch is updated

**Review by marcalwestf — APPROVED** [review]
- Check no compiler errors -> OK
- Check build -> OK
- Check new window type for window _Basket_ -> OK
- Open CRM windows and create records -> OK
- Open **several other windows** and create records -> OK

**Test passed**

**Comment by e-Evolution** [comment]
Testing was success

1.- Create new Lead
2.- Convert Lead to Opportunity  and  Validated that use MBPartner and MOpportunity as Class model 
3.- Create a Project form Opportunity and  Validated that use MProject as Class mode
4.- Create a Distribution Order and Validated that use MDDOrder as Class mode

**Pull request merged**
