### PR TITLE
Allows define discount based on combinations

### PR DESCRIPTION
**Pull request by yamelsenih**
This pull request allows define many discounts combinations based on real combination and hierarchy of filters.

Currently the discount schema apply a search based on sequence and it don't have a way for create a combination like **Product** and **Business Partner** directly.

With this change the hierarchy can be defined like the follow:

1. Product
2. Business Partner
3. Product Category
4. Business Partner Group

Now you can define a combination like:

- Product + Business Partner
- Product + Business Partner Group
- Product Category + Business Partner
- Product Category + Business Partner Group
- Product Only
- Product Category Only
- Business Partner Only
- Business Partner Group Only
- Any

It is very useful for retailers customers and is tested with a customer

## Step by step to test it:

- Go to window **"Discount Schema"**
- Note that already exist a discount schema named **"Combined Discount"**
- You can see the follow combination:

Product Category | Product | Break Value | B.Partner Flat Discount | Break Discount %
-- | -- | -- | -- | --
  | PChair_Patio Chair | 0.0 | No | 7.0
Chemicals |   | 0.0 | No | 5.0
  | Mulch_Mulch 10# | 0.0 | No | 10.0

Note that Chemicals category have  the follows products:
Search Key | Name
-- | --
Fertilizer#50 | Fertilizer #50
Fertilizer#70 | Fertilizer #70
Mulch | Mulch 10#

Like you can see the product **Mulch 10#** is part of **Chemicals** and exist a specific discount for him of **10.0 %** however exists other discount applied to **Chemicals** category of **5.0 %**

You can see a example with the order **500** created for **C&W Construction** (Note that C&W Construction have configured the **Combined Discount** on **Customer** tab)

## Formula
The formula used is a standard calculation of discount, you can see a dynamic calculator [here](https://www.omnicalculator.com/finance/percentage-discount)

### Data
 - The base price for discount is **Standar Price**
 - The percentage applied is based on combination getted from Discount Schema

## Result:
- The first line is for **Fertilizer#70** and the discount applied is **5%**
- The second line is for **Mulch10#**, note that this product is inside **Chemicals** category but it have a special discount of **10%**

## Some interest comments
If you see the discount applied on **Sales Order** for **Fertilizer#70** tou can see **10.43** (Ohh this is wrong..... No, remember that the discount is calculated between **Standard Price** and **Unit Price**). The discount calculated in sales order is based on **Price List** and **Unit Price**.

For **Fertilizer #70** has the follows values:
- Price List: **35.00**
- Standard Price: **33.00**
- Price with Discount: **31.35**

A simple calculation of discount is:
```Java
StandardPrice = 33.00
DiscountPercentage = 5

New Price Calculation
-----------------------------------------------
NewPrice = ((100 - DiscountPercentage) / 100) * StandardPrice
NewPrice = ((100 - 5) / 100) * 33.00
NewPrice = 31.35

Discount Amount
-----------------------------------------------
DiscountAmount = StandardPrice - NewPrice
DiscountAmount = 33.00 - 31.35
DiscountAmount = 1.65

Discount Rate based on Sales Order
-----------------------------------------------
DiscountRate = ((PriceList - NewPrice) / PriceList) * 100
DiscountRate = ((35.00 - 31.35) / 35.00) * 100
DiscountRate = ((3.65) / 35.00) * 100
DiscountRate = (0.104285714) * 100
DiscountRate = 10.4285714 ~ 10.43
```

Here exist a XML with the taste: https://github.com/adempiere/adempiere/pull/3852/files#diff-e495c5a1cca88974283598b52fe8d82ba678850b3b1d4a72d64fa174b351ce5c

### CODE REVIEW

**Review by marcalwestf — COMMENTED** [review]
XML Applied -> OK

Check Discount Schema  -> OK
Selection_175

Open Order, check discount calculated  -> OK
imagen

imagen


Debug Discount by changing qty  and single-stepping methods -> OK

Additional tests
Add a break line: a new product with 50% discount above qty of 10:  
imagen

If the quantity is above 10:  -> OK
imagen

If the quantity is below 10:  -> OK
imagen

If the discount is below limit price there is an error:   -> OK
imagen


All tests passed

**Review by marcalwestf — CHANGES_REQUESTED** [review]
@yamelsenih  there is only a little change needed to accept these changes:
The _**Default Logic**_ of the column _M_Product_Category_ID_ in table _M_DiscountSchemaBreak_ must be set to **-1**

imagen

Otherwise, when creating a new Discount Break for a product for the first time, it can be a confusion before saving, because both fields Product Category and Product seem to be set: 
imagen

Even if after saving everything is OK:
imagen

**Comment by yamelsenih** [comment]
> @yamelsenih there is only a little change needed to accept these changes: The _**Default Logic**_ of the column _M_Product_Category_ID_ in table _M_DiscountSchemaBreak_ must be set to **-1**
> 
> imagen
> 
> Otherwise, when creating a new Discount Break for a product for the first time, it can be a confusion before saving, because both fields Product Category and Product seem to be set: imagen
> 
> Even if after saving everything is OK: imagen

Hi @marcalwestf here is the change: https://github.com/adempiere/adempiere/pull/3852/commits/fe3eceb5ab4f7c274fef0768340757d537e856b3

**Review by marcalwestf — APPROVED** [review]
Changes as requested.

**Pull request merged**
